Fix the upgrade issue for tracing
istio/istio pull request #16128
Opened 2019-08-08 09:44 UTC by clyang82

Signed-off-by: Chun Lin Yang <clyang@cn.ibm.com>

When we installed the istio with tracing.provider=jaeger. then use helm to upgrade to use `zipkin` provider.
```
helm upgrade istio ./install/kubernetes/helm/istio --tls --set tracing.enabled=true --set tracing.provider=zipkin
```
 it throws 
```
Error: UPGRADE FAILED: Deployment.apps "istio-tracing" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"jaeger"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

I suggest to share the same selector for both jaeger and zipkin. the fix changes the `LabelSelector` so when upgrade from 1.2.x to this version, it needs to use `--force`. in future, do not need to force upgrade.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

2019-08-08 09:49 UTC, istio-testing commented
@clyang82: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
istio-lint-master | 4e769f8172337b7c411502c41bf8e8fc8f653bd4 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/istio-lint-master/2659) | `/test istio-lint-master`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-08-08 09:53 UTC, istio-testing commented
@clyang82: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
istio-lint-master | 4e769f8172337b7c411502c41bf8e8fc8f653bd4 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/istio-lint-master/2659) | `/test istio-lint-master`
e2e-simpleTests-distroless-master | 4e769f8172337b7c411502c41bf8e8fc8f653bd4 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/e2e-simpleTests-distroless-master/970) | `/test e2e-simpleTests-distroless-master`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-08-08 10:16 UTC, istio-testing commented
@clyang82: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
istio-lint-master | 4e769f8172337b7c411502c41bf8e8fc8f653bd4 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/istio-lint-master/2659) | `/test istio-lint-master`
e2e-simpleTests-distroless-master | 4e769f8172337b7c411502c41bf8e8fc8f653bd4 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/e2e-simpleTests-distroless-master/970) | `/test e2e-simpleTests-distroless-master`
istio-pilot-multicluster-e2e-master | 4e769f8172337b7c411502c41bf8e8fc8f653bd4 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/istio-pilot-multicluster-e2e-master/3925) | `/test istio-pilot-multicluster-e2e-master`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-08-08 10:19 UTC, istio-testing commented
@clyang82: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
istio-lint-master | 4e769f8172337b7c411502c41bf8e8fc8f653bd4 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/istio-lint-master/2659) | `/test istio-lint-master`
e2e-simpleTests-distroless-master | 4e769f8172337b7c411502c41bf8e8fc8f653bd4 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/e2e-simpleTests-distroless-master/970) | `/test e2e-simpleTests-distroless-master`
istio-pilot-multicluster-e2e-master | 4e769f8172337b7c411502c41bf8e8fc8f653bd4 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/istio-pilot-multicluster-e2e-master/3925) | `/test istio-pilot-multicluster-e2e-master`
integ-telemetry-k8s-presubmit-tests-master | 4e769f8172337b7c411502c41bf8e8fc8f653bd4 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-presubmit-tests-master/2870) | `/test integ-telemetry-k8s-presubmit-tests-master`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-08-08 10:51 UTC, morvencao commented on install/kubernetes/helm/istio/charts/tracing/templates/deployment.yaml
> +        scheduler.alpha.kubernetes.io/critical-pod: ""
Please remove the critical-pod annotation as it's going to be deprecated and removed in future k8s version, see: https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/#marking-pod-as-critical

2019-08-09 06:10 UTC, istio-testing commented
@clyang82: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
istio-pilot-multicluster-e2e-master | 4e769f8172337b7c411502c41bf8e8fc8f653bd4 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/istio-pilot-multicluster-e2e-master/3925) | `/test istio-pilot-multicluster-e2e-master`
integ-telemetry-k8s-presubmit-tests-master | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-presubmit-tests-master/2945) | `/test integ-telemetry-k8s-presubmit-tests-master`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-08-09 13:00 UTC, morvencao commented
@clyang82 Have you merge the same PR to istio/installer? All installer PR should go to istio/installer firstly, see comments here: https://github.com/istio/istio/pull/16121#issuecomment-519552992

2019-08-29 01:23 UTC, clyang82 commented
> @clyang82 Have you merge the same PR to istio/installer? All installer PR should go to istio/installer firstly, see comments here: [#16121 (comment)](https://github.com/istio/istio/pull/16121#issuecomment-519552992)

PR https://github.com/istio/installer/pull/359 was created in installer.

2019-09-03 21:37 UTC, douglas-reid commented
Is this PR needed for 1.3?

2019-09-06 01:15 UTC, clyang82 commented
> Is this PR needed for 1.3?

I think we should have it in 1.3. that is related with upgrading.

2019-09-07 03:46 UTC, istio-testing commented
@clyang82: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-presubmit-tests-master | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-presubmit-tests-master/2945) | `/test integ-telemetry-k8s-presubmit-tests-master`
integ-telemetry-k8s-tests_istio | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-tests_istio/45) | `/test integ-telemetry-k8s-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-09 13:52 UTC, sdake commented
cc @sdake

2019-09-09 14:09 UTC, howardjohn requested changes
I don't think we should merge them. We can solve the issue without merging the charts into one complicated monolith by making them use the same labels,right?. This comment applies more to the change on istio/installer but I think it applies here as well

2019-09-09 15:20 UTC, linsun commented
Seems pretty advanced scenario, not sure if it ever worked before.  Ok to not have it in 1.3 imho.

2019-09-11 03:01 UTC, clyang82 commented
> I don't think we should merge them. We can solve the issue without merging the charts into one complicated monolith by making them use the same labels,right?. This comment applies more to the change on istio/installer but I think it applies here as well

Thanks for your comment. Let me update to keep separated files with the same labels.

2019-09-13 15:27 UTC, istio-testing commented
@clyang82: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-presubmit-tests-master | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-presubmit-tests-master/2945) | `/test integ-telemetry-k8s-presubmit-tests-master`
integ-telemetry-k8s-tests_istio | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-tests_istio/45) | `/test integ-telemetry-k8s-tests_istio`
e2e-simpleTests-cni_istio | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/e2e-simpleTests-cni_istio/249) | `/test e2e-simpleTests-cni_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-14 20:44 UTC, istio-testing commented
@clyang82: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-presubmit-tests-master | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-presubmit-tests-master/2945) | `/test integ-telemetry-k8s-presubmit-tests-master`
integ-telemetry-k8s-tests_istio | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-tests_istio/45) | `/test integ-telemetry-k8s-tests_istio`
e2e-simpleTests-cni_istio | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/e2e-simpleTests-cni_istio/249) | `/test e2e-simpleTests-cni_istio`
lintmodern_istio | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/lintmodern_istio/53) | `/test lintmodern_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-19 02:08 UTC, istio-testing commented
@clyang82: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-presubmit-tests-master | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-presubmit-tests-master/2945) | `/test integ-telemetry-k8s-presubmit-tests-master`
integ-telemetry-k8s-tests_istio | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-tests_istio/45) | `/test integ-telemetry-k8s-tests_istio`
e2e-simpleTests-cni_istio | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/e2e-simpleTests-cni_istio/249) | `/test e2e-simpleTests-cni_istio`
lintmodern_istio | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/lintmodern_istio/53) | `/test lintmodern_istio`
lint_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/lint_istio/557) | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-19 02:08 UTC, istio-testing commented
@clyang82: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-presubmit-tests-master | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-presubmit-tests-master/2945) | `/test integ-telemetry-k8s-presubmit-tests-master`
integ-telemetry-k8s-tests_istio | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-tests_istio/45) | `/test integ-telemetry-k8s-tests_istio`
e2e-simpleTests-cni_istio | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/e2e-simpleTests-cni_istio/249) | `/test e2e-simpleTests-cni_istio`
lintmodern_istio | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/lintmodern_istio/53) | `/test lintmodern_istio`
lint_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/lint_istio/557) | `/test lint`
release-test_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/release-test_istio/546) | `/test release-test`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-19 02:14 UTC, istio-testing commented
@clyang82: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-presubmit-tests-master | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-presubmit-tests-master/2945) | `/test integ-telemetry-k8s-presubmit-tests-master`
integ-telemetry-k8s-tests_istio | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-tests_istio/45) | `/test integ-telemetry-k8s-tests_istio`
e2e-simpleTests-cni_istio | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/e2e-simpleTests-cni_istio/249) | `/test e2e-simpleTests-cni_istio`
lint_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/lint_istio/557) | `/test lint`
release-test_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/release-test_istio/546) | `/test release-test`
unit-tests_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/unit-tests_istio/571) | `/test unit-tests`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-19 02:15 UTC, istio-testing commented
@clyang82: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-presubmit-tests-master | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-presubmit-tests-master/2945) | `/test integ-telemetry-k8s-presubmit-tests-master`
integ-telemetry-k8s-tests_istio | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-tests_istio/45) | `/test integ-telemetry-k8s-tests_istio`
e2e-simpleTests-cni_istio | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/e2e-simpleTests-cni_istio/249) | `/test e2e-simpleTests-cni_istio`
lint_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/lint_istio/557) | `/test lint`
release-test_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/release-test_istio/546) | `/test release-test`
unit-tests_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/unit-tests_istio/571) | `/test unit-tests`
racetest_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/racetest_istio/571) | `/test racetest`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-19 02:16 UTC, istio-testing commented
@clyang82: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-presubmit-tests-master | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-presubmit-tests-master/2945) | `/test integ-telemetry-k8s-presubmit-tests-master`
e2e-simpleTests-cni_istio | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/e2e-simpleTests-cni_istio/249) | `/test e2e-simpleTests-cni_istio`
lint_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/lint_istio/557) | `/test lint`
release-test_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/release-test_istio/546) | `/test release-test`
unit-tests_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/unit-tests_istio/571) | `/test unit-tests`
racetest_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/racetest_istio/571) | `/test racetest`
integ-telemetry-k8s-tests_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-tests_istio/554) | `/test integ-telemetry-k8s-tests`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-19 02:19 UTC, istio-testing commented
@clyang82: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-presubmit-tests-master | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-presubmit-tests-master/2945) | `/test integ-telemetry-k8s-presubmit-tests-master`
lint_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/lint_istio/557) | `/test lint`
release-test_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/release-test_istio/546) | `/test release-test`
unit-tests_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/unit-tests_istio/571) | `/test unit-tests`
racetest_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/racetest_istio/571) | `/test racetest`
integ-telemetry-k8s-tests_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-tests_istio/554) | `/test integ-telemetry-k8s-tests`
codecov_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/codecov_istio/555) | `/test codecov`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-19 02:25 UTC, howardjohn commented
This doesn't seem like a good idea. We will break upgrade for 100% of users to support the very few that switch providers. Why not just have --force when you switch rather than make everyone --force?

2019-09-19 02:30 UTC, istio-testing commented
@clyang82: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-presubmit-tests-master | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-presubmit-tests-master/2945) | `/test integ-telemetry-k8s-presubmit-tests-master`
lint_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/lint_istio/557) | `/test lint`
release-test_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/release-test_istio/546) | `/test release-test`
unit-tests_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/unit-tests_istio/571) | `/test unit-tests`
racetest_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/racetest_istio/571) | `/test racetest`
integ-telemetry-k8s-tests_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-tests_istio/554) | `/test integ-telemetry-k8s-tests`
codecov_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/codecov_istio/555) | `/test codecov`
integ-new-install-k8s-tests_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-new-install-k8s-tests_istio/394) | `/test integ-new-install-k8s-tests`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-19 02:56 UTC, clyang82 commented
> This doesn't seem like a good idea. We will break upgrade for 100% of users to support the very few that switch providers. Why not just have --force when you switch rather than make everyone --force?

Yes. Just checked the upgrade document - there is no --force. this fix requires everyone to use --force which is not a good idea. but for istio tracing, i think we should use the same name instead of different provider. Anyway, this is a minor case. If no better idea for this case, I will close it. Thanks.

2019-09-19 03:15 UTC, istio-testing commented
@clyang82: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-presubmit-tests-master | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-presubmit-tests-master/2945) | `/test integ-telemetry-k8s-presubmit-tests-master`
release-test_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/release-test_istio/546) | `/test release-test`
integ-telemetry-k8s-tests_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-tests_istio/554) | `/test integ-telemetry-k8s-tests`
integ-new-install-k8s-tests_istio | 28a57c863c7e21c2477a25525de4ee7094c9854c | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-new-install-k8s-tests_istio/397) | `/test integ-new-install-k8s-tests`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-19 03:18 UTC, istio-testing commented
@clyang82: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-presubmit-tests-master | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-presubmit-tests-master/2945) | `/test integ-telemetry-k8s-presubmit-tests-master`
release-test_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/release-test_istio/546) | `/test release-test`
integ-telemetry-k8s-tests_istio | 35095ec33500291593a1fd325da659f6608a0eb9 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-tests_istio/554) | `/test integ-telemetry-k8s-tests`
integ-new-install-k8s-tests_istio | 28a57c863c7e21c2477a25525de4ee7094c9854c | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-new-install-k8s-tests_istio/397) | `/test integ-new-install-k8s-tests`
integ-mixer-k8s-tests_istio | 28a57c863c7e21c2477a25525de4ee7094c9854c | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-mixer-k8s-tests_istio/416) | `/test integ-mixer-k8s-tests`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-19 03:27 UTC, istio-testing commented
@clyang82: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-presubmit-tests-master | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-presubmit-tests-master/2945) | `/test integ-telemetry-k8s-presubmit-tests-master`
integ-new-install-k8s-tests_istio | 28a57c863c7e21c2477a25525de4ee7094c9854c | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-new-install-k8s-tests_istio/397) | `/test integ-new-install-k8s-tests`
integ-mixer-k8s-tests_istio | 28a57c863c7e21c2477a25525de4ee7094c9854c | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-mixer-k8s-tests_istio/416) | `/test integ-mixer-k8s-tests`
integ-telemetry-k8s-tests_istio | 28a57c863c7e21c2477a25525de4ee7094c9854c | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-tests_istio/557) | `/test integ-telemetry-k8s-tests`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-19 22:53 UTC, howardjohn commented
/retest

2019-09-19 23:35 UTC, istio-testing commented
@clyang82: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-presubmit-tests-master | 8905f55df4af0a8f33378dbb0271b846a022378b | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-presubmit-tests-master/2945) | `/test integ-telemetry-k8s-presubmit-tests-master`
integ-telemetry-k8s-tests_istio | 28a57c863c7e21c2477a25525de4ee7094c9854c | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16128/integ-telemetry-k8s-tests_istio/619) | `/test integ-telemetry-k8s-tests`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-23 02:19 UTC, closed without merging