Pilot: increase protocol detection timeout to 1s
istio/istio pull request #16835
Opened 2019-09-04 23:36 UTC by yxue

Increase protocol detection timeout to 1s

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

2019-09-04 23:39 UTC, howardjohn approved these changes

2019-09-04 23:43 UTC, istio-testing commented
@yxue: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-galley-local-presubmit-tests-master | cadeeaed4f490665e9be2327b247a8031af3f5e1 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-galley-local-presubmit-tests-master/5610) | `/test integ-galley-local-presubmit-tests-master`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-04 23:53 UTC, istio-testing commented
@yxue: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-galley-local-presubmit-tests-master | f4ac04536a304a5f7fbb3323b78248c164369287 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-galley-local-presubmit-tests-master/5611) | `/test integ-galley-local-presubmit-tests-master`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-05 00:12 UTC, howardjohn commented
@istio/wg-config-maintainers ptal, needed for 1.3

2019-09-05 00:29 UTC, istio-testing commented
@yxue: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
istio-unit-tests-master | 35782f86d0faab413c90e86ec09ed1847b3de45f | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-unit-tests-master/6681) | `/test istio-unit-tests-master`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-05 00:32 UTC, istio-testing commented
@yxue: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
istio-unit-tests-master | 35782f86d0faab413c90e86ec09ed1847b3de45f | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-unit-tests-master/6681) | `/test istio-unit-tests-master`
istio-racetest-master | 35782f86d0faab413c90e86ec09ed1847b3de45f | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-racetest-master/4789) | `/test istio-racetest-master`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-05 00:43 UTC, yxue commented
/test istio-unit-tests-master
/test istio-racetest-master

2019-09-05 00:45 UTC, rshriram requested changes
Lets not arbitrarily increase the timeout to 1s as this will impact not just mysql but all outbound listeners as well. Please fix the code in buildListeners to apply 100ms timeout for inbound and 500ms timeout for outbound listeners respectively. Otherwise, the penalty for enabling protocol sniffing (which is on by default) is much higher latency in the mesh for normal operations due to this gratuitous 1s timeout!

2019-09-05 00:46 UTC, rshriram commented
Actually,  thinking about this, in some cases, the entire thing will become dead slow because there is a 1s timeout in the egress listener and then there is another 1s timeout on the ingress listener!!

2019-09-05 00:51 UTC, istio-testing commented
@yxue: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
istio-unit-tests-master | 35782f86d0faab413c90e86ec09ed1847b3de45f | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-unit-tests-master/6681) | `/test istio-unit-tests-master`
istio-racetest-master | 35782f86d0faab413c90e86ec09ed1847b3de45f | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-racetest-master/4789) | `/test istio-racetest-master`
integ-security-k8s-presubmit-tests-master | 35782f86d0faab413c90e86ec09ed1847b3de45f | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-security-k8s-presubmit-tests-master/5577) | `/test integ-security-k8s-presubmit-tests-master`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-05 01:03 UTC, istio-testing commented
@yxue: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
istio-racetest-master | 35782f86d0faab413c90e86ec09ed1847b3de45f | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-racetest-master/4789) | `/test istio-racetest-master`
integ-security-k8s-presubmit-tests-master | 35782f86d0faab413c90e86ec09ed1847b3de45f | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-security-k8s-presubmit-tests-master/5577) | `/test integ-security-k8s-presubmit-tests-master`
istio-unit-tests-master | 35782f86d0faab413c90e86ec09ed1847b3de45f | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-unit-tests-master/6685) | `/test istio-unit-tests-master`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-05 01:06 UTC, istio-testing commented
@yxue: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-k8s-presubmit-tests-master | 35782f86d0faab413c90e86ec09ed1847b3de45f | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-security-k8s-presubmit-tests-master/5577) | `/test integ-security-k8s-presubmit-tests-master`
istio-unit-tests-master | 35782f86d0faab413c90e86ec09ed1847b3de45f | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-unit-tests-master/6685) | `/test istio-unit-tests-master`
istio-racetest-master | 35782f86d0faab413c90e86ec09ed1847b3de45f | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-racetest-master/4793) | `/test istio-racetest-master`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-05 03:33 UTC, howardjohn commented
I would prefer a minimum of 500ms (I think infinite is best). Round trip times cross country are pretty slow... normal requests failing is worse than MySQL being slow. For MySQL they can just configure destination rule and they are fine.. for https traffic if we are ever a little too slow it will break, and there is nothing we can do about it.

We had tls inspector with no timeout for a long time, I don't know why we feel the need to bundle a timeout on tls inspector with protocol sniffint

2019-09-05 03:49 UTC, yxue commented
@howardjohn I missed something during the discussion. Actually, we have multiple problems regarding the timeout:

If we set timeout to infinite,
1. For permissive mTLS filter chain (TLS inspector), MySQL will be broken;
2. For protocol sniffing filter chain (HTTP inspector), TCP traffic could be broken, e.g., if client sends `GET` only, the http inspector will get stuck

If we set timeout to 1s, 
1. For permissive mTLS filter chain (TLS inspector),  MySQL will have 1s delay;   <----- this might be acceptable. 
2. For protocol sniffing filter chain (HTTP inspector), some TCP traffic will have 1s delay, e.g. client sends `GET` only;  <----- I don't think this will be accepted.

2019-09-05 03:59 UTC, howardjohn commented
what do other systems do?

On Wed, Sep 4, 2019, 8:50 PM Yan Xue <notifications@github.com> wrote:

> @howardjohn <https://github.com/howardjohn> I missed something during the
> discussion. Actually, we have multiple problems regarding the timeout:
>
> If we set timeout to infinite,
>
>    1. For permissive mTLS filter chain (TLS inspector), MySQL will be
>    broken;
>    2. For protocol sniffing filter chain (HTTP inspector), TCP traffic
>    could be broken, e.g., if client sends GET only, the http inspector
>    will get stuck
>
> If we set timeout to 1s,
>
>    1. For permissive mTLS filter chain (TLS inspector), MySQL will have
>    1s delay; <----- this might be acceptable.
>    2. For protocol sniffing filter chain (HTTP inspector), some TCP
>    traffic will have 1s delay, e.g. client sends GET only; <----- I don't
>    think this will be accepted.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/istio/pull/16835?email_source=notifications&email_token=AAEYGXPISY4NCIO3LQ4GHFDQIB6ZZA5CNFSM4ITXS6VKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD55XL4Q#issuecomment-528184818>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAEYGXP3KSIJJWACOJM5M7DQIB6ZZANCNFSM4ITXS6VA>
> .
>

2019-09-05 15:12 UTC, rshriram commented
The problems pointed by @yxue are exactly why I didn't approve this PR :). 

So here is a possible solution:
 * Set the listener filter timeout on all ingress listeners for sidecars with TLS_inspector/http inspector and multiple filter chains (i.e. permissive mode).
 * set the listener filter timeout on all egress listeners on sidecars with http_inspector

In both cases, you do not have to increase the default timeout. Or may be we can set it to 100ms on the ingress listener. On the egress listener, it should always be small (10ms) because the traffic is coming from localhost loopback socket and not over the wire.

2019-09-05 15:22 UTC, howardjohn commented
> set the listener filter timeout on all egress listeners on sidecars with http_inspector

We cannot keep this at 10ms, that was what the original issue was, egress traffic. We can't just set it on the http_inspector, the timeout is shared for TLS inspector and the same listener can have both. I don't know *why* it times out, but it does -- 3 people have reproduced it independently. Having 50% of HTTPS traffic fail is not acceptable...

2019-09-05 17:52 UTC, rshriram commented
> We cannot keep this at 10ms, that was what the original issue was, egress traffic. We can't just set it on the http_inspector, the timeout is shared for TLS inspector and the same listener can have both. I don't know why it times out, but it does -- 3 people have reproduced it independently. Having 50% of HTTPS traffic fail is not acceptable...

The original issue was that a listener +tls inspector with filter chain with sni match had 10ms timeout. My proposal is to set the 10ms timeout on only the sidecar egress listeners that have http inspector. Such listeners will not have SNI matches.  their filter chain match will be based on whether the protocol was HTTP or not. In this case, missing the protocol detection, the filter chain will default to TCP and traffic will flow. And remember that this affects only cases where the ports are NOT named.

2019-09-05 18:13 UTC, howardjohn commented
>  Such listeners will not have SNI matches. their filter chain match will be based on whether the protocol was HTTP or not

You can have a listener with tls inspector + http inspector. Proof (note -  I think this is a bug @yxue):

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-ext
  namespace: default
spec:
  hosts:
  - httpbin.org
  ports:
  - number: 7777
    name: http
    protocol: HTTP
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-ext2
  namespace: default
spec:
  hosts:
  - httpbin.org
  ports:
  - number: 7777
    name: https
    protocol: HTTPS
  resolution: DNS
```

produces config:

```json
    {
     "version_info": "2019-09-05T18:10:52Z/17",
     "listener": {
      "name": "0.0.0.0_7777",
      "address": {
       "socket_address": {
        "address": "0.0.0.0",
        "port_value": 7777
       }
      },
      "filter_chains": [
       {
        "filter_chain_match": {
         "prefix_ranges": [
          {
           "address_prefix": "10.28.0.21",
           "prefix_len": 32
          }
         ]
        },
        "filters": [
         {
          "name": "mixer",
          "typed_config": {
           "@type": "type.googleapis.com/istio.mixer.v1.config.client.TcpClientConfig",
           "transport": {
            "network_fail_policy": {
             "policy": "FAIL_CLOSE",
             "base_retry_wait": "0.080s",
             "max_retry_wait": "1s"
            },
            "check_cluster": "outbound|9091||istio-policy.istio-system.svc.cluster.local",
            "report_cluster": "outbound|9091||istio-telemetry.istio-system.svc.cluster.local",
            "report_batch_max_entries": 100,
            "report_batch_max_time": "1s"
           },
           "mixer_attributes": {
            "attributes": {
             "context.proxy_version": {
              "string_value": "1.3.0"
             },
             "context.reporter.kind": {
              "string_value": "outbound"
             },
             "context.reporter.uid": {
              "string_value": "kubernetes://shell-77dd85d479-mnnrl.default"
             },
             "destination.service.host": {
              "string_value": "httpbin.org"
             },
             "destination.service.name": {
              "string_value": "httpbin.org"
             },
             "destination.service.namespace": {
              "string_value": "default"
             },
             "source.namespace": {
              "string_value": "default"
             },
             "source.uid": {
              "string_value": "kubernetes://shell-77dd85d479-mnnrl.default"
             }
            }
           },
           "disable_check_calls": true
          }
         },
         {
          "name": "envoy.tcp_proxy",
          "typed_config": {
           "@type": "type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy",
           "stat_prefix": "BlackHoleCluster",
           "cluster": "BlackHoleCluster"
          }
         }
        ]
       },
       {
        "filter_chain_match": {
         "server_names": [
          "httpbin.org"
         ]
        },
        "filters": [
         {
          "name": "mixer",
          "typed_config": {
           "@type": "type.googleapis.com/istio.mixer.v1.config.client.TcpClientConfig",
           "transport": {
            "network_fail_policy": {
             "policy": "FAIL_CLOSE",
             "base_retry_wait": "0.080s",
             "max_retry_wait": "1s"
            },
            "check_cluster": "outbound|9091||istio-policy.istio-system.svc.cluster.local",
            "report_cluster": "outbound|9091||istio-telemetry.istio-system.svc.cluster.local",
            "report_batch_max_entries": 100,
            "report_batch_max_time": "1s"
           },
           "mixer_attributes": {
            "attributes": {
             "context.proxy_version": {
              "string_value": "1.3.0"
             },
             "context.reporter.kind": {
              "string_value": "outbound"
             },
             "context.reporter.uid": {
              "string_value": "kubernetes://shell-77dd85d479-mnnrl.default"
             },
             "destination.service.host": {
              "string_value": "httpbin.org"
             },
             "destination.service.name": {
              "string_value": "httpbin.org"
             },
             "destination.service.namespace": {
              "string_value": "default"
             },
             "source.namespace": {
              "string_value": "default"
             },
             "source.uid": {
              "string_value": "kubernetes://shell-77dd85d479-mnnrl.default"
             }
            }
           },
           "disable_check_calls": true
          }
         },
         {
          "name": "envoy.tcp_proxy",
          "typed_config": {
           "@type": "type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy",
           "stat_prefix": "outbound|7777||httpbin.org",
           "cluster": "outbound|7777||httpbin.org",
           "access_log": [
            {
             "name": "envoy.file_access_log",
             "typed_config": {
              "@type": "type.googleapis.com/envoy.config.accesslog.v2.FileAccessLog",
              "path": "/dev/stdout",
              "format": "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% \"%DYNAMIC_METADATA(istio.mixer:status)%\" \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\n"
             }
            }
           ]
          }
         }
        ]
       },
       {
        "filter_chain_match": {},
        "filters": [
         {
          "name": "mixer",
          "typed_config": {
           "@type": "type.googleapis.com/istio.mixer.v1.config.client.TcpClientConfig",
           "transport": {
            "network_fail_policy": {
             "policy": "FAIL_CLOSE",
             "base_retry_wait": "0.080s",
             "max_retry_wait": "1s"
            },
            "check_cluster": "outbound|9091||istio-policy.istio-system.svc.cluster.local",
            "report_cluster": "outbound|9091||istio-telemetry.istio-system.svc.cluster.local",
            "report_batch_max_entries": 100,
            "report_batch_max_time": "1s"
           },
           "mixer_attributes": {
            "attributes": {
             "context.proxy_version": {
              "string_value": "1.3.0"
             },
             "context.reporter.kind": {
              "string_value": "outbound"
             },
             "context.reporter.uid": {
              "string_value": "kubernetes://shell-77dd85d479-mnnrl.default"
             },
             "destination.service.host": {
              "string_value": "httpbin.org"
             },
             "destination.service.name": {
              "string_value": "httpbin.org"
             },
             "destination.service.namespace": {
              "string_value": "default"
             },
             "source.namespace": {
              "string_value": "default"
             },
             "source.uid": {
              "string_value": "kubernetes://shell-77dd85d479-mnnrl.default"
             }
            }
           },
           "disable_check_calls": true
          }
         },
         {
          "name": "envoy.tcp_proxy",
          "typed_config": {
           "@type": "type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy",
           "stat_prefix": "PassthroughCluster",
           "cluster": "PassthroughCluster"
          }
         }
  [...]

2019-09-05 18:29 UTC, rshriram commented
> You can have a listener with tls inspector + http inspector. Proof (note - I think this is a bug @yxue):

So this is the corner case and I think this is going to be quite uncommon. It did not work in previous releases. So in this release, we can make this slow but make it work. 

How about this:
 when we construct the filter chains, we add some metadata or some other param to track how many protocols are being detected.. 
 - if its http & tcp only,  then set 10ms timeout
 - if its https only (i.e. sni based routing), no timeout
 - if its http, https, and tcp, then it is a case where the user has both http and https services on same port. We can set a large timeout here like 200ms.
 - on  inbound, we should not increase timeout at all IMO. inbound scenario is straight forward. its always between http and tcp [with or without tls sniffing]. or if we feel too nervous about 10ms, then we can bump it to 25ms. But really, the 90% of k8s clusters are inside one dc where RTTs are <1ms

2019-09-05 20:48 UTC, rlenglet approved these changes

2019-09-05 20:52 UTC, howardjohn approved these changes

2019-09-05 21:09 UTC, istio-testing commented
@yxue: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
istio-unit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-unit-tests-master/6754) | `/test istio-unit-tests-master`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-05 21:09 UTC, yxue commented
/test istio-unit-tests-master

2019-09-05 21:17 UTC, ayj approved these changes
The test data change for galley conversion tests lgtm.

2019-09-05 21:18 UTC, istio-testing commented
@yxue: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
istio-unit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-unit-tests-master/6754) | `/test istio-unit-tests-master`
integ-mixer-k8s-presubmit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-mixer-k8s-presubmit-tests-master/4951) | `/test integ-mixer-k8s-presubmit-tests-master`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-05 21:32 UTC, istio-testing commented
@yxue: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-mixer-k8s-presubmit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-mixer-k8s-presubmit-tests-master/4951) | `/test integ-mixer-k8s-presubmit-tests-master`
istio-unit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-unit-tests-master/6757) | `/test istio-unit-tests-master`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-06 17:35 UTC, rshriram commented on pkg/config/mesh/mesh.go
> +		ProtocolDetectionTimeout:          types.DurationProto(100 * time.Millisecond),
you have to change the helm charts as well.

2019-09-06 17:40 UTC, rshriram approved these changes

2019-09-06 17:51 UTC, rlenglet commented
/test istio-unit-tests-master

2019-09-06 17:52 UTC, istio-testing commented
@yxue: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-mixer-k8s-presubmit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-mixer-k8s-presubmit-tests-master/4951) | `/test integ-mixer-k8s-presubmit-tests-master`
istio-unit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-unit-tests-master/6834) | `/test istio-unit-tests-master`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-06 18:04 UTC, istio-testing commented
@yxue: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-mixer-k8s-presubmit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-mixer-k8s-presubmit-tests-master/4951) | `/test integ-mixer-k8s-presubmit-tests-master`
istio-unit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-unit-tests-master/6834) | `/test istio-unit-tests-master`
istio-lint-master | 224ab746f97fb5d77c347969cfc628b8d7be4990 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-lint-master/4166) | `/test istio-lint-master`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-06 18:09 UTC, istio-testing commented
@yxue: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-mixer-k8s-presubmit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-mixer-k8s-presubmit-tests-master/4951) | `/test integ-mixer-k8s-presubmit-tests-master`
istio-lint-master | 224ab746f97fb5d77c347969cfc628b8d7be4990 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-lint-master/4166) | `/test istio-lint-master`
istio-unit-tests-master | 224ab746f97fb5d77c347969cfc628b8d7be4990 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-unit-tests-master/6835) | `/test istio-unit-tests-master`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-06 18:09 UTC, rlenglet commented
I messed up indentation when fixing merge conflicts today. Sorry @yxue.

2019-09-06 18:18 UTC, istio-testing commented
@yxue: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-mixer-k8s-presubmit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-mixer-k8s-presubmit-tests-master/4951) | `/test integ-mixer-k8s-presubmit-tests-master`
istio-lint-master | 224ab746f97fb5d77c347969cfc628b8d7be4990 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-lint-master/4166) | `/test istio-lint-master`
istio-unit-tests-master | 224ab746f97fb5d77c347969cfc628b8d7be4990 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-unit-tests-master/6835) | `/test istio-unit-tests-master`
integ-pilot-k8s-presubmit-tests-master | 224ab746f97fb5d77c347969cfc628b8d7be4990 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-pilot-k8s-presubmit-tests-master/5353) | `/test integ-pilot-k8s-presubmit-tests-master`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-06 18:18 UTC, istio-testing commented
@yxue: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2019-09-06 18:20 UTC, istio-testing commented
@yxue: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-mixer-k8s-presubmit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-mixer-k8s-presubmit-tests-master/4951) | `/test integ-mixer-k8s-presubmit-tests-master`
istio-lint-master | 224ab746f97fb5d77c347969cfc628b8d7be4990 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-lint-master/4166) | `/test istio-lint-master`
istio-unit-tests-master | 224ab746f97fb5d77c347969cfc628b8d7be4990 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-unit-tests-master/6835) | `/test istio-unit-tests-master`
integ-pilot-k8s-presubmit-tests-master | 224ab746f97fb5d77c347969cfc628b8d7be4990 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-pilot-k8s-presubmit-tests-master/5353) | `/test integ-pilot-k8s-presubmit-tests-master`
integ-galley-local-presubmit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-galley-local-presubmit-tests-master/5721) | `/test integ-galley-local-presubmit-tests-master`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-06 18:20 UTC, istio-testing commented
@yxue: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-mixer-k8s-presubmit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-mixer-k8s-presubmit-tests-master/4951) | `/test integ-mixer-k8s-presubmit-tests-master`
istio-lint-master | 224ab746f97fb5d77c347969cfc628b8d7be4990 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-lint-master/4166) | `/test istio-lint-master`
istio-unit-tests-master | 224ab746f97fb5d77c347969cfc628b8d7be4990 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-unit-tests-master/6835) | `/test istio-unit-tests-master`
integ-pilot-k8s-presubmit-tests-master | 224ab746f97fb5d77c347969cfc628b8d7be4990 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-pilot-k8s-presubmit-tests-master/5353) | `/test integ-pilot-k8s-presubmit-tests-master`
integ-galley-local-presubmit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-galley-local-presubmit-tests-master/5721) | `/test integ-galley-local-presubmit-tests-master`
istio-codecov-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-codecov-master/5160) | `/test istio-codecov-master`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-06 18:20 UTC, istio-testing commented
@yxue: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-mixer-k8s-presubmit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-mixer-k8s-presubmit-tests-master/4951) | `/test integ-mixer-k8s-presubmit-tests-master`
istio-lint-master | 224ab746f97fb5d77c347969cfc628b8d7be4990 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-lint-master/4166) | `/test istio-lint-master`
istio-unit-tests-master | 224ab746f97fb5d77c347969cfc628b8d7be4990 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-unit-tests-master/6835) | `/test istio-unit-tests-master`
integ-pilot-k8s-presubmit-tests-master | 224ab746f97fb5d77c347969cfc628b8d7be4990 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-pilot-k8s-presubmit-tests-master/5353) | `/test integ-pilot-k8s-presubmit-tests-master`
integ-galley-local-presubmit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-galley-local-presubmit-tests-master/5721) | `/test integ-galley-local-presubmit-tests-master`
istio-codecov-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-codecov-master/5160) | `/test istio-codecov-master`
integ-telemetry-k8s-presubmit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-telemetry-k8s-presubmit-tests-master/4136) | `/test integ-telemetry-k8s-presubmit-tests-master`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-06 18:21 UTC, istio-testing commented
@yxue: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-mixer-k8s-presubmit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-mixer-k8s-presubmit-tests-master/4951) | `/test integ-mixer-k8s-presubmit-tests-master`
istio-lint-master | 224ab746f97fb5d77c347969cfc628b8d7be4990 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-lint-master/4166) | `/test istio-lint-master`
istio-unit-tests-master | 224ab746f97fb5d77c347969cfc628b8d7be4990 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-unit-tests-master/6835) | `/test istio-unit-tests-master`
integ-pilot-k8s-presubmit-tests-master | 224ab746f97fb5d77c347969cfc628b8d7be4990 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-pilot-k8s-presubmit-tests-master/5353) | `/test integ-pilot-k8s-presubmit-tests-master`
integ-galley-local-presubmit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-galley-local-presubmit-tests-master/5721) | `/test integ-galley-local-presubmit-tests-master`
istio-codecov-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-codecov-master/5160) | `/test istio-codecov-master`
integ-telemetry-k8s-presubmit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-telemetry-k8s-presubmit-tests-master/4136) | `/test integ-telemetry-k8s-presubmit-tests-master`
istio_e2e_cloudfoundry-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio_e2e_cloudfoundry-master/3376) | `/test istio_e2e_cloudfoundry-master`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-06 18:21 UTC, istio-testing commented
@yxue: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
istio-lint-master | 224ab746f97fb5d77c347969cfc628b8d7be4990 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-lint-master/4166) | `/test istio-lint-master`
istio-unit-tests-master | 224ab746f97fb5d77c347969cfc628b8d7be4990 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-unit-tests-master/6835) | `/test istio-unit-tests-master`
integ-pilot-k8s-presubmit-tests-master | 224ab746f97fb5d77c347969cfc628b8d7be4990 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-pilot-k8s-presubmit-tests-master/5353) | `/test integ-pilot-k8s-presubmit-tests-master`
integ-galley-local-presubmit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-galley-local-presubmit-tests-master/5721) | `/test integ-galley-local-presubmit-tests-master`
istio-codecov-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-codecov-master/5160) | `/test istio-codecov-master`
integ-telemetry-k8s-presubmit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-telemetry-k8s-presubmit-tests-master/4136) | `/test integ-telemetry-k8s-presubmit-tests-master`
istio_e2e_cloudfoundry-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio_e2e_cloudfoundry-master/3376) | `/test istio_e2e_cloudfoundry-master`
integ-mixer-k8s-presubmit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-mixer-k8s-presubmit-tests-master/4991) | `/test integ-mixer-k8s-presubmit-tests-master`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-06 18:21 UTC, istio-testing commented
@yxue: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
istio-lint-master | 224ab746f97fb5d77c347969cfc628b8d7be4990 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-lint-master/4166) | `/test istio-lint-master`
istio-unit-tests-master | 224ab746f97fb5d77c347969cfc628b8d7be4990 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-unit-tests-master/6835) | `/test istio-unit-tests-master`
integ-pilot-k8s-presubmit-tests-master | 224ab746f97fb5d77c347969cfc628b8d7be4990 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-pilot-k8s-presubmit-tests-master/5353) | `/test integ-pilot-k8s-presubmit-tests-master`
integ-galley-local-presubmit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-galley-local-presubmit-tests-master/5721) | `/test integ-galley-local-presubmit-tests-master`
istio-codecov-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-codecov-master/5160) | `/test istio-codecov-master`
integ-telemetry-k8s-presubmit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-telemetry-k8s-presubmit-tests-master/4136) | `/test integ-telemetry-k8s-presubmit-tests-master`
istio_e2e_cloudfoundry-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio_e2e_cloudfoundry-master/3376) | `/test istio_e2e_cloudfoundry-master`
integ-mixer-k8s-presubmit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-mixer-k8s-presubmit-tests-master/4991) | `/test integ-mixer-k8s-presubmit-tests-master`
integ-istioctl-k8s-presubmit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-istioctl-k8s-presubmit-tests-master/4273) | `/test integ-istioctl-k8s-presubmit-tests-master`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-06 18:21 UTC, istio-testing commented
@yxue: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
istio-lint-master | 224ab746f97fb5d77c347969cfc628b8d7be4990 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-lint-master/4166) | `/test istio-lint-master`
istio-unit-tests-master | 224ab746f97fb5d77c347969cfc628b8d7be4990 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-unit-tests-master/6835) | `/test istio-unit-tests-master`
integ-pilot-k8s-presubmit-tests-master | 224ab746f97fb5d77c347969cfc628b8d7be4990 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-pilot-k8s-presubmit-tests-master/5353) | `/test integ-pilot-k8s-presubmit-tests-master`
integ-galley-local-presubmit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-galley-local-presubmit-tests-master/5721) | `/test integ-galley-local-presubmit-tests-master`
istio-codecov-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio-codecov-master/5160) | `/test istio-codecov-master`
integ-telemetry-k8s-presubmit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-telemetry-k8s-presubmit-tests-master/4136) | `/test integ-telemetry-k8s-presubmit-tests-master`
istio_e2e_cloudfoundry-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/istio_e2e_cloudfoundry-master/3376) | `/test istio_e2e_cloudfoundry-master`
integ-mixer-k8s-presubmit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-mixer-k8s-presubmit-tests-master/4991) | `/test integ-mixer-k8s-presubmit-tests-master`
integ-istioctl-k8s-presubmit-tests-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/integ-istioctl-k8s-presubmit-tests-master/4273) | `/test integ-istioctl-k8s-presubmit-tests-master`
e2e-simpleTestsMinProfile-master | d6ae5ae77f0d54566888ca30999a7dbb5b612a5e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16835/e2e-simpleTestsMinProfile-master/4085) | `/test e2e-simpleTestsMinProfile-master`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-06 19:22 UTC, merged

2019-09-06 19:22 UTC, istio-testing commented
In response to a cherrypick label: #16835 failed to apply on top of branch "release-1.3":
```Applying: increase timeout to 100ms
Applying: add timeout for virtual inbound listener
.git/rebase-apply/patch:14: trailing whitespace.
	
warning: 1 line adds whitespace errors.
error: Failed to merge in the changes.
Using index info to reconstruct a base tree...
M	pilot/pkg/features/pilot.go
Falling back to patching base and 3-way merge...
Auto-merging pilot/pkg/features/pilot.go
CONFLICT (content): Merge conflict in pilot/pkg/features/pilot.go
Patch failed at 0002 add timeout for virtual inbound listener

```

2019-09-06 19:47 UTC, rlenglet commented
@yxue Can you please create a manual backport PR? This is probably the same conflict we had this morning in `master`.