WIP: install: deploy ingressgateway as DaemonSet when "daemonsetEnabled: true"
istio/istio pull request #17184
Opened 2019-09-18 17:55 UTC by mnktsts2

Please provide a description for what this PR is for.

Makes `kind` of istio-ingressgateway pod template configurable for deploying as `DaemonSet` via Helm values. 

* if `gateways.istio-ingressgateway.daemonsetEnabled` is `false` or `nil`, istio-ingressgateway is deployed as `Deployment` as usual
  * and its `HorizontalAutoScaler` is also deployed
* if `gateways.istio-ingressgateway.daemonsetEnabled` is `true`, istio-ingressgateway is deployed as `DaemonSet` with `updateStrategy` field
  * and its `HorizontalAutoScaler` is NOT deployed

I think this flag is useful when "externalTrafficPolicy" is set to "Local".
How is it ?

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

2019-09-18 18:07 UTC, istio-testing commented
@mnktsts2: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
racetest_istio | 6fca7c95a362d59eb635920e261d1b7d4f14d982 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/17184/racetest_istio/510) | `/test racetest`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-09-18 18:07 UTC, howardjohn requested changes
We are trying to limit major changes here as the https://istio.io/docs/setup/install/operator/ will ship with charts from github.com/istio/installer. So I don't think we can merge this here, as it is a substantial change without testing, documentation, etc. I would recommend trying to send this to that repo

2019-09-19 15:10 UTC, mnktsts2 commented
@howardjohn Thank you for your advice.
As you said, I'll try to ask about this in github.com/istio/installer.

2019-09-19 15:10 UTC, closed without merging

2020-03-02 12:19 UTC, queeno commented
What is the status with this PR? The `github.com/istio/installer` PR has been automatically closed due to inactivity.

@howardjohn  Could this PR still be merged here?
It would be nice to have this functionality in the istio installer.

2020-06-10 04:02 UTC, Samith88 commented
This is a very important PR, i don't know why you guys are not considering this. :(

2021-04-13 08:52 UTC, mehyedes commented
> So I don't think we can merge this here, as it is a substantial change without testing, documentation, etc. I would recommend trying to send this to that repo
@howardjohn 
The https://github.com/istio/installer repo has been archived.

Would be great if this PR would be reconsidered as this is important for many people who prefer using the helm chart instead of the operator for installing Istio.