Workaround for Helm 2.15 regression
istio/istio pull request #18170
Opened 2019-10-22 15:53 UTC by howardjohn

`int` is broken on Helm 2.15. See
https://github.com/helm/helm/issues/6708

I don't see how anyone can use Helm 2.15 given the breakage, but might
as well support those users that do and fix this...

I did a diff of helm 2.14 and helm 2.15 and there were no changes after
this patch.

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

2019-10-22 16:52 UTC, rcernich approved these changes
lgtm

2019-10-22 16:55 UTC, howardjohn commented
Fixes https://github.com/istio/istio/issues/18172

2019-10-22 17:01 UTC, istio-testing commented
@howardjohn: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pilot-multicluster-e2e_istio | 79b7597ef8eb86eb372bc0abfae03f96fbf452f3 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18170/pilot-multicluster-e2e_istio/2034) | `/test pilot-multicluster-e2e_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-10-22 19:32 UTC, bacongobbler commented
If you want to hold out for a fix, we are actively working on one in https://github.com/helm/helm/pull/6709.

Sorry for not catching this bug sooner in the release process.

2019-10-22 19:47 UTC, sdake requested changes
I'm not sure how we can constantly be in the business of helm workarounds because Helm's CI failed to detect this use case.  I prefer a warning.

2019-10-22 19:50 UTC, sdake commented
> If you want to hold out for a fix, we are actively working on one in [helm/helm#6709](https://github.com/helm/helm/pull/6709). Worst case scenario, we revert the original PR and cut 2.15.1 without it, restoring old behaviour.
> 
> Sorry for not catching this bug sooner in the release process.

@bacongobbler the problem with holding off for the fix is the fact remains Helm 2.15 has been tagged and people have used it or are using it.  Months from now, some poor unsuspecting soul may come across a helm 2.15 tarball, and find out just how poorly of a choice they made when not following the warnings in the documentation.  This means either a doc fix (don't use that) or a code fix (workiaround this problem) is mandated for Iistio.

@frankbu fyi.

2019-10-22 20:06 UTC, howardjohn commented
>  find out just how poorly of a choice they made when not following the warnings in the documentation

I do not want a warning in our docs 6 months from now about how some old version of Helm may not work. Each warning has a very high cost. Our install docs should be "follow steps 1, 2, 3 and done", not "WARNING WARNING WARNING step 1 WARNING step 2.." it confuses users

2019-10-22 20:24 UTC, bacongobbler commented
For what it's worth, our [metrics from get.helm.sh](https://helm.sh/blog/get-helm-sh/) indicate that once a patch release is out, the amount of users actively using the previous patch releases drop significantly. Helm 2.14.2 downloads account for just under 3.5% of all downloads, compared to 2.14.3 which accounts for 36.7% of all downloads. 2.14.1 sits at 1.7%.

I would urge you to consider @howardjohn's point on this one. Pandering to only 1.5% of users running 2.15.0 in 6 months is going to confuse the community as a whole. Perhaps a "System Requirements" document explaining which versions of Helm are suported and which are not would be a better approach. We have to do the same for Helm, with a [Distribution Guide for various flavours of Kubernetes](https://helm.sh/docs/using_helm/#kubernetes-distribution-guide).

2019-10-23 00:51 UTC, howardjohn commented
By the time this gets to users helm will probably be patched anyways

2019-10-23 00:51 UTC, closed without merging