Inject alpn protocol for telemetry v2 to use metadata exchange filter
istio/istio pull request #18992
Opened 2019-11-15 18:10 UTC by gargnupur

Inject alpn protocol for telemetry v2 to use metadata exchange filter when using mTLS

This PR injects Alpn protocol named "istio-mixerless", to select metadata exchange filter in envoy.

2019-11-15 18:22 UTC, istio-testing commented
@gargnupur: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-local-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-local-tests_istio/3894) | `/test integ-security-local-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-15 18:24 UTC, istio-testing commented
@gargnupur: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-local-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-local-tests_istio/3894) | `/test integ-security-local-tests_istio`
unit-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/unit-tests_istio/4114) | `/test unit-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-15 18:25 UTC, rshriram requested changes
please let us not add yet another ALPN. We have had plenty of issues with respect to upgrades. Isn't there any other way?

2019-11-15 18:25 UTC, istio-testing commented
@gargnupur: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-local-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-local-tests_istio/3894) | `/test integ-security-local-tests_istio`
unit-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/unit-tests_istio/4114) | `/test unit-tests_istio`
e2e-mixer-no_auth_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/e2e-mixer-no_auth_istio/3940) | `/test e2e-mixer-no_auth_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-15 18:26 UTC, istio-testing commented
@gargnupur: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-local-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-local-tests_istio/3894) | `/test integ-security-local-tests_istio`
unit-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/unit-tests_istio/4114) | `/test unit-tests_istio`
e2e-mixer-no_auth_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/e2e-mixer-no_auth_istio/3940) | `/test e2e-mixer-no_auth_istio`
e2e-dashboard_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/e2e-dashboard_istio/3919) | `/test e2e-dashboard_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-15 18:31 UTC, istio-testing commented
@gargnupur: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-local-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-local-tests_istio/3894) | `/test integ-security-local-tests_istio`
unit-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/unit-tests_istio/4114) | `/test unit-tests_istio`
e2e-mixer-no_auth_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/e2e-mixer-no_auth_istio/3940) | `/test e2e-mixer-no_auth_istio`
e2e-dashboard_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/e2e-dashboard_istio/3919) | `/test e2e-dashboard_istio`
integ-istioio-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-istioio-k8s-tests_istio/1478) | `/test integ-istioio-k8s-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-15 18:32 UTC, istio-testing commented
@gargnupur: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-local-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-local-tests_istio/3894) | `/test integ-security-local-tests_istio`
unit-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/unit-tests_istio/4114) | `/test unit-tests_istio`
e2e-mixer-no_auth_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/e2e-mixer-no_auth_istio/3940) | `/test e2e-mixer-no_auth_istio`
e2e-dashboard_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/e2e-dashboard_istio/3919) | `/test e2e-dashboard_istio`
integ-istioio-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-istioio-k8s-tests_istio/1478) | `/test integ-istioio-k8s-tests_istio`
pilot-e2e-envoyv2-v1alpha3_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/pilot-e2e-envoyv2-v1alpha3_istio/3955) | `/test pilot-e2e-envoyv2-v1alpha3_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-15 18:37 UTC, istio-testing commented
@gargnupur: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-local-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-local-tests_istio/3894) | `/test integ-security-local-tests_istio`
unit-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/unit-tests_istio/4114) | `/test unit-tests_istio`
e2e-mixer-no_auth_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/e2e-mixer-no_auth_istio/3940) | `/test e2e-mixer-no_auth_istio`
e2e-dashboard_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/e2e-dashboard_istio/3919) | `/test e2e-dashboard_istio`
integ-istioio-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-istioio-k8s-tests_istio/1478) | `/test integ-istioio-k8s-tests_istio`
pilot-e2e-envoyv2-v1alpha3_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/pilot-e2e-envoyv2-v1alpha3_istio/3955) | `/test pilot-e2e-envoyv2-v1alpha3_istio`
pilot-multicluster-e2e_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/pilot-multicluster-e2e_istio/3214) | `/test pilot-multicluster-e2e_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-15 18:39 UTC, istio-testing commented
@gargnupur: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-local-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-local-tests_istio/3894) | `/test integ-security-local-tests_istio`
unit-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/unit-tests_istio/4114) | `/test unit-tests_istio`
e2e-mixer-no_auth_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/e2e-mixer-no_auth_istio/3940) | `/test e2e-mixer-no_auth_istio`
e2e-dashboard_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/e2e-dashboard_istio/3919) | `/test e2e-dashboard_istio`
integ-istioio-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-istioio-k8s-tests_istio/1478) | `/test integ-istioio-k8s-tests_istio`
pilot-e2e-envoyv2-v1alpha3_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/pilot-e2e-envoyv2-v1alpha3_istio/3955) | `/test pilot-e2e-envoyv2-v1alpha3_istio`
pilot-multicluster-e2e_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/pilot-multicluster-e2e_istio/3214) | `/test pilot-multicluster-e2e_istio`
integ-telemetry-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-telemetry-k8s-tests_istio/3953) | `/test integ-telemetry-k8s-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-15 18:45 UTC, istio-testing commented
@gargnupur: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-local-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-local-tests_istio/3894) | `/test integ-security-local-tests_istio`
unit-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/unit-tests_istio/4114) | `/test unit-tests_istio`
e2e-mixer-no_auth_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/e2e-mixer-no_auth_istio/3940) | `/test e2e-mixer-no_auth_istio`
e2e-dashboard_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/e2e-dashboard_istio/3919) | `/test e2e-dashboard_istio`
integ-istioio-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-istioio-k8s-tests_istio/1478) | `/test integ-istioio-k8s-tests_istio`
pilot-e2e-envoyv2-v1alpha3_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/pilot-e2e-envoyv2-v1alpha3_istio/3955) | `/test pilot-e2e-envoyv2-v1alpha3_istio`
pilot-multicluster-e2e_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/pilot-multicluster-e2e_istio/3214) | `/test pilot-multicluster-e2e_istio`
integ-telemetry-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-telemetry-k8s-tests_istio/3953) | `/test integ-telemetry-k8s-tests_istio`
integ-mixer-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-mixer-k8s-tests_istio/3107) | `/test integ-mixer-k8s-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-15 18:46 UTC, istio-testing commented
@gargnupur: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-local-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-local-tests_istio/3894) | `/test integ-security-local-tests_istio`
unit-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/unit-tests_istio/4114) | `/test unit-tests_istio`
e2e-mixer-no_auth_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/e2e-mixer-no_auth_istio/3940) | `/test e2e-mixer-no_auth_istio`
e2e-dashboard_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/e2e-dashboard_istio/3919) | `/test e2e-dashboard_istio`
integ-istioio-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-istioio-k8s-tests_istio/1478) | `/test integ-istioio-k8s-tests_istio`
pilot-e2e-envoyv2-v1alpha3_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/pilot-e2e-envoyv2-v1alpha3_istio/3955) | `/test pilot-e2e-envoyv2-v1alpha3_istio`
pilot-multicluster-e2e_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/pilot-multicluster-e2e_istio/3214) | `/test pilot-multicluster-e2e_istio`
integ-telemetry-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-telemetry-k8s-tests_istio/3953) | `/test integ-telemetry-k8s-tests_istio`
integ-mixer-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-mixer-k8s-tests_istio/3107) | `/test integ-mixer-k8s-tests_istio`
integ-new-install-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-new-install-k8s-tests_istio/3103) | `/test integ-new-install-k8s-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-15 18:46 UTC, yxue reviewed
+1 for @rshriram

2019-11-15 18:46 UTC, yxue commented on pilot/pkg/networking/core/v1alpha3/listener.go
> +	mtlsHTTPALPNs      = []string{"istio-http/1.0", "istio-http/1.1", "istio-h2", "istio-mixerless"}
This is not the place to inject the alpn. You should add those to `mtlsHTTP10ALPN`, etc.

2019-11-15 18:51 UTC, istio-testing commented
@gargnupur: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-local-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-local-tests_istio/3894) | `/test integ-security-local-tests_istio`
unit-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/unit-tests_istio/4114) | `/test unit-tests_istio`
e2e-mixer-no_auth_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/e2e-mixer-no_auth_istio/3940) | `/test e2e-mixer-no_auth_istio`
e2e-dashboard_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/e2e-dashboard_istio/3919) | `/test e2e-dashboard_istio`
integ-istioio-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-istioio-k8s-tests_istio/1478) | `/test integ-istioio-k8s-tests_istio`
pilot-e2e-envoyv2-v1alpha3_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/pilot-e2e-envoyv2-v1alpha3_istio/3955) | `/test pilot-e2e-envoyv2-v1alpha3_istio`
pilot-multicluster-e2e_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/pilot-multicluster-e2e_istio/3214) | `/test pilot-multicluster-e2e_istio`
integ-telemetry-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-telemetry-k8s-tests_istio/3953) | `/test integ-telemetry-k8s-tests_istio`
integ-mixer-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-mixer-k8s-tests_istio/3107) | `/test integ-mixer-k8s-tests_istio`
integ-new-install-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-new-install-k8s-tests_istio/3103) | `/test integ-new-install-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-pilot-k8s-tests_istio/3958) | `/test integ-pilot-k8s-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-15 19:12 UTC, istio-testing commented
@gargnupur: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-local-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-local-tests_istio/3894) | `/test integ-security-local-tests_istio`
unit-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/unit-tests_istio/4114) | `/test unit-tests_istio`
e2e-mixer-no_auth_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/e2e-mixer-no_auth_istio/3940) | `/test e2e-mixer-no_auth_istio`
e2e-dashboard_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/e2e-dashboard_istio/3919) | `/test e2e-dashboard_istio`
integ-istioio-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-istioio-k8s-tests_istio/1478) | `/test integ-istioio-k8s-tests_istio`
pilot-e2e-envoyv2-v1alpha3_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/pilot-e2e-envoyv2-v1alpha3_istio/3955) | `/test pilot-e2e-envoyv2-v1alpha3_istio`
pilot-multicluster-e2e_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/pilot-multicluster-e2e_istio/3214) | `/test pilot-multicluster-e2e_istio`
integ-telemetry-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-telemetry-k8s-tests_istio/3953) | `/test integ-telemetry-k8s-tests_istio`
integ-mixer-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-mixer-k8s-tests_istio/3107) | `/test integ-mixer-k8s-tests_istio`
integ-new-install-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-new-install-k8s-tests_istio/3103) | `/test integ-new-install-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-pilot-k8s-tests_istio/3958) | `/test integ-pilot-k8s-tests_istio`
integ-security-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-k8s-tests_istio/4130) | `/test integ-security-k8s-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-19 23:53 UTC, istio-testing commented
@gargnupur: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
unit-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/unit-tests_istio/4114) | `/test unit-tests_istio`
e2e-mixer-no_auth_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/e2e-mixer-no_auth_istio/3940) | `/test e2e-mixer-no_auth_istio`
e2e-dashboard_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/e2e-dashboard_istio/3919) | `/test e2e-dashboard_istio`
integ-istioio-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-istioio-k8s-tests_istio/1478) | `/test integ-istioio-k8s-tests_istio`
pilot-e2e-envoyv2-v1alpha3_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/pilot-e2e-envoyv2-v1alpha3_istio/3955) | `/test pilot-e2e-envoyv2-v1alpha3_istio`
pilot-multicluster-e2e_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/pilot-multicluster-e2e_istio/3214) | `/test pilot-multicluster-e2e_istio`
integ-telemetry-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-telemetry-k8s-tests_istio/3953) | `/test integ-telemetry-k8s-tests_istio`
integ-mixer-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-mixer-k8s-tests_istio/3107) | `/test integ-mixer-k8s-tests_istio`
integ-new-install-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-new-install-k8s-tests_istio/3103) | `/test integ-new-install-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-pilot-k8s-tests_istio/3958) | `/test integ-pilot-k8s-tests_istio`
integ-security-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-k8s-tests_istio/4130) | `/test integ-security-k8s-tests_istio`
integ-security-local-tests_istio | f8496eb92c9d0a0781d2648a3efd38f5f525ac12 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-local-tests_istio/3996) | `/test integ-security-local-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-19 23:56 UTC, istio-testing commented
@gargnupur: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
e2e-mixer-no_auth_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/e2e-mixer-no_auth_istio/3940) | `/test e2e-mixer-no_auth_istio`
integ-istioio-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-istioio-k8s-tests_istio/1478) | `/test integ-istioio-k8s-tests_istio`
pilot-e2e-envoyv2-v1alpha3_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/pilot-e2e-envoyv2-v1alpha3_istio/3955) | `/test pilot-e2e-envoyv2-v1alpha3_istio`
pilot-multicluster-e2e_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/pilot-multicluster-e2e_istio/3214) | `/test pilot-multicluster-e2e_istio`
integ-telemetry-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-telemetry-k8s-tests_istio/3953) | `/test integ-telemetry-k8s-tests_istio`
integ-mixer-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-mixer-k8s-tests_istio/3107) | `/test integ-mixer-k8s-tests_istio`
integ-new-install-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-new-install-k8s-tests_istio/3103) | `/test integ-new-install-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-pilot-k8s-tests_istio/3958) | `/test integ-pilot-k8s-tests_istio`
integ-security-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-k8s-tests_istio/4130) | `/test integ-security-k8s-tests_istio`
integ-security-local-tests_istio | f8496eb92c9d0a0781d2648a3efd38f5f525ac12 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-local-tests_istio/3996) | `/test integ-security-local-tests_istio`
unit-tests_istio | f8496eb92c9d0a0781d2648a3efd38f5f525ac12 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/unit-tests_istio/4217) | `/test unit-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-20 00:16 UTC, istio-testing commented
@gargnupur: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pilot-multicluster-e2e_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/pilot-multicluster-e2e_istio/3214) | `/test pilot-multicluster-e2e_istio`
integ-security-k8s-tests_istio | 9950d8b631b1712f4cb5c40b2be5a09be78d82f5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-k8s-tests_istio/4130) | `/test integ-security-k8s-tests_istio`
integ-security-local-tests_istio | f8496eb92c9d0a0781d2648a3efd38f5f525ac12 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-local-tests_istio/3996) | `/test integ-security-local-tests_istio`
unit-tests_istio | f8496eb92c9d0a0781d2648a3efd38f5f525ac12 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/unit-tests_istio/4217) | `/test unit-tests_istio`
integ-mixer-k8s-tests_istio | f8496eb92c9d0a0781d2648a3efd38f5f525ac12 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-mixer-k8s-tests_istio/3189) | `/test integ-mixer-k8s-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-20 19:30 UTC, istio-testing commented
@gargnupur: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
unit-tests_istio | f8496eb92c9d0a0781d2648a3efd38f5f525ac12 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/unit-tests_istio/4217) | `/test unit-tests_istio`
integ-mixer-k8s-tests_istio | f8496eb92c9d0a0781d2648a3efd38f5f525ac12 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-mixer-k8s-tests_istio/3189) | `/test integ-mixer-k8s-tests_istio`
integ-security-local-tests_istio | 651037b6534bbe6d14045056797b30c01e70087c | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-local-tests_istio/4036) | `/test integ-security-local-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-20 19:31 UTC, istio-testing commented
@gargnupur: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-mixer-k8s-tests_istio | f8496eb92c9d0a0781d2648a3efd38f5f525ac12 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-mixer-k8s-tests_istio/3189) | `/test integ-mixer-k8s-tests_istio`
integ-security-local-tests_istio | 651037b6534bbe6d14045056797b30c01e70087c | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-local-tests_istio/4036) | `/test integ-security-local-tests_istio`
unit-tests_istio | 651037b6534bbe6d14045056797b30c01e70087c | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/unit-tests_istio/4258) | `/test unit-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-20 20:01 UTC, istio-testing commented
@gargnupur: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-local-tests_istio | 651037b6534bbe6d14045056797b30c01e70087c | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-local-tests_istio/4036) | `/test integ-security-local-tests_istio`
unit-tests_istio | 651037b6534bbe6d14045056797b30c01e70087c | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/unit-tests_istio/4258) | `/test unit-tests_istio`
integ-mixer-k8s-tests_istio | 651037b6534bbe6d14045056797b30c01e70087c | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-mixer-k8s-tests_istio/3223) | `/test integ-mixer-k8s-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-20 22:16 UTC, istio-testing commented
@gargnupur: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
unit-tests_istio | 651037b6534bbe6d14045056797b30c01e70087c | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/unit-tests_istio/4258) | `/test unit-tests_istio`
integ-mixer-k8s-tests_istio | 651037b6534bbe6d14045056797b30c01e70087c | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-mixer-k8s-tests_istio/3223) | `/test integ-mixer-k8s-tests_istio`
integ-security-local-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-local-tests_istio/4042) | `/test integ-security-local-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-20 22:20 UTC, istio-testing commented
@gargnupur: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-mixer-k8s-tests_istio | 651037b6534bbe6d14045056797b30c01e70087c | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-mixer-k8s-tests_istio/3223) | `/test integ-mixer-k8s-tests_istio`
integ-security-local-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-local-tests_istio/4042) | `/test integ-security-local-tests_istio`
unit-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/unit-tests_istio/4264) | `/test unit-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-20 22:31 UTC, istio-testing commented
@gargnupur: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-mixer-k8s-tests_istio | 651037b6534bbe6d14045056797b30c01e70087c | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-mixer-k8s-tests_istio/3223) | `/test integ-mixer-k8s-tests_istio`
integ-security-local-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-local-tests_istio/4042) | `/test integ-security-local-tests_istio`
unit-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/unit-tests_istio/4264) | `/test unit-tests_istio`
pilot-e2e-envoyv2-v1alpha3_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/pilot-e2e-envoyv2-v1alpha3_istio/4107) | `/test pilot-e2e-envoyv2-v1alpha3_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-20 22:38 UTC, istio-testing commented
@gargnupur: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-mixer-k8s-tests_istio | 651037b6534bbe6d14045056797b30c01e70087c | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-mixer-k8s-tests_istio/3223) | `/test integ-mixer-k8s-tests_istio`
integ-security-local-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-local-tests_istio/4042) | `/test integ-security-local-tests_istio`
unit-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/unit-tests_istio/4264) | `/test unit-tests_istio`
pilot-e2e-envoyv2-v1alpha3_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/pilot-e2e-envoyv2-v1alpha3_istio/4107) | `/test pilot-e2e-envoyv2-v1alpha3_istio`
integ-pilot-k8s-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-pilot-k8s-tests_istio/4110) | `/test integ-pilot-k8s-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-20 22:39 UTC, istio-testing commented
@gargnupur: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-mixer-k8s-tests_istio | 651037b6534bbe6d14045056797b30c01e70087c | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-mixer-k8s-tests_istio/3223) | `/test integ-mixer-k8s-tests_istio`
integ-security-local-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-local-tests_istio/4042) | `/test integ-security-local-tests_istio`
unit-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/unit-tests_istio/4264) | `/test unit-tests_istio`
pilot-e2e-envoyv2-v1alpha3_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/pilot-e2e-envoyv2-v1alpha3_istio/4107) | `/test pilot-e2e-envoyv2-v1alpha3_istio`
integ-pilot-k8s-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-pilot-k8s-tests_istio/4110) | `/test integ-pilot-k8s-tests_istio`
integ-new-install-k8s-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-new-install-k8s-tests_istio/3254) | `/test integ-new-install-k8s-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-20 22:50 UTC, istio-testing commented
@gargnupur: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-local-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-local-tests_istio/4042) | `/test integ-security-local-tests_istio`
unit-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/unit-tests_istio/4264) | `/test unit-tests_istio`
pilot-e2e-envoyv2-v1alpha3_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/pilot-e2e-envoyv2-v1alpha3_istio/4107) | `/test pilot-e2e-envoyv2-v1alpha3_istio`
integ-pilot-k8s-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-pilot-k8s-tests_istio/4110) | `/test integ-pilot-k8s-tests_istio`
integ-new-install-k8s-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-new-install-k8s-tests_istio/3254) | `/test integ-new-install-k8s-tests_istio`
integ-mixer-k8s-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-mixer-k8s-tests_istio/3229) | `/test integ-mixer-k8s-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-20 22:51 UTC, istio-testing commented
@gargnupur: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-local-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-local-tests_istio/4042) | `/test integ-security-local-tests_istio`
unit-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/unit-tests_istio/4264) | `/test unit-tests_istio`
pilot-e2e-envoyv2-v1alpha3_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/pilot-e2e-envoyv2-v1alpha3_istio/4107) | `/test pilot-e2e-envoyv2-v1alpha3_istio`
integ-pilot-k8s-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-pilot-k8s-tests_istio/4110) | `/test integ-pilot-k8s-tests_istio`
integ-new-install-k8s-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-new-install-k8s-tests_istio/3254) | `/test integ-new-install-k8s-tests_istio`
integ-mixer-k8s-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-mixer-k8s-tests_istio/3229) | `/test integ-mixer-k8s-tests_istio`
pilot-multicluster-e2e_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/pilot-multicluster-e2e_istio/3374) | `/test pilot-multicluster-e2e_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-20 22:51 UTC, istio-testing commented
@gargnupur: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-local-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-local-tests_istio/4042) | `/test integ-security-local-tests_istio`
unit-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/unit-tests_istio/4264) | `/test unit-tests_istio`
pilot-e2e-envoyv2-v1alpha3_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/pilot-e2e-envoyv2-v1alpha3_istio/4107) | `/test pilot-e2e-envoyv2-v1alpha3_istio`
integ-pilot-k8s-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-pilot-k8s-tests_istio/4110) | `/test integ-pilot-k8s-tests_istio`
integ-new-install-k8s-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-new-install-k8s-tests_istio/3254) | `/test integ-new-install-k8s-tests_istio`
integ-mixer-k8s-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-mixer-k8s-tests_istio/3229) | `/test integ-mixer-k8s-tests_istio`
pilot-multicluster-e2e_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/pilot-multicluster-e2e_istio/3374) | `/test pilot-multicluster-e2e_istio`
integ-security-k8s-tests_istio | eeb7e2182ddfab297c63569db1b88c9385f87284 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18992/integ-security-k8s-tests_istio/4281) | `/test integ-security-k8s-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-26 18:13 UTC, gargnupur commented
/cc @rshriram , @mandarjog , @kyessenov 
Keeping a hold on this PR for now.. as we evaluate auto-mtls approach

2019-12-11 20:16 UTC, closed without merging