add option to use unix domain socket as Envoy admin endpoint
istio/istio pull request #20931
Opened 2020-02-07 08:59 UTC by yxue

Issue: https://github.com/istio/istio/issues/19684

API change PR: https://github.com/istio/api/pull/1278

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

2020-02-07 09:36 UTC, istio-testing commented
@yxue: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | 1ba8711de14b596160e71a7e04190279b91135a1 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/20931/integ-pilot-k8s-tests_istio/7912) | `/test integ-pilot-k8s-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-02-07 12:38 UTC, jwendell commented on install/kubernetes/helm/istio/values.yaml
> +    # Specify whether use TCP loopback address as Envoy admin endpoint.
Are we still updating helm charts? Those changes should go in operator, no?

2020-02-07 14:55 UTC, howardjohn requested changes
it seems like the proper place for this is in mesh config. Is there really a requirement to make it configurable as an annotation and not mesh wide?

2020-02-07 15:32 UTC, rlenglet requested changes

2020-02-07 15:32 UTC, rlenglet commented on install/kubernetes/helm/istio/files/injection-template.yaml
> +  - --httpAdminEndpoint
This needs to be renamed. Envoy's admin interface always uses HTTP regardless of whether is over TCP or UDS.

2020-02-07 15:32 UTC, rlenglet commented on install/kubernetes/helm/istio/values.yaml
> +    # If it's set to false, unix domain socket will be used for admin endpoint.
I think this is the wrong logic. This shouldn't be an either/or setting. Envoy should be configured to use UDS unconditionally for the admin interface. The option should be about enabling a TCP proxy to the admin interface in pilot-agent.

2020-02-07 17:23 UTC, rshriram requested changes
Repeating what I said in the API PR
I think this PR needs a larger discussion to identify if this is really an issue. It is a question of usability vs paranoia and I would prefer to enable usability first. If you wish, create an annotation to specify the admin endpoint completely. Interested users can specify their own unix domain socket or any other port they wish (it increases the burden for people who are paranoid about this but not for people who are (currently) okay with this).

2020-02-13 04:05 UTC, istio-testing commented
@yxue: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2020-02-20 16:51 UTC, istio-testing commented
@yxue: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-local-tests_istio | 1ba8711de14b596160e71a7e04190279b91135a1 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/20931/integ-local-tests_istio/30) | `/test integ-local-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-03-23 18:43 UTC, istio-testing commented
@yxue: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-local-tests_istio | 1ba8711de14b596160e71a7e04190279b91135a1 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/20931/integ-local-tests_istio/30) | `/test integ-local-tests_istio`
integ-multicluster-k8s-tests_istio | 1ba8711de14b596160e71a7e04190279b91135a1 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/20931/integ-multicluster-k8s-tests_istio/614) | `/test integ-multicluster-k8s-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-03-24 05:07 UTC, closed without merging