Support for variable setting sidcar.
istio/istio pull request #21179
Opened 2020-02-16 11:36 UTC by wangfakang

Sidcar can be specified with helm, for example `helm template install/kubernetes/helm/istio  --name istio --namespace istio-system --set global.sidcar.binaryPath=/user/bin/${sidcar}`. This makes it easier to support multiple sidcars later in Istio.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

2020-02-16 11:36 UTC, istio-testing commented
Hi @wangfakang. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2020-02-16 14:15 UTC, wangfakang commented
> Thanks for your pull request. It looks like this may be your first contribution to a Google open source project (if not, look below for help). Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please visit https://cla.developers.google.com/ to sign.**
> 
> Once you've signed (or fixed any issues), please reply here with `@googlebot I signed it!` and we'll verify it.
> 
> #### What to do if you already signed the CLA
> ##### Individual signers
> * It's possible we don't have your GitHub username or you're using a different email address on your commit. Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> 
> ##### Corporate signers
> * Your company has a Point of Contact who decides which employees are authorized to participate. Ask your POC to be added to the group of authorized contributors. If you don't know who your Point of Contact is, direct the Google project maintainer to [go/cla#troubleshoot](http://go/cla#troubleshoot) ([Public version](https://opensource.google/docs/cla/#troubleshoot)).
> * The email used to register you as an authorized contributor must be the email used for the Git commit. Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * The email used to register you as an authorized contributor must also be [attached to your GitHub account](https://github.com/settings/emails).
> 
> ℹ️ **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fistio%2Fistio%2Fpull%2F21179) for more info**.

@googlebot I signed it!

2020-02-16 15:45 UTC, howardjohn requested changes
This folder is deprecated and will be removed within a week or so. If you want to submit this change please send it to the manifests/ folder 

However, I am fairly sure this change is not needed in manifests and already supported, since all values in mesh config are read directly

2020-02-19 19:35 UTC, istio-testing commented
@wangfakang: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2020-02-20 00:27 UTC, howardjohn commented
We have removed this file

2020-02-20 00:27 UTC, closed without merging

2020-03-23 08:38 UTC, wangfakang commented
> This folder is deprecated and will be removed within a week or so. If you want to submit this change please send it to the manifests/ folder
> 
> However, I am fairly sure this change is not needed in manifests and already supported, since all values in mesh config are read directly

@wangfakang  

How to add custom variables when use `istioctl` to install Istio ?

forexample :

I hope `istioctl manifest generate  --set values.global.sidecar.binarypath="/user/bin/envoy"` could set `binaryPath`, but now it will return errors

```
Error: validation errors (use --force to override):
unknown field "sidecar" in v1alpha1.GlobalConfig

```

![image](https://user-images.githubusercontent.com/8215757/77297324-106c3a80-6d24-11ea-9358-1828ddb1c0f7.png)