Fix extra .Value in deployment file for stackdriver tracing vars
istio/istio pull request #21218
Opened 2020-02-18 18:35 UTC by gargnupur

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

2020-02-18 18:44 UTC, bianpengyuan approved these changes

2020-02-18 18:46 UTC, howardjohn requested changes
what is this needed for? these are legacy install charts that are about to be removed and do not support telemetry v2?

2020-02-18 18:53 UTC, istio-testing commented
@gargnupur: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
unit-tests_istio | 89d467475ef2277b19f884ebee5a9f53bbb5b2fe | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21218/unit-tests_istio/8754) | `/test unit-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-02-18 18:57 UTC, gargnupur commented
> what is this needed for? these are legacy install charts that are about to be removed and do not support telemetry v2?

This was added in https://github.com/istio/istio/pull/21005/files#diff-e6fff6556e114913dd0fb810c79eaada and is not correct. So, fixing it so that we don't have wrong values.. if this file itself will be removed soon, then we can skip this PR.

2020-02-18 19:35 UTC, istio-testing commented
@gargnupur: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2020-02-20 16:43 UTC, istio-testing commented
@gargnupur: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
unit-tests_istio | 89d467475ef2277b19f884ebee5a9f53bbb5b2fe | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21218/unit-tests_istio/8754) | `/test unit-tests_istio`
integ-local-tests_istio | 89d467475ef2277b19f884ebee5a9f53bbb5b2fe | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21218/integ-local-tests_istio/16) | `/test integ-local-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-02-25 21:03 UTC, gargnupur commented
Looks like this file is deleted for Istio 1.6. Will create a PR targeting 1.5 directly.

2020-02-25 21:03 UTC, closed without merging