Remove istiod.enabled
istio/istio pull request #21685
Opened 2020-03-01 14:59 UTC by clyang82

Signed-off-by: clyang82 <clyang@cn.ibm.com>

Remove istiod.enabled which is not used anymore.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

2020-03-01 15:07 UTC, istio-testing commented
@clyang82: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | c66c8fc4b0c3e262210287fa49a9080e7d2e6179 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21685/gencheck_istio/7618) | `/test gencheck_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-03-01 15:12 UTC, istio-testing commented
@clyang82: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | c66c8fc4b0c3e262210287fa49a9080e7d2e6179 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21685/gencheck_istio/7618) | `/test gencheck_istio`
unit-tests_istio | c66c8fc4b0c3e262210287fa49a9080e7d2e6179 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21685/unit-tests_istio/9475) | `/test unit-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-03-02 02:03 UTC, istio-testing commented
@clyang82: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
unit-tests_istio | c66c8fc4b0c3e262210287fa49a9080e7d2e6179 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21685/unit-tests_istio/9475) | `/test unit-tests_istio`
gencheck_istio | 0fd03f50481bf4ef37d0e3f1b6b9e82bf1ca525c | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21685/gencheck_istio/7624) | `/test gencheck_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-03-02 02:09 UTC, istio-testing commented
@clyang82: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | 0fd03f50481bf4ef37d0e3f1b6b9e82bf1ca525c | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21685/gencheck_istio/7624) | `/test gencheck_istio`
unit-tests_istio | 0fd03f50481bf4ef37d0e3f1b6b9e82bf1ca525c | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21685/unit-tests_istio/9481) | `/test unit-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-03-02 02:31 UTC, istio-testing commented
@clyang82: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
unit-tests_istio | 0fd03f50481bf4ef37d0e3f1b6b9e82bf1ca525c | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21685/unit-tests_istio/9481) | `/test unit-tests_istio`
gencheck_istio | f700d518d6a382d6ed29a341424749cf1cc2a3ee | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21685/gencheck_istio/7625) | `/test gencheck_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-03-02 16:21 UTC, howardjohn commented on operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
> +            - MUTUAL_TLS
this does not look correct, it should be NONE. we probably need to remove this flag longer term

2020-03-05 21:56 UTC, howardjohn requested changes
can you revert the control plane auth part?

2020-03-06 01:51 UTC, clyang82 commented
> can you revert the control plane auth part?

@howardjohn from the code changes, you will see the `istiod.enable` is only used by `prometheus` deployment. so I think `istiod.enabled` can be able to remove. anyway, let me double check today. Thanks.

2020-03-08 11:29 UTC, clyang82 commented
@howardjohn I just removed the istiod.enabled in 
```
global.yaml
operator/data/profiles/default.yaml
operator/data/profiles/separate.yaml
manifests/istio-telemetry/prometheus/templates/deployment.yaml
```
then run `make gen`, it updates the others automatically. What do you mean `revert the control plane auth part`?

2020-03-08 15:01 UTC, howardjohn commented
If you are just changing a value that was always true, then the generated output should not change. But in this case it did change

2020-03-12 09:53 UTC, istio-testing commented
@clyang82: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | 30f76a6d0a9ce2a241b3953b566d7c4b444b0149 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21685/gencheck_istio/8218) | `/test gencheck_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-03-12 09:57 UTC, istio-testing commented
@clyang82: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | 30f76a6d0a9ce2a241b3953b566d7c4b444b0149 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21685/gencheck_istio/8218) | `/test gencheck_istio`
unit-tests_istio | 30f76a6d0a9ce2a241b3953b566d7c4b444b0149 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21685/unit-tests_istio/10092) | `/test unit-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-03-12 10:57 UTC, istio-testing commented
@clyang82: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
unit-tests_istio | 30f76a6d0a9ce2a241b3953b566d7c4b444b0149 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21685/unit-tests_istio/10092) | `/test unit-tests_istio`
integ-local-tests_istio | 50546211261a1966cb9728fd063692691ea9dbe8 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21685/integ-local-tests_istio/1196) | `/test integ-local-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-03-12 10:57 UTC, istio-testing commented
@clyang82: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-local-tests_istio | 50546211261a1966cb9728fd063692691ea9dbe8 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21685/integ-local-tests_istio/1196) | `/test integ-local-tests_istio`
unit-tests_istio | 50546211261a1966cb9728fd063692691ea9dbe8 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21685/unit-tests_istio/10093) | `/test unit-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-03-22 00:58 UTC, istio-testing commented
@clyang82: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2020-03-23 18:33 UTC, istio-testing commented
@clyang82: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-local-tests_istio | 50546211261a1966cb9728fd063692691ea9dbe8 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21685/integ-local-tests_istio/1196) | `/test integ-local-tests_istio`
unit-tests_istio | 50546211261a1966cb9728fd063692691ea9dbe8 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21685/unit-tests_istio/10093) | `/test unit-tests_istio`
integ-multicluster-k8s-tests_istio | 50546211261a1966cb9728fd063692691ea9dbe8 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21685/integ-multicluster-k8s-tests_istio/603) | `/test integ-multicluster-k8s-tests_istio`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-04-23 05:09 UTC, closed without merging