fix service overlay for tracing service.
istio/istio pull request #22747
Opened 2020-04-06 10:36 UTC by morvencao

Please provide a description for what this PR is for.
resolve: https://github.com/istio/istio/issues/22726

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

2020-04-06 14:32 UTC, howardjohn requested changes
I think this will break existing users, require docs updates, etc?

2020-04-06 14:32 UTC, howardjohn commented on manifests/istio-telemetry/tracing/templates/service.yaml
> +  name: istio-tracing
this is a backwards incompatible change

2020-05-01 21:45 UTC, dex80526 commented
@morvencao: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2020-05-02 20:22 UTC, istio-testing commented
@morvencao: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2020-05-22 05:09 UTC, closed without merging