Disable DNS feature by default
istio/istio pull request #22758
Opened 2020-04-06 21:07 UTC by howardjohn

This was accidentally enabled by default (or accidentally approved when
it was enabled by default). We should not be enabling new features by
default, especially ones like this that are adding new containers.

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

2020-04-06 21:14 UTC, istio-testing commented
@howardjohn: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | d4a29c2616a22c72d64de221e64de48b7f452784 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/22758/lint_istio/10903) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-04-07 11:44 UTC, rshriram reviewed
Costin said he will send a subsequent pr to have a proper toggle to disable/enable it in couple of days. That’s why I was okay with the pr:)

2020-04-07 15:13 UTC, costinm reviewed
Let's leave the DNS-TLS on and just disable DNS_CAPTURE - if it really creates problems. 

We DO enable features by default during development - so they get coverage. We should not 
enable it in the release - but that's how we tested many other important features - autocapture, istiod, etc.

2020-04-07 15:15 UTC, costinm commented
And the reason for leaving DNS-TLS on is that capture can be enabled with a pod annotation.

This feature is an important security improvement - we have not yet decided on enabling it by 
default in 'strict' mode, but at the very least it should be possible to enable it for 'security sensitive'
workloads.

2020-04-07 15:17 UTC, costinm commented
@rshriram it was merged over weekend - we're still few days. I want to wait until we get some bugs or more feedback - like see if it impacts the metrics in perf clusters, etc. 

What's the hurry to turn it off ?

2020-04-07 15:47 UTC, costinm requested changes
Approving the change - but requesting a 1-week hold, so we can get feedback from the tests and perf clusters.

How is testing going for the multi-control plane ? Do we have any tests deploying a canary + prod versions of istiod ? If yes, can we turn it on in canary ?

2020-04-08 18:42 UTC, costinm approved these changes
Found a better way to handle DNS, will remove the coredns sidecar shortly.

2020-04-08 19:12 UTC, merged