Apply global.proxy.excludeIPRanges to istio-cni
istio/istio pull request #22889
Opened 2020-04-12 15:50 UTC by cagataygurturk

Enables the CNI plugin to respect global.proxy.excludeIPRanges configuration value.

Fixes #19939
Depends on istio/cni#293

[ ] Configuration Infrastructure
[ ] Docs
[ x] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

2020-04-12 15:50 UTC, istio-testing commented
Hi @cagataygurturk. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2020-04-12 23:50 UTC, rlenglet commented
/ok-to-test

2020-04-13 03:34 UTC, rlenglet requested changes
This PR is not necessary.
The same can already be configured using existing configuration mechanisms.
Cf. my comments in https://github.com/istio/cni/pull/293#pullrequestreview-391934795

2020-04-13 15:37 UTC, cagataygurturk commented
See 

#22902
istio/cni#293

2020-04-13 15:37 UTC, closed without merging