Multi-version configuration initial support
istio/istio pull request #23104
Opened 2020-04-21 06:26 UTC by jasonwzm

Please provide a description for what this PR is for.
Provides a permanent fix for https://github.com/istio/istio/issues/20449

Initial implementation of https://github.com/istio/istio/issues/2119

This PR adds multi-version config for Istio resources. As a result, validation webhook is able to validate v1beta1 and v1alpha3 networking configuration (see changes in `validation.go`).

Version conversion coming in another PR.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[] User Experience
[ ] Developer Infrastructure

2020-04-21 06:30 UTC, istio-testing commented
@jasonwzm: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | a9ef9e696044ff288dd094c3374a37724869c62e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/lint_istio/11548) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-04-21 06:41 UTC, istio-testing commented
@jasonwzm: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | a9ef9e696044ff288dd094c3374a37724869c62e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/lint_istio/11548) | `/test lint_istio`
integ-galley-k8s-tests_istio | a9ef9e696044ff288dd094c3374a37724869c62e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/integ-galley-k8s-tests_istio/11544) | `/test integ-galley-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-04-21 06:41 UTC, istio-testing commented
@jasonwzm: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | a9ef9e696044ff288dd094c3374a37724869c62e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/lint_istio/11548) | `/test lint_istio`
integ-galley-k8s-tests_istio | a9ef9e696044ff288dd094c3374a37724869c62e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/integ-galley-k8s-tests_istio/11544) | `/test integ-galley-k8s-tests_istio`
unit-tests_istio | a9ef9e696044ff288dd094c3374a37724869c62e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/unit-tests_istio/12027) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-04-21 06:49 UTC, istio-testing commented
@jasonwzm: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | a9ef9e696044ff288dd094c3374a37724869c62e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/lint_istio/11548) | `/test lint_istio`
integ-galley-k8s-tests_istio | a9ef9e696044ff288dd094c3374a37724869c62e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/integ-galley-k8s-tests_istio/11544) | `/test integ-galley-k8s-tests_istio`
unit-tests_istio | a9ef9e696044ff288dd094c3374a37724869c62e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/unit-tests_istio/12027) | `/test unit-tests_istio`
integ-pilot-k8s-tests_istio | a9ef9e696044ff288dd094c3374a37724869c62e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/integ-pilot-k8s-tests_istio/11600) | `/test integ-pilot-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-04-21 08:29 UTC, istio-testing commented
@jasonwzm: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | a9ef9e696044ff288dd094c3374a37724869c62e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/lint_istio/11548) | `/test lint_istio`
integ-galley-k8s-tests_istio | a9ef9e696044ff288dd094c3374a37724869c62e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/integ-galley-k8s-tests_istio/11544) | `/test integ-galley-k8s-tests_istio`
unit-tests_istio | a9ef9e696044ff288dd094c3374a37724869c62e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/unit-tests_istio/12027) | `/test unit-tests_istio`
integ-pilot-k8s-tests_istio | a9ef9e696044ff288dd094c3374a37724869c62e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/integ-pilot-k8s-tests_istio/11600) | `/test integ-pilot-k8s-tests_istio`
integ-local-tests_istio | a9ef9e696044ff288dd094c3374a37724869c62e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/integ-local-tests_istio/3110) | `/test integ-local-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-04-21 14:52 UTC, howardjohn commented
Please revert the assetts.gen change, we do not check that in anymore

2020-04-21 14:55 UTC, howardjohn reviewed
lgtm overall

2020-04-21 14:56 UTC, howardjohn commented
> Version conversion coming in another PR.

Can you please elaborate on this? Is this https://docs.google.com/document/d/1js1x0vf9H7kqknGwTyHhzPe9L7gG-dNIhC6ypPsKm3g?

2020-04-24 18:11 UTC, istio-testing commented
@jasonwzm: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | a9ef9e696044ff288dd094c3374a37724869c62e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/lint_istio/11548) | `/test lint_istio`
integ-galley-k8s-tests_istio | a9ef9e696044ff288dd094c3374a37724869c62e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/integ-galley-k8s-tests_istio/11544) | `/test integ-galley-k8s-tests_istio`
unit-tests_istio | a9ef9e696044ff288dd094c3374a37724869c62e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/unit-tests_istio/12027) | `/test unit-tests_istio`
integ-pilot-k8s-tests_istio | a9ef9e696044ff288dd094c3374a37724869c62e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/integ-pilot-k8s-tests_istio/11600) | `/test integ-pilot-k8s-tests_istio`
integ-local-tests_istio | a9ef9e696044ff288dd094c3374a37724869c62e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/integ-local-tests_istio/3110) | `/test integ-local-tests_istio`
gencheck_istio | 21dca79ef8d9562c2040626792ba961c434d6de3 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/gencheck_istio/10440) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-04-24 18:16 UTC, jasonwzm commented
@howardjohn yes, I think the main concern you had was around multi control plane. When the doc was written, we did not think too much about that. Let me sync offline on this topic and will add to the doc and also discuss with you. This PR should be good to go once tests pass.

2020-04-24 18:22 UTC, istio-testing commented
@jasonwzm: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-galley-k8s-tests_istio | a9ef9e696044ff288dd094c3374a37724869c62e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/integ-galley-k8s-tests_istio/11544) | `/test integ-galley-k8s-tests_istio`
unit-tests_istio | a9ef9e696044ff288dd094c3374a37724869c62e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/unit-tests_istio/12027) | `/test unit-tests_istio`
integ-pilot-k8s-tests_istio | a9ef9e696044ff288dd094c3374a37724869c62e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/integ-pilot-k8s-tests_istio/11600) | `/test integ-pilot-k8s-tests_istio`
integ-local-tests_istio | a9ef9e696044ff288dd094c3374a37724869c62e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/integ-local-tests_istio/3110) | `/test integ-local-tests_istio`
gencheck_istio | 5c3d4bf52ba47ceca36d1335933a22121ab2e3b5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/gencheck_istio/10441) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-04-24 18:27 UTC, istio-testing commented
@jasonwzm: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | a9ef9e696044ff288dd094c3374a37724869c62e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/integ-pilot-k8s-tests_istio/11600) | `/test integ-pilot-k8s-tests_istio`
integ-local-tests_istio | a9ef9e696044ff288dd094c3374a37724869c62e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/integ-local-tests_istio/3110) | `/test integ-local-tests_istio`
gencheck_istio | 5c3d4bf52ba47ceca36d1335933a22121ab2e3b5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/gencheck_istio/10441) | `/test gencheck_istio`
unit-tests_istio | 5c3d4bf52ba47ceca36d1335933a22121ab2e3b5 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/unit-tests_istio/12343) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-04-24 18:47 UTC, esnible approved these changes

2020-04-24 18:55 UTC, istio-testing commented
@jasonwzm: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
unit-tests_istio | fe9d065d7bd62df4a35f542f7a0d5bc8592ab439 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/unit-tests_istio/12347) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-04-24 19:27 UTC, howardjohn commented
@jasonwzm why are you sending a PR for a design that is not approved?

2020-04-24 19:31 UTC, jasonwzm commented
@howardjohn This PR is more about a permanent fix for https://github.com/istio/istio/issues/20449 rather a complete implementation of the multi version conversion design. This PR does not involve any version conversion.

2020-04-24 19:33 UTC, howardjohn commented
@jasonwzm I don't have concerns with this PR, just the theoretical future pr

2020-04-24 19:34 UTC, howardjohn commented
I was waiting for tests to pass to review

2020-04-24 20:03 UTC, jasonwzm commented
@howardjohn will talk more about your concerns in the doc. fixing the unit test now.

2020-04-24 23:22 UTC, howardjohn requested changes
I am really confused here. Why are we watching multiple versions of the same object? This just means 2x the load on the api server for no benefit. As far as I understand it, the whole basis for k8s versioning is that you just read/write a single version and it automagically (through conversion webhooks or otherwise) handles things for you?

At the very least, we are triggering 2x events on every CRD change for things with multiple versions, so we cannot merge as is

2020-04-24 23:53 UTC, howardjohn requested changes
This does not fix the main problem - Pilot CRD reader in kube/crd/controller. Nothing is really using MCP anymore

2020-04-24 23:53 UTC, howardjohn commented on galley/pkg/config/source/kube/apiserver/source.go
> +			// only create watchers for stored versions.
what happens when an MCP client requests a different version?

2020-04-24 23:57 UTC, istio-testing commented
@jasonwzm: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
unit-tests_istio | 32e00ba0748d6969283e3aabc7dd560d8286f682 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/unit-tests_istio/12384) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-05-01 21:45 UTC, dex80526 commented
@jasonwzm: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2020-05-02 20:22 UTC, istio-testing commented
@jasonwzm: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2020-06-22 19:21 UTC, istio-testing commented
@jasonwzm: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
unit-tests_istio | 32e00ba0748d6969283e3aabc7dd560d8286f682 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/unit-tests_istio/12384) | `/test unit-tests_istio`
integ-ipv6-k8s-tests_istio | 32e00ba0748d6969283e3aabc7dd560d8286f682 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/integ-ipv6-k8s-tests_istio/707) | `/test integ-ipv6-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-06-30 21:06 UTC, istio-testing commented
@jasonwzm: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
unit-tests_istio | 32e00ba0748d6969283e3aabc7dd560d8286f682 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/unit-tests_istio/12384) | `/test unit-tests_istio`
integ-ipv6-k8s-tests_istio | 32e00ba0748d6969283e3aabc7dd560d8286f682 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/integ-ipv6-k8s-tests_istio/707) | `/test integ-ipv6-k8s-tests_istio`
analyze-tests_istio | 32e00ba0748d6969283e3aabc7dd560d8286f682 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23104/analyze-tests_istio/74) | `/test analyze-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-07-27 19:02 UTC, howardjohn commented
Is this still valid?

2020-08-21 17:00 UTC, closed without merging