always put sidecars to front of containers list in pods
istio/istio pull request #25383
Opened 2020-07-09 21:06 UTC by tariq1890

Please provide a description for what this PR is for.
It is known that Kubelet performs the startup of containers of a Pod in the order that they are provided. Putting sidecars to the front of the list is a default that is safe enough. 

This is based on @luksa's PR #24737 

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[X] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

2020-07-09 21:12 UTC, istio-testing commented
@tariq1890: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | 633b98b0a8cff62d26c9feb5086b2b692e2995b0 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/gencheck_istio/14210) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-07-09 21:16 UTC, istio-testing commented
@tariq1890: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | 633b98b0a8cff62d26c9feb5086b2b692e2995b0 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/gencheck_istio/14210) | `/test gencheck_istio`
unit-tests_istio | 633b98b0a8cff62d26c9feb5086b2b692e2995b0 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/unit-tests_istio/16208) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-07-09 21:23 UTC, istio-testing commented
@tariq1890: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | 633b98b0a8cff62d26c9feb5086b2b692e2995b0 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/gencheck_istio/14210) | `/test gencheck_istio`
unit-tests_istio | 633b98b0a8cff62d26c9feb5086b2b692e2995b0 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/unit-tests_istio/16208) | `/test unit-tests_istio`
integ-ipv6-k8s-tests_istio | 633b98b0a8cff62d26c9feb5086b2b692e2995b0 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-ipv6-k8s-tests_istio/1877) | `/test integ-ipv6-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-07-09 21:23 UTC, istio-testing commented
@tariq1890: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | 633b98b0a8cff62d26c9feb5086b2b692e2995b0 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/gencheck_istio/14210) | `/test gencheck_istio`
unit-tests_istio | 633b98b0a8cff62d26c9feb5086b2b692e2995b0 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/unit-tests_istio/16208) | `/test unit-tests_istio`
integ-ipv6-k8s-tests_istio | 633b98b0a8cff62d26c9feb5086b2b692e2995b0 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-ipv6-k8s-tests_istio/1877) | `/test integ-ipv6-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 633b98b0a8cff62d26c9feb5086b2b692e2995b0 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-distroless-k8s-tests_istio/8870) | `/test integ-distroless-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-07-09 22:11 UTC, istio-testing commented
@tariq1890: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-ipv6-k8s-tests_istio | 633b98b0a8cff62d26c9feb5086b2b692e2995b0 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-ipv6-k8s-tests_istio/1877) | `/test integ-ipv6-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 633b98b0a8cff62d26c9feb5086b2b692e2995b0 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-distroless-k8s-tests_istio/8870) | `/test integ-distroless-k8s-tests_istio`
unit-tests_istio | 0479db6d5783f1c1c17be4338dc47c143701a30e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/unit-tests_istio/16218) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-07-09 22:14 UTC, istio-testing commented
@tariq1890: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-ipv6-k8s-tests_istio | 633b98b0a8cff62d26c9feb5086b2b692e2995b0 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-ipv6-k8s-tests_istio/1877) | `/test integ-ipv6-k8s-tests_istio`
unit-tests_istio | 0479db6d5783f1c1c17be4338dc47c143701a30e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/unit-tests_istio/16218) | `/test unit-tests_istio`
integ-distroless-k8s-tests_istio | 0479db6d5783f1c1c17be4338dc47c143701a30e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-distroless-k8s-tests_istio/8880) | `/test integ-distroless-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-07-09 22:15 UTC, istio-testing commented
@tariq1890: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
unit-tests_istio | 0479db6d5783f1c1c17be4338dc47c143701a30e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/unit-tests_istio/16218) | `/test unit-tests_istio`
integ-distroless-k8s-tests_istio | 0479db6d5783f1c1c17be4338dc47c143701a30e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-distroless-k8s-tests_istio/8880) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 0479db6d5783f1c1c17be4338dc47c143701a30e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-ipv6-k8s-tests_istio/1887) | `/test integ-ipv6-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-07-09 22:39 UTC, istio-testing commented
@tariq1890: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-distroless-k8s-tests_istio | 0479db6d5783f1c1c17be4338dc47c143701a30e | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-distroless-k8s-tests_istio/8880) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 2010e2726e7b35eded7025ab7814e781a314bb66 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-ipv6-k8s-tests_istio/1891) | `/test integ-ipv6-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-07-09 22:41 UTC, istio-testing commented
@tariq1890: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-ipv6-k8s-tests_istio | 2010e2726e7b35eded7025ab7814e781a314bb66 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-ipv6-k8s-tests_istio/1891) | `/test integ-ipv6-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 2010e2726e7b35eded7025ab7814e781a314bb66 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-distroless-k8s-tests_istio/8884) | `/test integ-distroless-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-07-09 23:13 UTC, istio-testing commented
@tariq1890: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-ipv6-k8s-tests_istio | 2010e2726e7b35eded7025ab7814e781a314bb66 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-ipv6-k8s-tests_istio/1891) | `/test integ-ipv6-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 2010e2726e7b35eded7025ab7814e781a314bb66 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-distroless-k8s-tests_istio/8884) | `/test integ-distroless-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 2010e2726e7b35eded7025ab7814e781a314bb66 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-pilot-k8s-tests_istio/15761) | `/test integ-pilot-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-07-09 23:17 UTC, istio-testing commented
@tariq1890: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-ipv6-k8s-tests_istio | 2010e2726e7b35eded7025ab7814e781a314bb66 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-ipv6-k8s-tests_istio/1891) | `/test integ-ipv6-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 2010e2726e7b35eded7025ab7814e781a314bb66 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-distroless-k8s-tests_istio/8884) | `/test integ-distroless-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 2010e2726e7b35eded7025ab7814e781a314bb66 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-pilot-k8s-tests_istio/15761) | `/test integ-pilot-k8s-tests_istio`
integ-security-k8s-tests_istio | 2010e2726e7b35eded7025ab7814e781a314bb66 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-security-k8s-tests_istio/15896) | `/test integ-security-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-07-09 23:17 UTC, howardjohn requested changes
The ordering of containers launching is unlikely to have any impact on startup problems without the full solution provided by https://github.com/istio/istio/pull/24737. The containers start extremely quickly, its not like its waiting for them to be come ready or anything

https://github.com/istio/istio/issues/20069 has more info

This has real impacts on users - any scripts or similar commands that rely on the implicit ordering will break. For example `kubectl logs` and `kubectl exec` will now behave different.

Given this is a breaking change and we do not have any evidence (yet? would be happy to be proven wrong) it will improve the problem, I do not think we should do this right now

2020-07-09 23:19 UTC, tariq1890 commented
/retest

2020-07-09 23:28 UTC, tariq1890 commented
> This has real impacts on users - any scripts or similar commands that rely on the implicit ordering will break. For example kubectl logs and kubectl exec will now behave different.

This is unfortunate. I agree that it's a breaking change.

2020-07-09 23:38 UTC, istio-testing commented
@tariq1890: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-distroless-k8s-tests_istio | 2010e2726e7b35eded7025ab7814e781a314bb66 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-distroless-k8s-tests_istio/8884) | `/test integ-distroless-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 2010e2726e7b35eded7025ab7814e781a314bb66 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-pilot-k8s-tests_istio/15761) | `/test integ-pilot-k8s-tests_istio`
integ-security-k8s-tests_istio | 2010e2726e7b35eded7025ab7814e781a314bb66 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-security-k8s-tests_istio/15896) | `/test integ-security-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 2010e2726e7b35eded7025ab7814e781a314bb66 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-ipv6-k8s-tests_istio/1894) | `/test integ-ipv6-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-07-09 23:38 UTC, istio-testing commented
@tariq1890: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | 2010e2726e7b35eded7025ab7814e781a314bb66 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-pilot-k8s-tests_istio/15761) | `/test integ-pilot-k8s-tests_istio`
integ-security-k8s-tests_istio | 2010e2726e7b35eded7025ab7814e781a314bb66 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-security-k8s-tests_istio/15896) | `/test integ-security-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 2010e2726e7b35eded7025ab7814e781a314bb66 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-ipv6-k8s-tests_istio/1894) | `/test integ-ipv6-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 2010e2726e7b35eded7025ab7814e781a314bb66 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-distroless-k8s-tests_istio/8887) | `/test integ-distroless-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-07-10 00:20 UTC, istio-testing commented
@tariq1890: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | 2010e2726e7b35eded7025ab7814e781a314bb66 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-pilot-k8s-tests_istio/15761) | `/test integ-pilot-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 2010e2726e7b35eded7025ab7814e781a314bb66 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-ipv6-k8s-tests_istio/1894) | `/test integ-ipv6-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 2010e2726e7b35eded7025ab7814e781a314bb66 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-distroless-k8s-tests_istio/8887) | `/test integ-distroless-k8s-tests_istio`
integ-security-k8s-tests_istio | 2010e2726e7b35eded7025ab7814e781a314bb66 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-security-k8s-tests_istio/15899) | `/test integ-security-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-07-10 00:21 UTC, istio-testing commented
@tariq1890: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-ipv6-k8s-tests_istio | 2010e2726e7b35eded7025ab7814e781a314bb66 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-ipv6-k8s-tests_istio/1894) | `/test integ-ipv6-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 2010e2726e7b35eded7025ab7814e781a314bb66 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-distroless-k8s-tests_istio/8887) | `/test integ-distroless-k8s-tests_istio`
integ-security-k8s-tests_istio | 2010e2726e7b35eded7025ab7814e781a314bb66 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-security-k8s-tests_istio/15899) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 2010e2726e7b35eded7025ab7814e781a314bb66 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25383/integ-pilot-k8s-tests_istio/15764) | `/test integ-pilot-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-07-10 18:31 UTC, tariq1890 commented
@howardjohn While I understand that this may not be merged, can we understand why the E2E tests are failing? Any starting point for me to analyze/debug would be helpful. This would atleast help me understand Istio better

2020-07-18 00:06 UTC, closed without merging