Deprecate built in charts
istio/istio pull request #25951
Opened 2020-07-29 18:20 UTC by howardjohn

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

2020-07-29 18:21 UTC, istio-testing commented
@howardjohn: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 13303184a2e86cb7571418ddf9925e79a506b6ac | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/25951/release-notes_istio/844) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-07-29 18:24 UTC, istio-testing commented
@howardjohn: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 13303184a2e86cb7571418ddf9925e79a506b6ac | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/25951/release-notes_istio/844) | `/test release-notes_istio`
lint_istio | 13303184a2e86cb7571418ddf9925e79a506b6ac | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/25951/lint_istio/17084) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-07-30 03:51 UTC, morvencao approved these changes

2020-07-30 05:29 UTC, costinm approved these changes

2020-07-30 08:24 UTC, sdake requested changes
We should have a broader discussion about this topic in Env. I do not like, nor have never liked `--charts`. I also don't really like built in charts.

what would be better is a chart to istioctl mapping where charts are stored along side the binaries. I was late Wednesday, but perhaps this is what @ostromart was talking about.

What is the pain point you are trying to solve by removing built in charts?

Cheers,
-steve

2020-08-01 05:18 UTC, sdake commented
John and I spoke about this on slack. I don't have a problem with deprecating this feature in 1.8, giving us an opportunity to release versioned charts with each version of istioctl, and hopefully, some way to retrieve them remotely from a storage location such as gcr.io. I just didn't want this deprecated in 1.7 without a clear transition plan.

@howardjohn was this your interpretation of our conversation?

Cheers,
-steve

2020-08-03 16:32 UTC, shamsher31 commented on operator/cmd/mesh/manifest-apply.go
> +		cmd.PrintErrln("! Using deprecated compiled in charts, which will be removed in a future release. Please pass --charts. See https://istio.io/latest/docs/setup/install/istioctl/ for more information
I think this URL will be more appropriate?
https://istio.io/latest/docs/setup/install/istioctl/#install-from-external-charts

2020-08-10 20:07 UTC, istio-testing commented
@howardjohn: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2020-08-18 23:01 UTC, closed without merging