Remove redundant --charts flag
istio/istio pull request #27119
Opened 2020-09-08 06:34 UTC by shamsher31

`--manifests` is used instead of `--charts` and is good to remove for `1.8`.

Related:
https://github.com/istio/istio/pull/24749
https://github.com/istio/istio.io/pull/7655

2020-09-08 14:14 UTC, howardjohn requested changes, later dismissed
can we just hide it? Every release we make some minor change to the install command. Irs a huge pain for users that we make backwards incompatible changes for no real reason

2020-09-08 14:51 UTC, shamsher31 commented
> can we just hide it?

I thought about that initially, but after looking at `1.7` docs, found out that it was completely replaced by `--manifests`. So I think for `1.8` this will be good to remove? I can hide if it will be critical?

2020-09-08 14:54 UTC, howardjohn commented
Just because its not in the docs doesn't mean users are not using it. EVERY
release so far we have made a breaking change in this command for pretty
much no reason other than to annoy users

On Tue, Sep 8, 2020 at 7:51 AM Shamsher Ansari <notifications@github.com>
wrote:

> can we just hide it?
>
> I thought about that initially, but after looking at 1.7 docs, found out
> that it was completely replaced by --manifests. So I think for 1.8 this
> will be good to remove? I can hide if it will be critical?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/istio/pull/27119#issuecomment-688930632>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEYGXMDXDVWH7Q2IRYNEMLSEZAIDANCNFSM4Q7QRBGQ>
> .
>

2020-09-08 15:01 UTC, shamsher31 commented
> Just because its not in the docs doesn't mean users are not using it. EVERY release so far we have made a breaking change in this command for pretty much no reason other than to annoy users

I agree, The user experience was not good with `install`. I will hide this `--charts` flag.

2020-09-10 09:50 UTC, shamsher31 commented
@esnible PTAL?

2020-09-10 15:56 UTC, shamsher31 commented
@howardjohn Is this look good?

2020-09-10 15:59 UTC, howardjohn commented
@shamsher31 looks good to me. I am not an istioctl maintainer nor do I know if this is write from a code perspective but the concept is good

2020-09-10 16:47 UTC, shamsher31 commented
@howardjohn Thanks. I recently learned that here https://github.com/istio/istio/pull/26987

2020-09-11 15:05 UTC, esnible approved these changes

2020-09-11 15:58 UTC, merged