support --cluster-number for multi-cluster test
istio/istio pull request #27287
Opened 2020-09-14 07:32 UTC by irisdingbj

2020-09-14 07:33 UTC, istio-testing commented
@irisdingbj: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 662e8fee9c0759ee28425823e8031c7aaacaed81 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3300) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 07:35 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 662e8fee9c0759ee28425823e8031c7aaacaed81 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3300) | `/test release-notes_istio`
integ-multicluster-k8s-tests_istio | 662e8fee9c0759ee28425823e8031c7aaacaed81 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10470) | `/test integ-multicluster-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 07:44 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 662e8fee9c0759ee28425823e8031c7aaacaed81 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3300) | `/test release-notes_istio`
integ-multicluster-k8s-tests_istio | 662e8fee9c0759ee28425823e8031c7aaacaed81 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10470) | `/test integ-multicluster-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19793) | `/test integ-telemetry-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 07:44 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 662e8fee9c0759ee28425823e8031c7aaacaed81 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3300) | `/test release-notes_istio`
integ-multicluster-k8s-tests_istio | 662e8fee9c0759ee28425823e8031c7aaacaed81 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10470) | `/test integ-multicluster-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19793) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20126) | `/test integ-security-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 07:44 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 662e8fee9c0759ee28425823e8031c7aaacaed81 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3300) | `/test release-notes_istio`
integ-multicluster-k8s-tests_istio | 662e8fee9c0759ee28425823e8031c7aaacaed81 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10470) | `/test integ-multicluster-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19793) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20126) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20030) | `/test integ-pilot-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 07:44 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 662e8fee9c0759ee28425823e8031c7aaacaed81 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3300) | `/test release-notes_istio`
integ-multicluster-k8s-tests_istio | 662e8fee9c0759ee28425823e8031c7aaacaed81 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10470) | `/test integ-multicluster-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19793) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20126) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20030) | `/test integ-pilot-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13041) | `/test integ-distroless-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 07:45 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 662e8fee9c0759ee28425823e8031c7aaacaed81 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3300) | `/test release-notes_istio`
integ-multicluster-k8s-tests_istio | 662e8fee9c0759ee28425823e8031c7aaacaed81 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10470) | `/test integ-multicluster-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19793) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20126) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20030) | `/test integ-pilot-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13041) | `/test integ-distroless-k8s-tests_istio`
integ-operator-controller-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8171) | `/test integ-operator-controller-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 07:45 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-multicluster-k8s-tests_istio | 662e8fee9c0759ee28425823e8031c7aaacaed81 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10470) | `/test integ-multicluster-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19793) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20126) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20030) | `/test integ-pilot-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13041) | `/test integ-distroless-k8s-tests_istio`
integ-operator-controller-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8171) | `/test integ-operator-controller-tests_istio`
release-notes_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3302) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 07:45 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-multicluster-k8s-tests_istio | 662e8fee9c0759ee28425823e8031c7aaacaed81 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10470) | `/test integ-multicluster-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19793) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20126) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20030) | `/test integ-pilot-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13041) | `/test integ-distroless-k8s-tests_istio`
integ-operator-controller-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8171) | `/test integ-operator-controller-tests_istio`
release-notes_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3302) | `/test release-notes_istio`
integ-ipv6-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6012) | `/test integ-ipv6-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 07:47 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19793) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20126) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20030) | `/test integ-pilot-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13041) | `/test integ-distroless-k8s-tests_istio`
integ-operator-controller-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8171) | `/test integ-operator-controller-tests_istio`
release-notes_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3302) | `/test release-notes_istio`
integ-ipv6-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6012) | `/test integ-ipv6-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10471) | `/test integ-multicluster-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 07:50 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19793) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20126) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20030) | `/test integ-pilot-k8s-tests_istio`
integ-operator-controller-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8171) | `/test integ-operator-controller-tests_istio`
release-notes_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3302) | `/test release-notes_istio`
integ-ipv6-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6012) | `/test integ-ipv6-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10471) | `/test integ-multicluster-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13043) | `/test integ-distroless-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 07:50 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19793) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20126) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20030) | `/test integ-pilot-k8s-tests_istio`
integ-operator-controller-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8171) | `/test integ-operator-controller-tests_istio`
release-notes_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3302) | `/test release-notes_istio`
integ-multicluster-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10471) | `/test integ-multicluster-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13043) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6014) | `/test integ-ipv6-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 07:50 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20126) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20030) | `/test integ-pilot-k8s-tests_istio`
integ-operator-controller-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8171) | `/test integ-operator-controller-tests_istio`
release-notes_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3302) | `/test release-notes_istio`
integ-multicluster-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10471) | `/test integ-multicluster-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13043) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6014) | `/test integ-ipv6-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19795) | `/test integ-telemetry-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 07:51 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20126) | `/test integ-security-k8s-tests_istio`
integ-operator-controller-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8171) | `/test integ-operator-controller-tests_istio`
release-notes_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3302) | `/test release-notes_istio`
integ-multicluster-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10471) | `/test integ-multicluster-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13043) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6014) | `/test integ-ipv6-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19795) | `/test integ-telemetry-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20032) | `/test integ-pilot-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 07:51 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20126) | `/test integ-security-k8s-tests_istio`
integ-operator-controller-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8171) | `/test integ-operator-controller-tests_istio`
integ-multicluster-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10471) | `/test integ-multicluster-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13043) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6014) | `/test integ-ipv6-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19795) | `/test integ-telemetry-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20032) | `/test integ-pilot-k8s-tests_istio`
release-notes_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3304) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 07:51 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20126) | `/test integ-security-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10471) | `/test integ-multicluster-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13043) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6014) | `/test integ-ipv6-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19795) | `/test integ-telemetry-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20032) | `/test integ-pilot-k8s-tests_istio`
release-notes_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3304) | `/test release-notes_istio`
integ-operator-controller-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8173) | `/test integ-operator-controller-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 07:52 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-multicluster-k8s-tests_istio | 4b95af59ca88477f1ac84d08f33cb269e63ad82a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10471) | `/test integ-multicluster-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13043) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6014) | `/test integ-ipv6-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19795) | `/test integ-telemetry-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20032) | `/test integ-pilot-k8s-tests_istio`
release-notes_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3304) | `/test release-notes_istio`
integ-operator-controller-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8173) | `/test integ-operator-controller-tests_istio`
integ-security-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20128) | `/test integ-security-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 07:53 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-distroless-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13043) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6014) | `/test integ-ipv6-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19795) | `/test integ-telemetry-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20032) | `/test integ-pilot-k8s-tests_istio`
release-notes_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3304) | `/test release-notes_istio`
integ-operator-controller-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8173) | `/test integ-operator-controller-tests_istio`
integ-security-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20128) | `/test integ-security-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10473) | `/test integ-multicluster-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 08:14 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-distroless-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13043) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6014) | `/test integ-ipv6-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19795) | `/test integ-telemetry-k8s-tests_istio`
release-notes_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3304) | `/test release-notes_istio`
integ-operator-controller-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8173) | `/test integ-operator-controller-tests_istio`
integ-security-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20128) | `/test integ-security-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10473) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20034) | `/test integ-pilot-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 08:14 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-distroless-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13043) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6014) | `/test integ-ipv6-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19795) | `/test integ-telemetry-k8s-tests_istio`
integ-operator-controller-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8173) | `/test integ-operator-controller-tests_istio`
integ-security-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20128) | `/test integ-security-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10473) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20034) | `/test integ-pilot-k8s-tests_istio`
release-notes_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3306) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 08:14 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-distroless-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13043) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6014) | `/test integ-ipv6-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19795) | `/test integ-telemetry-k8s-tests_istio`
integ-operator-controller-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8173) | `/test integ-operator-controller-tests_istio`
integ-multicluster-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10473) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20034) | `/test integ-pilot-k8s-tests_istio`
release-notes_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3306) | `/test release-notes_istio`
integ-security-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20130) | `/test integ-security-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 08:14 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-distroless-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13043) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19795) | `/test integ-telemetry-k8s-tests_istio`
integ-operator-controller-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8173) | `/test integ-operator-controller-tests_istio`
integ-multicluster-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10473) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20034) | `/test integ-pilot-k8s-tests_istio`
release-notes_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3306) | `/test release-notes_istio`
integ-security-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20130) | `/test integ-security-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6016) | `/test integ-ipv6-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 08:15 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-distroless-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13043) | `/test integ-distroless-k8s-tests_istio`
integ-operator-controller-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8173) | `/test integ-operator-controller-tests_istio`
integ-multicluster-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10473) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20034) | `/test integ-pilot-k8s-tests_istio`
release-notes_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3306) | `/test release-notes_istio`
integ-security-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20130) | `/test integ-security-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6016) | `/test integ-ipv6-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19797) | `/test integ-telemetry-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 08:15 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-operator-controller-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8173) | `/test integ-operator-controller-tests_istio`
integ-multicluster-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10473) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20034) | `/test integ-pilot-k8s-tests_istio`
release-notes_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3306) | `/test release-notes_istio`
integ-security-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20130) | `/test integ-security-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6016) | `/test integ-ipv6-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19797) | `/test integ-telemetry-k8s-tests_istio`
integ-distroless-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13045) | `/test integ-distroless-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 08:15 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-multicluster-k8s-tests_istio | 2bf28b15b743bc62adaa205afa01f0e57bfff658 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10473) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20034) | `/test integ-pilot-k8s-tests_istio`
release-notes_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3306) | `/test release-notes_istio`
integ-security-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20130) | `/test integ-security-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6016) | `/test integ-ipv6-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19797) | `/test integ-telemetry-k8s-tests_istio`
integ-distroless-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13045) | `/test integ-distroless-k8s-tests_istio`
integ-operator-controller-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8175) | `/test integ-operator-controller-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 08:18 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20034) | `/test integ-pilot-k8s-tests_istio`
release-notes_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3306) | `/test release-notes_istio`
integ-security-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20130) | `/test integ-security-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6016) | `/test integ-ipv6-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19797) | `/test integ-telemetry-k8s-tests_istio`
integ-distroless-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13045) | `/test integ-distroless-k8s-tests_istio`
integ-operator-controller-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8175) | `/test integ-operator-controller-tests_istio`
integ-multicluster-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10475) | `/test integ-multicluster-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 08:35 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20034) | `/test integ-pilot-k8s-tests_istio`
release-notes_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3306) | `/test release-notes_istio`
integ-ipv6-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6016) | `/test integ-ipv6-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19797) | `/test integ-telemetry-k8s-tests_istio`
integ-distroless-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13045) | `/test integ-distroless-k8s-tests_istio`
integ-operator-controller-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8175) | `/test integ-operator-controller-tests_istio`
integ-multicluster-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10475) | `/test integ-multicluster-k8s-tests_istio`
integ-security-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20133) | `/test integ-security-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 08:36 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20034) | `/test integ-pilot-k8s-tests_istio`
release-notes_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3306) | `/test release-notes_istio`
integ-ipv6-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6016) | `/test integ-ipv6-k8s-tests_istio`
integ-distroless-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13045) | `/test integ-distroless-k8s-tests_istio`
integ-operator-controller-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8175) | `/test integ-operator-controller-tests_istio`
integ-multicluster-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10475) | `/test integ-multicluster-k8s-tests_istio`
integ-security-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20133) | `/test integ-security-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19800) | `/test integ-telemetry-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 08:36 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20034) | `/test integ-pilot-k8s-tests_istio`
release-notes_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3306) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13045) | `/test integ-distroless-k8s-tests_istio`
integ-operator-controller-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8175) | `/test integ-operator-controller-tests_istio`
integ-multicluster-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10475) | `/test integ-multicluster-k8s-tests_istio`
integ-security-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20133) | `/test integ-security-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19800) | `/test integ-telemetry-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6019) | `/test integ-ipv6-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 08:37 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20034) | `/test integ-pilot-k8s-tests_istio`
integ-distroless-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13045) | `/test integ-distroless-k8s-tests_istio`
integ-operator-controller-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8175) | `/test integ-operator-controller-tests_istio`
integ-multicluster-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10475) | `/test integ-multicluster-k8s-tests_istio`
integ-security-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20133) | `/test integ-security-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19800) | `/test integ-telemetry-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6019) | `/test integ-ipv6-k8s-tests_istio`
release-notes_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3309) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 08:37 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20034) | `/test integ-pilot-k8s-tests_istio`
integ-distroless-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13045) | `/test integ-distroless-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10475) | `/test integ-multicluster-k8s-tests_istio`
integ-security-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20133) | `/test integ-security-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19800) | `/test integ-telemetry-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6019) | `/test integ-ipv6-k8s-tests_istio`
release-notes_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3309) | `/test release-notes_istio`
integ-operator-controller-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8178) | `/test integ-operator-controller-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 08:37 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20034) | `/test integ-pilot-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10475) | `/test integ-multicluster-k8s-tests_istio`
integ-security-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20133) | `/test integ-security-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19800) | `/test integ-telemetry-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6019) | `/test integ-ipv6-k8s-tests_istio`
release-notes_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3309) | `/test release-notes_istio`
integ-operator-controller-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8178) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13048) | `/test integ-distroless-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 08:37 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-multicluster-k8s-tests_istio | dface2ede77d38c28430a83b340a0a3ec795b164 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10475) | `/test integ-multicluster-k8s-tests_istio`
integ-security-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20133) | `/test integ-security-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19800) | `/test integ-telemetry-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6019) | `/test integ-ipv6-k8s-tests_istio`
release-notes_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3309) | `/test release-notes_istio`
integ-operator-controller-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8178) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13048) | `/test integ-distroless-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20037) | `/test integ-pilot-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 08:40 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20133) | `/test integ-security-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19800) | `/test integ-telemetry-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6019) | `/test integ-ipv6-k8s-tests_istio`
release-notes_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3309) | `/test release-notes_istio`
integ-operator-controller-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8178) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13048) | `/test integ-distroless-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20037) | `/test integ-pilot-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10478) | `/test integ-multicluster-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 09:41 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20133) | `/test integ-security-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19800) | `/test integ-telemetry-k8s-tests_istio`
release-notes_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3309) | `/test release-notes_istio`
integ-operator-controller-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8178) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13048) | `/test integ-distroless-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20037) | `/test integ-pilot-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10478) | `/test integ-multicluster-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6021) | `/test integ-ipv6-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 09:41 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20133) | `/test integ-security-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19800) | `/test integ-telemetry-k8s-tests_istio`
release-notes_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3309) | `/test release-notes_istio`
integ-operator-controller-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8178) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13048) | `/test integ-distroless-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10478) | `/test integ-multicluster-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6021) | `/test integ-ipv6-k8s-tests_istio`
integ-pilot-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20039) | `/test integ-pilot-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 09:41 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20133) | `/test integ-security-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19800) | `/test integ-telemetry-k8s-tests_istio`
release-notes_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3309) | `/test release-notes_istio`
integ-operator-controller-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8178) | `/test integ-operator-controller-tests_istio`
integ-multicluster-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10478) | `/test integ-multicluster-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6021) | `/test integ-ipv6-k8s-tests_istio`
integ-pilot-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20039) | `/test integ-pilot-k8s-tests_istio`
integ-distroless-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13050) | `/test integ-distroless-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 09:42 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20133) | `/test integ-security-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19800) | `/test integ-telemetry-k8s-tests_istio`
release-notes_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3309) | `/test release-notes_istio`
integ-multicluster-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10478) | `/test integ-multicluster-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6021) | `/test integ-ipv6-k8s-tests_istio`
integ-pilot-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20039) | `/test integ-pilot-k8s-tests_istio`
integ-distroless-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13050) | `/test integ-distroless-k8s-tests_istio`
integ-operator-controller-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8180) | `/test integ-operator-controller-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 09:42 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20133) | `/test integ-security-k8s-tests_istio`
release-notes_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3309) | `/test release-notes_istio`
integ-multicluster-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10478) | `/test integ-multicluster-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6021) | `/test integ-ipv6-k8s-tests_istio`
integ-pilot-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20039) | `/test integ-pilot-k8s-tests_istio`
integ-distroless-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13050) | `/test integ-distroless-k8s-tests_istio`
integ-operator-controller-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8180) | `/test integ-operator-controller-tests_istio`
integ-telemetry-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19802) | `/test integ-telemetry-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 09:43 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20133) | `/test integ-security-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10478) | `/test integ-multicluster-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6021) | `/test integ-ipv6-k8s-tests_istio`
integ-pilot-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20039) | `/test integ-pilot-k8s-tests_istio`
integ-distroless-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13050) | `/test integ-distroless-k8s-tests_istio`
integ-operator-controller-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8180) | `/test integ-operator-controller-tests_istio`
integ-telemetry-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19802) | `/test integ-telemetry-k8s-tests_istio`
release-notes_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3311) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 09:43 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-multicluster-k8s-tests_istio | 0cf1cf0677b05f1c03a79ee6f0f44d5658f6e3cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10478) | `/test integ-multicluster-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6021) | `/test integ-ipv6-k8s-tests_istio`
integ-pilot-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20039) | `/test integ-pilot-k8s-tests_istio`
integ-distroless-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13050) | `/test integ-distroless-k8s-tests_istio`
integ-operator-controller-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8180) | `/test integ-operator-controller-tests_istio`
integ-telemetry-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19802) | `/test integ-telemetry-k8s-tests_istio`
release-notes_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3311) | `/test release-notes_istio`
integ-security-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20135) | `/test integ-security-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 09:44 UTC, istio-testing commented
@irisdingbj: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-ipv6-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-ipv6-k8s-tests_istio/6021) | `/test integ-ipv6-k8s-tests_istio`
integ-pilot-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-pilot-k8s-tests_istio/20039) | `/test integ-pilot-k8s-tests_istio`
integ-distroless-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-distroless-k8s-tests_istio/13050) | `/test integ-distroless-k8s-tests_istio`
integ-operator-controller-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-operator-controller-tests_istio/8180) | `/test integ-operator-controller-tests_istio`
integ-telemetry-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-telemetry-k8s-tests_istio/19802) | `/test integ-telemetry-k8s-tests_istio`
release-notes_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/release-notes_istio/3311) | `/test release-notes_istio`
integ-security-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-security-k8s-tests_istio/20135) | `/test integ-security-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | fb1690b9440ad0e546b1f6706c939ea71d353046 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27287/integ-multicluster-k8s-tests_istio/10480) | `/test integ-multicluster-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-14 13:49 UTC, brian-avery approved these changes

2020-09-14 14:45 UTC, howardjohn requested changes

2020-09-14 14:45 UTC, howardjohn commented on prow/lib.sh
>      # Network 1 contains clusters 1, 2 and 3
I don't understand how we can have a variable number of clusters but then this is fixed?

2020-09-14 14:59 UTC, nmittler reviewed
I'm not sure this PR is the right path forward.

@su225 is working on a more flexible way of specifying a variable number of clusters (see https://github.com/istio/common-files/pull/310). I think we should wait for that work to complete and then just use that for the config cluster job.

FYI @stevenctl @howardjohn

2020-09-15 00:45 UTC, irisdingbj commented
@nmittler Thanks for this pointer.  basically we need a way to specify different cluster setting for at least different prow jobs.   I left a question in https://github.com/istio/istio/pull/27248

2020-09-15 14:59 UTC, nmittler commented
@irisdingbj 

> @nmittler Thanks for this pointer. basically we need a way to specify different cluster setting for at least different prow jobs. I left a question in #27248

Yeah, that's basically what that PR is intended to support.

FYI @su225

2020-09-16 00:43 UTC, irisdingbj commented
Thanks  @su225 @nmittler for offering function needed in #27248. 
Thanks for the review @brian-avery  @howardjohn  since #27248 offer the related function. Let me close this PR.

2020-09-16 00:43 UTC, closed without merging