Add a global switch so we can disable default retry policy(#27340)
istio/istio pull request #27341
Opened 2020-09-16 03:49 UTC by zhaohuabing

The default retry policy causes problems when the service is none-idempotent.

Pilot adds a default retry policy to HTTP routes, which can potentially call a non-idempotent service two times with a single request. Event though retries only happen when the connection fails or an error response by the server, the server may have already done some modification on its state. In this case, it's better to let the downstream decide whether it should retry or not.

Signed-off-by: huabing zhao <zhaohuabing@gmail.com>

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[*] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[*] Does not have any changes that may affect Istio users.

2020-09-16 03:50 UTC, istio-testing commented
@zhaohuabing: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 997d97b96eb19e16efa8811dffed6c5cef9d132a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27341/release-notes_istio/3462) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-16 03:51 UTC, howardjohn requested changes
https://github.com/istio/istio/issues/6861#issuecomment-691365787

there has been substantial amount of design work going into solving this. We should focus on moving this forward than adding yet another environment variable hack.

2020-09-16 03:52 UTC, istio-testing commented
@zhaohuabing: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 997d97b96eb19e16efa8811dffed6c5cef9d132a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27341/release-notes_istio/3462) | `/test release-notes_istio`
gencheck_istio | 997d97b96eb19e16efa8811dffed6c5cef9d132a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27341/gencheck_istio/18472) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-16 03:57 UTC, zhaohuabing commented
Glad to see that it's already in progress.

2020-09-25 05:03 UTC, istio-testing commented
@zhaohuabing: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 997d97b96eb19e16efa8811dffed6c5cef9d132a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27341/release-notes_istio/3462) | `/test release-notes_istio`
gencheck_istio | 997d97b96eb19e16efa8811dffed6c5cef9d132a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27341/gencheck_istio/18472) | `/test gencheck_istio`
integ-pilot-multicluster-tests_istio | 997d97b96eb19e16efa8811dffed6c5cef9d132a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27341/integ-pilot-multicluster-tests_istio/1641) | `/test integ-pilot-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-04 18:28 UTC, istio-testing commented
@zhaohuabing: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2020-10-27 23:29 UTC, howardjohn commented
Closing per plan of action in https://github.com/istio/istio/pull/27341#pullrequestreview-489253316 which is in 1.9 roadmap. Thanks!!

2020-10-27 23:29 UTC, closed without merging