istio-cluster ConfigMap to set default network for clsuter
istio/istio pull request #28081
Opened 2020-10-19 20:17 UTC by stevenctl

Implements a minimal portion of [RFC: Default network for cluster](https://docs.google.com/document/d/19PPGzw04gjk4evQA85oscYbJBOS6G8DMwc2q_UNBsZA/edit#) to deal with uninjected workloads and multi-network.

2020-10-19 20:18 UTC, istio-testing commented
@stevenctl: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 3313ea41b47e72bd8505c41ef1a4146dfc830058 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-notes_istio/5795) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-19 20:18 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 3313ea41b47e72bd8505c41ef1a4146dfc830058 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-notes_istio/5795) | `/test release-notes_istio`
unit-tests_istio | 3313ea41b47e72bd8505c41ef1a4146dfc830058 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22588) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-19 20:19 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 3313ea41b47e72bd8505c41ef1a4146dfc830058 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-notes_istio/5795) | `/test release-notes_istio`
unit-tests_istio | 3313ea41b47e72bd8505c41ef1a4146dfc830058 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22588) | `/test unit-tests_istio`
analyze-tests_istio | 3313ea41b47e72bd8505c41ef1a4146dfc830058 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/analyze-tests_istio/4158) | `/test analyze-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-19 20:19 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 3313ea41b47e72bd8505c41ef1a4146dfc830058 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-notes_istio/5795) | `/test release-notes_istio`
unit-tests_istio | 3313ea41b47e72bd8505c41ef1a4146dfc830058 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22588) | `/test unit-tests_istio`
analyze-tests_istio | 3313ea41b47e72bd8505c41ef1a4146dfc830058 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/analyze-tests_istio/4158) | `/test analyze-tests_istio`
release-test_istio | 3313ea41b47e72bd8505c41ef1a4146dfc830058 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-test_istio/21584) | `/test release-test_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-19 20:22 UTC, stevenctl commented on pkg/kube/meta.go
> +	cm, err := client.CoreV1().ConfigMaps(namespace).Get(context.TODO(), "istio-cluster", metaV1.GetOptions{})
need to include revision in lookup

2020-10-19 20:22 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
unit-tests_istio | 3313ea41b47e72bd8505c41ef1a4146dfc830058 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22588) | `/test unit-tests_istio`
analyze-tests_istio | 3313ea41b47e72bd8505c41ef1a4146dfc830058 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/analyze-tests_istio/4158) | `/test analyze-tests_istio`
release-test_istio | 3313ea41b47e72bd8505c41ef1a4146dfc830058 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-test_istio/21584) | `/test release-test_istio`
gencheck_istio | dd33e4636c87fa6a42435a67990fe348237e1bde | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20307) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-19 20:22 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
unit-tests_istio | 3313ea41b47e72bd8505c41ef1a4146dfc830058 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22588) | `/test unit-tests_istio`
analyze-tests_istio | 3313ea41b47e72bd8505c41ef1a4146dfc830058 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/analyze-tests_istio/4158) | `/test analyze-tests_istio`
release-test_istio | 3313ea41b47e72bd8505c41ef1a4146dfc830058 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-test_istio/21584) | `/test release-test_istio`
gencheck_istio | dd33e4636c87fa6a42435a67990fe348237e1bde | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20307) | `/test gencheck_istio`
lint_istio | dd33e4636c87fa6a42435a67990fe348237e1bde | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21714) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-19 20:23 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
unit-tests_istio | 3313ea41b47e72bd8505c41ef1a4146dfc830058 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22588) | `/test unit-tests_istio`
analyze-tests_istio | 3313ea41b47e72bd8505c41ef1a4146dfc830058 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/analyze-tests_istio/4158) | `/test analyze-tests_istio`
release-test_istio | 3313ea41b47e72bd8505c41ef1a4146dfc830058 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-test_istio/21584) | `/test release-test_istio`
gencheck_istio | dd33e4636c87fa6a42435a67990fe348237e1bde | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20307) | `/test gencheck_istio`
lint_istio | dd33e4636c87fa6a42435a67990fe348237e1bde | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21714) | `/test lint_istio`
integ-distroless-k8s-tests_istio | dd33e4636c87fa6a42435a67990fe348237e1bde | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15029) | `/test integ-distroless-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-19 20:46 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | dd33e4636c87fa6a42435a67990fe348237e1bde | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20307) | `/test gencheck_istio`
integ-distroless-k8s-tests_istio | dd33e4636c87fa6a42435a67990fe348237e1bde | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15029) | `/test integ-distroless-k8s-tests_istio`
lint_istio | a01392b148074b6edaf8e2a368842edebdc512e4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21718) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-19 20:46 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-distroless-k8s-tests_istio | dd33e4636c87fa6a42435a67990fe348237e1bde | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15029) | `/test integ-distroless-k8s-tests_istio`
lint_istio | a01392b148074b6edaf8e2a368842edebdc512e4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21718) | `/test lint_istio`
gencheck_istio | a01392b148074b6edaf8e2a368842edebdc512e4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20311) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-19 23:39 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | a01392b148074b6edaf8e2a368842edebdc512e4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20311) | `/test gencheck_istio`
lint_istio | 159354e9d840f73f390a77e61b4142b67cd4ed8f | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21736) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-19 23:40 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | 159354e9d840f73f390a77e61b4142b67cd4ed8f | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21736) | `/test lint_istio`
gencheck_istio | 159354e9d840f73f390a77e61b4142b67cd4ed8f | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20329) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 00:07 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | 159354e9d840f73f390a77e61b4142b67cd4ed8f | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20329) | `/test gencheck_istio`
lint_istio | 907a23b5054eef35b4e36250de1f94cdefa81615 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21741) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 00:08 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | 907a23b5054eef35b4e36250de1f94cdefa81615 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21741) | `/test lint_istio`
gencheck_istio | 907a23b5054eef35b4e36250de1f94cdefa81615 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20334) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 00:50 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | 907a23b5054eef35b4e36250de1f94cdefa81615 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20334) | `/test gencheck_istio`
lint_istio | 9409a536fc068836ca6b63daf93d63e4e66d21b9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21753) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 00:52 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | 9409a536fc068836ca6b63daf93d63e4e66d21b9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21753) | `/test lint_istio`
gencheck_istio | 9409a536fc068836ca6b63daf93d63e4e66d21b9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20346) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 01:10 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | 9409a536fc068836ca6b63daf93d63e4e66d21b9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21753) | `/test lint_istio`
gencheck_istio | 12cd974f0fda67f24597a17e5ad56a86356ea45d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20353) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 01:18 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | 12cd974f0fda67f24597a17e5ad56a86356ea45d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20353) | `/test gencheck_istio`
analyze-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/analyze-tests_istio/4207) | `/test analyze-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 01:18 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | 12cd974f0fda67f24597a17e5ad56a86356ea45d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20353) | `/test gencheck_istio`
analyze-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/analyze-tests_istio/4207) | `/test analyze-tests_istio`
unit-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22640) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 01:18 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | 12cd974f0fda67f24597a17e5ad56a86356ea45d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20353) | `/test gencheck_istio`
analyze-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/analyze-tests_istio/4207) | `/test analyze-tests_istio`
unit-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22640) | `/test unit-tests_istio`
release-test_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-test_istio/21633) | `/test release-test_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 01:19 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
analyze-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/analyze-tests_istio/4207) | `/test analyze-tests_istio`
unit-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22640) | `/test unit-tests_istio`
release-test_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-test_istio/21633) | `/test release-test_istio`
gencheck_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20355) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 01:19 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
analyze-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/analyze-tests_istio/4207) | `/test analyze-tests_istio`
unit-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22640) | `/test unit-tests_istio`
release-test_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-test_istio/21633) | `/test release-test_istio`
gencheck_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20355) | `/test gencheck_istio`
lint_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21762) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 01:19 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
analyze-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/analyze-tests_istio/4207) | `/test analyze-tests_istio`
unit-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22640) | `/test unit-tests_istio`
release-test_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-test_istio/21633) | `/test release-test_istio`
gencheck_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20355) | `/test gencheck_istio`
lint_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21762) | `/test lint_istio`
integ-telemetry-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21877) | `/test integ-telemetry-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 01:19 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
analyze-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/analyze-tests_istio/4207) | `/test analyze-tests_istio`
unit-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22640) | `/test unit-tests_istio`
release-test_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-test_istio/21633) | `/test release-test_istio`
gencheck_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20355) | `/test gencheck_istio`
lint_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21762) | `/test lint_istio`
integ-telemetry-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21877) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22197) | `/test integ-security-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 01:19 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
analyze-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/analyze-tests_istio/4207) | `/test analyze-tests_istio`
unit-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22640) | `/test unit-tests_istio`
release-test_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-test_istio/21633) | `/test release-test_istio`
gencheck_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20355) | `/test gencheck_istio`
lint_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21762) | `/test lint_istio`
integ-telemetry-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21877) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22197) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-pilot-k8s-tests_istio/22131) | `/test integ-pilot-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 01:19 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
analyze-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/analyze-tests_istio/4207) | `/test analyze-tests_istio`
unit-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22640) | `/test unit-tests_istio`
release-test_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-test_istio/21633) | `/test release-test_istio`
gencheck_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20355) | `/test gencheck_istio`
lint_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21762) | `/test lint_istio`
integ-telemetry-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21877) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22197) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-pilot-k8s-tests_istio/22131) | `/test integ-pilot-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-ipv6-k8s-tests_istio/8048) | `/test integ-ipv6-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 01:19 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
analyze-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/analyze-tests_istio/4207) | `/test analyze-tests_istio`
unit-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22640) | `/test unit-tests_istio`
release-test_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-test_istio/21633) | `/test release-test_istio`
gencheck_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20355) | `/test gencheck_istio`
lint_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21762) | `/test lint_istio`
integ-telemetry-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21877) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22197) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-pilot-k8s-tests_istio/22131) | `/test integ-pilot-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-ipv6-k8s-tests_istio/8048) | `/test integ-ipv6-k8s-tests_istio`
integ-operator-controller-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-operator-controller-tests_istio/10209) | `/test integ-operator-controller-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 01:21 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
analyze-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/analyze-tests_istio/4207) | `/test analyze-tests_istio`
unit-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22640) | `/test unit-tests_istio`
release-test_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-test_istio/21633) | `/test release-test_istio`
gencheck_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20355) | `/test gencheck_istio`
lint_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21762) | `/test lint_istio`
integ-telemetry-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21877) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22197) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-pilot-k8s-tests_istio/22131) | `/test integ-pilot-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-ipv6-k8s-tests_istio/8048) | `/test integ-ipv6-k8s-tests_istio`
integ-operator-controller-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-operator-controller-tests_istio/10209) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15077) | `/test integ-distroless-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 01:22 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
analyze-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/analyze-tests_istio/4207) | `/test analyze-tests_istio`
unit-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22640) | `/test unit-tests_istio`
release-test_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-test_istio/21633) | `/test release-test_istio`
gencheck_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20355) | `/test gencheck_istio`
lint_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21762) | `/test lint_istio`
integ-telemetry-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21877) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22197) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-pilot-k8s-tests_istio/22131) | `/test integ-pilot-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-ipv6-k8s-tests_istio/8048) | `/test integ-ipv6-k8s-tests_istio`
integ-operator-controller-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-operator-controller-tests_istio/10209) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15077) | `/test integ-distroless-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-multicluster-k8s-tests_istio/12540) | `/test integ-multicluster-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 01:26 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
analyze-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/analyze-tests_istio/4207) | `/test analyze-tests_istio`
unit-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22640) | `/test unit-tests_istio`
release-test_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-test_istio/21633) | `/test release-test_istio`
lint_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21762) | `/test lint_istio`
integ-telemetry-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21877) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22197) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-pilot-k8s-tests_istio/22131) | `/test integ-pilot-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-ipv6-k8s-tests_istio/8048) | `/test integ-ipv6-k8s-tests_istio`
integ-operator-controller-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-operator-controller-tests_istio/10209) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15077) | `/test integ-distroless-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | db77df3a139232c750700835a81b8102787538e7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-multicluster-k8s-tests_istio/12540) | `/test integ-multicluster-k8s-tests_istio`
gencheck_istio | d60e6cdddaafae84ddfc0230a9c4eb79e2cbcaf1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20357) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 03:02 UTC, istio-testing commented
@stevenctl: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2020-10-20 03:03 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | d60e6cdddaafae84ddfc0230a9c4eb79e2cbcaf1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20357) | `/test gencheck_istio`
integ-distroless-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15081) | `/test integ-distroless-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 03:03 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | d60e6cdddaafae84ddfc0230a9c4eb79e2cbcaf1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20357) | `/test gencheck_istio`
integ-distroless-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15081) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21881) | `/test integ-telemetry-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 03:03 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | d60e6cdddaafae84ddfc0230a9c4eb79e2cbcaf1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20357) | `/test gencheck_istio`
integ-distroless-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15081) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21881) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22201) | `/test integ-security-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 03:03 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | d60e6cdddaafae84ddfc0230a9c4eb79e2cbcaf1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20357) | `/test gencheck_istio`
integ-distroless-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15081) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21881) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22201) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-pilot-k8s-tests_istio/22135) | `/test integ-pilot-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 03:03 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | d60e6cdddaafae84ddfc0230a9c4eb79e2cbcaf1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20357) | `/test gencheck_istio`
integ-distroless-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15081) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21881) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22201) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-pilot-k8s-tests_istio/22135) | `/test integ-pilot-k8s-tests_istio`
integ-operator-controller-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-operator-controller-tests_istio/10213) | `/test integ-operator-controller-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 03:03 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | d60e6cdddaafae84ddfc0230a9c4eb79e2cbcaf1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20357) | `/test gencheck_istio`
integ-distroless-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15081) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21881) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22201) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-pilot-k8s-tests_istio/22135) | `/test integ-pilot-k8s-tests_istio`
integ-operator-controller-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-operator-controller-tests_istio/10213) | `/test integ-operator-controller-tests_istio`
integ-multicluster-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-multicluster-k8s-tests_istio/12544) | `/test integ-multicluster-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 03:03 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | d60e6cdddaafae84ddfc0230a9c4eb79e2cbcaf1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20357) | `/test gencheck_istio`
integ-distroless-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15081) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21881) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22201) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-pilot-k8s-tests_istio/22135) | `/test integ-pilot-k8s-tests_istio`
integ-operator-controller-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-operator-controller-tests_istio/10213) | `/test integ-operator-controller-tests_istio`
integ-multicluster-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-multicluster-k8s-tests_istio/12544) | `/test integ-multicluster-k8s-tests_istio`
unit-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22644) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 03:03 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | d60e6cdddaafae84ddfc0230a9c4eb79e2cbcaf1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20357) | `/test gencheck_istio`
integ-distroless-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15081) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21881) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22201) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-pilot-k8s-tests_istio/22135) | `/test integ-pilot-k8s-tests_istio`
integ-operator-controller-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-operator-controller-tests_istio/10213) | `/test integ-operator-controller-tests_istio`
integ-multicluster-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-multicluster-k8s-tests_istio/12544) | `/test integ-multicluster-k8s-tests_istio`
unit-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22644) | `/test unit-tests_istio`
release-test_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-test_istio/21637) | `/test release-test_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 03:03 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | d60e6cdddaafae84ddfc0230a9c4eb79e2cbcaf1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20357) | `/test gencheck_istio`
integ-distroless-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15081) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21881) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22201) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-pilot-k8s-tests_istio/22135) | `/test integ-pilot-k8s-tests_istio`
integ-operator-controller-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-operator-controller-tests_istio/10213) | `/test integ-operator-controller-tests_istio`
integ-multicluster-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-multicluster-k8s-tests_istio/12544) | `/test integ-multicluster-k8s-tests_istio`
unit-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22644) | `/test unit-tests_istio`
release-test_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-test_istio/21637) | `/test release-test_istio`
release-notes_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-notes_istio/5849) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 03:03 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | d60e6cdddaafae84ddfc0230a9c4eb79e2cbcaf1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20357) | `/test gencheck_istio`
integ-distroless-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15081) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21881) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22201) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-pilot-k8s-tests_istio/22135) | `/test integ-pilot-k8s-tests_istio`
integ-operator-controller-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-operator-controller-tests_istio/10213) | `/test integ-operator-controller-tests_istio`
integ-multicluster-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-multicluster-k8s-tests_istio/12544) | `/test integ-multicluster-k8s-tests_istio`
unit-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22644) | `/test unit-tests_istio`
release-test_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-test_istio/21637) | `/test release-test_istio`
release-notes_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-notes_istio/5849) | `/test release-notes_istio`
lint_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21766) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 03:03 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-distroless-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15081) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21881) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22201) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-pilot-k8s-tests_istio/22135) | `/test integ-pilot-k8s-tests_istio`
integ-operator-controller-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-operator-controller-tests_istio/10213) | `/test integ-operator-controller-tests_istio`
integ-multicluster-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-multicluster-k8s-tests_istio/12544) | `/test integ-multicluster-k8s-tests_istio`
unit-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22644) | `/test unit-tests_istio`
release-test_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-test_istio/21637) | `/test release-test_istio`
release-notes_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-notes_istio/5849) | `/test release-notes_istio`
lint_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21766) | `/test lint_istio`
gencheck_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20359) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 03:04 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-distroless-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15081) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21881) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22201) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-pilot-k8s-tests_istio/22135) | `/test integ-pilot-k8s-tests_istio`
integ-operator-controller-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-operator-controller-tests_istio/10213) | `/test integ-operator-controller-tests_istio`
integ-multicluster-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-multicluster-k8s-tests_istio/12544) | `/test integ-multicluster-k8s-tests_istio`
unit-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22644) | `/test unit-tests_istio`
release-test_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-test_istio/21637) | `/test release-test_istio`
release-notes_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-notes_istio/5849) | `/test release-notes_istio`
lint_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21766) | `/test lint_istio`
gencheck_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20359) | `/test gencheck_istio`
analyze-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/analyze-tests_istio/4211) | `/test analyze-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 03:04 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-distroless-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15081) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21881) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22201) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-pilot-k8s-tests_istio/22135) | `/test integ-pilot-k8s-tests_istio`
integ-operator-controller-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-operator-controller-tests_istio/10213) | `/test integ-operator-controller-tests_istio`
integ-multicluster-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-multicluster-k8s-tests_istio/12544) | `/test integ-multicluster-k8s-tests_istio`
unit-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22644) | `/test unit-tests_istio`
release-test_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-test_istio/21637) | `/test release-test_istio`
release-notes_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-notes_istio/5849) | `/test release-notes_istio`
lint_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21766) | `/test lint_istio`
gencheck_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20359) | `/test gencheck_istio`
analyze-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/analyze-tests_istio/4211) | `/test analyze-tests_istio`
integ-ipv6-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-ipv6-k8s-tests_istio/8052) | `/test integ-ipv6-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 03:16 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-distroless-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15081) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21881) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22201) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-pilot-k8s-tests_istio/22135) | `/test integ-pilot-k8s-tests_istio`
integ-operator-controller-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-operator-controller-tests_istio/10213) | `/test integ-operator-controller-tests_istio`
integ-multicluster-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-multicluster-k8s-tests_istio/12544) | `/test integ-multicluster-k8s-tests_istio`
unit-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22644) | `/test unit-tests_istio`
release-test_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-test_istio/21637) | `/test release-test_istio`
release-notes_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-notes_istio/5849) | `/test release-notes_istio`
gencheck_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20359) | `/test gencheck_istio`
analyze-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/analyze-tests_istio/4211) | `/test analyze-tests_istio`
integ-ipv6-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-ipv6-k8s-tests_istio/8052) | `/test integ-ipv6-k8s-tests_istio`
lint_istio | 7e5d4baa4c33f08ac24363446ef4c30e74950883 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21771) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 03:18 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-distroless-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15081) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21881) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22201) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-pilot-k8s-tests_istio/22135) | `/test integ-pilot-k8s-tests_istio`
integ-operator-controller-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-operator-controller-tests_istio/10213) | `/test integ-operator-controller-tests_istio`
integ-multicluster-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-multicluster-k8s-tests_istio/12544) | `/test integ-multicluster-k8s-tests_istio`
unit-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22644) | `/test unit-tests_istio`
release-test_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/release-test_istio/21637) | `/test release-test_istio`
analyze-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/analyze-tests_istio/4211) | `/test analyze-tests_istio`
integ-ipv6-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-ipv6-k8s-tests_istio/8052) | `/test integ-ipv6-k8s-tests_istio`
lint_istio | 7e5d4baa4c33f08ac24363446ef4c30e74950883 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21771) | `/test lint_istio`
gencheck_istio | 7e5d4baa4c33f08ac24363446ef4c30e74950883 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20364) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 03:37 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21881) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22201) | `/test integ-security-k8s-tests_istio`
gencheck_istio | 7e5d4baa4c33f08ac24363446ef4c30e74950883 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20364) | `/test gencheck_istio`
lint_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21773) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 03:37 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21881) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22201) | `/test integ-security-k8s-tests_istio`
lint_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21773) | `/test lint_istio`
gencheck_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20366) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 03:39 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21881) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22201) | `/test integ-security-k8s-tests_istio`
lint_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21773) | `/test lint_istio`
gencheck_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20366) | `/test gencheck_istio`
integ-operator-controller-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-operator-controller-tests_istio/10220) | `/test integ-operator-controller-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 03:39 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21881) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22201) | `/test integ-security-k8s-tests_istio`
lint_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21773) | `/test lint_istio`
gencheck_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20366) | `/test gencheck_istio`
integ-operator-controller-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-operator-controller-tests_istio/10220) | `/test integ-operator-controller-tests_istio`
integ-pilot-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-pilot-k8s-tests_istio/22142) | `/test integ-pilot-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 03:39 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21881) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22201) | `/test integ-security-k8s-tests_istio`
lint_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21773) | `/test lint_istio`
gencheck_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20366) | `/test gencheck_istio`
integ-operator-controller-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-operator-controller-tests_istio/10220) | `/test integ-operator-controller-tests_istio`
integ-pilot-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-pilot-k8s-tests_istio/22142) | `/test integ-pilot-k8s-tests_istio`
integ-distroless-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15088) | `/test integ-distroless-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 03:40 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21881) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22201) | `/test integ-security-k8s-tests_istio`
lint_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21773) | `/test lint_istio`
gencheck_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20366) | `/test gencheck_istio`
integ-operator-controller-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-operator-controller-tests_istio/10220) | `/test integ-operator-controller-tests_istio`
integ-pilot-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-pilot-k8s-tests_istio/22142) | `/test integ-pilot-k8s-tests_istio`
integ-distroless-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15088) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-ipv6-k8s-tests_istio/8059) | `/test integ-ipv6-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 03:40 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21881) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22201) | `/test integ-security-k8s-tests_istio`
lint_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21773) | `/test lint_istio`
gencheck_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20366) | `/test gencheck_istio`
integ-operator-controller-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-operator-controller-tests_istio/10220) | `/test integ-operator-controller-tests_istio`
integ-pilot-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-pilot-k8s-tests_istio/22142) | `/test integ-pilot-k8s-tests_istio`
integ-distroless-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15088) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-ipv6-k8s-tests_istio/8059) | `/test integ-ipv6-k8s-tests_istio`
unit-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22652) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 03:40 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21881) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22201) | `/test integ-security-k8s-tests_istio`
lint_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21773) | `/test lint_istio`
gencheck_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20366) | `/test gencheck_istio`
integ-operator-controller-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-operator-controller-tests_istio/10220) | `/test integ-operator-controller-tests_istio`
integ-pilot-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-pilot-k8s-tests_istio/22142) | `/test integ-pilot-k8s-tests_istio`
integ-distroless-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15088) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-ipv6-k8s-tests_istio/8059) | `/test integ-ipv6-k8s-tests_istio`
unit-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22652) | `/test unit-tests_istio`
analyze-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/analyze-tests_istio/4218) | `/test analyze-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 03:42 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21881) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22201) | `/test integ-security-k8s-tests_istio`
lint_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21773) | `/test lint_istio`
gencheck_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20366) | `/test gencheck_istio`
integ-operator-controller-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-operator-controller-tests_istio/10220) | `/test integ-operator-controller-tests_istio`
integ-pilot-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-pilot-k8s-tests_istio/22142) | `/test integ-pilot-k8s-tests_istio`
integ-distroless-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15088) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-ipv6-k8s-tests_istio/8059) | `/test integ-ipv6-k8s-tests_istio`
unit-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22652) | `/test unit-tests_istio`
analyze-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/analyze-tests_istio/4218) | `/test analyze-tests_istio`
integ-multicluster-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-multicluster-k8s-tests_istio/12551) | `/test integ-multicluster-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 03:42 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21881) | `/test integ-telemetry-k8s-tests_istio`
lint_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21773) | `/test lint_istio`
gencheck_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20366) | `/test gencheck_istio`
integ-operator-controller-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-operator-controller-tests_istio/10220) | `/test integ-operator-controller-tests_istio`
integ-pilot-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-pilot-k8s-tests_istio/22142) | `/test integ-pilot-k8s-tests_istio`
integ-distroless-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15088) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-ipv6-k8s-tests_istio/8059) | `/test integ-ipv6-k8s-tests_istio`
unit-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22652) | `/test unit-tests_istio`
analyze-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/analyze-tests_istio/4218) | `/test analyze-tests_istio`
integ-multicluster-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-multicluster-k8s-tests_istio/12551) | `/test integ-multicluster-k8s-tests_istio`
integ-security-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22208) | `/test integ-security-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 03:46 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21881) | `/test integ-telemetry-k8s-tests_istio`
lint_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21773) | `/test lint_istio`
integ-operator-controller-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-operator-controller-tests_istio/10220) | `/test integ-operator-controller-tests_istio`
integ-pilot-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-pilot-k8s-tests_istio/22142) | `/test integ-pilot-k8s-tests_istio`
integ-distroless-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15088) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-ipv6-k8s-tests_istio/8059) | `/test integ-ipv6-k8s-tests_istio`
unit-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22652) | `/test unit-tests_istio`
analyze-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/analyze-tests_istio/4218) | `/test analyze-tests_istio`
integ-multicluster-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-multicluster-k8s-tests_istio/12551) | `/test integ-multicluster-k8s-tests_istio`
integ-security-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22208) | `/test integ-security-k8s-tests_istio`
gencheck_istio | 02db7a9656a99139a2c3346dc57572a03ef42bc6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20367) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 03:46 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | ae92187c0724fd260adb363584a15c2341aa44b2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-telemetry-k8s-tests_istio/21881) | `/test integ-telemetry-k8s-tests_istio`
integ-operator-controller-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-operator-controller-tests_istio/10220) | `/test integ-operator-controller-tests_istio`
integ-pilot-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-pilot-k8s-tests_istio/22142) | `/test integ-pilot-k8s-tests_istio`
integ-distroless-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-distroless-k8s-tests_istio/15088) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-ipv6-k8s-tests_istio/8059) | `/test integ-ipv6-k8s-tests_istio`
unit-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/unit-tests_istio/22652) | `/test unit-tests_istio`
analyze-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/analyze-tests_istio/4218) | `/test analyze-tests_istio`
integ-multicluster-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-multicluster-k8s-tests_istio/12551) | `/test integ-multicluster-k8s-tests_istio`
integ-security-k8s-tests_istio | f739a00f527f4e47476c483e54941a9fdc94f721 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/integ-security-k8s-tests_istio/22208) | `/test integ-security-k8s-tests_istio`
gencheck_istio | 02db7a9656a99139a2c3346dc57572a03ef42bc6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20367) | `/test gencheck_istio`
lint_istio | 02db7a9656a99139a2c3346dc57572a03ef42bc6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21774) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 04:17 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | 02db7a9656a99139a2c3346dc57572a03ef42bc6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21774) | `/test lint_istio`
gencheck_istio | 79e95177d1312b7d986f5c63c32fb67d617d9a00 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20372) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 04:24 UTC, istio-testing commented
@stevenctl: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | bbba191b65f70c61e8fb70df661f13a2b9d0fcde | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20373) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 04:26 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | bbba191b65f70c61e8fb70df661f13a2b9d0fcde | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20373) | `/test gencheck_istio`
lint_istio | bbba191b65f70c61e8fb70df661f13a2b9d0fcde | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21780) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 04:40 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | bbba191b65f70c61e8fb70df661f13a2b9d0fcde | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/lint_istio/21780) | `/test lint_istio`
gencheck_istio | bc79cd6bb683fbed12482096db480acc89bda045 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20376) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 04:48 UTC, istio-testing commented
@stevenctl: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | 15d3324faedfbd7992557c9441adc8379f26d672 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28081/gencheck_istio/20378) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-20 11:54 UTC, hzxuzhonghu requested changes
This should be treated same as API change. I donot think the proposal is approved

2020-10-21 04:07 UTC, stevenctl commented
closed in favor of #28126

2020-10-21 04:07 UTC, closed without merging