istioctl bug-report: skip further scanning if istio is not installed in any namespace
istio/istio pull request #28478
Opened 2020-11-02 11:10 UTC by shamsher31

To fix https://github.com/istio/istio/issues/28401

Before:
```
$ istioctl bug-report

Target cluster context: kind-istio-testing

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-system, kube-public, kube-node-lease, local-path-storage }
end-time: 2020-10-29 19:15:14.8697752 +0530 IST

The following Istio control plane revisions/versions were found in the cluster:
The following proxy revisions/versions were found in the cluster:

Fetching proxy logs for the following containers:
Fetching Istio control plane information from cluster.

Creating an archive at /home/shaansar/Projects/src/istio.io/istio/bug-report.tgz.
Cleaning up temporary files in /tmp/bug-report.
Done.
```

After:
Check-in default namespace. 
```
$ istioctl bug-report
no running Istio pods in "istio-system"
```

Check-in another namespace. 
```
$ istioctl bug-report --istio-namespace=redhat
no running Istio pods in "redhat"
```

2020-11-02 14:50 UTC, howardjohn requested changes
I am not sure this is what we want. There are many valid cases for not having Istio installed but still running the bug report, such as external Istiod or multicluster where there is no control plane installed.

2020-11-03 07:10 UTC, shamsher31 commented
Let me try and see if `bug-report` also collects logs from external Istiod or multicluster.

2020-11-03 14:52 UTC, howardjohn commented
> Let me try and see if bug-report also collects logs from external Istiod or multicluster.

Even if we don't, bug-report collects things from things other than the control plane like proxies, etc so its still useful

2020-11-03 14:56 UTC, shamsher31 commented
> Even if we don't, bug-report collects things from things other than the control plane like proxies, etc so its still useful.

In that case, I think this PR and issue is not relevant. I will close this. Thanks.

2020-11-03 14:56 UTC, closed without merging