istioctl upgrade: use yaml diff for upgrade iops
istio/istio pull request #28572
Opened 2020-11-04 10:59 UTC by shamsher31

To fix https://github.com/istio/istio/issues/28555

Based on https://github.com/istio/istio/issues/28555#issuecomment-721655199

2020-11-04 11:04 UTC, istio-testing commented
@shamsher31: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | 1a351d817e1e0344ee418e17d80aa5c5541f04e2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28572/lint_istio/1323943029895073792) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-11-04 11:12 UTC, shamsher31 commented
/test lint_istio

2020-11-04 11:13 UTC, istio-testing commented
@shamsher31: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | 1a351d817e1e0344ee418e17d80aa5c5541f04e2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28572/lint_istio/1323946161844785152) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-11-04 11:33 UTC, shamsher31 commented on operator/cmd/mesh/upgrade.go
> -	if args.inFilenames != nil {
I just realized this might be required if user use `-f` for `upgrade`?

2020-11-04 14:38 UTC, su225 commented
@shamsher31  - Just a minor suggestion. While showing diffs, does it make sense to color them like git does? It looks better than searing for small `+` or `-` sign at the start of the line.

2020-11-04 14:55 UTC, shamsher31 commented
@su225 I will definitely prefer the colored output but not sure if the diff lib accepts any parameter to decorate the output.
https://github.com/kylelemons/godebug/tree/master/diff

2020-11-04 15:46 UTC, su225 commented
@shamsher31 - It is possible. Output is a string and it is well-documented that it would be either `+`, `-` in the library. As a nice to have it is possible to split the lines and put it ourselves in case we could not find a good library. This is generic enough that we could use it for other purposes like profile diffs (whatever diff, basically). As coloring is nice to have, we could leave it by creating an issue if this is urgent.

2020-11-05 10:47 UTC, shamsher31 commented
@su225 Thanks. added your suggestion for colored output https://github.com/istio/istio/pull/28572#issue-515305641

2020-11-05 10:50 UTC, istio-testing commented
@shamsher31: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | 948dafdcff47ac2a8acf84fc41e86053ba0ad155 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28572/lint_istio/1324301694967746560) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-11-05 10:50 UTC, istio-testing commented
@shamsher31: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | 948dafdcff47ac2a8acf84fc41e86053ba0ad155 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28572/lint_istio/1324301694967746560) | `/test lint_istio`
unit-tests_istio | 948dafdcff47ac2a8acf84fc41e86053ba0ad155 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28572/unit-tests_istio/1324301690786025472) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-11-05 11:05 UTC, istio-testing commented
@shamsher31: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-multicluster-k8s-tests_istio | a75f918e0159ffe2dddee2d2085ac84d6a23fe45 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28572/integ-multicluster-k8s-tests_istio/1324303385616191488) | `/test integ-multicluster-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-11-05 11:06 UTC, shamsher31 commented
/test integ-multicluster-k8s-tests_istio

2020-11-05 14:21 UTC, su225 commented
@shamsher31 : Looks nice. Just a nitpick - why additional newline?

2020-11-09 05:54 UTC, shamsher31 commented
@ostromart PTAL.

2020-11-11 04:09 UTC, ostromart commented
using yamldiff is not going to work well - it was actually used before the compare package was written, but the drawback that it has is that it doesn't give the full tree path of changed elements. so you end up seeing the leaf changed without seeing where in the tree that happened. a better approach would be to fix the relatively minor issues with compare to get a nicer output.

2020-11-11 04:09 UTC, ostromart requested changes

2020-11-11 04:09 UTC, ostromart commented on operator/cmd/mesh/upgrade.go
> -	if args.inFilenames != nil {
i don't think we can delete this. upgrade uses the user config to not bother diffing values that are changed by the user (and which therefore are not affected by change in defaults).

2020-11-11 14:31 UTC, shamsher31 commented
> using yamldiff is not going to work well - it was actually used before the compare package was written, but the drawback that it has is that it doesn't give the full tree path of changed elements. so you end up seeing the leaf changed without seeing where in the tree that happened.

I agree that it displays full YAML https://github.com/istio/istio/issues/28555#issuecomment-721655199, but that is the whole point of this PR because it highlights which part has been removed (- in red color) and which has been newly added(+ in green color). so the user can take better decisions, instead of just showing not so readable output where it is hard to identify changes in YAML.

2020-11-15 23:37 UTC, istio-testing commented
@shamsher31: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2020-11-16 18:17 UTC, ostromart commented
if you can figure out how to display the full path for yamldiff then i'd be ok with this approach. but we can't have "floating" value deltas that show (say) cpu setting changed without giving a context of which component it changed for. 
i think it would be much more fruitful to just fix the relatively minor formatting issues in the compare package rather than trying to fix this problem in yamldiff.

2020-11-16 18:37 UTC, istio-testing commented
@shamsher31: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-multicluster-tests_istio | a75f918e0159ffe2dddee2d2085ac84d6a23fe45 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28572/integ-pilot-multicluster-tests_istio/1328406789737156608) | `/test integ-pilot-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-11-17 07:25 UTC, istio-testing commented
@shamsher31: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-mc-k8s-tests_istio | f22d21152153d3a9c1d22e5c5e941ff38e07981d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28572/integ-telemetry-mc-k8s-tests_istio/1328584394775990272) | `/test integ-telemetry-mc-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-11-17 07:50 UTC, shamsher31 commented
/test integ-telemetry-mc-k8s-tests_istio

2021-01-01 08:07 UTC, closed without merging