Add health check using TCP
istio/istio pull request #28737
Opened 2020-11-10 05:55 UTC by shamsher31

Based on https://github.com/istio/istio.io/pull/8246#issuecomment-704190021

Follow up for https://github.com/istio/istio.io/pull/8246

2020-11-20 09:58 UTC, SkySonR commented
TCP health checks does not work at all. Check https://github.com/istio/istio/issues/15178
the documentation and examples are wrong

2020-11-20 18:00 UTC, howardjohn requested changes
I am not sure this is right. AFAIK TCP socket health check is broken by design in Istio, since its not possible to proxy a "can I connect" check.

2020-11-20 18:02 UTC, howardjohn commented on samples/health-check/liveness-tcp.yml
> +            port: 8001
you can set this to literally any port and it will pass if the sidecar is injected

2020-12-10 06:52 UTC, shamsher31 commented
> you can set this to literally any port and it will pass if the sidecar is injected.

Closing this as it's not the correct solution.

2020-12-10 06:52 UTC, closed without merging