remove unused cert option in self sign ca flow
istio/istio pull request #29320
Opened 2020-12-02 06:48 UTC by mayocream

Please provide a description for what this PR is for.

"IsDualUse" option is provide but not used.

```go
// security/pkg/pki/util/generate_cert.go

func genCertTemplateFromOptions() {
 ...
	exts := []pkix.Extension{}
	if h := options.Host; len(h) > 0 {
		s, err := BuildSubjectAltNameExtension(h)
		if err != nil {
			return nil, err
		}
		if options.IsDualUse {
			cn, err := DualUseCommonName(h)
			if err != nil {
				// log and continue
				log.Errorf("dual-use failed for cert template - omitting CN (%v)", err)
			} else {
				subject.CommonName = cn
			}
		}
		exts = []pkix.Extension{*s}
	}
...
}
```

This option is used unless cert Host is specified.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[X] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any changes that may affect Istio users.

2020-12-02 06:48 UTC, istio-testing commented
Hi @mayocream. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2020-12-02 06:51 UTC, mayocream commented
@googlebot I signed it!

2020-12-02 18:12 UTC, lei-tang requested changes
As shown in the following calling flow, IsDualUse is used.

util.GenCertKeyFromOptions(options) ->
genCert(options, rsaPriv, &rsaPriv.PublicKey) ->
genCertTemplateFromOptions(options) ->
		if options.IsDualUse {
			cn, err := DualUseCommonName(h)
                  ...
                  }

2020-12-03 01:46 UTC, mayocream commented
> 
> 
> As shown in the following calling flow, IsDualUse is used. Can you clarify why you think IsDualUse is not used?
> 
> util.GenCertKeyFromOptions(options) ->
> genCert(options, rsaPriv, &rsaPriv.PublicKey) ->
> genCertTemplateFromOptions(options) ->
> if options.IsDualUse {
> cn, err := DualUseCommonName(h)
> ...
> }

```go
// security/pkg/pki/ca/ca.go

func NewSelfSignedIstioCAOptions() {
...
// secret not found, so we will create priv key self signed cert
            if scrtErr != nil {
   		options := util.CertOptions{
			TTL:          caCertTTL,
			Org:          org,
			IsCA:         true,
			IsSelfSigned: true,
			RSAKeySize:   caRSAKeySize,
			// Whether this certificate is for dual-use clients (SAN+CN).
			IsDualUse:    dualUse, // this params actually not being used
		}
		pemCert, pemKey, ckErr := util.GenCertKeyFromOptions(options)
            }
...
}

```


```go
// security/pkg/pki/util/generate_cert.go

func GenCertKeyFromOptions(options CertOptions) {
...
    return genCert(options, ecPriv, &ecPriv.PublicKey)
}

func genCert(options CertOptions, priv interface{}, key interface{})
...
template, err := genCertTemplateFromOptions(options)
...
}

func genCertTemplateFromOptions(options CertOptions) {
...
	// we will sign a ca cert, and "host" is not specified
	if h := options.Host; len(h) > 0 {
		...
		if options.IsDualUse {
                   ...
		}
		exts = []pkix.Extension{*s}
	}
...
}
```

When creating ca cert, `options.Host` is "",  so `options.IsDualUse` is not used.

2020-12-03 02:29 UTC, lei-tang commented
> > As shown in the following calling flow, IsDualUse is used. Can you clarify why you think IsDualUse is not used?
> > util.GenCertKeyFromOptions(options) ->
> > genCert(options, rsaPriv, &rsaPriv.PublicKey) ->
> > genCertTemplateFromOptions(options) ->
> > if options.IsDualUse {
> > cn, err := DualUseCommonName(h)
> > ...
> > }
> 
> ```go
> // security/pkg/pki/ca/ca.go
> 
> func NewSelfSignedIstioCAOptions() {
> ...
> // secret not found, so we will create priv key self signed cert
>             if scrtErr != nil {
>    		options := util.CertOptions{
> 			TTL:          caCertTTL,
> 			Org:          org,
> 			IsCA:         true,
> 			IsSelfSigned: true,
> 			RSAKeySize:   caRSAKeySize,
> 			// Whether this certificate is for dual-use clients (SAN+CN).
> 			IsDualUse:    dualUse, // this params actually not being used
> 		}
> 		pemCert, pemKey, ckErr := util.GenCertKeyFromOptions(options)
>             }
> ...
> }
> ```
> 
> ```go
> // security/pkg/pki/util/generate_cert.go
> 
> func GenCertKeyFromOptions(options CertOptions) {
> ...
>     return genCert(options, ecPriv, &ecPriv.PublicKey)
> }
> 
> func genCert(options CertOptions, priv interface{}, key interface{})
> ...
> template, err := genCertTemplateFromOptions(options)
> ...
> }
> 
> func genCertTemplateFromOptions(options CertOptions) {
> ...
> 	// we will sign a ca cert, and "host" is not specified
> 	if h := options.Host; len(h) > 0 {
> 		...
> 		if options.IsDualUse {
>                    ...
> 		}
> 		exts = []pkix.Extension{*s}
> 	}
> ...
> }
> ```
> 
> When creating ca cert, `options.Host` is "", so `options.IsDualUse` is not used.

In the flow you mentioned, options.Host is "". But there are other flows that options.Host is not "", which leads to options.IsDualUse being used. An example flow is as follows:
getCertificatesForEachAddress() {
	signerOpts := util.CertOptions{
			Host:         spiffeURI,
         ...
         certPem, privPem, err := util.GenCertKeyFromOptions(signerOpts)
} ->

func GenCertKeyFromOptions(options CertOptions) () ->

func genCert(options CertOptions, priv interface{}, key interface{})() ->

genCertTemplateFromOptions(options) {
	if h := options.Host; len(h) > 0 {
		s, err := BuildSubjectAltNameExtension(h)
		if err != nil {
			return nil, err
		}
		if options.IsDualUse {
}

2021-01-17 05:09 UTC, closed without merging