Fix gateways discoveryAddress outside istio-system
istio/istio pull request #29961
Opened 2021-01-10 22:47 UTC by elfinhe

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

2021-01-10 22:47 UTC, istio-testing commented
Skipping CI for Draft Pull Request.
If you want CI signal for your change, please convert it to an actual PR.
You can still manually trigger a test run with `/test all`

2021-01-10 22:47 UTC, elfinhe commented
/test all

2021-01-10 22:50 UTC, istio-testing commented
@elfinhe: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 3a7d74114fd83b934660f02f6a2e19a8b2bb83ae | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29961/release-notes_istio/1348401099656138752) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-10 23:49 UTC, howardjohn requested changes
Shouldn't we put the full proxy config there? By doing this we give the false impression that this actually works, when in reality any proxy config field will not.

Note that any custom CA or XDS config, including external istiod and mesh ca, require proxy config customization, so it's a very common case

2021-01-11 03:23 UTC, morvencao reviewed
If the gws are installed into different namespace from the istiod, the mesh configmap can't be mounted into the gw pods:
https://github.com/istio/istio/blob/e60c24a399ab0e8293abfc74e9c7d7b7e7e4391e/manifests/charts/gateways/istio-ingress/templates/deployment.yaml#L331-L334
Do we need a copy of the mesh configmap when gws are installed into a different namespace?

2021-01-11 04:57 UTC, elfinhe commented
> proxy config

Thanks John for the quick help. 

As morvencao also pointed out, do you agree if copying the ConfigMap istio-<REV> into the target namespace can be a more reasonable workaround?

btw I add this PR because I see more users reported the same issue happened to them in https://github.com/istio/istio/issues/27265.

2021-01-11 16:08 UTC, howardjohn commented
@elfinhe I think we have a few options

* Add full proxy config into proxy config annotation. Downside: changes to mesh configmap directly have no effect, need to pass all the mesh config settings to gateway install
* Copy configmap to other namespaces. Downside: changes to mesh configmap directly have no effect, need to pass all the mesh config settings to gateway, depend on *how* we copy it it may be complex
* Inject the gateway. Downsides: new (incomplete) feature, more moving parts, untested. But it doesn't have any issues above

2021-01-12 20:50 UTC, elfinhe commented
> @elfinhe I think we have a few options
> 
> * Add full proxy config into proxy config annotation. Downside: changes to mesh configmap directly have no effect, need to pass all the mesh config settings to gateway install
> * Copy configmap to other namespaces. Downside: changes to mesh configmap directly have no effect, need to pass all the mesh config settings to gateway, depend on _how_ we copy it it may be complex
> * Inject the gateway. Downsides: new (incomplete) feature, more moving parts, untested. But it doesn't have any issues above

@howardjohn for the short-term fix, I am thinking about the first option - proxy config annotation. 
Question - will proxy configs other than establishing Istiod/xds connections be pushed by istiod and override the ones in Istio agent during/after the bootstrapping? What's the source of truth?

I will update the PR with annotation copied from the config map. Just noticed that as for meshca workflow, proxyMetadata is already passed as envs for the istio-proxy in the gateway templates.

2021-01-12 20:53 UTC, istio-testing commented
@elfinhe: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | 30328b23946ed94e7cff40a09a951bbb46a3a3bf | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29961/lint_istio/1349096561803530240) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-12 22:02 UTC, istio-testing commented
@elfinhe: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | 30328b23946ed94e7cff40a09a951bbb46a3a3bf | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29961/lint_istio/1349096561803530240) | `/test lint_istio`
gencheck_istio | 00466c1d208933adfca5682a6307f784e8a7f0b4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29961/gencheck_istio/1349114038566522880) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-12 22:02 UTC, istio-testing commented
@elfinhe: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | 00466c1d208933adfca5682a6307f784e8a7f0b4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29961/gencheck_istio/1349114038566522880) | `/test gencheck_istio`
lint_istio | 00466c1d208933adfca5682a6307f784e8a7f0b4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29961/lint_istio/1349114037748633600) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-12 22:04 UTC, istio-testing commented
@elfinhe: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | 00466c1d208933adfca5682a6307f784e8a7f0b4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29961/gencheck_istio/1349114038566522880) | `/test gencheck_istio`
lint_istio | 00466c1d208933adfca5682a6307f784e8a7f0b4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29961/lint_istio/1349114037748633600) | `/test lint_istio`
unit-tests_istio | 00466c1d208933adfca5682a6307f784e8a7f0b4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29961/unit-tests_istio/1349114033533358080) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-12 23:07 UTC, istio-testing commented
@elfinhe: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | 00466c1d208933adfca5682a6307f784e8a7f0b4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29961/lint_istio/1349114037748633600) | `/test lint_istio`
gencheck_istio | c877023aec3d5be29ceffe2b984f269a0dccff4b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29961/gencheck_istio/1349129476524478464) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-12 23:07 UTC, istio-testing commented
@elfinhe: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | c877023aec3d5be29ceffe2b984f269a0dccff4b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29961/gencheck_istio/1349129476524478464) | `/test gencheck_istio`
lint_istio | c877023aec3d5be29ceffe2b984f269a0dccff4b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29961/lint_istio/1349129475685617664) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-12 23:28 UTC, istio-testing commented
@elfinhe: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | 99521536df1b8194e86aeec831204da01b34c995 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29961/lint_istio/1349135588967583744) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-12 23:38 UTC, istio-testing commented
@elfinhe: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | c24f96918578a851a8bb5546bbe74ffa1eac4062 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29961/lint_istio/1349137966441697280) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-13 17:16 UTC, howardjohn requested changes

2021-01-13 17:16 UTC, howardjohn commented on manifests/charts/gateways/istio-egress/templates/deployment.yaml
> +          {{- if .Values.global.meshID }}
I don't think we want to copy the entire thing here, as we will miss new fields. Also, I don't think this is correct as it doesn't handle the merging the we do in the real mesh config with `values.meshConfig`.

I think the way around this is to use templates in helm which I guess doesn't work with multiple charts... but I guess we could at least have a makefile component that syncs them (we do it for istio-remote today)

2021-01-31 21:00 UTC, istio-testing commented
@elfinhe: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-02-28 05:06 UTC, closed without merging