Make iptables wait for the xtables lock
istio/istio pull request #30394
Opened 2021-01-26 14:58 UTC by luksa

By default, the iptables command fails if the xtables lock is held
by another process. Using the -w flag allows iptables to wait for
the lock to be released.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

2021-01-26 14:58 UTC, istio-testing commented
Hi @luksa. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-01-26 15:59 UTC, howardjohn commented
/ok-to-test

2021-01-26 16:00 UTC, howardjohn commented
What situations lead to the xtables lock being held?

My (limited) understanding is if the xtables lock is held, today the init container would crash. When it crashes, won't it just restart anyways? Does CNI behave the same on crashes?

2021-01-26 16:03 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 8c59f6aaa8e166ccd6a66afbe15a077e8e052bf2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1354096695826190336) | `/test release-notes_istio`
unit-tests_istio | 8c59f6aaa8e166ccd6a66afbe15a077e8e052bf2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/unit-tests_istio/1354096689966747648) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-26 16:14 UTC, luksa commented
If the CNI plugin fails, the creation of the pod fails. It is then retried and will eventually succeed. In some cases, OpenShift SDN seems to be making iptables changes during pod creation (concurrently with Istio CNI). Some users are reporting repeated failures due to high contention.

Basically, Istio CNI should not assume that it will be able to get the xtables lock. Adding the `-w` flag makes it more robust.

2021-01-27 01:29 UTC, rlenglet approved these changes
LGTM

2021-01-27 01:33 UTC, rlenglet requested changes
Actually we shouldn't wait indefinitely. Add a timeout to the `-w` option, like 10 seconds. Otherwise, this could make the Istio CNI plugin potentially block indefinitely.

2021-01-29 14:29 UTC, istio-testing commented
@luksa: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-01-29 14:30 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 8c59f6aaa8e166ccd6a66afbe15a077e8e052bf2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1354096695826190336) | `/test release-notes_istio`
unit-tests_istio | 8c59f6aaa8e166ccd6a66afbe15a077e8e052bf2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/unit-tests_istio/1354096689966747648) | `/test unit-tests_istio`
integ-pilot-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355161191059558400) | `/test integ-pilot-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 14:30 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 8c59f6aaa8e166ccd6a66afbe15a077e8e052bf2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1354096695826190336) | `/test release-notes_istio`
unit-tests_istio | 8c59f6aaa8e166ccd6a66afbe15a077e8e052bf2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/unit-tests_istio/1354096689966747648) | `/test unit-tests_istio`
integ-pilot-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355161191059558400) | `/test integ-pilot-k8s-tests_istio`
lint_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1355161195199336448) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 14:30 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 8c59f6aaa8e166ccd6a66afbe15a077e8e052bf2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1354096695826190336) | `/test release-notes_istio`
unit-tests_istio | 8c59f6aaa8e166ccd6a66afbe15a077e8e052bf2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/unit-tests_istio/1354096689966747648) | `/test unit-tests_istio`
integ-pilot-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355161191059558400) | `/test integ-pilot-k8s-tests_istio`
lint_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1355161195199336448) | `/test lint_istio`
integ-ipv6-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355161191227330560) | `/test integ-ipv6-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 14:30 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 8c59f6aaa8e166ccd6a66afbe15a077e8e052bf2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1354096695826190336) | `/test release-notes_istio`
unit-tests_istio | 8c59f6aaa8e166ccd6a66afbe15a077e8e052bf2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/unit-tests_istio/1354096689966747648) | `/test unit-tests_istio`
integ-pilot-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355161191059558400) | `/test integ-pilot-k8s-tests_istio`
lint_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1355161195199336448) | `/test lint_istio`
integ-ipv6-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355161191227330560) | `/test integ-ipv6-k8s-tests_istio`
integ-security-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355161191084724224) | `/test integ-security-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 14:30 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 8c59f6aaa8e166ccd6a66afbe15a077e8e052bf2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1354096695826190336) | `/test release-notes_istio`
integ-pilot-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355161191059558400) | `/test integ-pilot-k8s-tests_istio`
lint_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1355161195199336448) | `/test lint_istio`
integ-ipv6-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355161191227330560) | `/test integ-ipv6-k8s-tests_istio`
integ-security-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355161191084724224) | `/test integ-security-k8s-tests_istio`
unit-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/unit-tests_istio/1355161191005032448) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 14:30 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 8c59f6aaa8e166ccd6a66afbe15a077e8e052bf2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1354096695826190336) | `/test release-notes_istio`
integ-pilot-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355161191059558400) | `/test integ-pilot-k8s-tests_istio`
lint_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1355161195199336448) | `/test lint_istio`
integ-ipv6-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355161191227330560) | `/test integ-ipv6-k8s-tests_istio`
integ-security-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355161191084724224) | `/test integ-security-k8s-tests_istio`
unit-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/unit-tests_istio/1355161191005032448) | `/test unit-tests_istio`
release-test_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-test_istio/1355161191030198272) | `/test release-test_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 14:30 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 8c59f6aaa8e166ccd6a66afbe15a077e8e052bf2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1354096695826190336) | `/test release-notes_istio`
integ-pilot-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355161191059558400) | `/test integ-pilot-k8s-tests_istio`
lint_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1355161195199336448) | `/test lint_istio`
integ-ipv6-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355161191227330560) | `/test integ-ipv6-k8s-tests_istio`
integ-security-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355161191084724224) | `/test integ-security-k8s-tests_istio`
unit-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/unit-tests_istio/1355161191005032448) | `/test unit-tests_istio`
release-test_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-test_istio/1355161191030198272) | `/test release-test_istio`
integ-telemetry-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355161191114084352) | `/test integ-telemetry-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 14:30 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 8c59f6aaa8e166ccd6a66afbe15a077e8e052bf2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1354096695826190336) | `/test release-notes_istio`
integ-pilot-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355161191059558400) | `/test integ-pilot-k8s-tests_istio`
lint_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1355161195199336448) | `/test lint_istio`
integ-ipv6-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355161191227330560) | `/test integ-ipv6-k8s-tests_istio`
integ-security-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355161191084724224) | `/test integ-security-k8s-tests_istio`
unit-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/unit-tests_istio/1355161191005032448) | `/test unit-tests_istio`
release-test_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-test_istio/1355161191030198272) | `/test release-test_istio`
integ-telemetry-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355161191114084352) | `/test integ-telemetry-k8s-tests_istio`
integ-security-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355161192682754048) | `/test integ-security-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 14:30 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 8c59f6aaa8e166ccd6a66afbe15a077e8e052bf2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1354096695826190336) | `/test release-notes_istio`
integ-pilot-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355161191059558400) | `/test integ-pilot-k8s-tests_istio`
lint_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1355161195199336448) | `/test lint_istio`
integ-ipv6-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355161191227330560) | `/test integ-ipv6-k8s-tests_istio`
integ-security-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355161191084724224) | `/test integ-security-k8s-tests_istio`
unit-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/unit-tests_istio/1355161191005032448) | `/test unit-tests_istio`
release-test_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-test_istio/1355161191030198272) | `/test release-test_istio`
integ-telemetry-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355161191114084352) | `/test integ-telemetry-k8s-tests_istio`
integ-security-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355161192682754048) | `/test integ-security-multicluster-tests_istio`
integ-operator-controller-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1355161191260884992) | `/test integ-operator-controller-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 14:30 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 8c59f6aaa8e166ccd6a66afbe15a077e8e052bf2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1354096695826190336) | `/test release-notes_istio`
integ-pilot-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355161191059558400) | `/test integ-pilot-k8s-tests_istio`
lint_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1355161195199336448) | `/test lint_istio`
integ-ipv6-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355161191227330560) | `/test integ-ipv6-k8s-tests_istio`
integ-security-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355161191084724224) | `/test integ-security-k8s-tests_istio`
unit-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/unit-tests_istio/1355161191005032448) | `/test unit-tests_istio`
release-test_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-test_istio/1355161191030198272) | `/test release-test_istio`
integ-telemetry-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355161191114084352) | `/test integ-telemetry-k8s-tests_istio`
integ-security-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355161192682754048) | `/test integ-security-multicluster-tests_istio`
integ-operator-controller-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1355161191260884992) | `/test integ-operator-controller-tests_istio`
gencheck_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/gencheck_istio/1355161196038197248) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 14:30 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 8c59f6aaa8e166ccd6a66afbe15a077e8e052bf2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1354096695826190336) | `/test release-notes_istio`
integ-pilot-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355161191059558400) | `/test integ-pilot-k8s-tests_istio`
lint_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1355161195199336448) | `/test lint_istio`
integ-ipv6-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355161191227330560) | `/test integ-ipv6-k8s-tests_istio`
integ-security-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355161191084724224) | `/test integ-security-k8s-tests_istio`
unit-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/unit-tests_istio/1355161191005032448) | `/test unit-tests_istio`
release-test_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-test_istio/1355161191030198272) | `/test release-test_istio`
integ-telemetry-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355161191114084352) | `/test integ-telemetry-k8s-tests_istio`
integ-security-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355161192682754048) | `/test integ-security-multicluster-tests_istio`
integ-operator-controller-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1355161191260884992) | `/test integ-operator-controller-tests_istio`
gencheck_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/gencheck_istio/1355161196038197248) | `/test gencheck_istio`
integ-pilot-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1355161191848087552) | `/test integ-pilot-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 14:30 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 8c59f6aaa8e166ccd6a66afbe15a077e8e052bf2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1354096695826190336) | `/test release-notes_istio`
integ-pilot-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355161191059558400) | `/test integ-pilot-k8s-tests_istio`
lint_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1355161195199336448) | `/test lint_istio`
integ-ipv6-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355161191227330560) | `/test integ-ipv6-k8s-tests_istio`
integ-security-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355161191084724224) | `/test integ-security-k8s-tests_istio`
unit-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/unit-tests_istio/1355161191005032448) | `/test unit-tests_istio`
release-test_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-test_istio/1355161191030198272) | `/test release-test_istio`
integ-telemetry-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355161191114084352) | `/test integ-telemetry-k8s-tests_istio`
integ-security-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355161192682754048) | `/test integ-security-multicluster-tests_istio`
integ-operator-controller-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1355161191260884992) | `/test integ-operator-controller-tests_istio`
gencheck_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/gencheck_istio/1355161196038197248) | `/test gencheck_istio`
integ-pilot-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1355161191848087552) | `/test integ-pilot-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1355161191139250176) | `/test integ-telemetry-mc-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 14:30 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 8c59f6aaa8e166ccd6a66afbe15a077e8e052bf2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1354096695826190336) | `/test release-notes_istio`
integ-pilot-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355161191059558400) | `/test integ-pilot-k8s-tests_istio`
lint_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1355161195199336448) | `/test lint_istio`
integ-ipv6-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355161191227330560) | `/test integ-ipv6-k8s-tests_istio`
integ-security-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355161191084724224) | `/test integ-security-k8s-tests_istio`
unit-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/unit-tests_istio/1355161191005032448) | `/test unit-tests_istio`
release-test_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-test_istio/1355161191030198272) | `/test release-test_istio`
integ-telemetry-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355161191114084352) | `/test integ-telemetry-k8s-tests_istio`
integ-security-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355161192682754048) | `/test integ-security-multicluster-tests_istio`
integ-operator-controller-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1355161191260884992) | `/test integ-operator-controller-tests_istio`
gencheck_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/gencheck_istio/1355161196038197248) | `/test gencheck_istio`
integ-pilot-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1355161191848087552) | `/test integ-pilot-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1355161191139250176) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-helm-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1355161193521614848) | `/test integ-helm-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 14:30 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 8c59f6aaa8e166ccd6a66afbe15a077e8e052bf2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1354096695826190336) | `/test release-notes_istio`
integ-pilot-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355161191059558400) | `/test integ-pilot-k8s-tests_istio`
lint_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1355161195199336448) | `/test lint_istio`
integ-ipv6-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355161191227330560) | `/test integ-ipv6-k8s-tests_istio`
integ-security-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355161191084724224) | `/test integ-security-k8s-tests_istio`
unit-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/unit-tests_istio/1355161191005032448) | `/test unit-tests_istio`
release-test_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-test_istio/1355161191030198272) | `/test release-test_istio`
integ-telemetry-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355161191114084352) | `/test integ-telemetry-k8s-tests_istio`
integ-security-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355161192682754048) | `/test integ-security-multicluster-tests_istio`
integ-operator-controller-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1355161191260884992) | `/test integ-operator-controller-tests_istio`
gencheck_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/gencheck_istio/1355161196038197248) | `/test gencheck_istio`
integ-pilot-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1355161191848087552) | `/test integ-pilot-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1355161191139250176) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-helm-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1355161193521614848) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1355161191168610304) | `/test integ-multicluster-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 14:30 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 8c59f6aaa8e166ccd6a66afbe15a077e8e052bf2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1354096695826190336) | `/test release-notes_istio`
integ-pilot-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355161191059558400) | `/test integ-pilot-k8s-tests_istio`
lint_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1355161195199336448) | `/test lint_istio`
integ-ipv6-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355161191227330560) | `/test integ-ipv6-k8s-tests_istio`
integ-security-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355161191084724224) | `/test integ-security-k8s-tests_istio`
unit-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/unit-tests_istio/1355161191005032448) | `/test unit-tests_istio`
release-test_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-test_istio/1355161191030198272) | `/test release-test_istio`
integ-telemetry-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355161191114084352) | `/test integ-telemetry-k8s-tests_istio`
integ-security-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355161192682754048) | `/test integ-security-multicluster-tests_istio`
integ-operator-controller-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1355161191260884992) | `/test integ-operator-controller-tests_istio`
gencheck_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/gencheck_istio/1355161196038197248) | `/test gencheck_istio`
integ-pilot-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1355161191848087552) | `/test integ-pilot-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1355161191139250176) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-helm-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1355161193521614848) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1355161191168610304) | `/test integ-multicluster-k8s-tests_istio`
analyze-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/analyze-tests_istio/1355161194364669952) | `/test analyze-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 14:30 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 8c59f6aaa8e166ccd6a66afbe15a077e8e052bf2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1354096695826190336) | `/test release-notes_istio`
integ-pilot-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355161191059558400) | `/test integ-pilot-k8s-tests_istio`
lint_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1355161195199336448) | `/test lint_istio`
integ-ipv6-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355161191227330560) | `/test integ-ipv6-k8s-tests_istio`
integ-security-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355161191084724224) | `/test integ-security-k8s-tests_istio`
unit-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/unit-tests_istio/1355161191005032448) | `/test unit-tests_istio`
release-test_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-test_istio/1355161191030198272) | `/test release-test_istio`
integ-telemetry-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355161191114084352) | `/test integ-telemetry-k8s-tests_istio`
integ-security-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355161192682754048) | `/test integ-security-multicluster-tests_istio`
integ-operator-controller-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1355161191260884992) | `/test integ-operator-controller-tests_istio`
gencheck_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/gencheck_istio/1355161196038197248) | `/test gencheck_istio`
integ-pilot-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1355161191848087552) | `/test integ-pilot-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1355161191139250176) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-helm-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1355161193521614848) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1355161191168610304) | `/test integ-multicluster-k8s-tests_istio`
analyze-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/analyze-tests_istio/1355161194364669952) | `/test analyze-tests_istio`
integ-distroless-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1355161191197970432) | `/test integ-distroless-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 14:30 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355161191059558400) | `/test integ-pilot-k8s-tests_istio`
lint_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1355161195199336448) | `/test lint_istio`
integ-ipv6-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355161191227330560) | `/test integ-ipv6-k8s-tests_istio`
integ-security-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355161191084724224) | `/test integ-security-k8s-tests_istio`
unit-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/unit-tests_istio/1355161191005032448) | `/test unit-tests_istio`
release-test_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-test_istio/1355161191030198272) | `/test release-test_istio`
integ-telemetry-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355161191114084352) | `/test integ-telemetry-k8s-tests_istio`
integ-security-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355161192682754048) | `/test integ-security-multicluster-tests_istio`
integ-operator-controller-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1355161191260884992) | `/test integ-operator-controller-tests_istio`
gencheck_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/gencheck_istio/1355161196038197248) | `/test gencheck_istio`
integ-pilot-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1355161191848087552) | `/test integ-pilot-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1355161191139250176) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-helm-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1355161193521614848) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1355161191168610304) | `/test integ-multicluster-k8s-tests_istio`
analyze-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/analyze-tests_istio/1355161194364669952) | `/test analyze-tests_istio`
integ-distroless-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1355161191197970432) | `/test integ-distroless-k8s-tests_istio`
release-notes_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1355161196877058048) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 14:38 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355161191059558400) | `/test integ-pilot-k8s-tests_istio`
lint_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1355161195199336448) | `/test lint_istio`
integ-ipv6-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355161191227330560) | `/test integ-ipv6-k8s-tests_istio`
integ-security-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355161191084724224) | `/test integ-security-k8s-tests_istio`
unit-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/unit-tests_istio/1355161191005032448) | `/test unit-tests_istio`
release-test_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-test_istio/1355161191030198272) | `/test release-test_istio`
integ-telemetry-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355161191114084352) | `/test integ-telemetry-k8s-tests_istio`
integ-security-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355161192682754048) | `/test integ-security-multicluster-tests_istio`
integ-operator-controller-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1355161191260884992) | `/test integ-operator-controller-tests_istio`
gencheck_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/gencheck_istio/1355161196038197248) | `/test gencheck_istio`
integ-pilot-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1355161191848087552) | `/test integ-pilot-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1355161191139250176) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-helm-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1355161193521614848) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1355161191168610304) | `/test integ-multicluster-k8s-tests_istio`
analyze-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/analyze-tests_istio/1355161194364669952) | `/test analyze-tests_istio`
integ-distroless-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1355161191197970432) | `/test integ-distroless-k8s-tests_istio`
release-notes_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1355163255592456192) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 14:39 UTC, luksa commented
@rlenglet Thanks. You're right. I've now introduced a 10s wait time. This should probably be configurable, but 10s sounds like a good value.

2021-01-29 14:44 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355161191059558400) | `/test integ-pilot-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355161191227330560) | `/test integ-ipv6-k8s-tests_istio`
integ-security-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355161191084724224) | `/test integ-security-k8s-tests_istio`
release-test_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-test_istio/1355161191030198272) | `/test release-test_istio`
integ-telemetry-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355161191114084352) | `/test integ-telemetry-k8s-tests_istio`
integ-security-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355161192682754048) | `/test integ-security-multicluster-tests_istio`
integ-operator-controller-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1355161191260884992) | `/test integ-operator-controller-tests_istio`
integ-pilot-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1355161191848087552) | `/test integ-pilot-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1355161191139250176) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-helm-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1355161193521614848) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1355161191168610304) | `/test integ-multicluster-k8s-tests_istio`
release-notes_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1355163255592456192) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1355163249888202752) | `/test integ-distroless-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 14:53 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355161191059558400) | `/test integ-pilot-k8s-tests_istio`
integ-security-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355161191084724224) | `/test integ-security-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355161191114084352) | `/test integ-telemetry-k8s-tests_istio`
integ-security-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355161192682754048) | `/test integ-security-multicluster-tests_istio`
integ-operator-controller-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1355161191260884992) | `/test integ-operator-controller-tests_istio`
integ-pilot-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1355161191848087552) | `/test integ-pilot-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1355161191139250176) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-helm-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1355161193521614848) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1355161191168610304) | `/test integ-multicluster-k8s-tests_istio`
release-notes_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1355163255592456192) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1355163249888202752) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355163249909174272) | `/test integ-ipv6-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 14:54 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355161191059558400) | `/test integ-pilot-k8s-tests_istio`
integ-security-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355161191084724224) | `/test integ-security-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355161191114084352) | `/test integ-telemetry-k8s-tests_istio`
integ-security-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355161192682754048) | `/test integ-security-multicluster-tests_istio`
integ-operator-controller-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1355161191260884992) | `/test integ-operator-controller-tests_istio`
integ-pilot-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1355161191848087552) | `/test integ-pilot-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1355161191139250176) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1355161191168610304) | `/test integ-multicluster-k8s-tests_istio`
release-notes_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1355163255592456192) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1355163249888202752) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355163249909174272) | `/test integ-ipv6-k8s-tests_istio`
integ-helm-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1355163252237012992) | `/test integ-helm-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 14:54 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355161191059558400) | `/test integ-pilot-k8s-tests_istio`
integ-security-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355161191084724224) | `/test integ-security-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355161191114084352) | `/test integ-telemetry-k8s-tests_istio`
integ-security-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355161192682754048) | `/test integ-security-multicluster-tests_istio`
integ-operator-controller-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1355161191260884992) | `/test integ-operator-controller-tests_istio`
integ-pilot-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1355161191848087552) | `/test integ-pilot-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1355161191139250176) | `/test integ-telemetry-mc-k8s-tests_istio`
release-notes_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1355163255592456192) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1355163249888202752) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355163249909174272) | `/test integ-ipv6-k8s-tests_istio`
integ-helm-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1355163252237012992) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1355163249871425536) | `/test integ-multicluster-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 14:59 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355161191059558400) | `/test integ-pilot-k8s-tests_istio`
integ-security-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355161191084724224) | `/test integ-security-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355161191114084352) | `/test integ-telemetry-k8s-tests_istio`
integ-security-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355161192682754048) | `/test integ-security-multicluster-tests_istio`
integ-pilot-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1355161191848087552) | `/test integ-pilot-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1355161191139250176) | `/test integ-telemetry-mc-k8s-tests_istio`
release-notes_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1355163255592456192) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1355163249888202752) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355163249909174272) | `/test integ-ipv6-k8s-tests_istio`
integ-helm-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1355163252237012992) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1355163249871425536) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1355163249934340096) | `/test integ-operator-controller-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 15:09 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355161191059558400) | `/test integ-pilot-k8s-tests_istio`
integ-security-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355161191084724224) | `/test integ-security-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355161191114084352) | `/test integ-telemetry-k8s-tests_istio`
integ-security-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355161192682754048) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1355161191139250176) | `/test integ-telemetry-mc-k8s-tests_istio`
release-notes_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1355163255592456192) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1355163249888202752) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355163249909174272) | `/test integ-ipv6-k8s-tests_istio`
integ-helm-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1355163252237012992) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1355163249871425536) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1355163249934340096) | `/test integ-operator-controller-tests_istio`
integ-pilot-multicluster-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1355163250563485696) | `/test integ-pilot-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 15:17 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355161191084724224) | `/test integ-security-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355161191114084352) | `/test integ-telemetry-k8s-tests_istio`
integ-security-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355161192682754048) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1355161191139250176) | `/test integ-telemetry-mc-k8s-tests_istio`
release-notes_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1355163255592456192) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1355163249888202752) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355163249909174272) | `/test integ-ipv6-k8s-tests_istio`
integ-helm-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1355163252237012992) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1355163249871425536) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1355163249934340096) | `/test integ-operator-controller-tests_istio`
integ-pilot-multicluster-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1355163250563485696) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355163249770762240) | `/test integ-pilot-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 16:06 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355161191084724224) | `/test integ-security-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355161191114084352) | `/test integ-telemetry-k8s-tests_istio`
integ-security-multicluster-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355161192682754048) | `/test integ-security-multicluster-tests_istio`
release-notes_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1355163255592456192) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1355163249888202752) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355163249909174272) | `/test integ-ipv6-k8s-tests_istio`
integ-helm-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1355163252237012992) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1355163249871425536) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1355163249934340096) | `/test integ-operator-controller-tests_istio`
integ-pilot-multicluster-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1355163250563485696) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355163249770762240) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1355163249846259712) | `/test integ-telemetry-mc-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 16:17 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355161191084724224) | `/test integ-security-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355161191114084352) | `/test integ-telemetry-k8s-tests_istio`
release-notes_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1355163255592456192) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1355163249888202752) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355163249909174272) | `/test integ-ipv6-k8s-tests_istio`
integ-helm-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1355163252237012992) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1355163249871425536) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1355163249934340096) | `/test integ-operator-controller-tests_istio`
integ-pilot-multicluster-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1355163250563485696) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355163249770762240) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1355163249846259712) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355163251423318016) | `/test integ-security-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 16:39 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-k8s-tests_istio | e12557d1d52ab9bf6eac67945a0010bd2214adfc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355161191084724224) | `/test integ-security-k8s-tests_istio`
release-notes_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1355163255592456192) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1355163249888202752) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355163249909174272) | `/test integ-ipv6-k8s-tests_istio`
integ-helm-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1355163252237012992) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1355163249871425536) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1355163249934340096) | `/test integ-operator-controller-tests_istio`
integ-pilot-multicluster-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1355163250563485696) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355163249770762240) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1355163249846259712) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355163251423318016) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355163249825288192) | `/test integ-telemetry-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 16:39 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1355163255592456192) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1355163249888202752) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355163249909174272) | `/test integ-ipv6-k8s-tests_istio`
integ-helm-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1355163252237012992) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1355163249871425536) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1355163249934340096) | `/test integ-operator-controller-tests_istio`
integ-pilot-multicluster-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1355163250563485696) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355163249770762240) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1355163249846259712) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355163251423318016) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355163249825288192) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355163249800122368) | `/test integ-security-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-29 16:46 UTC, rlenglet approved these changes
Looks good. Thanks!

2021-01-29 16:46 UTC, rlenglet commented on tools/istio-clean-iptables/pkg/cmd/cleanup.go
> +		ext.RunQuietlyAndIgnore(cmd, "-w", "-t", table, "-F", chain)
For consistency, it would be good to add the timeout to the commands in this file as well.
Not a blocker, though.

2021-02-03 14:51 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-distroless-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1355163249888202752) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355163249909174272) | `/test integ-ipv6-k8s-tests_istio`
integ-helm-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1355163252237012992) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1355163249871425536) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1355163249934340096) | `/test integ-operator-controller-tests_istio`
integ-pilot-multicluster-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1355163250563485696) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355163249770762240) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1355163249846259712) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355163251423318016) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355163249825288192) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355163249800122368) | `/test integ-security-k8s-tests_istio`
lint_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1356977219615854592) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-03 14:59 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-ipv6-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1355163249909174272) | `/test integ-ipv6-k8s-tests_istio`
integ-helm-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1355163252237012992) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1355163249871425536) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1355163249934340096) | `/test integ-operator-controller-tests_istio`
integ-pilot-multicluster-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1355163250563485696) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355163249770762240) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1355163249846259712) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355163251423318016) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355163249825288192) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355163249800122368) | `/test integ-security-k8s-tests_istio`
lint_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1356977219615854592) | `/test lint_istio`
integ-distroless-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1356977215597711360) | `/test integ-distroless-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-03 15:02 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-helm-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1355163252237012992) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1355163249871425536) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1355163249934340096) | `/test integ-operator-controller-tests_istio`
integ-pilot-multicluster-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1355163250563485696) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355163249770762240) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1355163249846259712) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355163251423318016) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355163249825288192) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355163249800122368) | `/test integ-security-k8s-tests_istio`
lint_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1356977219615854592) | `/test lint_istio`
integ-distroless-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1356977215597711360) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1356977215618682880) | `/test integ-ipv6-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-03 15:07 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-helm-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1355163252237012992) | `/test integ-helm-tests_istio`
integ-operator-controller-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1355163249934340096) | `/test integ-operator-controller-tests_istio`
integ-pilot-multicluster-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1355163250563485696) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355163249770762240) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1355163249846259712) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355163251423318016) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355163249825288192) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355163249800122368) | `/test integ-security-k8s-tests_istio`
lint_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1356977219615854592) | `/test lint_istio`
integ-distroless-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1356977215597711360) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1356977215618682880) | `/test integ-ipv6-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1356977215564156928) | `/test integ-multicluster-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-03 15:11 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-helm-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1355163252237012992) | `/test integ-helm-tests_istio`
integ-pilot-multicluster-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1355163250563485696) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355163249770762240) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1355163249846259712) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355163251423318016) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355163249825288192) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355163249800122368) | `/test integ-security-k8s-tests_istio`
lint_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1356977219615854592) | `/test lint_istio`
integ-distroless-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1356977215597711360) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1356977215618682880) | `/test integ-ipv6-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1356977215564156928) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1356977215643848704) | `/test integ-operator-controller-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-03 15:13 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-multicluster-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1355163250563485696) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355163249770762240) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1355163249846259712) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355163251423318016) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355163249825288192) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355163249800122368) | `/test integ-security-k8s-tests_istio`
lint_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1356977219615854592) | `/test lint_istio`
integ-distroless-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1356977215597711360) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1356977215618682880) | `/test integ-ipv6-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1356977215564156928) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1356977215643848704) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1356977217942327296) | `/test integ-helm-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-03 15:41 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1355163249770762240) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1355163249846259712) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355163251423318016) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355163249825288192) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355163249800122368) | `/test integ-security-k8s-tests_istio`
lint_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1356977219615854592) | `/test lint_istio`
integ-distroless-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1356977215597711360) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1356977215618682880) | `/test integ-ipv6-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1356977215564156928) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1356977215643848704) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1356977217942327296) | `/test integ-helm-tests_istio`
integ-pilot-multicluster-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1356977216260411392) | `/test integ-pilot-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-03 15:55 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-mc-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1355163249846259712) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355163251423318016) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355163249825288192) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355163249800122368) | `/test integ-security-k8s-tests_istio`
lint_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1356977219615854592) | `/test lint_istio`
integ-distroless-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1356977215597711360) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1356977215618682880) | `/test integ-ipv6-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1356977215564156928) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1356977215643848704) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1356977217942327296) | `/test integ-helm-tests_istio`
integ-pilot-multicluster-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1356977216260411392) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1356977215471882240) | `/test integ-pilot-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-03 16:11 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-multicluster-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1355163251423318016) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355163249825288192) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355163249800122368) | `/test integ-security-k8s-tests_istio`
lint_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1356977219615854592) | `/test lint_istio`
integ-distroless-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1356977215597711360) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1356977215618682880) | `/test integ-ipv6-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1356977215564156928) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1356977215643848704) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1356977217942327296) | `/test integ-helm-tests_istio`
integ-pilot-multicluster-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1356977216260411392) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1356977215471882240) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1356977215543185408) | `/test integ-telemetry-mc-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-03 16:31 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1355163249825288192) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355163249800122368) | `/test integ-security-k8s-tests_istio`
lint_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1356977219615854592) | `/test lint_istio`
integ-distroless-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1356977215597711360) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1356977215618682880) | `/test integ-ipv6-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1356977215564156928) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1356977215643848704) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1356977217942327296) | `/test integ-helm-tests_istio`
integ-pilot-multicluster-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1356977216260411392) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1356977215471882240) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1356977215543185408) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1356977217103466496) | `/test integ-security-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-03 16:47 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-k8s-tests_istio | 640b2287b6a0e38bac3ec2dc55b1bdf470cbb58d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1355163249800122368) | `/test integ-security-k8s-tests_istio`
lint_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1356977219615854592) | `/test lint_istio`
integ-distroless-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1356977215597711360) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1356977215618682880) | `/test integ-ipv6-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1356977215564156928) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1356977215643848704) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1356977217942327296) | `/test integ-helm-tests_istio`
integ-pilot-multicluster-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1356977216260411392) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1356977215471882240) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1356977215543185408) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1356977217103466496) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1356977215509630976) | `/test integ-telemetry-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-03 16:47 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1356977219615854592) | `/test lint_istio`
integ-distroless-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1356977215597711360) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1356977215618682880) | `/test integ-ipv6-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1356977215564156928) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1356977215643848704) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1356977217942327296) | `/test integ-helm-tests_istio`
integ-pilot-multicluster-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1356977216260411392) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1356977215471882240) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1356977215543185408) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1356977217103466496) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1356977215509630976) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1356977215497048064) | `/test integ-security-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-06 00:19 UTC, istio-testing commented
@luksa: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-02-09 15:34 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-distroless-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1356977215597711360) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1356977215618682880) | `/test integ-ipv6-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1356977215564156928) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1356977215643848704) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1356977217942327296) | `/test integ-helm-tests_istio`
integ-pilot-multicluster-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1356977216260411392) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1356977215471882240) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1356977215543185408) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1356977217103466496) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1356977215509630976) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1356977215497048064) | `/test integ-security-k8s-tests_istio`
lint_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1359163120198619136) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-09 15:35 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-distroless-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1356977215597711360) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1356977215618682880) | `/test integ-ipv6-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1356977215564156928) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1356977215643848704) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1356977217942327296) | `/test integ-helm-tests_istio`
integ-pilot-multicluster-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1356977216260411392) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1356977215471882240) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1356977215543185408) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1356977217103466496) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1356977215509630976) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1356977215497048064) | `/test integ-security-k8s-tests_istio`
lint_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1359163120198619136) | `/test lint_istio`
release-notes_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1359163121876340736) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-09 15:38 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-ipv6-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1356977215618682880) | `/test integ-ipv6-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1356977215564156928) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1356977215643848704) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1356977217942327296) | `/test integ-helm-tests_istio`
integ-pilot-multicluster-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1356977216260411392) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1356977215471882240) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1356977215543185408) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1356977217103466496) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1356977215509630976) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1356977215497048064) | `/test integ-security-k8s-tests_istio`
lint_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1359163120198619136) | `/test lint_istio`
release-notes_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1359163121876340736) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1359163116180475904) | `/test integ-distroless-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-09 15:46 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-multicluster-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1356977215564156928) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1356977215643848704) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1356977217942327296) | `/test integ-helm-tests_istio`
integ-pilot-multicluster-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1356977216260411392) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1356977215471882240) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1356977215543185408) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1356977217103466496) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1356977215509630976) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1356977215497048064) | `/test integ-security-k8s-tests_istio`
lint_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1359163120198619136) | `/test lint_istio`
release-notes_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1359163121876340736) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1359163116180475904) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1359163116197253120) | `/test integ-ipv6-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-09 15:46 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-multicluster-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1356977215564156928) | `/test integ-multicluster-k8s-tests_istio`
integ-helm-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1356977217942327296) | `/test integ-helm-tests_istio`
integ-pilot-multicluster-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1356977216260411392) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1356977215471882240) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1356977215543185408) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1356977217103466496) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1356977215509630976) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1356977215497048064) | `/test integ-security-k8s-tests_istio`
lint_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1359163120198619136) | `/test lint_istio`
release-notes_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1359163121876340736) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1359163116180475904) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1359163116197253120) | `/test integ-ipv6-k8s-tests_istio`
integ-operator-controller-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1359163116226613248) | `/test integ-operator-controller-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-09 15:50 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-multicluster-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1356977215564156928) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1356977216260411392) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1356977215471882240) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1356977215543185408) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1356977217103466496) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1356977215509630976) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1356977215497048064) | `/test integ-security-k8s-tests_istio`
lint_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1359163120198619136) | `/test lint_istio`
release-notes_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1359163121876340736) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1359163116180475904) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1359163116197253120) | `/test integ-ipv6-k8s-tests_istio`
integ-operator-controller-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1359163116226613248) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1359163118525091840) | `/test integ-helm-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-09 15:55 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-multicluster-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1356977216260411392) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1356977215471882240) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1356977215543185408) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1356977217103466496) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1356977215509630976) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1356977215497048064) | `/test integ-security-k8s-tests_istio`
lint_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1359163120198619136) | `/test lint_istio`
release-notes_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1359163121876340736) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1359163116180475904) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1359163116197253120) | `/test integ-ipv6-k8s-tests_istio`
integ-operator-controller-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1359163116226613248) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1359163118525091840) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1359163116155310080) | `/test integ-multicluster-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-09 16:13 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1356977215471882240) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1356977215543185408) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1356977217103466496) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1356977215509630976) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1356977215497048064) | `/test integ-security-k8s-tests_istio`
lint_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1359163120198619136) | `/test lint_istio`
release-notes_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1359163121876340736) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1359163116180475904) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1359163116197253120) | `/test integ-ipv6-k8s-tests_istio`
integ-operator-controller-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1359163116226613248) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1359163118525091840) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1359163116155310080) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1359163116843175936) | `/test integ-pilot-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-09 16:52 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-mc-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1356977215543185408) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1356977217103466496) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1356977215509630976) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1356977215497048064) | `/test integ-security-k8s-tests_istio`
lint_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1359163120198619136) | `/test lint_istio`
release-notes_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1359163121876340736) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1359163116180475904) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1359163116197253120) | `/test integ-ipv6-k8s-tests_istio`
integ-operator-controller-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1359163116226613248) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1359163118525091840) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1359163116155310080) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1359163116843175936) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1359163116058841088) | `/test integ-pilot-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-09 16:56 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-multicluster-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1356977217103466496) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1356977215509630976) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1356977215497048064) | `/test integ-security-k8s-tests_istio`
lint_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1359163120198619136) | `/test lint_istio`
release-notes_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1359163121876340736) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1359163116180475904) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1359163116197253120) | `/test integ-ipv6-k8s-tests_istio`
integ-operator-controller-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1359163116226613248) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1359163118525091840) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1359163116155310080) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1359163116843175936) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1359163116058841088) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1359163116134338560) | `/test integ-telemetry-mc-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-09 17:09 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1356977215509630976) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1356977215497048064) | `/test integ-security-k8s-tests_istio`
lint_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1359163120198619136) | `/test lint_istio`
release-notes_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1359163121876340736) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1359163116180475904) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1359163116197253120) | `/test integ-ipv6-k8s-tests_istio`
integ-operator-controller-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1359163116226613248) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1359163118525091840) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1359163116155310080) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1359163116843175936) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1359163116058841088) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1359163116134338560) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1359163117690425344) | `/test integ-security-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-09 17:17 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1356977215509630976) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1356977215497048064) | `/test integ-security-k8s-tests_istio`
lint_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/lint_istio/1359163120198619136) | `/test lint_istio`
integ-distroless-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1359163116180475904) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1359163116197253120) | `/test integ-ipv6-k8s-tests_istio`
integ-operator-controller-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1359163116226613248) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1359163118525091840) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1359163116155310080) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1359163116843175936) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1359163116058841088) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1359163116134338560) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1359163117690425344) | `/test integ-security-multicluster-tests_istio`
release-notes_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1359189438894182400) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-09 17:22 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1356977215509630976) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1356977215497048064) | `/test integ-security-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1359163116197253120) | `/test integ-ipv6-k8s-tests_istio`
integ-operator-controller-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1359163116226613248) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1359163118525091840) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1359163116155310080) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1359163116843175936) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1359163116058841088) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1359163116134338560) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1359163117690425344) | `/test integ-security-multicluster-tests_istio`
release-notes_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1359189438894182400) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1359189433240260608) | `/test integ-distroless-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-09 17:31 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1356977215509630976) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1356977215497048064) | `/test integ-security-k8s-tests_istio`
integ-operator-controller-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1359163116226613248) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1359163118525091840) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1359163116155310080) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1359163116843175936) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1359163116058841088) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1359163116134338560) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1359163117690425344) | `/test integ-security-multicluster-tests_istio`
release-notes_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1359189438894182400) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1359189433240260608) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1359189433261232128) | `/test integ-ipv6-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-09 17:31 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1356977215509630976) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1356977215497048064) | `/test integ-security-k8s-tests_istio`
integ-helm-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1359163118525091840) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1359163116155310080) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1359163116843175936) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1359163116058841088) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1359163116134338560) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1359163117690425344) | `/test integ-security-multicluster-tests_istio`
release-notes_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1359189438894182400) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1359189433240260608) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1359189433261232128) | `/test integ-ipv6-k8s-tests_istio`
integ-operator-controller-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1359189433273815040) | `/test integ-operator-controller-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-09 17:35 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1356977215509630976) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1356977215497048064) | `/test integ-security-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1359163116155310080) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1359163116843175936) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1359163116058841088) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1359163116134338560) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1359163117690425344) | `/test integ-security-multicluster-tests_istio`
release-notes_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1359189438894182400) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1359189433240260608) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1359189433261232128) | `/test integ-ipv6-k8s-tests_istio`
integ-operator-controller-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1359189433273815040) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1359189435542933504) | `/test integ-helm-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-09 17:39 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1356977215509630976) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1356977215497048064) | `/test integ-security-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1359163116843175936) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1359163116058841088) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1359163116134338560) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1359163117690425344) | `/test integ-security-multicluster-tests_istio`
release-notes_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1359189438894182400) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1359189433240260608) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1359189433261232128) | `/test integ-ipv6-k8s-tests_istio`
integ-operator-controller-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1359189433273815040) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1359189435542933504) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1359189433202511872) | `/test integ-multicluster-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-09 17:59 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1356977215509630976) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1356977215497048064) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1359163116058841088) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1359163116134338560) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1359163117690425344) | `/test integ-security-multicluster-tests_istio`
release-notes_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1359189438894182400) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1359189433240260608) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1359189433261232128) | `/test integ-ipv6-k8s-tests_istio`
integ-operator-controller-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1359189433273815040) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1359189435542933504) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1359189433202511872) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1359189433881989120) | `/test integ-pilot-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-09 18:03 UTC, rlenglet commented
@luksa please address the test failure issues. This PR won't merge until you do that.
I looked at the failing `integ-distroless-k8s-tests_istio` test.
Found this in one of the [`istio-proxy` container logs](https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1359189433240260608/artifacts/kind/istio-testing-control-plane/pods/test-ns1-2-56965_vm-v1-6cb7f8bc58-glblq_030615e8-8644-4877-96fb-bd945ac0d567/istio-proxy/0.log):
```
2021-02-09T17:20:59.653131256Z stdout F iptables-restore -w 10 --noflush /tmp/iptables-rules-1612891259652358218.txt879865237
2021-02-09T17:20:59.654770885Z stdout F iptables-save 
2021-02-09T17:20:59.654801547Z stderr F iptables-restore: invalid option -- 'w'
2021-02-09T17:20:59.654818604Z stderr F Unknown arguments found on commandline
...
2021-02-09T17:20:59.659428909Z stderr F panic: exit status 1
2021-02-09T17:20:59.659459288Z stderr F 
2021-02-09T17:20:59.65946595Z stderr F goroutine 1 [running]:
2021-02-09T17:20:59.659472002Z stderr F istio.io/istio/tools/istio-iptables/pkg/dependencies.(*RealDependencies).RunOrFail(0x2696e18, 0x18b1546, 0x10, 0xc000825900, 0x4, 0x4)
2021-02-09T17:20:59.659478559Z stderr F 	istio.io/istio/tools/istio-iptables/pkg/dependencies/implementation.go:43 +0x9c
2021-02-09T17:20:59.659488313Z stderr F istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeIptablesRestoreCommand(0xc0009dbd78, 0x7f3f74903a01, 0x0, 0x0)
2021-02-09T17:20:59.659503088Z stderr F 	istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:619 +0x3ac
2021-02-09T17:20:59.659509423Z stderr F istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeCommands(0xc0009dbd78)
2021-02-09T17:20:59.659515474Z stderr F 	istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:626 +0x45
2021-02-09T17:20:59.659521163Z stderr F istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).run(0xc0009dbd78)
2021-02-09T17:20:59.659560909Z stderr F 	istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:564 +0x2dbb
2021-02-09T17:20:59.659597004Z stderr F istio.io/istio/tools/istio-iptables/pkg/cmd.glob..func2(0x2650920, 0x2696e18, 0x0, 0x0)
2021-02-09T17:20:59.65960785Z stderr F 	istio.io/istio/tools/istio-iptables/pkg/cmd/root.go:65 +0x165
2021-02-09T17:20:59.659616003Z stderr F github.com/spf13/cobra.(*Command).execute(0x2650920, 0x2696e18, 0x0, 0x0, 0x2650920, 0x2696e18)
2021-02-09T17:20:59.659627321Z stderr F 	github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
2021-02-09T17:20:59.659635741Z stderr F github.com/spf13/cobra.(*Command).ExecuteC(0x2650bc0, 0x41af01, 0x0, 0x0)
2021-02-09T17:20:59.659643701Z stderr F 	github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
2021-02-09T17:20:59.659683259Z stderr F github.com/spf13/cobra.(*Command).Execute(...)
2021-02-09T17:20:59.659701523Z stderr F 	github.com/spf13/cobra@v1.1.1/command.go:895
2021-02-09T17:20:59.659706156Z stderr F main.main()
2021-02-09T17:20:59.659710741Z stderr F 	istio.io/istio/pilot/cmd/pilot-agent/main.go:455 +0x31
```

I'm not sure what particular test is failing here.
It seems like some container images contain versions of `iptables-restore` that don't support the `-w` option?

2021-02-09 18:39 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1356977215509630976) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1356977215497048064) | `/test integ-security-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1359163116134338560) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1359163117690425344) | `/test integ-security-multicluster-tests_istio`
release-notes_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1359189438894182400) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1359189433240260608) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1359189433261232128) | `/test integ-ipv6-k8s-tests_istio`
integ-operator-controller-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1359189433273815040) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1359189435542933504) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1359189433202511872) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1359189433881989120) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1359189433080877056) | `/test integ-pilot-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-09 18:42 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1356977215509630976) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1356977215497048064) | `/test integ-security-k8s-tests_istio`
integ-security-multicluster-tests_istio | 4055caf806ff30e801e0e79bc3ef5529de865f7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1359163117690425344) | `/test integ-security-multicluster-tests_istio`
release-notes_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1359189438894182400) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1359189433240260608) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1359189433261232128) | `/test integ-ipv6-k8s-tests_istio`
integ-operator-controller-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1359189433273815040) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1359189435542933504) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1359189433202511872) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1359189433881989120) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1359189433080877056) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1359189433185734656) | `/test integ-telemetry-mc-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-09 18:53 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1356977215509630976) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1356977215497048064) | `/test integ-security-k8s-tests_istio`
release-notes_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1359189438894182400) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1359189433240260608) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1359189433261232128) | `/test integ-ipv6-k8s-tests_istio`
integ-operator-controller-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1359189433273815040) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1359189435542933504) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1359189433202511872) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1359189433881989120) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1359189433080877056) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1359189433185734656) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1359189434699878400) | `/test integ-security-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-09 19:17 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-k8s-tests_istio | f75114e67fe9d6f6c775209a4578e835593f73a3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1356977215497048064) | `/test integ-security-k8s-tests_istio`
release-notes_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1359189438894182400) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1359189433240260608) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1359189433261232128) | `/test integ-ipv6-k8s-tests_istio`
integ-operator-controller-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1359189433273815040) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1359189435542933504) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1359189433202511872) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1359189433881989120) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1359189433080877056) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1359189433185734656) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1359189434699878400) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1359189433143791616) | `/test integ-telemetry-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-09 19:18 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1359189438894182400) | `/test release-notes_istio`
integ-distroless-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1359189433240260608) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1359189433261232128) | `/test integ-ipv6-k8s-tests_istio`
integ-operator-controller-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1359189433273815040) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1359189435542933504) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1359189433202511872) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1359189433881989120) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1359189433080877056) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1359189433185734656) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1359189434699878400) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1359189433143791616) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1359189433106042880) | `/test integ-security-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-10 21:26 UTC, istio-testing commented
@luksa: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-03-12 08:00 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-distroless-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1359189433240260608) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1359189433261232128) | `/test integ-ipv6-k8s-tests_istio`
integ-operator-controller-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1359189433273815040) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1359189435542933504) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1359189433202511872) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1359189433881989120) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1359189433080877056) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1359189433185734656) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1359189434699878400) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1359189433143791616) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1359189433106042880) | `/test integ-security-k8s-tests_istio`
release-notes_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1370282747456655360) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-12 08:12 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-distroless-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1359189433240260608) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1359189433261232128) | `/test integ-ipv6-k8s-tests_istio`
integ-helm-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1359189435542933504) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1359189433202511872) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1359189433881989120) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1359189433080877056) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1359189433185734656) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1359189434699878400) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1359189433143791616) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1359189433106042880) | `/test integ-security-k8s-tests_istio`
release-notes_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1370282747456655360) | `/test release-notes_istio`
integ-operator-controller-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1370282741811122176) | `/test integ-operator-controller-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-12 08:13 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-ipv6-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1359189433261232128) | `/test integ-ipv6-k8s-tests_istio`
integ-helm-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1359189435542933504) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1359189433202511872) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1359189433881989120) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1359189433080877056) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1359189433185734656) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1359189434699878400) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1359189433143791616) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1359189433106042880) | `/test integ-security-k8s-tests_istio`
release-notes_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1370282747456655360) | `/test release-notes_istio`
integ-operator-controller-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1370282741811122176) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1370282741764984832) | `/test integ-distroless-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-12 08:13 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-helm-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1359189435542933504) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1359189433202511872) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1359189433881989120) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1359189433080877056) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1359189433185734656) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1359189434699878400) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1359189433143791616) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1359189433106042880) | `/test integ-security-k8s-tests_istio`
release-notes_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1370282747456655360) | `/test release-notes_istio`
integ-operator-controller-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1370282741811122176) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1370282741764984832) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1370282741785956352) | `/test integ-ipv6-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-12 08:14 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-multicluster-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1359189433202511872) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1359189433881989120) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1359189433080877056) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1359189433185734656) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1359189434699878400) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1359189433143791616) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1359189433106042880) | `/test integ-security-k8s-tests_istio`
release-notes_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1370282747456655360) | `/test release-notes_istio`
integ-operator-controller-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1370282741811122176) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1370282741764984832) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1370282741785956352) | `/test integ-ipv6-k8s-tests_istio`
integ-helm-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1370282744101212160) | `/test integ-helm-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-12 08:20 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-multicluster-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1359189433881989120) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1359189433080877056) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1359189433185734656) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1359189434699878400) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1359189433143791616) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1359189433106042880) | `/test integ-security-k8s-tests_istio`
release-notes_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1370282747456655360) | `/test release-notes_istio`
integ-operator-controller-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1370282741811122176) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1370282741764984832) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1370282741785956352) | `/test integ-ipv6-k8s-tests_istio`
integ-helm-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1370282744101212160) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1370282741739819008) | `/test integ-multicluster-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-12 08:44 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1359189433080877056) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1359189433185734656) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1359189434699878400) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1359189433143791616) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1359189433106042880) | `/test integ-security-k8s-tests_istio`
release-notes_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1370282747456655360) | `/test release-notes_istio`
integ-operator-controller-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1370282741811122176) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1370282741764984832) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1370282741785956352) | `/test integ-ipv6-k8s-tests_istio`
integ-helm-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1370282744101212160) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1370282741739819008) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1370282742427684864) | `/test integ-pilot-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-12 09:21 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-mc-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1359189433185734656) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1359189434699878400) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1359189433143791616) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1359189433106042880) | `/test integ-security-k8s-tests_istio`
release-notes_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1370282747456655360) | `/test release-notes_istio`
integ-operator-controller-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1370282741811122176) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1370282741764984832) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1370282741785956352) | `/test integ-ipv6-k8s-tests_istio`
integ-helm-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1370282744101212160) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1370282741739819008) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1370282742427684864) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1370282741639155712) | `/test integ-pilot-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-12 09:23 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-multicluster-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1359189434699878400) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1359189433143791616) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1359189433106042880) | `/test integ-security-k8s-tests_istio`
release-notes_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1370282747456655360) | `/test release-notes_istio`
integ-operator-controller-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1370282741811122176) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1370282741764984832) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1370282741785956352) | `/test integ-ipv6-k8s-tests_istio`
integ-helm-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1370282744101212160) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1370282741739819008) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1370282742427684864) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1370282741639155712) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1370282741714653184) | `/test integ-telemetry-mc-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-12 09:57 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-telemetry-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1359189433143791616) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1359189433106042880) | `/test integ-security-k8s-tests_istio`
release-notes_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1370282747456655360) | `/test release-notes_istio`
integ-operator-controller-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1370282741811122176) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1370282741764984832) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1370282741785956352) | `/test integ-ipv6-k8s-tests_istio`
integ-helm-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1370282744101212160) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1370282741739819008) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1370282742427684864) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1370282741639155712) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1370282741714653184) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1370282743262351360) | `/test integ-security-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-12 09:58 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-k8s-tests_istio | 361c32432f8c8e36d1781553b544dc6bfac0b754 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1359189433106042880) | `/test integ-security-k8s-tests_istio`
release-notes_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1370282747456655360) | `/test release-notes_istio`
integ-operator-controller-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1370282741811122176) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1370282741764984832) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1370282741785956352) | `/test integ-ipv6-k8s-tests_istio`
integ-helm-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1370282744101212160) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1370282741739819008) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1370282742427684864) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1370282741639155712) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1370282741714653184) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1370282743262351360) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1370282741685293056) | `/test integ-telemetry-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-12 09:58 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/release-notes_istio/1370282747456655360) | `/test release-notes_istio`
integ-operator-controller-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1370282741811122176) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1370282741764984832) | `/test integ-distroless-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1370282741785956352) | `/test integ-ipv6-k8s-tests_istio`
integ-helm-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1370282744101212160) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1370282741739819008) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1370282742427684864) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1370282741639155712) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1370282741714653184) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1370282743262351360) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1370282741685293056) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1370282741660127232) | `/test integ-security-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-06 20:39 UTC, therealmitchconnors commented
the latest test failures appear to be a panic in istio-proxy:

```
goroutine 1 [running]:
istio.io/istio/tools/istio-iptables/pkg/dependencies.(*RealDependencies).RunOrFail(0x2882af8, 0x19cd8dd, 0x10, 0xc00072f180, 0x4, 0x4)
	istio.io/istio/tools/istio-iptables/pkg/dependencies/implementation.go:42 +0x9c
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeIptablesRestoreCommand(0xc00081fd78, 0x1, 0x0, 0x0)
	istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:673 +0x3ac
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeCommands(0xc000773d78)
	istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:680 +0x45
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).run(0xc00081fd78)
	istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:558 +0x23e5
istio.io/istio/tools/istio-iptables/pkg/cmd.glob..func1(0x283b9e0, 0x2882af8, 0x0, 0x0)
	istio.io/istio/tools/istio-iptables/pkg/cmd/root.go:60 +0x165
github.com/spf13/cobra.(*Command).execute(0x283b9e0, 0x2882af8, 0x0, 0x0, 0x283b9e0, 0x2882af8)
	github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x283bc60, 0x41af01, 0x0, 0x0)
	github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	istio.io/istio/pilot/cmd/pilot-agent/main.go:446 +0x31
```

2021-04-06 20:43 UTC, mandarjog commented
Why wasn’t this merged?
Does iptables-restore actually support -w option?
I don’t think it does.

2021-04-06 20:46 UTC, mandarjog commented
It may be because iptables-restore does not support a -w option. We just need to put the invocation in a retry / back off loop.

2021-04-06 20:56 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-operator-controller-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1370282741811122176) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1370282741764984832) | `/test integ-distroless-k8s-tests_istio`
integ-helm-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1370282744101212160) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1370282741739819008) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1370282742427684864) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1370282741639155712) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1370282741714653184) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1370282743262351360) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1370282741685293056) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1370282741660127232) | `/test integ-security-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1379534368485150720) | `/test integ-ipv6-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-06 20:57 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-operator-controller-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1370282741811122176) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1370282744101212160) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1370282741739819008) | `/test integ-multicluster-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1370282742427684864) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1370282741639155712) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1370282741714653184) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1370282743262351360) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1370282741685293056) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1370282741660127232) | `/test integ-security-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1379534368485150720) | `/test integ-ipv6-k8s-tests_istio`
integ-distroless-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1379534368497733632) | `/test integ-distroless-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-06 21:03 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-operator-controller-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1370282741811122176) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1370282744101212160) | `/test integ-helm-tests_istio`
integ-pilot-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1370282742427684864) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1370282741639155712) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1370282741714653184) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1370282743262351360) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1370282741685293056) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1370282741660127232) | `/test integ-security-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1379534368485150720) | `/test integ-ipv6-k8s-tests_istio`
integ-distroless-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1379534368497733632) | `/test integ-distroless-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1379534368430624768) | `/test integ-multicluster-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-06 21:06 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-helm-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1370282744101212160) | `/test integ-helm-tests_istio`
integ-pilot-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1370282742427684864) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1370282741639155712) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1370282741714653184) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1370282743262351360) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1370282741685293056) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1370282741660127232) | `/test integ-security-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1379534368485150720) | `/test integ-ipv6-k8s-tests_istio`
integ-distroless-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1379534368497733632) | `/test integ-distroless-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1379534368430624768) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1379534368489345024) | `/test integ-operator-controller-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-06 21:08 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1370282742427684864) | `/test integ-pilot-multicluster-tests_istio`
integ-pilot-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1370282741639155712) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1370282741714653184) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1370282743262351360) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1370282741685293056) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1370282741660127232) | `/test integ-security-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1379534368485150720) | `/test integ-ipv6-k8s-tests_istio`
integ-distroless-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1379534368497733632) | `/test integ-distroless-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1379534368430624768) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1379534368489345024) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1379534370829766656) | `/test integ-helm-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-06 21:42 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1370282741639155712) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-mc-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1370282741714653184) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1370282743262351360) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1370282741685293056) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1370282741660127232) | `/test integ-security-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1379534368485150720) | `/test integ-ipv6-k8s-tests_istio`
integ-distroless-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1379534368497733632) | `/test integ-distroless-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1379534368430624768) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1379534368489345024) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1379534370829766656) | `/test integ-helm-tests_istio`
integ-pilot-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1379534369156239360) | `/test integ-pilot-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-06 22:10 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1370282741639155712) | `/test integ-pilot-k8s-tests_istio`
integ-security-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1370282743262351360) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1370282741685293056) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1370282741660127232) | `/test integ-security-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1379534368485150720) | `/test integ-ipv6-k8s-tests_istio`
integ-distroless-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1379534368497733632) | `/test integ-distroless-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1379534368430624768) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1379534368489345024) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1379534370829766656) | `/test integ-helm-tests_istio`
integ-pilot-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1379534369156239360) | `/test integ-pilot-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1379534368413847552) | `/test integ-telemetry-mc-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-06 22:17 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1370282743262351360) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1370282741685293056) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1370282741660127232) | `/test integ-security-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1379534368485150720) | `/test integ-ipv6-k8s-tests_istio`
integ-distroless-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1379534368497733632) | `/test integ-distroless-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1379534368430624768) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1379534368489345024) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1379534370829766656) | `/test integ-helm-tests_istio`
integ-pilot-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1379534369156239360) | `/test integ-pilot-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1379534368413847552) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-pilot-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1379534368346738689) | `/test integ-pilot-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-06 22:41 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1370282743262351360) | `/test integ-security-multicluster-tests_istio`
integ-security-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1370282741660127232) | `/test integ-security-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1379534368485150720) | `/test integ-ipv6-k8s-tests_istio`
integ-distroless-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1379534368497733632) | `/test integ-distroless-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1379534368430624768) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1379534368489345024) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1379534370829766656) | `/test integ-helm-tests_istio`
integ-pilot-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1379534369156239360) | `/test integ-pilot-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1379534368413847552) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-pilot-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1379534368346738689) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1379534368380293120) | `/test integ-telemetry-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-06 22:42 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1370282743262351360) | `/test integ-security-multicluster-tests_istio`
integ-ipv6-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1379534368485150720) | `/test integ-ipv6-k8s-tests_istio`
integ-distroless-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1379534368497733632) | `/test integ-distroless-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1379534368430624768) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1379534368489345024) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1379534370829766656) | `/test integ-helm-tests_istio`
integ-pilot-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1379534369156239360) | `/test integ-pilot-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1379534368413847552) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-pilot-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1379534368346738689) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1379534368380293120) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1379534368367710208) | `/test integ-security-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-06 22:45 UTC, istio-testing commented
@luksa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-ipv6-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-ipv6-k8s-tests_istio/1379534368485150720) | `/test integ-ipv6-k8s-tests_istio`
integ-distroless-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-distroless-k8s-tests_istio/1379534368497733632) | `/test integ-distroless-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-multicluster-k8s-tests_istio/1379534368430624768) | `/test integ-multicluster-k8s-tests_istio`
integ-operator-controller-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-operator-controller-tests_istio/1379534368489345024) | `/test integ-operator-controller-tests_istio`
integ-helm-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-helm-tests_istio/1379534370829766656) | `/test integ-helm-tests_istio`
integ-pilot-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-multicluster-tests_istio/1379534369156239360) | `/test integ-pilot-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-mc-k8s-tests_istio/1379534368413847552) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-pilot-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-pilot-k8s-tests_istio/1379534368346738689) | `/test integ-pilot-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-telemetry-k8s-tests_istio/1379534368380293120) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-k8s-tests_istio/1379534368367710208) | `/test integ-security-k8s-tests_istio`
integ-security-multicluster-tests_istio | dadca45e13a9854ca664059c1571a54c1b8a4817 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30394/integ-security-multicluster-tests_istio/1379534369990905856) | `/test integ-security-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-22 15:32 UTC, istio-testing commented
@luksa: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-05-07 05:07 UTC, mandarjog commented
We will fix this by retries.

2021-05-07 05:07 UTC, closed without merging

2023-09-13 13:22 UTC, aojea commented
> Does iptables-restore actually support -w option?

@mandarjog it does since `1.6.2`

You have a solid implementation of iptables in kubernetes https://github.com/kubernetes/kubernetes/blob/master/pkg/util/iptables/iptables.go if you want to make this happen