envoy: avoid sending health checks via proxy
istio/istio pull request #31442
Opened 2021-03-12 22:49 UTC by kyessenov

Signed-off-by: Kuat Yessenov <kuat@google.com>

It is unnecessary to route health checks via a static listener on envoy. The agent already checks that the listener has started (warmed and worker accepting), so it does not add any value on top. Moreover, it complicates the set-up making it difficult to run two agents/envoys on one VM.

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

2021-03-12 22:49 UTC, istio-testing commented
@kyessenov: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 552498106204f4d4143f026194d5e7202abf858c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31442/release-notes_istio/1370507217219883008) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-12 22:52 UTC, howardjohn commented
We intentionally switch to this to give more coverage to ensure that envoy is *actually* listening and serving traffic. There are a lot of ways that envoy may not be serving traffic but the probe succeeds otherwise, such as envoy deadlock, envoy crashing and we don't notice (this shouldn't happen though, but I suppose it could), bugs in envoy, etc. The check that the listener is ready is just asking envoy one time at startup "are you ready?" - sending traffic actually proves this.

2021-03-12 22:53 UTC, howardjohn commented
Its certainly not the most useful check in the world though. But its not clear to me how this actually helps the problem of multiple envoys, given we have many other ports that also conflict

2021-03-12 22:54 UTC, istio-testing commented
@kyessenov: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 552498106204f4d4143f026194d5e7202abf858c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31442/release-notes_istio/1370507217219883008) | `/test release-notes_istio`
unit-tests_istio | 552498106204f4d4143f026194d5e7202abf858c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31442/unit-tests_istio/1370507211356246016) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-12 22:58 UTC, kyessenov commented
Can you provide me at least one case when stats would report that xDS is accepted, listeners have warmed, workers have started, and static listener is ready, but it dead locked? Envoy has to be running for agent to ping its stats.
If anything like that happens, it is a much more serious issue that we should not be hiding via accidentally successful health checks.

2021-03-12 22:58 UTC, howardjohn commented
> Envoy has to be running for agent to ping its stats.

We only ping stats at startup. Once we are ready once we never do it again

2021-03-12 22:59 UTC, istio-testing commented
@kyessenov: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
unit-tests_istio | 552498106204f4d4143f026194d5e7202abf858c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31442/unit-tests_istio/1370507211356246016) | `/test unit-tests_istio`
release-notes_istio | 696bc367a7820b1f798a17ca8a37dd2c9c80d8b5 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31442/release-notes_istio/1370509779469864960) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-12 23:00 UTC, howardjohn commented
https://github.com/istio/istio/pull/21488 was the original PR for context.

Also 15021 is part of the API at this point - its used in many public docs for load balancer health check configurations.

2021-03-12 23:01 UTC, kyessenov commented
@howardjohn If envoy crashes, you're going to get child process termination signal. Health checks in the pod is not a good mediation solution as Envoy will crash again most likely (and it if it does not, a security attack is possible). Hard coding ports 15021 and 15020 in the bootstrap is absolutely a problem.

cc @mandarjog

2021-03-12 23:02 UTC, istio-testing commented
@kyessenov: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 696bc367a7820b1f798a17ca8a37dd2c9c80d8b5 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31442/release-notes_istio/1370509779469864960) | `/test release-notes_istio`
unit-tests_istio | 696bc367a7820b1f798a17ca8a37dd2c9c80d8b5 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31442/unit-tests_istio/1370509763644755968) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-12 23:03 UTC, howardjohn commented
I believe the original issue was worker thread got stuck in a deadlock, our health check succeeded. Its generally best practice to hit as much of the real request path in a readiness probe as possible.

2021-03-12 23:04 UTC, howardjohn requested changes
This will at the very least break external health checks and port changes like this are on the "Will never be approved again" list from TOC.

2021-03-12 23:08 UTC, howardjohn commented
To clarify: probably no Istio tests will break from this, but a bunch of docs and user configs like https://cloud.google.com/solutions/exposing-service-mesh-apps-through-gke-ingress#deploying_gke_ingress will, where they have external health checks

2021-03-12 23:09 UTC, kyessenov commented
@howardjohn The ingress external port can remain 15021, I can re-route it back to 15020.

2021-03-12 23:12 UTC, closed without merging

2021-03-12 23:20 UTC, mandarjog commented
@kyessenov regardless of the correctness of the original PR, We cannot change ports that can result in breaking users.
If re-route like you mentioned is possible, then its ok. Can you elaborate on re-routing ?

2021-03-12 23:22 UTC, kyessenov commented
I think John's concern is the external service port. This is just standard k8s service-port mapping. We can keep that the same and change pod port.

2021-03-12 23:24 UTC, howardjohn commented
I am not sure that is sufficient. While it probably works in some cases, I am not sure it does for all. For example, folks may have firewall rules allowing port 15021 *and use systems the healthcheck pods directly* so they don't care about the port mapping.

This may sound like FUD but we did this exact same thing - twice - and caused a lot of pain.

2021-03-12 23:28 UTC, kyessenov commented
@howardjohn GCP instructions are clearly about external LBs trying to health check gateways. I think we're safe there on other platforms. I don't think any external LB checks for container health.

2021-03-12 23:29 UTC, kyessenov commented
This is also a good case why named ports would be better. But that ship has passed.

2021-03-12 23:29 UTC, howardjohn commented
I believe NEGs are checking container health directly.

2021-03-12 23:32 UTC, kyessenov commented
@howardjohn Let's not divert the discussion. I can easily make it 15021 instead of 15020 on the ingress gateways. The real question is why we proxy health checks to agent when agent calls proxy back.

2021-03-12 23:34 UTC, howardjohn commented
>  I can easily make it 15021 instead of 15020 on the ingress gateways. 

I don't think this is true without more proof. Do not take this so lightly - we had this exact discussion *twice* in the past where we thought the exact same change was safe, and now people complain about it to us every month or so. Ask @duderino , he reminds me and costin to not change ports about once a week now...

2021-03-12 23:35 UTC, howardjohn commented
Even if we didn't - the envoy admin interface and real worker thread are pretty independent and one often deadlocks when the other doesn't

2021-03-12 23:36 UTC, mandarjog commented
The original thought was to ensure that the (or a) worker is responsive.
@kyessenov If we can do the health check in better ways like using watchdog/ mega  misses etc that is welcome. Also we could expand the search space to include what else we can do with Envoy, or considering the higher level problem of what the application could be doing.

All these solutions were controlplane only so far, they dont have to be.

2021-03-12 23:38 UTC, kyessenov commented
Anything that can be done with agent, can be done better with envoy since you have access to internals. There's a lot of speculation about deadlocks and workers, but no links to actual bugs. Envoy is not a magic black box, we can make it report health that satisfies the needs.

2021-03-12 23:39 UTC, mandarjog commented
I agree, So we can move the discussion there perhaps and find a good solution.
The only sticking point is changing ports, and breaking users.  I am sure there are better health check solutions.

2021-03-12 23:40 UTC, kyessenov commented
BTW I agree entirely with @duderino that changing ports is not a good idea, which is why I'm proposing to revert the hacky PR that got merged. It's doubly bad because all the ports are hard-coded, so there is no mediation with config.

2021-03-12 23:43 UTC, howardjohn commented
It doesn't really matter how bad the PR was - it could have been the worst PR ever, we are stuck with the change and cannot break things again.

maybe this would be more productive if the context of why we need to change anything was shared?

2021-03-12 23:50 UTC, mandarjog commented
Similar to [there requirements](https://docs.google.com/document/d/1xHy2jQ8oiwMponMVY2zJr2eUAmHW_Hi9JK42a7cg5Pc/edit#bookmark=id.uzcgjyodob15)

2021-03-12 23:51 UTC, kyessenov commented
cc @yskopets . Yes, this is one obvious issue preventing two istio proxies on one VM.

2021-03-12 23:52 UTC, kyessenov commented
@howardjohn I think a better way to look at it - what can be done better next time? Maybe we need tougher process to prevent hard-to-undo changes from making it to Istio within days of release and no way to opt out of them.

2021-03-13 00:04 UTC, howardjohn commented
@kyessenov I don't understand your problems with the PR. It was open for 2 weeks, approved by 2 working groups, and made 3 months before the release it was included in (1.6). I don't think criticizing decisions from a year ago is productive, so this will probably be my last comment here...

2021-03-13 00:15 UTC, kyessenov commented
Oh, sorry, I misread the date to be this year, not last year. Ok, then it's been awhile since it got merged.

2021-03-13 00:20 UTC, mandarjog commented
Work still remains
1. How do we make ports configurable, or otherwise have them share the same VM. 
2. Is there a better way to do health checks.