Fix read and write conflicts
istio/istio pull request #31923
Opened 2021-04-06 03:10 UTC by wzshiming

Signed-off-by: Shiming Zhang <wzshiming@foxmail.com>

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[x] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any changes that may affect Istio users.

2021-04-06 03:35 UTC, istio-testing commented
@wzshiming: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | 1d6b6d1f6b119912898172ba5caaccc46b7fc10c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/integ-pilot-k8s-tests_istio/1379270366412673024) | `/test integ-pilot-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-06 04:10 UTC, istio-testing commented
@wzshiming: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | 1d6b6d1f6b119912898172ba5caaccc46b7fc10c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/integ-pilot-k8s-tests_istio/1379270366412673024) | `/test integ-pilot-k8s-tests_istio`
integ-security-k8s-tests_istio | 1d6b6d1f6b119912898172ba5caaccc46b7fc10c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/integ-security-k8s-tests_istio/1379270366442033152) | `/test integ-security-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-06 15:10 UTC, howardjohn requested changes
Thanks for the PR! Please add a description of all PRs you submit. Without this, its hard to understand the motivation for the change and what its intended to do. Please let me know when you have added this and I will look at the change. Thanks!

2021-04-07 06:38 UTC, wzshiming commented
`its.Expires` and `its.Token` it is now possible to be read and written concurrently, there is a chance of panic.
This PR optimize lock logic to ensure thread safety

2021-04-07 06:38 UTC, wzshiming commented
/retest

2021-04-07 07:01 UTC, istio-testing commented
@wzshiming: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-k8s-tests_istio | 1d6b6d1f6b119912898172ba5caaccc46b7fc10c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/integ-security-k8s-tests_istio/1379270366442033152) | `/test integ-security-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 1d6b6d1f6b119912898172ba5caaccc46b7fc10c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/integ-pilot-k8s-tests_istio/1379685019592691712) | `/test integ-pilot-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-07 07:02 UTC, wzshiming commented
/retest

2021-04-07 07:25 UTC, istio-testing commented
@wzshiming: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | 1d6b6d1f6b119912898172ba5caaccc46b7fc10c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/integ-pilot-k8s-tests_istio/1379691151329595392) | `/test integ-pilot-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-07 07:26 UTC, wzshiming commented
/retest

2021-04-07 07:50 UTC, istio-testing commented
@wzshiming: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | 1d6b6d1f6b119912898172ba5caaccc46b7fc10c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/integ-pilot-k8s-tests_istio/1379697183846043648) | `/test integ-pilot-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-07 14:43 UTC, howardjohn commented
Is it theoretical or has it crashed? can you show a log of a crash?

2021-04-07 16:27 UTC, howardjohn requested changes
Can you add tests? I agree there is a race today but don't feel comfortable with the changes without tests

2021-04-07 16:27 UTC, howardjohn commented on pkg/kube/rpc_creds.go
> +		"authorization": "Bearer " + token,
doesn't this mean if its not going to expire token will be `""`?

2021-04-08 09:37 UTC, istio-testing commented
@wzshiming: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | 1d6b6d1f6b119912898172ba5caaccc46b7fc10c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/integ-pilot-k8s-tests_istio/1379697183846043648) | `/test integ-pilot-k8s-tests_istio`
lint_istio | ddf483f5d7c603c275546567b5159dee66df7a7a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/lint_istio/1380092118952841216) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-08 09:38 UTC, istio-testing commented
@wzshiming: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | 1d6b6d1f6b119912898172ba5caaccc46b7fc10c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/integ-pilot-k8s-tests_istio/1379697183846043648) | `/test integ-pilot-k8s-tests_istio`
lint_istio | e917cfbbf74f970a1bcd26e4d129dbbc2b1445cc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/lint_istio/1380092390324310016) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-08 09:40 UTC, istio-testing commented
@wzshiming: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | 1d6b6d1f6b119912898172ba5caaccc46b7fc10c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/integ-pilot-k8s-tests_istio/1379697183846043648) | `/test integ-pilot-k8s-tests_istio`
lint_istio | 745d0cae85eb89ac5b33a78bda791e8b6959f429 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/lint_istio/1380093140144230400) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-08 09:44 UTC, istio-testing commented
@wzshiming: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | 1d6b6d1f6b119912898172ba5caaccc46b7fc10c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/integ-pilot-k8s-tests_istio/1379697183846043648) | `/test integ-pilot-k8s-tests_istio`
lint_istio | 588c80467f454f35d010371a2a4e3da9844f2087 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/lint_istio/1380093949158363136) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-08 09:45 UTC, istio-testing commented
@wzshiming: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | 1d6b6d1f6b119912898172ba5caaccc46b7fc10c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/integ-pilot-k8s-tests_istio/1379697183846043648) | `/test integ-pilot-k8s-tests_istio`
lint_istio | 588c80467f454f35d010371a2a4e3da9844f2087 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/lint_istio/1380093949158363136) | `/test lint_istio`
gencheck_istio | 588c80467f454f35d010371a2a4e3da9844f2087 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/gencheck_istio/1380093950819307520) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-08 09:47 UTC, istio-testing commented
@wzshiming: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | 1d6b6d1f6b119912898172ba5caaccc46b7fc10c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/integ-pilot-k8s-tests_istio/1379697183846043648) | `/test integ-pilot-k8s-tests_istio`
lint_istio | 588c80467f454f35d010371a2a4e3da9844f2087 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/lint_istio/1380093949158363136) | `/test lint_istio`
gencheck_istio | cda366050399df8c6c7dbe49aee9fa9424e8c140 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/gencheck_istio/1380094616258220032) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-08 09:48 UTC, istio-testing commented
@wzshiming: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | 1d6b6d1f6b119912898172ba5caaccc46b7fc10c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/integ-pilot-k8s-tests_istio/1379697183846043648) | `/test integ-pilot-k8s-tests_istio`
gencheck_istio | cda366050399df8c6c7dbe49aee9fa9424e8c140 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/gencheck_istio/1380094616258220032) | `/test gencheck_istio`
lint_istio | cda366050399df8c6c7dbe49aee9fa9424e8c140 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/lint_istio/1380094615415164928) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-08 09:51 UTC, istio-testing commented
@wzshiming: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | 1d6b6d1f6b119912898172ba5caaccc46b7fc10c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/integ-pilot-k8s-tests_istio/1379697183846043648) | `/test integ-pilot-k8s-tests_istio`
gencheck_istio | cda366050399df8c6c7dbe49aee9fa9424e8c140 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/gencheck_istio/1380094616258220032) | `/test gencheck_istio`
lint_istio | cda366050399df8c6c7dbe49aee9fa9424e8c140 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/lint_istio/1380094615415164928) | `/test lint_istio`
unit-tests_istio | cda366050399df8c6c7dbe49aee9fa9424e8c140 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/unit-tests_istio/1380094600714129408) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-08 09:57 UTC, istio-testing commented
@wzshiming: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | 1d6b6d1f6b119912898172ba5caaccc46b7fc10c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/integ-pilot-k8s-tests_istio/1379697183846043648) | `/test integ-pilot-k8s-tests_istio`
lint_istio | cda366050399df8c6c7dbe49aee9fa9424e8c140 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/lint_istio/1380094615415164928) | `/test lint_istio`
unit-tests_istio | cda366050399df8c6c7dbe49aee9fa9424e8c140 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/unit-tests_istio/1380094600714129408) | `/test unit-tests_istio`
gencheck_istio | 26a1f4bd6bacf090cebc2d246da5085c6e57e126 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/gencheck_istio/1380096999314952192) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-08 09:58 UTC, istio-testing commented
@wzshiming: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | 1d6b6d1f6b119912898172ba5caaccc46b7fc10c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/integ-pilot-k8s-tests_istio/1379697183846043648) | `/test integ-pilot-k8s-tests_istio`
unit-tests_istio | cda366050399df8c6c7dbe49aee9fa9424e8c140 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/unit-tests_istio/1380094600714129408) | `/test unit-tests_istio`
gencheck_istio | 26a1f4bd6bacf090cebc2d246da5085c6e57e126 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/gencheck_istio/1380096999314952192) | `/test gencheck_istio`
lint_istio | 26a1f4bd6bacf090cebc2d246da5085c6e57e126 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/lint_istio/1380096998488674304) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-08 10:05 UTC, istio-testing commented
@wzshiming: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | 1d6b6d1f6b119912898172ba5caaccc46b7fc10c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/integ-pilot-k8s-tests_istio/1379697183846043648) | `/test integ-pilot-k8s-tests_istio`
lint_istio | 26a1f4bd6bacf090cebc2d246da5085c6e57e126 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/lint_istio/1380096998488674304) | `/test lint_istio`
gencheck_istio | 2a4fe14ecc4bb5615d41573618b1cf6af1679f3f | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/gencheck_istio/1380098851167277056) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-08 10:05 UTC, istio-testing commented
@wzshiming: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | 1d6b6d1f6b119912898172ba5caaccc46b7fc10c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/integ-pilot-k8s-tests_istio/1379697183846043648) | `/test integ-pilot-k8s-tests_istio`
gencheck_istio | 2a4fe14ecc4bb5615d41573618b1cf6af1679f3f | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/gencheck_istio/1380098851167277056) | `/test gencheck_istio`
lint_istio | 2a4fe14ecc4bb5615d41573618b1cf6af1679f3f | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/lint_istio/1380098849510526976) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-08 10:12 UTC, istio-testing commented
@wzshiming: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | 1d6b6d1f6b119912898172ba5caaccc46b7fc10c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/integ-pilot-k8s-tests_istio/1379697183846043648) | `/test integ-pilot-k8s-tests_istio`
integ-security-multicluster-tests_istio | 5a1ceed8d68a7e47a0bd4b30434567b76f2f1cd2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/integ-security-multicluster-tests_istio/1380100354200309760) | `/test integ-security-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-08 10:24 UTC, istio-testing commented
@wzshiming: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-k8s-tests_istio | 1d6b6d1f6b119912898172ba5caaccc46b7fc10c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/integ-pilot-k8s-tests_istio/1379697183846043648) | `/test integ-pilot-k8s-tests_istio`
integ-security-multicluster-tests_istio | 5a1ceed8d68a7e47a0bd4b30434567b76f2f1cd2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/integ-security-multicluster-tests_istio/1380100354200309760) | `/test integ-security-multicluster-tests_istio`
integ-ipv6-k8s-tests_istio | 5a1ceed8d68a7e47a0bd4b30434567b76f2f1cd2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/integ-ipv6-k8s-tests_istio/1380100349603352576) | `/test integ-ipv6-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-08 10:46 UTC, wzshiming commented
/retest

2021-04-08 14:55 UTC, howardjohn commented on pkg/kube/rpc_creds_test.go
> +	"istio.io/istio/galley/pkg/testing/mock"
Please don't use this package, it is deprecated. Use `kube.NewFakeClient()`. Thanks!

2021-04-08 14:55 UTC, howardjohn commented on pkg/kube/rpc_creds_test.go
> +	time.Sleep(time.Second)
time.Sleep is not appropriate in tests, see https://github.com/istio/istio/wiki/Test-Flakes

2021-04-09 05:43 UTC, wzshiming commented on pkg/kube/rpc_creds_test.go
> +	clientset.PrependReactor("create", "serviceaccounts",
Expected here is "serviceaccounts/token", but `fake.NewSimpleClientset` does not support. kubernetes/kubernetes#100938

2021-04-09 14:20 UTC, howardjohn approved these changes
Thanks!

2021-04-09 16:08 UTC, istio-testing commented
@wzshiming: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-multicluster-tests_istio | 45e08226f109381e23b193526399f40229e57223 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31923/integ-security-multicluster-tests_istio/1380526183048810496) | `/test integ-security-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-09 16:53 UTC, wzshiming commented
/retest

2021-04-09 19:31 UTC, merged