Add support for contains operator for authz header matcher
istio/istio pull request #32180
Opened 2021-04-14 22:51 UTC by dmorina

closes #32173

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

2021-04-14 22:51 UTC, istio-testing commented
Hi @dmorina. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-04-14 22:55 UTC, dmorina commented
@googlebot I signed it!

2021-04-17 05:42 UTC, kebe7jun reviewed
/ok-to-test

2021-04-17 05:42 UTC, kebe7jun commented on pilot/pkg/security/authz/matcher/header.go
> +				ContainsMatch: v[1 : len(v)-1],
```suggestion
				ContainsMatch: v[1:len(v)-1],
```

2021-04-17 05:46 UTC, istio-testing commented
@dmorina: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | d47d195ee885991e8832d49d1b64314600796e89 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32180/release-notes_istio/1383294894193250304) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-17 05:51 UTC, istio-testing commented
@dmorina: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | e62977719f49add8d9659639d68335e641784f3d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32180/release-notes_istio/1383296999683526656) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-17 05:53 UTC, istio-testing commented
@dmorina: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | e62977719f49add8d9659639d68335e641784f3d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32180/release-notes_istio/1383296999683526656) | `/test release-notes_istio`
gencheck_istio | e62977719f49add8d9659639d68335e641784f3d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32180/gencheck_istio/1383296998832082944) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-17 05:54 UTC, istio-testing commented
@dmorina: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | e62977719f49add8d9659639d68335e641784f3d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32180/release-notes_istio/1383296999683526656) | `/test release-notes_istio`
gencheck_istio | e62977719f49add8d9659639d68335e641784f3d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32180/gencheck_istio/1383296998832082944) | `/test gencheck_istio`
lint_istio | e62977719f49add8d9659639d68335e641784f3d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32180/lint_istio/1383296997993222144) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-17 05:56 UTC, kebe7jun commented on pilot/pkg/security/authz/matcher/header.go
> +				ContainsMatch: v[1 : len(v)-1],
oh, It looks like I was wrong.

2021-04-17 06:21 UTC, istio-testing commented
@dmorina: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | e62977719f49add8d9659639d68335e641784f3d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32180/release-notes_istio/1383296999683526656) | `/test release-notes_istio`
gencheck_istio | e62977719f49add8d9659639d68335e641784f3d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32180/gencheck_istio/1383296998832082944) | `/test gencheck_istio`
lint_istio | e62977719f49add8d9659639d68335e641784f3d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32180/lint_istio/1383296997993222144) | `/test lint_istio`
integ-security-multicluster-tests_istio | e62977719f49add8d9659639d68335e641784f3d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32180/integ-security-multicluster-tests_istio/1383296995472445440) | `/test integ-security-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-17 06:21 UTC, istio-testing commented
@dmorina: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | e62977719f49add8d9659639d68335e641784f3d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32180/release-notes_istio/1383296999683526656) | `/test release-notes_istio`
gencheck_istio | e62977719f49add8d9659639d68335e641784f3d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32180/gencheck_istio/1383296998832082944) | `/test gencheck_istio`
lint_istio | e62977719f49add8d9659639d68335e641784f3d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32180/lint_istio/1383296997993222144) | `/test lint_istio`
integ-security-multicluster-tests_istio | e62977719f49add8d9659639d68335e641784f3d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32180/integ-security-multicluster-tests_istio/1383296995472445440) | `/test integ-security-multicluster-tests_istio`
integ-pilot-multicluster-tests_istio | e62977719f49add8d9659639d68335e641784f3d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32180/integ-pilot-multicluster-tests_istio/1383296994641973248) | `/test integ-pilot-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-18 03:56 UTC, istio-testing commented
@dmorina: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | e62977719f49add8d9659639d68335e641784f3d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32180/gencheck_istio/1383296998832082944) | `/test gencheck_istio`
lint_istio | e62977719f49add8d9659639d68335e641784f3d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32180/lint_istio/1383296997993222144) | `/test lint_istio`
integ-security-multicluster-tests_istio | e62977719f49add8d9659639d68335e641784f3d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32180/integ-security-multicluster-tests_istio/1383296995472445440) | `/test integ-security-multicluster-tests_istio`
integ-pilot-multicluster-tests_istio | e62977719f49add8d9659639d68335e641784f3d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32180/integ-pilot-multicluster-tests_istio/1383296994641973248) | `/test integ-pilot-multicluster-tests_istio`
release-notes_istio | e43877284073e8873843b0045fe563a646ac9401 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32180/release-notes_istio/1383629671710593024) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-18 04:00 UTC, istio-testing commented
@dmorina: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-multicluster-tests_istio | e62977719f49add8d9659639d68335e641784f3d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32180/integ-security-multicluster-tests_istio/1383296995472445440) | `/test integ-security-multicluster-tests_istio`
integ-pilot-multicluster-tests_istio | e62977719f49add8d9659639d68335e641784f3d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32180/integ-pilot-multicluster-tests_istio/1383296994641973248) | `/test integ-pilot-multicluster-tests_istio`
release-notes_istio | e43877284073e8873843b0045fe563a646ac9401 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32180/release-notes_istio/1383629671710593024) | `/test release-notes_istio`
unit-tests_istio | e43877284073e8873843b0045fe563a646ac9401 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32180/unit-tests_istio/1383629665825984512) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-18 06:16 UTC, dmorina commented on pilot/pkg/security/authz/matcher/header.go
> +				ContainsMatch: v[1 : len(v)-1],
no worries, reverted it

2021-04-20 22:17 UTC, yangminzhu requested changes
Thanks for the change! I think this is a reasonable improvement but we will need to hold the PR a little bit because it involves API changes even the change itself is rather small.

Please note the authorization API is currently in beta stage and we have high requirements for any API changes in a beta feature.

Could you bring this up in the next security WG meeting ([schedule](https://docs.google.com/document/d/12Xz8fCuql2tPL-cpdLXGGE44kYT4o9NB6mljSiS_01U/edit#)) and discuss the API change there? Once the API change is approved, we can go ahead with the implementation.

cc @lizan @liminw @myidpt

2021-04-20 22:36 UTC, dmorina commented
Sounds good! I will join the 4/28 meeting to discuss this change. Thanks!

2021-05-04 17:27 UTC, dmorina commented
@yangminzhu we discussed this in the last WG meeting 4/28 and the change was approved, let me know how you want to proceed from here. Thanks!

2021-06-05 05:04 UTC, closed without merging