Fix returnStatusToPool
istio/istio pull request #32274
Opened 2021-04-19 10:33 UTC by wzshiming

Signed-off-by: Shiming Zhang <wzshiming@foxmail.com>

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

2021-04-19 10:36 UTC, istio-testing commented
@wzshiming: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 4f9bb1a3cfc8f9d79fdd7bdcb44a8b4bcf70043b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32274/release-notes_istio/1384092815234961408) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-19 10:38 UTC, wzshiming commented
/retest

2021-04-19 10:39 UTC, istio-testing commented
@wzshiming: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 4f9bb1a3cfc8f9d79fdd7bdcb44a8b4bcf70043b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32274/release-notes_istio/1384094019226701824) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-19 10:44 UTC, kebe7jun commented
/test release-notes_istio

2021-04-19 15:16 UTC, howardjohn requested changes
Can you please put a description on the PR?

2021-04-20 01:56 UTC, wzshiming commented
> Can you please put a description on the PR?

Done

2021-04-20 14:30 UTC, howardjohn commented
What user facing bugs does this fix? I am very hesitant to make any changes to galley/ since we are planning to remove it ASAP

2021-05-21 08:09 UTC, closed without merging