bootstrap: cleanup status port and config dir
istio/istio pull request #32786
Opened 2021-05-11 16:17 UTC by kyessenov

Signed-off-by: Kuat Yessenov <kuat@google.com>

- change 15021 to a UDS port
- use ConfigPath instead of hardcoded paths in bootstrap template

Relevant link https://docs.google.com/document/d/1xHy2jQ8oiwMponMVY2zJr2eUAmHW_Hi9JK42a7cg5Pc/edit#bookmark=id.uzcgjyodob15

2021-05-11 16:42 UTC, howardjohn requested changes
This will break external load balancer health checks, which rely on hitting this from outside of the pod

2021-05-11 16:51 UTC, istio-testing commented
@kyessenov: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-ipv6-k8s-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-ipv6-k8s-tests_istio/1392151834113609728) | `/test integ-ipv6-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-multicluster-k8s-tests_istio/1392151834038112256) | `/test integ-multicluster-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-distroless-k8s-tests_istio/1392151834084249600) | `/test integ-distroless-k8s-tests_istio`
integ-helm-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-helm-tests_istio/1392151836982513664) | `/test integ-helm-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-05-11 17:03 UTC, istio-testing commented
@kyessenov: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-ipv6-k8s-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-ipv6-k8s-tests_istio/1392151834113609728) | `/test integ-ipv6-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-multicluster-k8s-tests_istio/1392151834038112256) | `/test integ-multicluster-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-distroless-k8s-tests_istio/1392151834084249600) | `/test integ-distroless-k8s-tests_istio`
integ-helm-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-helm-tests_istio/1392151836982513664) | `/test integ-helm-tests_istio`
integ-operator-controller-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-operator-controller-tests_istio/1392151834486902784) | `/test integ-operator-controller-tests_istio`
integ-pilot-multicluster-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-pilot-multicluster-tests_istio/1392151835308986368) | `/test integ-pilot-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-05-11 17:12 UTC, istio-testing commented
@kyessenov: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-ipv6-k8s-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-ipv6-k8s-tests_istio/1392151834113609728) | `/test integ-ipv6-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-multicluster-k8s-tests_istio/1392151834038112256) | `/test integ-multicluster-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-distroless-k8s-tests_istio/1392151834084249600) | `/test integ-distroless-k8s-tests_istio`
integ-helm-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-helm-tests_istio/1392151836982513664) | `/test integ-helm-tests_istio`
integ-operator-controller-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-operator-controller-tests_istio/1392151834486902784) | `/test integ-operator-controller-tests_istio`
integ-pilot-multicluster-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-pilot-multicluster-tests_istio/1392151835308986368) | `/test integ-pilot-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-telemetry-mc-k8s-tests_istio/1392151834008752128) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-pilot-k8s-tests_istio/1392151833740316672) | `/test integ-pilot-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-05-11 17:19 UTC, kyessenov commented
@howardjohn Let's discuss this offline. I'll ping you later.

2021-05-11 17:21 UTC, istio-testing commented
@kyessenov: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-ipv6-k8s-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-ipv6-k8s-tests_istio/1392151834113609728) | `/test integ-ipv6-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-multicluster-k8s-tests_istio/1392151834038112256) | `/test integ-multicluster-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-distroless-k8s-tests_istio/1392151834084249600) | `/test integ-distroless-k8s-tests_istio`
integ-helm-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-helm-tests_istio/1392151836982513664) | `/test integ-helm-tests_istio`
integ-operator-controller-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-operator-controller-tests_istio/1392151834486902784) | `/test integ-operator-controller-tests_istio`
integ-pilot-multicluster-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-pilot-multicluster-tests_istio/1392151835308986368) | `/test integ-pilot-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-telemetry-mc-k8s-tests_istio/1392151834008752128) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-pilot-k8s-tests_istio/1392151833740316672) | `/test integ-pilot-k8s-tests_istio`
integ-security-multicluster-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-security-multicluster-tests_istio/1392151836139458560) | `/test integ-security-multicluster-tests_istio`
integ-telemetry-k8s-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-telemetry-k8s-tests_istio/1392151833966809088) | `/test integ-telemetry-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-05-11 19:40 UTC, istio-testing commented
@kyessenov: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-helm-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-helm-tests_istio/1392151836982513664) | `/test integ-helm-tests_istio`
integ-pilot-multicluster-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-pilot-multicluster-tests_istio/1392151835308986368) | `/test integ-pilot-multicluster-tests_istio`
integ-security-multicluster-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-security-multicluster-tests_istio/1392151836139458560) | `/test integ-security-multicluster-tests_istio`
release-test_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/release-test_istio/1392202064137818112) | `/test release-test_istio`
unit-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/unit-tests_istio/1392202064116846592) | `/test unit-tests_istio`
integ-operator-controller-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-operator-controller-tests_istio/1392202064959901696) | `/test integ-operator-controller-tests_istio`
integ-security-k8s-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-security-k8s-tests_istio/1392202064196538368) | `/test integ-security-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-ipv6-k8s-tests_istio/1392202064284618752) | `/test integ-ipv6-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-pilot-k8s-tests_istio/1392202064158789632) | `/test integ-pilot-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-05-11 19:41 UTC, istio-testing commented
@kyessenov: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-helm-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-helm-tests_istio/1392151836982513664) | `/test integ-helm-tests_istio`
integ-security-multicluster-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-security-multicluster-tests_istio/1392151836139458560) | `/test integ-security-multicluster-tests_istio`
release-test_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/release-test_istio/1392202064137818112) | `/test release-test_istio`
unit-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/unit-tests_istio/1392202064116846592) | `/test unit-tests_istio`
integ-operator-controller-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-operator-controller-tests_istio/1392202064959901696) | `/test integ-operator-controller-tests_istio`
integ-security-k8s-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-security-k8s-tests_istio/1392202064196538368) | `/test integ-security-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-ipv6-k8s-tests_istio/1392202064284618752) | `/test integ-ipv6-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-pilot-k8s-tests_istio/1392202064158789632) | `/test integ-pilot-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-distroless-k8s-tests_istio/1392202064272035840) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-telemetry-k8s-tests_istio/1392202064225898496) | `/test integ-telemetry-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-pilot-multicluster-tests_istio/1392202065802956800) | `/test integ-pilot-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-05-11 19:41 UTC, istio-testing commented
@kyessenov: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-multicluster-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-security-multicluster-tests_istio/1392151836139458560) | `/test integ-security-multicluster-tests_istio`
release-test_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/release-test_istio/1392202064137818112) | `/test release-test_istio`
unit-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/unit-tests_istio/1392202064116846592) | `/test unit-tests_istio`
integ-operator-controller-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-operator-controller-tests_istio/1392202064959901696) | `/test integ-operator-controller-tests_istio`
integ-security-k8s-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-security-k8s-tests_istio/1392202064196538368) | `/test integ-security-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-ipv6-k8s-tests_istio/1392202064284618752) | `/test integ-ipv6-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-pilot-k8s-tests_istio/1392202064158789632) | `/test integ-pilot-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-distroless-k8s-tests_istio/1392202064272035840) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-telemetry-k8s-tests_istio/1392202064225898496) | `/test integ-telemetry-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-pilot-multicluster-tests_istio/1392202065802956800) | `/test integ-pilot-multicluster-tests_istio`
lint_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/lint_istio/1392202069154205696) | `/test lint_istio`
integ-helm-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-helm-tests_istio/1392202067476484096) | `/test integ-helm-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-05-11 19:42 UTC, istio-testing commented
@kyessenov: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-security-multicluster-tests_istio | 1d7197fd7a484acacdc6a16e07fc0ab951547090 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-security-multicluster-tests_istio/1392151836139458560) | `/test integ-security-multicluster-tests_istio`
release-test_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/release-test_istio/1392202064137818112) | `/test release-test_istio`
unit-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/unit-tests_istio/1392202064116846592) | `/test unit-tests_istio`
integ-operator-controller-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-operator-controller-tests_istio/1392202064959901696) | `/test integ-operator-controller-tests_istio`
integ-security-k8s-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-security-k8s-tests_istio/1392202064196538368) | `/test integ-security-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-ipv6-k8s-tests_istio/1392202064284618752) | `/test integ-ipv6-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-pilot-k8s-tests_istio/1392202064158789632) | `/test integ-pilot-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-distroless-k8s-tests_istio/1392202064272035840) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-telemetry-k8s-tests_istio/1392202064225898496) | `/test integ-telemetry-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-pilot-multicluster-tests_istio/1392202065802956800) | `/test integ-pilot-multicluster-tests_istio`
lint_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/lint_istio/1392202069154205696) | `/test lint_istio`
integ-helm-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-helm-tests_istio/1392202067476484096) | `/test integ-helm-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-telemetry-mc-k8s-tests_istio/1392202064230092800) | `/test integ-telemetry-mc-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-05-11 19:45 UTC, kyessenov commented on manifests/profiles/demo.yaml
> +              targetPort: 15020
Main docs for GLBC use different target port https://cloud.google.com/kubernetes-engine/docs/how-to/load-balance-ingress. Are you sure about lack of support?

2021-05-11 19:52 UTC, istio-testing commented
@kyessenov: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-test_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/release-test_istio/1392202064137818112) | `/test release-test_istio`
unit-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/unit-tests_istio/1392202064116846592) | `/test unit-tests_istio`
integ-operator-controller-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-operator-controller-tests_istio/1392202064959901696) | `/test integ-operator-controller-tests_istio`
integ-security-k8s-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-security-k8s-tests_istio/1392202064196538368) | `/test integ-security-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-ipv6-k8s-tests_istio/1392202064284618752) | `/test integ-ipv6-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-pilot-k8s-tests_istio/1392202064158789632) | `/test integ-pilot-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-distroless-k8s-tests_istio/1392202064272035840) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-telemetry-k8s-tests_istio/1392202064225898496) | `/test integ-telemetry-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-pilot-multicluster-tests_istio/1392202065802956800) | `/test integ-pilot-multicluster-tests_istio`
integ-helm-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-helm-tests_istio/1392202067476484096) | `/test integ-helm-tests_istio`
integ-telemetry-mc-k8s-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-telemetry-mc-k8s-tests_istio/1392202064230092800) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-security-multicluster-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-security-multicluster-tests_istio/1392202066641817600) | `/test integ-security-multicluster-tests_istio`
gencheck_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/gencheck_istio/1392202069988872192) | `/test gencheck_istio`
integ-multicluster-k8s-tests_istio | 46834ab1043705b77dd2915b5bd651af65ce758b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-multicluster-k8s-tests_istio/1392202064251064320) | `/test integ-multicluster-k8s-tests_istio`
lint_istio | 83e6b30ed781feaba747179cc16274934b321762 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/lint_istio/1392204947679875072) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-05-11 20:53 UTC, istio-testing commented
@kyessenov: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-helm-tests_istio | 83e6b30ed781feaba747179cc16274934b321762 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-helm-tests_istio/1392204946010542080) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 959fcc83b4ac577d18d7ad9f09d2440ba857bba0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-multicluster-k8s-tests_istio/1392216313920753664) | `/test integ-multicluster-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-05-11 20:53 UTC, istio-testing commented
@kyessenov: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-helm-tests_istio | 83e6b30ed781feaba747179cc16274934b321762 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-helm-tests_istio/1392204946010542080) | `/test integ-helm-tests_istio`
integ-multicluster-k8s-tests_istio | 959fcc83b4ac577d18d7ad9f09d2440ba857bba0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-multicluster-k8s-tests_istio/1392216313920753664) | `/test integ-multicluster-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 959fcc83b4ac577d18d7ad9f09d2440ba857bba0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-distroless-k8s-tests_istio/1392216313958502400) | `/test integ-distroless-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-05-11 21:07 UTC, istio-testing commented
@kyessenov: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-distroless-k8s-tests_istio | 959fcc83b4ac577d18d7ad9f09d2440ba857bba0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-distroless-k8s-tests_istio/1392216313958502400) | `/test integ-distroless-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | 0950a4dbf8e9e332725c50ed1cfa0cd5f660f043 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-multicluster-k8s-tests_istio/1392221629341241344) | `/test integ-multicluster-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-05-11 21:11 UTC, istio-testing commented
@kyessenov: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-multicluster-k8s-tests_istio | 0950a4dbf8e9e332725c50ed1cfa0cd5f660f043 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-multicluster-k8s-tests_istio/1392221629341241344) | `/test integ-multicluster-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | 0950a4dbf8e9e332725c50ed1cfa0cd5f660f043 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-ipv6-k8s-tests_istio/1392221631018962944) | `/test integ-ipv6-k8s-tests_istio`
integ-distroless-k8s-tests_istio | 0950a4dbf8e9e332725c50ed1cfa0cd5f660f043 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-distroless-k8s-tests_istio/1392221630180102144) | `/test integ-distroless-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-05-11 23:41 UTC, kyessenov commented
/retest

2021-05-12 00:02 UTC, istio-testing commented
@kyessenov: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-helm-tests_istio | 061e341672407dca26f49e732acf01ac22033a00 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-helm-tests_istio/1392263544216489984) | `/test integ-helm-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-05-12 02:00 UTC, kyessenov commented
/retest

2021-05-12 02:29 UTC, istio-testing commented
@kyessenov: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-helm-tests_istio | c3427ab02a9199b324c12e222fc96f66ed0d3e2a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-helm-tests_istio/1392299564748247040) | `/test integ-helm-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-05-12 02:41 UTC, istio-testing commented
@kyessenov: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-helm-tests_istio | c3427ab02a9199b324c12e222fc96f66ed0d3e2a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-helm-tests_istio/1392299564748247040) | `/test integ-helm-tests_istio`
integ-security-multicluster-tests_istio | c3427ab02a9199b324c12e222fc96f66ed0d3e2a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32786/integ-security-multicluster-tests_istio/1392299563909386240) | `/test integ-security-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-05-12 04:20 UTC, kyessenov commented
@howardjohn Any idea what is this hybrid using 1.9 injection template with 1.10 proxy container? Why does a new proxy pick up old control plane?

2021-05-12 04:51 UTC, kyessenov commented
I think I'll abandon this approach. It's truly a mess with two status ports, so we're stuck with them.

2021-05-12 04:51 UTC, closed without merging