add validation context for simple if subject alt names exist
istio/istio pull request #32821
Opened 2021-05-12 11:42 UTC by ramaraochavali

Fixes https://github.com/istio/istio/issues/32539

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2021-05-12 11:48 UTC, istio-testing commented
@ramaraochavali: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | 80f81f29c1cb4984b62008755fd8bb4222fb7291 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32821/lint_istio/1392445898805481472) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-05-12 11:52 UTC, istio-testing commented
@ramaraochavali: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | 80f81f29c1cb4984b62008755fd8bb4222fb7291 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32821/lint_istio/1392445898805481472) | `/test lint_istio`
unit-tests_istio | 80f81f29c1cb4984b62008755fd8bb4222fb7291 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32821/unit-tests_istio/1392445881625612288) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-05-12 12:02 UTC, istio-testing commented
@ramaraochavali: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
unit-tests_istio | 686625b0b6a5eca6105249bcaa2f995e42eb901e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32821/unit-tests_istio/1392447971609546752) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-05-12 12:59 UTC, ramaraochavali commented
/test unit-tests_istio

2021-05-12 16:26 UTC, ericvn approved these changes

2021-05-12 20:19 UTC, howardjohn requested changes
Does this work? AFAIK Envoy will NACK this if you don't have trusted CA set

2021-05-13 04:52 UTC, ramaraochavali commented
> Does this work? AFAIK Envoy will NACK this if you don't have trusted CA set

As per docs, both are optional can be provided independently with a warning on match_subject_alt_name to be used only with trusted_ca.

But looking at the code, you are right - it does throw an exception if trusted_ca is not set https://github.com/envoyproxy/envoy/blob/a12869fa9e9add4301a700978d5489e6a0cc0526/source/common/ssl/certificate_validation_context_config_impl.cc#L48.

2021-05-13 04:52 UTC, closed without merging