Refactor cluster patch
istio/istio pull request #33431
Opened 2021-06-15 06:44 UTC by hzxuzhonghu

Please provide a description for what this PR is for.

Now this is the general way to do cluster patch, like listener patch.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2021-06-15 06:45 UTC, istio-testing commented
@hzxuzhonghu: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | daa23f61204892ee9285efdd2167b324f7781ef3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/33431/release-notes_istio/1404691289101832192) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-06-15 06:47 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | daa23f61204892ee9285efdd2167b324f7781ef3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/33431/release-notes_istio/1404691289101832192) | `/test release-notes_istio`
lint_istio | daa23f61204892ee9285efdd2167b324f7781ef3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/33431/lint_istio/1404691287407333376) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-06-15 15:01 UTC, howardjohn requested changes
We used to do things this way and it was intentionally changed to support https://github.com/istio/istio/pull/33338. I would prefer we don't revert or we will not be able to cache CDS

2021-06-16 01:56 UTC, hzxuzhonghu commented
They should not conflict, the cache key used by cds is not changed.

2021-06-16 01:59 UTC, howardjohn commented
We need to apply the patches to individual clusters, not all clusters in
aggregate. The cache works on a per-cluster basis not a collection of
clusters

On Tue, Jun 15, 2021, 6:56 PM Zhonghu Xu ***@***.***> wrote:

> They should not conflict, the cache key used by cds is not changed.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/istio/pull/33431#issuecomment-861955420>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEYGXNNONCJ5NYIILTZHXDTTAAGNANCNFSM46WTITGQ>
> .
>

2021-07-11 20:34 UTC, istio-testing commented
@hzxuzhonghu: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-07-31 05:05 UTC, closed without merging