Add sidecar egress hosts conflict check
istio/istio pull request #33786
Opened 2021-07-02 03:31 UTC by kebe7jun

For https://github.com/istio/istio/pull/33766#issuecomment-872667419

2021-07-02 10:09 UTC, ramaraochavali commented
LGTM. Will leave it for others to review

2021-07-02 16:16 UTC, howardjohn requested changes
Making previously valid configurations invalid is a breaking API change. At most we can warn.

2021-07-08 06:56 UTC, kebe7jun commented
> Making previously valid configurations invalid is a breaking API change. At most we can warn.

@howardjohn  Is this an indication that we only need to print the logs?

2021-07-08 08:03 UTC, hzxuzhonghu commented
Add a warning, and add a TODO maybe in 1.12 we can make it this way.

FYI: `WrapWarning`

2021-07-08 09:06 UTC, kebe7jun commented
> Add a warning, and add a TODO maybe in 1.12 we can make it this way.
> 
> FYI: `WrapWarning`

Thanks for your suggestions, I did it.

2021-07-08 15:11 UTC, howardjohn commented
> Add a warning, and add a TODO maybe in 1.12 we can make it this way.

We can never make it this way without it being a breaking API change. To do this it would require a new ApiVersion

2021-07-08 15:38 UTC, howardjohn commented on pkg/config/validation/validation_test.go
> +		{"skip(1.11): sidecar egress duplicated with wildcarded same namespace .", &networking.Sidecar{
what does "skip(1.11)" mean?

2021-07-08 15:38 UTC, howardjohn commented on pkg/config/validation/validation_test.go
> +		{"skip(1.11): sidecar egress duplicated with wildcarded same namespace .", &networking.Sidecar{
Oh I see. We should test the warnings as well, using checkValidationMessage like some other tests

2021-07-13 04:14 UTC, hzxuzhonghu commented
@howardjohn https://kubernetes.io/docs/reference/using-api/deprecation-policy/

2021-07-13 04:19 UTC, howardjohn commented
Yes, I would think this violates "Rule #1: API elements may only be removed
by incrementing the version of the API group"

Removing an element (either key or legal value) and making it invalid are
effectively the same?

On Mon, Jul 12, 2021, 9:14 PM Zhonghu Xu ***@***.***> wrote:

> @howardjohn <https://github.com/howardjohn>
> https://kubernetes.io/docs/reference/using-api/deprecation-policy/
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/istio/pull/33786#issuecomment-878763514>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEYGXK6GTVHZXOYMYTE4BDTXO4S3ANCNFSM47V4SROQ>
> .
>

2021-07-15 10:40 UTC, kebe7jun commented
@howardjohn  I see the same action is allowed in Kubernetes: https://github.com/kubernetes/kubernetes/pull/103245.

2021-07-15 16:42 UTC, howardjohn commented
Looks like that may be for an alpha feature flag protected field?

On Thu, Jul 15, 2021 at 3:41 AM Kebe ***@***.***> wrote:

> @howardjohn <https://github.com/howardjohn> I see the same action is
> allowed in Kubernetes: kubernetes/kubernetes#103245
> <https://github.com/kubernetes/kubernetes/pull/103245>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/istio/pull/33786#issuecomment-880590215>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEYGXJYF6EITF27N7UJ7SDTX23LZANCNFSM47V4SROQ>
> .
>

2021-07-16 01:49 UTC, kebe7jun commented
> Looks like that may be for an alpha feature flag protected field?

Yes, but this one does not affect the API and resources, it is only print some warnings in pilot, I can not do this also?

2021-07-16 01:56 UTC, kebe7jun commented
> Looks like that may be for an alpha feature flag protected field?

Yes, but this one does not affect the API and resources, it is only print some warnings in pilot, can we not do this either?

2021-07-16 03:23 UTC, hzxuzhonghu commented
LGTM, it only add some warning in validation, does not break any old configs

2021-07-16 03:30 UTC, howardjohn commented
Sorry I either misread it or didn't look at the update - adding a warning is good, just not error

2021-07-16 06:25 UTC, hzxuzhonghu approved these changes

2021-07-16 07:05 UTC, merged