generate virtual host domains based on virtual service hosts
istio/istio pull request #34137
Opened 2021-07-19 09:57 UTC by ramaraochavali

This is one of the issues we have identified in https://github.com/istio/istio/pull/33904. Since that is getting delayed, I just push this PR to generate domains based on virtual service hosts.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2021-07-19 09:59 UTC, istio-testing commented
@ramaraochavali: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 93438b4de76d14d3205fc811c3dabca62d48dc53 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34137/release-notes_istio/1417061064285097984) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-07-19 10:01 UTC, ramaraochavali commented
/test release-notes_istio

2021-07-19 16:54 UTC, howardjohn commented
/test benchmark_istio

2021-07-19 16:55 UTC, howardjohn commented
Can you explain more why we are doing this? I can see the XDS changes:
```
        map[*.global:7442:[*.global *.global:7442] allow_any:[*] test-service-one.com:7442:[test-service-one.com test-service-one.com:7442] test-service-two.com:7442:[test-service-two.com test-service-two.com:7442]], wanted
        map[*.com:7442:[*.com *.com:7442] *.foo.global:7442:[*.foo.global *.foo.global:7442] *.global:7442:[*.global *.global:7442] allow_any:[*]]
```

But not sure what the positive and negative impacts are of this change.

2021-07-20 04:55 UTC, ramaraochavali commented
> Can you explain more why we are doing this? I can see the XDS changes:

I think it is because when some one specifies virtual services should not we generate domains based on configured host? Right now the domains are random based on what service it matches.

2021-07-20 17:33 UTC, howardjohn commented
> I think it is because when some one specifies virtual services should not we generate domains based on configured host? Right now the domains are random based on what service it matches.

Ah I think I get it. So if there are no services matching, we put `*.example.com`. But then suddenly if someone adds a service `foo.example.com`, we start matching only foo.example.com, which is unexpected.

The flipside is that now a user can create `*.cluster.local` (or with your other PR, `*`), and capture ALL traffic - with higher precedence than explicitly FQDN. That is extremely dangerous, and a major breaking API change.

So I can see some benefits of this, but I think we need to be more careful here around security and backwards compatibility.

2021-07-20 17:42 UTC, howardjohn requested changes
Also seeing a bug here:

```
  - domains:
    - '*.cluster.local'
    - '*.cluster.local:7070'
    - 10.96.116.22
    - 10.96.116.22:7070
```

from VS:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: route
spec:
  hosts:
  - "*.cluster.local"
  http:
  - route:
    - destination:
        host: echo
```

So its grabbing some random matching cluster IP

2021-07-21 03:32 UTC, ramaraochavali commented
> The flipside is that now a user can create *.cluster.local (or with your other PR, *), and capture ALL traffic - with higher precedence than explicitly FQDN. That is extremely dangerous, and a major breaking API change.

I will close my other PR because it does not make sense to allow `*` after thinking about it for some more time. But my question about why do we allow for gateways still remains - I think we should add a warning in validation for sure. If you are OK, I can repurpose that PR to add that warning.

> with higher precedence than explicitly FQDN. 
I guess this in general a problem with wildcard hosts in virtual service. But since we allow it now we must add some guardrails if we want to prevent that  - because I think we have never said in API that domains would be created with first matching host.
People expect domains to be same as what they specify in VS hosts for wildcards also.

> That is extremely dangerous, and a major breaking API change.

I agree it is dangerous. What API expectation this breaks? I am not fully following that part?

2021-07-21 03:35 UTC, howardjohn commented
> But my question about why do we allow for gateways still remains - I think we should add a warning in validation for sure. If you are OK, I can repurpose that PR to add that warning.

Because with gateway everything is opt-in/explicitly configured. So if I configure example.com, and you configure `*.com`, example.com takes precedence.

For sidecar, because if the way we setup hostnames for each Service automatically, the semantics get a bit blurry. Making `*.cluster.local` take precedence over all Services is both dangerous and unique to sidecars

2021-07-21 03:36 UTC, howardjohn commented
Btw I think `*` is just a specialized form of `*.cluster.local` or any other broad wildcards. The same applies concerns apply to either really

2021-07-21 03:36 UTC, ramaraochavali commented
> Btw I think * is just a specialized form of *.cluster.local or any other broad wildcards. The same applies concerns apply to either really

Yes. This was my point.

2021-07-24 07:31 UTC, ramaraochavali commented
I am closing as there is no agreement on whether this is the right the thing to do or not.

2021-07-24 07:31 UTC, closed without merging