adding debug/proxy-info to get proxy istio version
istio/istio pull request #34512
Opened 2021-08-04 09:50 UTC by ChenglongGao327

adding debug/proxy-info to get proxy istio version

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2021-08-04 09:53 UTC, istio-testing commented
@ChenglongGao327: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 7da9fa87a75fac51bbd1ca8581d78d1f9dc1b126 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-notes_istio/1422857526231175168) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-04 10:08 UTC, hzxuzhonghu commented on pkg/proxy/proxyinfo.go
> -	"istio.io/istio/pilot/pkg/xds"
Great, this can decouple importing `istio.io/istio/pilot`

2021-08-04 10:08 UTC, hzxuzhonghu approved these changes

2021-08-04 14:04 UTC, howardjohn reviewed
doesn't istioctl ps already show this info?

2021-08-05 01:36 UTC, hzxuzhonghu commented
I think it is to remove dependency on the pilot package. But `istioctl/pkg/writer/pilot/status.go` also depend on `xds.SyncStatus`.

2021-08-05 02:33 UTC, istio-testing commented
@ChenglongGao327: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-notes_istio/1423109820768063488) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-05 02:34 UTC, istio-testing commented
@ChenglongGao327: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-notes_istio/1423109820768063488) | `/test release-notes_istio`
unit-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/unit-tests_istio/1423109814052982784) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-05 02:34 UTC, istio-testing commented
@ChenglongGao327: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-notes_istio/1423109820768063488) | `/test release-notes_istio`
unit-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/unit-tests_istio/1423109814052982784) | `/test unit-tests_istio`
release-test_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-test_istio/1423109814103314432) | `/test release-test_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-05 02:35 UTC, istio-testing commented
@ChenglongGao327: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-notes_istio/1423109820768063488) | `/test release-notes_istio`
unit-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/unit-tests_istio/1423109814052982784) | `/test unit-tests_istio`
release-test_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-test_istio/1423109814103314432) | `/test release-test_istio`
integ-operator-controller-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-operator-controller-tests_istio/1423109814904426496) | `/test integ-operator-controller-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-05 02:35 UTC, istio-testing commented
@ChenglongGao327: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-notes_istio/1423109820768063488) | `/test release-notes_istio`
unit-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/unit-tests_istio/1423109814052982784) | `/test unit-tests_istio`
release-test_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-test_istio/1423109814103314432) | `/test release-test_istio`
integ-operator-controller-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-operator-controller-tests_istio/1423109814904426496) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-distroless-k8s-tests_istio/1423109814405304320) | `/test integ-distroless-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-05 02:35 UTC, istio-testing commented
@ChenglongGao327: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-notes_istio/1423109820768063488) | `/test release-notes_istio`
unit-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/unit-tests_istio/1423109814052982784) | `/test unit-tests_istio`
release-test_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-test_istio/1423109814103314432) | `/test release-test_istio`
integ-operator-controller-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-operator-controller-tests_istio/1423109814904426496) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-distroless-k8s-tests_istio/1423109814405304320) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-telemetry-k8s-tests_istio/1423109814266892288) | `/test integ-telemetry-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-05 02:36 UTC, istio-testing commented
@ChenglongGao327: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-notes_istio/1423109820768063488) | `/test release-notes_istio`
unit-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/unit-tests_istio/1423109814052982784) | `/test unit-tests_istio`
release-test_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-test_istio/1423109814103314432) | `/test release-test_istio`
integ-operator-controller-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-operator-controller-tests_istio/1423109814904426496) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-distroless-k8s-tests_istio/1423109814405304320) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-telemetry-k8s-tests_istio/1423109814266892288) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-security-k8s-tests_istio/1423109814241726464) | `/test integ-security-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-05 02:36 UTC, istio-testing commented
@ChenglongGao327: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-notes_istio/1423109820768063488) | `/test release-notes_istio`
unit-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/unit-tests_istio/1423109814052982784) | `/test unit-tests_istio`
release-test_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-test_istio/1423109814103314432) | `/test release-test_istio`
integ-operator-controller-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-operator-controller-tests_istio/1423109814904426496) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-distroless-k8s-tests_istio/1423109814405304320) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-telemetry-k8s-tests_istio/1423109814266892288) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-security-k8s-tests_istio/1423109814241726464) | `/test integ-security-k8s-tests_istio`
integ-helm-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-helm-tests_istio/1423109817425203200) | `/test integ-helm-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-05 02:36 UTC, istio-testing commented
@ChenglongGao327: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-notes_istio/1423109820768063488) | `/test release-notes_istio`
unit-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/unit-tests_istio/1423109814052982784) | `/test unit-tests_istio`
release-test_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-test_istio/1423109814103314432) | `/test release-test_istio`
integ-operator-controller-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-operator-controller-tests_istio/1423109814904426496) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-distroless-k8s-tests_istio/1423109814405304320) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-telemetry-k8s-tests_istio/1423109814266892288) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-security-k8s-tests_istio/1423109814241726464) | `/test integ-security-k8s-tests_istio`
integ-helm-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-helm-tests_istio/1423109817425203200) | `/test integ-helm-tests_istio`
integ-pilot-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-pilot-k8s-tests_istio/1423109814153646080) | `/test integ-pilot-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-05 02:36 UTC, istio-testing commented
@ChenglongGao327: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-notes_istio/1423109820768063488) | `/test release-notes_istio`
unit-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/unit-tests_istio/1423109814052982784) | `/test unit-tests_istio`
release-test_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-test_istio/1423109814103314432) | `/test release-test_istio`
integ-operator-controller-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-operator-controller-tests_istio/1423109814904426496) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-distroless-k8s-tests_istio/1423109814405304320) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-telemetry-k8s-tests_istio/1423109814266892288) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-security-k8s-tests_istio/1423109814241726464) | `/test integ-security-k8s-tests_istio`
integ-helm-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-helm-tests_istio/1423109817425203200) | `/test integ-helm-tests_istio`
integ-pilot-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-pilot-k8s-tests_istio/1423109814153646080) | `/test integ-pilot-k8s-tests_istio`
integ-security-multicluster-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-security-multicluster-tests_istio/1423109816569565184) | `/test integ-security-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-05 02:36 UTC, istio-testing commented
@ChenglongGao327: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-notes_istio/1423109820768063488) | `/test release-notes_istio`
unit-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/unit-tests_istio/1423109814052982784) | `/test unit-tests_istio`
release-test_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-test_istio/1423109814103314432) | `/test release-test_istio`
integ-operator-controller-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-operator-controller-tests_istio/1423109814904426496) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-distroless-k8s-tests_istio/1423109814405304320) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-telemetry-k8s-tests_istio/1423109814266892288) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-security-k8s-tests_istio/1423109814241726464) | `/test integ-security-k8s-tests_istio`
integ-helm-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-helm-tests_istio/1423109817425203200) | `/test integ-helm-tests_istio`
integ-pilot-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-pilot-k8s-tests_istio/1423109814153646080) | `/test integ-pilot-k8s-tests_istio`
integ-security-multicluster-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-security-multicluster-tests_istio/1423109816569565184) | `/test integ-security-multicluster-tests_istio`
integ-pilot-multicluster-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-pilot-multicluster-tests_istio/1423109815734898688) | `/test integ-pilot-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-05 02:36 UTC, istio-testing commented
@ChenglongGao327: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-notes_istio/1423109820768063488) | `/test release-notes_istio`
unit-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/unit-tests_istio/1423109814052982784) | `/test unit-tests_istio`
release-test_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-test_istio/1423109814103314432) | `/test release-test_istio`
integ-operator-controller-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-operator-controller-tests_istio/1423109814904426496) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-distroless-k8s-tests_istio/1423109814405304320) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-telemetry-k8s-tests_istio/1423109814266892288) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-security-k8s-tests_istio/1423109814241726464) | `/test integ-security-k8s-tests_istio`
integ-helm-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-helm-tests_istio/1423109817425203200) | `/test integ-helm-tests_istio`
integ-pilot-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-pilot-k8s-tests_istio/1423109814153646080) | `/test integ-pilot-k8s-tests_istio`
integ-security-multicluster-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-security-multicluster-tests_istio/1423109816569565184) | `/test integ-security-multicluster-tests_istio`
integ-pilot-multicluster-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-pilot-multicluster-tests_istio/1423109815734898688) | `/test integ-pilot-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-telemetry-mc-k8s-tests_istio/1423109814317223936) | `/test integ-telemetry-mc-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-05 02:36 UTC, istio-testing commented
@ChenglongGao327: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-notes_istio/1423109820768063488) | `/test release-notes_istio`
unit-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/unit-tests_istio/1423109814052982784) | `/test unit-tests_istio`
release-test_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-test_istio/1423109814103314432) | `/test release-test_istio`
integ-operator-controller-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-operator-controller-tests_istio/1423109814904426496) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-distroless-k8s-tests_istio/1423109814405304320) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-telemetry-k8s-tests_istio/1423109814266892288) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-security-k8s-tests_istio/1423109814241726464) | `/test integ-security-k8s-tests_istio`
integ-helm-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-helm-tests_istio/1423109817425203200) | `/test integ-helm-tests_istio`
integ-pilot-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-pilot-k8s-tests_istio/1423109814153646080) | `/test integ-pilot-k8s-tests_istio`
integ-security-multicluster-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-security-multicluster-tests_istio/1423109816569565184) | `/test integ-security-multicluster-tests_istio`
integ-pilot-multicluster-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-pilot-multicluster-tests_istio/1423109815734898688) | `/test integ-pilot-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-telemetry-mc-k8s-tests_istio/1423109814317223936) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-multicluster-k8s-tests_istio/1423109814363361280) | `/test integ-multicluster-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-05 02:36 UTC, istio-testing commented
@ChenglongGao327: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-notes_istio/1423109820768063488) | `/test release-notes_istio`
unit-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/unit-tests_istio/1423109814052982784) | `/test unit-tests_istio`
release-test_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-test_istio/1423109814103314432) | `/test release-test_istio`
integ-operator-controller-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-operator-controller-tests_istio/1423109814904426496) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-distroless-k8s-tests_istio/1423109814405304320) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-telemetry-k8s-tests_istio/1423109814266892288) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-security-k8s-tests_istio/1423109814241726464) | `/test integ-security-k8s-tests_istio`
integ-helm-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-helm-tests_istio/1423109817425203200) | `/test integ-helm-tests_istio`
integ-pilot-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-pilot-k8s-tests_istio/1423109814153646080) | `/test integ-pilot-k8s-tests_istio`
integ-security-multicluster-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-security-multicluster-tests_istio/1423109816569565184) | `/test integ-security-multicluster-tests_istio`
integ-pilot-multicluster-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-pilot-multicluster-tests_istio/1423109815734898688) | `/test integ-pilot-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-telemetry-mc-k8s-tests_istio/1423109814317223936) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-multicluster-k8s-tests_istio/1423109814363361280) | `/test integ-multicluster-k8s-tests_istio`
lint_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/lint_istio/1423109819086147584) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-05 02:36 UTC, istio-testing commented
@ChenglongGao327: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-notes_istio/1423109820768063488) | `/test release-notes_istio`
unit-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/unit-tests_istio/1423109814052982784) | `/test unit-tests_istio`
release-test_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-test_istio/1423109814103314432) | `/test release-test_istio`
integ-operator-controller-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-operator-controller-tests_istio/1423109814904426496) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-distroless-k8s-tests_istio/1423109814405304320) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-telemetry-k8s-tests_istio/1423109814266892288) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-security-k8s-tests_istio/1423109814241726464) | `/test integ-security-k8s-tests_istio`
integ-helm-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-helm-tests_istio/1423109817425203200) | `/test integ-helm-tests_istio`
integ-pilot-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-pilot-k8s-tests_istio/1423109814153646080) | `/test integ-pilot-k8s-tests_istio`
integ-security-multicluster-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-security-multicluster-tests_istio/1423109816569565184) | `/test integ-security-multicluster-tests_istio`
integ-pilot-multicluster-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-pilot-multicluster-tests_istio/1423109815734898688) | `/test integ-pilot-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-telemetry-mc-k8s-tests_istio/1423109814317223936) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-multicluster-k8s-tests_istio/1423109814363361280) | `/test integ-multicluster-k8s-tests_istio`
lint_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/lint_istio/1423109819086147584) | `/test lint_istio`
integ-cni-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-cni-k8s-tests_istio/1423109814199783424) | `/test integ-cni-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-05 02:39 UTC, istio-testing commented
@ChenglongGao327: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-notes_istio/1423109820768063488) | `/test release-notes_istio`
unit-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/unit-tests_istio/1423109814052982784) | `/test unit-tests_istio`
release-test_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-test_istio/1423109814103314432) | `/test release-test_istio`
integ-operator-controller-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-operator-controller-tests_istio/1423109814904426496) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-distroless-k8s-tests_istio/1423109814405304320) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-telemetry-k8s-tests_istio/1423109814266892288) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-security-k8s-tests_istio/1423109814241726464) | `/test integ-security-k8s-tests_istio`
integ-helm-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-helm-tests_istio/1423109817425203200) | `/test integ-helm-tests_istio`
integ-pilot-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-pilot-k8s-tests_istio/1423109814153646080) | `/test integ-pilot-k8s-tests_istio`
integ-security-multicluster-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-security-multicluster-tests_istio/1423109816569565184) | `/test integ-security-multicluster-tests_istio`
integ-pilot-multicluster-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-pilot-multicluster-tests_istio/1423109815734898688) | `/test integ-pilot-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-telemetry-mc-k8s-tests_istio/1423109814317223936) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-multicluster-k8s-tests_istio/1423109814363361280) | `/test integ-multicluster-k8s-tests_istio`
lint_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/lint_istio/1423109819086147584) | `/test lint_istio`
integ-cni-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-cni-k8s-tests_istio/1423109814199783424) | `/test integ-cni-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-ipv6-k8s-tests_istio/1423109814459830272) | `/test integ-ipv6-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-05 02:51 UTC, istio-testing commented
@ChenglongGao327: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
unit-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/unit-tests_istio/1423109814052982784) | `/test unit-tests_istio`
release-test_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-test_istio/1423109814103314432) | `/test release-test_istio`
integ-operator-controller-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-operator-controller-tests_istio/1423109814904426496) | `/test integ-operator-controller-tests_istio`
integ-distroless-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-distroless-k8s-tests_istio/1423109814405304320) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-telemetry-k8s-tests_istio/1423109814266892288) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-security-k8s-tests_istio/1423109814241726464) | `/test integ-security-k8s-tests_istio`
integ-helm-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-helm-tests_istio/1423109817425203200) | `/test integ-helm-tests_istio`
integ-pilot-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-pilot-k8s-tests_istio/1423109814153646080) | `/test integ-pilot-k8s-tests_istio`
integ-security-multicluster-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-security-multicluster-tests_istio/1423109816569565184) | `/test integ-security-multicluster-tests_istio`
integ-pilot-multicluster-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-pilot-multicluster-tests_istio/1423109815734898688) | `/test integ-pilot-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-telemetry-mc-k8s-tests_istio/1423109814317223936) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-multicluster-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-multicluster-k8s-tests_istio/1423109814363361280) | `/test integ-multicluster-k8s-tests_istio`
lint_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/lint_istio/1423109819086147584) | `/test lint_istio`
integ-cni-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-cni-k8s-tests_istio/1423109814199783424) | `/test integ-cni-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-ipv6-k8s-tests_istio/1423109814459830272) | `/test integ-ipv6-k8s-tests_istio`
release-notes_istio | 7da9fa87a75fac51bbd1ca8581d78d1f9dc1b126 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-notes_istio/1423114307108868096) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-05 02:59 UTC, istio-testing commented
@ChenglongGao327: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-test_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-test_istio/1423109814103314432) | `/test release-test_istio`
integ-distroless-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-distroless-k8s-tests_istio/1423109814405304320) | `/test integ-distroless-k8s-tests_istio`
integ-telemetry-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-telemetry-k8s-tests_istio/1423109814266892288) | `/test integ-telemetry-k8s-tests_istio`
integ-security-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-security-k8s-tests_istio/1423109814241726464) | `/test integ-security-k8s-tests_istio`
integ-helm-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-helm-tests_istio/1423109817425203200) | `/test integ-helm-tests_istio`
integ-pilot-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-pilot-k8s-tests_istio/1423109814153646080) | `/test integ-pilot-k8s-tests_istio`
integ-security-multicluster-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-security-multicluster-tests_istio/1423109816569565184) | `/test integ-security-multicluster-tests_istio`
integ-pilot-multicluster-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-pilot-multicluster-tests_istio/1423109815734898688) | `/test integ-pilot-multicluster-tests_istio`
integ-telemetry-mc-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-telemetry-mc-k8s-tests_istio/1423109814317223936) | `/test integ-telemetry-mc-k8s-tests_istio`
integ-cni-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-cni-k8s-tests_istio/1423109814199783424) | `/test integ-cni-k8s-tests_istio`
integ-ipv6-k8s-tests_istio | c4a4fd14cab94295c21bc08f1d055950d237c48e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/integ-ipv6-k8s-tests_istio/1423109814459830272) | `/test integ-ipv6-k8s-tests_istio`
release-notes_istio | 7da9fa87a75fac51bbd1ca8581d78d1f9dc1b126 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-notes_istio/1423114307108868096) | `/test release-notes_istio`
unit-tests_istio | 7da9fa87a75fac51bbd1ca8581d78d1f9dc1b126 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/unit-tests_istio/1423114300397981696) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-05 11:44 UTC, ChenglongGao327 commented
/retest

2021-08-05 11:45 UTC, istio-testing commented
@ChenglongGao327: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
unit-tests_istio | 7da9fa87a75fac51bbd1ca8581d78d1f9dc1b126 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/unit-tests_istio/1423114300397981696) | `/test unit-tests_istio`
release-notes_istio | 7da9fa87a75fac51bbd1ca8581d78d1f9dc1b126 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34512/release-notes_istio/1423248644315811840) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-05 13:45 UTC, howardjohn requested changes
Please explain why we need this since proxy status already has it. Thanks!

2021-08-06 02:21 UTC, ChenglongGao327 commented
> Please explain why we need this since proxy status already has it. Thanks!

sorry, missing it , i think it decouple importing ```istio.io/istio/pilot```, did not notice that istioctl ps can get these.

2021-09-09 20:34 UTC, istio-testing commented
@ChenglongGao327: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-09-20 05:05 UTC, closed without merging