fix data race issue
istio/istio pull request #34642
Opened 2021-08-11 19:15 UTC by williamaronli

**Please provide a description of this PR:**
ref: https://github.com/istio/istio/issues/34115

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2021-08-11 19:16 UTC, istio-testing commented
@williamaronli: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 7ef0f24fdac48b92e41db7574fa9966e9492291d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34642/release-notes_istio/1425536341319356416) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-11 19:31 UTC, istio-testing commented
@williamaronli: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 7ef0f24fdac48b92e41db7574fa9966e9492291d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34642/release-notes_istio/1425536341319356416) | `/test release-notes_istio`
unit-tests_istio | 7ef0f24fdac48b92e41db7574fa9966e9492291d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34642/unit-tests_istio/1425536333547311104) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-11 19:34 UTC, lei-tang approved these changes

2021-08-11 19:59 UTC, howardjohn requested changes

2021-08-11 19:59 UTC, howardjohn commented on security/pkg/nodeagent/caclient/providers/citadel/client_test.go
>  			if err := s.Serve(lis); err != nil {
s.Serve blocks, so the wg just hangs

2021-08-13 23:42 UTC, lei-tang reviewed
Had a discussion with William offline. The waiting operation should wait for the grpc server stops and should be waiting after the test completes but before the test exits.

2021-08-13 23:46 UTC, istio-testing commented
@williamaronli: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
unit-tests_istio | 4836c5501c4b8b6c7cfbc690b73e5402c5e45116 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34642/unit-tests_istio/1426327225354948608) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-13 23:51 UTC, williamaronli commented
/rerun

2021-08-13 23:52 UTC, williamaronli commented
/retest

2021-08-16 15:46 UTC, howardjohn approved these changes

2021-08-16 16:39 UTC, merged

2021-08-19 15:08 UTC, howardjohn commented
/cherrypick release-1.11

2021-08-19 15:10 UTC, istio-testing commented
@howardjohn: new pull request created: #34787

<details>

In response to [this](https://github.com/istio/istio/pull/34642#issuecomment-901995334):

>/cherrypick release-1.11


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>