use sets.Set to replace the array
istio/istio pull request #34655
Opened 2021-08-12 11:35 UTC by ChenglongGao327

1. use sets.Set
2. fix a typo

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2021-08-12 11:38 UTC, istio-testing commented
@ChenglongGao327: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | a6403f8dc83724860b55fb84362f2c082e57ab42 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34655/release-notes_istio/1425783126776352768) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-12 11:44 UTC, ChenglongGao327 commented on pilot/pkg/security/trustdomain/bundle.go
> +	return principalsForAliases.SortedList()
sort newPrincipal array, need adjust the order of test data

2021-08-12 16:16 UTC, howardjohn requested changes
I am suspicious that this is faster.. we need to alloc a map (slow) and sort it (slow).

if we are going to micro-optimize we should have benchmarks proving its actually an improvement IMO

2021-08-12 19:25 UTC, yangminzhu commented on pilot/pkg/security/trustdomain/bundle.go
> +	principalsForAliases := sets.Set{}
In most cases there will be only a few items in the `principalsForAliases` and `t.TrustDomains` list, this likely won't be any faster especially you have to do an extra `SortedList()` in the end.

2021-08-13 01:02 UTC, ChenglongGao327 commented
yes，if there only a few items this won't be faster

2021-08-13 01:02 UTC, closed without merging