make JwtProvider_RemoteJwks.RemoteJwks.HttpUri.Timeout and  JwtProvider_RemoteJwks.RemoteJwks.CacheDuration configurable
istio/istio pull request #34785
Opened 2021-08-19 12:53 UTC by ChenglongGao327

add env to make JwtProvider_RemoteJwks.RemoteJwks.HttpUri.Timeout and JwtProvider_RemoteJwks.RemoteJwks.CacheDuration configurable

**Please provide a description of this PR:**

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2021-08-19 12:56 UTC, istio-testing commented
@ChenglongGao327: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | b587bc4a2617dd6d635788d306f4d9d834785c67 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34785/release-notes_istio/1428339385337647104) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-19 12:56 UTC, istio-testing commented
@ChenglongGao327: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | b587bc4a2617dd6d635788d306f4d9d834785c67 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34785/release-notes_istio/1428339385337647104) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-19 12:57 UTC, istio-testing commented
@ChenglongGao327: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | b587bc4a2617dd6d635788d306f4d9d834785c67 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34785/release-notes_istio/1428339385337647104) | `/test release-notes_istio`
lint_istio | b587bc4a2617dd6d635788d306f4d9d834785c67 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34785/lint_istio/1428339383668314112) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-19 13:02 UTC, istio-testing commented
@ChenglongGao327: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | b587bc4a2617dd6d635788d306f4d9d834785c67 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34785/lint_istio/1428339383668314112) | `/test lint_istio`
release-notes_istio | 6941ee9a31f88a3de97f61799165aa4b89d3402a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34785/release-notes_istio/1428341233268297728) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-19 13:02 UTC, istio-testing commented
@ChenglongGao327: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | b587bc4a2617dd6d635788d306f4d9d834785c67 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34785/lint_istio/1428339383668314112) | `/test lint_istio`
release-notes_istio | 6941ee9a31f88a3de97f61799165aa4b89d3402a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34785/release-notes_istio/1428341233268297728) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-19 15:20 UTC, howardjohn requested changes
Can you explain the use case for this? Generally we are trying to avoid adding endless env vars for obscure settings

2021-08-20 03:03 UTC, istio-testing commented
@ChenglongGao327: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | ee5021d5df6faa091a4487f37ede66ca5a5c5c03 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34785/release-notes_istio/1428552470145011712) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-20 03:03 UTC, istio-testing commented
@ChenglongGao327: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | ee5021d5df6faa091a4487f37ede66ca5a5c5c03 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34785/release-notes_istio/1428552470145011712) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-20 03:12 UTC, ChenglongGao327 commented
> Can you explain the use case for this? Generally we are trying to avoid adding endless env vars for obscure settings

This scene is less used, and there are not enough scenes to make it configurable. Through environment variables, it will be more flexible to make it configurable.
I will roll back the changes and delete this unnecessary comment

2021-08-20 03:16 UTC, istio-testing commented
@ChenglongGao327: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 27e50783c3f039a9f5682e14233a9051960678a4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34785/release-notes_istio/1428556345207951360) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-20 03:16 UTC, istio-testing commented
@ChenglongGao327: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 27e50783c3f039a9f5682e14233a9051960678a4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34785/release-notes_istio/1428556345207951360) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-20 14:47 UTC, howardjohn approved these changes

2021-08-20 14:48 UTC, howardjohn commented
/retest

2021-08-20 15:56 UTC, merged