use EndpointSlices by default in 1.21
istio/istio pull request #34971
Opened 2021-08-31 22:34 UTC by stevenctl

Not sure if we have other examples changing default behavior conditionally on the k8s version, this seems like it would wor.

2021-08-31 22:34 UTC, stevenctl commented
Should this have a release note? I would think it's sort of an implementation detail of pilot.

2021-08-31 22:36 UTC, istio-testing commented
@stevenctl: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/release-notes_istio/1432834235323912192) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-31 22:39 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/release-notes_istio/1432834235323912192) | `/test release-notes_istio`
gencheck_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/gencheck_istio/1432834234485051392) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-31 22:41 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/release-notes_istio/1432834235323912192) | `/test release-notes_istio`
gencheck_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/gencheck_istio/1432834234485051392) | `/test gencheck_istio`
lint_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/lint_istio/1432834233646190592) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-31 22:44 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/release-notes_istio/1432834235323912192) | `/test release-notes_istio`
gencheck_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/gencheck_istio/1432834234485051392) | `/test gencheck_istio`
lint_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/lint_istio/1432834233646190592) | `/test lint_istio`
unit-tests_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/unit-tests_istio/1432834227832885248) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-31 22:48 UTC, howardjohn commented on tests/integration/pilot/endpointslice/endpointslice_test.go
> +				kubelib.IsLessThanVersion(t.Clusters().Kube().Default(), 21))
the sprintf doesn't seem to have any `%s`?

2021-08-31 22:56 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/release-notes_istio/1432834235323912192) | `/test release-notes_istio`
gencheck_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/gencheck_istio/1432834234485051392) | `/test gencheck_istio`
lint_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/lint_istio/1432834233646190592) | `/test lint_istio`
unit-tests_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/unit-tests_istio/1432834227832885248) | `/test unit-tests_istio`
integ-cni-k8s-tests_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/integ-cni-k8s-tests_istio/1432834228109709312) | `/test integ-cni-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-31 22:57 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/release-notes_istio/1432834235323912192) | `/test release-notes_istio`
gencheck_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/gencheck_istio/1432834234485051392) | `/test gencheck_istio`
lint_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/lint_istio/1432834233646190592) | `/test lint_istio`
unit-tests_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/unit-tests_istio/1432834227832885248) | `/test unit-tests_istio`
integ-cni-k8s-tests_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/integ-cni-k8s-tests_istio/1432834228109709312) | `/test integ-cni-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/integ-pilot-k8s-tests_istio/1432834227925159936) | `/test integ-pilot-k8s-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-08-31 23:06 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/release-notes_istio/1432834235323912192) | `/test release-notes_istio`
gencheck_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/gencheck_istio/1432834234485051392) | `/test gencheck_istio`
lint_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/lint_istio/1432834233646190592) | `/test lint_istio`
unit-tests_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/unit-tests_istio/1432834227832885248) | `/test unit-tests_istio`
integ-cni-k8s-tests_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/integ-cni-k8s-tests_istio/1432834228109709312) | `/test integ-cni-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/integ-pilot-k8s-tests_istio/1432834227925159936) | `/test integ-pilot-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/integ-pilot-multicluster-tests_istio/1432834230320107520) | `/test integ-pilot-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-09-01 15:35 UTC, howardjohn commented
Blocker: https://github.com/istio/istio/issues/34995

2021-09-01 15:36 UTC, howardjohn commented
> Should this have a release note? I would think it's sort of an implementation detail of pilot.

IMO yes. It is an implementation detail but a big enough one users should know about it for debugging, etc.

Also note users may manually create EndpointSlices that are currently ignored by Istiod, which will now not be ignored. So it can be user facing in edge cases

2021-09-01 17:10 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/gencheck_istio/1432834234485051392) | `/test gencheck_istio`
lint_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/lint_istio/1432834233646190592) | `/test lint_istio`
unit-tests_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/unit-tests_istio/1432834227832885248) | `/test unit-tests_istio`
integ-cni-k8s-tests_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/integ-cni-k8s-tests_istio/1432834228109709312) | `/test integ-cni-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/integ-pilot-k8s-tests_istio/1432834227925159936) | `/test integ-pilot-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/integ-pilot-multicluster-tests_istio/1432834230320107520) | `/test integ-pilot-multicluster-tests_istio`
release-notes_istio | 6c431b4100f6469a551b26ce7d079ff6ae4fd1c0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/release-notes_istio/1433114767186202624) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-09-01 17:13 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/gencheck_istio/1432834234485051392) | `/test gencheck_istio`
unit-tests_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/unit-tests_istio/1432834227832885248) | `/test unit-tests_istio`
integ-cni-k8s-tests_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/integ-cni-k8s-tests_istio/1432834228109709312) | `/test integ-cni-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/integ-pilot-k8s-tests_istio/1432834227925159936) | `/test integ-pilot-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/integ-pilot-multicluster-tests_istio/1432834230320107520) | `/test integ-pilot-multicluster-tests_istio`
release-notes_istio | 6c431b4100f6469a551b26ce7d079ff6ae4fd1c0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/release-notes_istio/1433114767186202624) | `/test release-notes_istio`
lint_istio | 6c431b4100f6469a551b26ce7d079ff6ae4fd1c0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/lint_istio/1433114765508481024) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-09-01 17:14 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
unit-tests_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/unit-tests_istio/1432834227832885248) | `/test unit-tests_istio`
integ-cni-k8s-tests_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/integ-cni-k8s-tests_istio/1432834228109709312) | `/test integ-cni-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/integ-pilot-k8s-tests_istio/1432834227925159936) | `/test integ-pilot-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/integ-pilot-multicluster-tests_istio/1432834230320107520) | `/test integ-pilot-multicluster-tests_istio`
release-notes_istio | 6c431b4100f6469a551b26ce7d079ff6ae4fd1c0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/release-notes_istio/1433114767186202624) | `/test release-notes_istio`
lint_istio | 6c431b4100f6469a551b26ce7d079ff6ae4fd1c0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/lint_istio/1433114765508481024) | `/test lint_istio`
gencheck_istio | 6c431b4100f6469a551b26ce7d079ff6ae4fd1c0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/gencheck_istio/1433114766347341824) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-09-01 17:18 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-cni-k8s-tests_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/integ-cni-k8s-tests_istio/1432834228109709312) | `/test integ-cni-k8s-tests_istio`
integ-pilot-k8s-tests_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/integ-pilot-k8s-tests_istio/1432834227925159936) | `/test integ-pilot-k8s-tests_istio`
integ-pilot-multicluster-tests_istio | 931f183e698ea817bbc9c587c004cda8fc0951fc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/integ-pilot-multicluster-tests_istio/1432834230320107520) | `/test integ-pilot-multicluster-tests_istio`
release-notes_istio | 6c431b4100f6469a551b26ce7d079ff6ae4fd1c0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/release-notes_istio/1433114767186202624) | `/test release-notes_istio`
lint_istio | 6c431b4100f6469a551b26ce7d079ff6ae4fd1c0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/lint_istio/1433114765508481024) | `/test lint_istio`
gencheck_istio | 6c431b4100f6469a551b26ce7d079ff6ae4fd1c0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/gencheck_istio/1433114766347341824) | `/test gencheck_istio`
unit-tests_istio | 6c431b4100f6469a551b26ce7d079ff6ae4fd1c0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/unit-tests_istio/1433114759653232640) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-09-01 17:45 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 6c431b4100f6469a551b26ce7d079ff6ae4fd1c0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/release-notes_istio/1433114767186202624) | `/test release-notes_istio`
lint_istio | 6c431b4100f6469a551b26ce7d079ff6ae4fd1c0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/lint_istio/1433114765508481024) | `/test lint_istio`
gencheck_istio | 6c431b4100f6469a551b26ce7d079ff6ae4fd1c0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/gencheck_istio/1433114766347341824) | `/test gencheck_istio`
unit-tests_istio | 6c431b4100f6469a551b26ce7d079ff6ae4fd1c0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/unit-tests_istio/1433114759653232640) | `/test unit-tests_istio`
integ-pilot-multicluster-tests_istio | 6c431b4100f6469a551b26ce7d079ff6ae4fd1c0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/integ-pilot-multicluster-tests_istio/1433114762157232128) | `/test integ-pilot-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-09-01 20:26 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio | 6c431b4100f6469a551b26ce7d079ff6ae4fd1c0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/lint_istio/1433114765508481024) | `/test lint_istio`
gencheck_istio | 6c431b4100f6469a551b26ce7d079ff6ae4fd1c0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/gencheck_istio/1433114766347341824) | `/test gencheck_istio`
unit-tests_istio | 6c431b4100f6469a551b26ce7d079ff6ae4fd1c0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/unit-tests_istio/1433114759653232640) | `/test unit-tests_istio`
integ-pilot-multicluster-tests_istio | 6c431b4100f6469a551b26ce7d079ff6ae4fd1c0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/integ-pilot-multicluster-tests_istio/1433114762157232128) | `/test integ-pilot-multicluster-tests_istio`
release-notes_istio | a2d9690981e796da0c92c3c5b59dad48afe44671 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/release-notes_istio/1433164185595809792) | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-09-01 20:39 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 458df74bfec5f6e0e52e6ae20d4775791ad1874e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/release-notes_istio/1433165114059526144) | `/test release-notes_istio`
unit-tests_istio | 458df74bfec5f6e0e52e6ae20d4775791ad1874e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/unit-tests_istio/1433165095482953728) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-09-01 21:02 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_istio | 458df74bfec5f6e0e52e6ae20d4775791ad1874e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/release-notes_istio/1433165114059526144) | `/test release-notes_istio`
unit-tests_istio | 458df74bfec5f6e0e52e6ae20d4775791ad1874e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/unit-tests_istio/1433165095482953728) | `/test unit-tests_istio`
integ-pilot-multicluster-tests_istio | 458df74bfec5f6e0e52e6ae20d4775791ad1874e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/integ-pilot-multicluster-tests_istio/1433165106404921344) | `/test integ-pilot-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-09-02 01:33 UTC, hzxuzhonghu approved these changes

2021-09-17 18:11 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-multicluster-tests_istio | 458df74bfec5f6e0e52e6ae20d4775791ad1874e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/integ-pilot-multicluster-tests_istio/1433165106404921344) | `/test integ-pilot-multicluster-tests_istio`
unit-tests_istio | dadb7405ce26d7307b69ca2945b443cd80e76245 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/unit-tests_istio/1438926033381232640) | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-09-17 18:32 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
unit-tests_istio | dadb7405ce26d7307b69ca2945b443cd80e76245 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/unit-tests_istio/1438926033381232640) | `/test unit-tests_istio`
integ-pilot-multicluster-tests_istio | dadb7405ce26d7307b69ca2945b443cd80e76245 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/integ-pilot-multicluster-tests_istio/1438926035889426432) | `/test integ-pilot-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-09-20 16:44 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
unit-tests_istio | dadb7405ce26d7307b69ca2945b443cd80e76245 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/unit-tests_istio/1438926033381232640) | `/test unit-tests_istio`
integ-pilot-multicluster-tests_istio | dadb7405ce26d7307b69ca2945b443cd80e76245 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/integ-pilot-multicluster-tests_istio/1438926035889426432) | `/test integ-pilot-multicluster-tests_istio`
lint_istio | 61643e0da539caf371331886dbfc2965b2e37556 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/lint_istio/1439993213866741760) | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-09-20 16:45 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
unit-tests_istio | dadb7405ce26d7307b69ca2945b443cd80e76245 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/unit-tests_istio/1438926033381232640) | `/test unit-tests_istio`
integ-pilot-multicluster-tests_istio | dadb7405ce26d7307b69ca2945b443cd80e76245 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/integ-pilot-multicluster-tests_istio/1438926035889426432) | `/test integ-pilot-multicluster-tests_istio`
lint_istio | 61643e0da539caf371331886dbfc2965b2e37556 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/lint_istio/1439993213866741760) | `/test lint_istio`
gencheck_istio | 61643e0da539caf371331886dbfc2965b2e37556 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/gencheck_istio/1439993214709796864) | `/test gencheck_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-09-20 17:19 UTC, istio-testing commented
@stevenctl: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-multicluster-tests_istio | 5a7c6e301f16a86903213ab12e7d76fa109213ee | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/integ-pilot-multicluster-tests_istio/1439994853587947520) | `/test integ-pilot-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-09-23 18:58 UTC, istio-testing commented
@stevenctl: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-pilot-multicluster-tests_istio | 9e62669a1f54fc74cf71d8104a936c71d9f418c2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34971/integ-pilot-multicluster-tests_istio/1441106615561359360) | true | `/test integ-pilot-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-09-27 18:18 UTC, howardjohn requested changes
This LGTM but would prefer https://github.com/istio/istio/issues/34995 to be fixed first. While its a relatively rare edge case, the impact is extremely bad and it is a regression

2021-11-03 20:35 UTC, istio-testing commented
@stevenctl: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-11-03 20:35 UTC, istio-testing commented
@stevenctl: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-11-11 17:59 UTC, stevenctl commented
With #35990 do we want to squeeze this into 1.12?

2021-11-11 18:11 UTC, howardjohn commented
This seems like a pretty large change to get this late into the release. I
think its ideal to get it in now for master so we get 4 months of soak time
before shipping?

On Thu, Nov 11, 2021 at 10:00 AM Steven Landow ***@***.***>
wrote:

> With #35990 <https://github.com/istio/istio/pull/35990> do we want to
> squeeze this into 1.12?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/istio/pull/34971#issuecomment-966507163>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEYGXJBU5I7DWKUQDZO3ETULQAB7ANCNFSM5DFDTZTA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-12 11:10 UTC, ramaraochavali commented
+1 for master

2021-11-12 17:10 UTC, howardjohn approved these changes

2021-11-12 18:34 UTC, merged