Add the error of validateExtensionProvider to errors when validate MeshConfig.
istio/istio pull request #35002
Opened 2021-09-02 04:49 UTC by devincd

Signed-off-by: devincd <505259926@qq.com>

**Please provide a description of this PR:**
I think it should add the error of validateExtensionProvider to the errors that validateMeshConfig returns. If some extensionProviders are invalid, there are can not be ignore, because we do not know which extension provider is used or not used.

Related issue: https://github.com/istio/istio/issues/34693

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2021-09-06 01:52 UTC, devincd commented
@hzxuzhonghu Please take a look, thinks.

2021-09-07 01:31 UTC, devincd commented
@incfly Please take a look, thinks.

2021-09-07 03:29 UTC, bianpengyuan commented
This reverts https://github.com/istio/istio/pull/30878 cc @yangminzhu

2021-09-07 17:01 UTC, incfly commented
@yangminzhu any context on #30824 ? what issue we are trying to address there? if the default install succeed, the error only happens when human edit meshconfig occurs right? by that time, they could fix the invalid config via intervention.

2021-09-08 00:09 UTC, yangminzhu commented
> @yangminzhu any context on #30824 ? what issue we are trying to address there? if the default install succeed, the error only happens when human edit meshconfig occurs right? by that time, they could fix the invalid config via intervention.

This is to provide a smoother user experience, the user might be trying out multiple configs and some of them could be invalid transiently, we don't want to force the user to delete them unless the config is actually being used.

2021-09-08 00:14 UTC, yangminzhu requested changes
can we instead fix this directly in pilot/pkg/security/authz/builder/extauthz.go? We intentionally didn't want to block the user from a config that might not be actively used in the MeshConfig.

2021-09-09 08:54 UTC, devincd commented
> can we instead fix this directly in pilot/pkg/security/authz/builder/extauthz.go? We intentionally didn't want to block the user from a config that might not be actively used in the MeshConfig.

I try to fix.

2021-09-09 09:44 UTC, istio-testing commented
@devincd: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integ-pilot-multicluster-tests_istio | efb1f94f6f14aef9efa0ab29bbd5ea2d8f797ed2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/35002/integ-pilot-multicluster-tests_istio/1435896832818417664) | `/test integ-pilot-multicluster-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-09-09 10:47 UTC, devincd commented
/retest

2021-09-10 01:44 UTC, devincd commented
@yangminzhu Please take a look, thinks

2021-09-10 02:55 UTC, devincd commented on pilot/pkg/security/authz/builder/extauthz.go
> +			errValidation := validation.ValidateExtensionProviderEnvoyExtAuthzGRPC(p.EnvoyExtAuthzGrpc)
yes, this is more better.

2021-09-10 17:48 UTC, yangminzhu approved these changes
thanks!

2021-09-13 02:31 UTC, devincd commented
@hzxuzhonghu PTAL,thinks.

2021-09-20 16:07 UTC, howardjohn approved these changes

2021-09-20 16:56 UTC, merged