change iptables probe port to string
istio/istio pull request #35752
Opened 2021-10-27 08:35 UTC by zackzhangkai

1. Change port from int to string.
2. Fix some typo.

~~3. Fix grpc xds port . 15012 port is grpc xds port, instead of https-dns.~~

```bash
# kubectl -n istio-system get istiod -oyaml
...
  - name: https-dns
    port: 15012
    protocol: TCP
```

~~Reference this [doc](https://istio.io/latest/docs/ops/deployment/requirements/#ports-used-by-istio) to verify the port.~~

~~So I think the port name should be changed to `grpc-xds`~~

Signed-off-by: zackzhangkai <zhangkaiamm@gmail.com>

2021-10-27 16:36 UTC, howardjohn requested changes

2021-10-28 16:24 UTC, howardjohn approved these changes

2021-10-28 16:58 UTC, merged

2021-11-01 15:21 UTC, ericvn commented
Cherry pick to release-1.12?

2021-11-01 15:23 UTC, howardjohn commented
I think its just refactoring? So probably not important?

On Mon, Nov 1, 2021 at 8:21 AM Eric Van Norman ***@***.***>
wrote:

> Cherry pick to release-1.12?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/istio/pull/35752#issuecomment-956326716>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEYGXLC7TC3VHLUNQQWYUDUJ2WABANCNFSM5GZXQDPQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-01 15:50 UTC, ericvn commented
It fixes some spelling errors with got reverted in the 1.12 docs is why I asked.

2021-11-01 18:49 UTC, ericvn commented
/cherry-pick release-1.12

2021-11-01 18:50 UTC, istio-testing commented
@ericvn: new pull request created: #35816

<details>

In response to [this](https://github.com/istio/istio/pull/35752#issuecomment-956495856):

>/cherry-pick release-1.12


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>