Remove duplicate Grafana Pod port definition.
istio/istio pull request #36183
Opened 2021-11-20 22:05 UTC by mt-inside

Keep the one named "service" because that's what the port's called on the _Service_

**Please provide a description of this PR:**

Minor fix to the Grafana addon resources.
Note that while `kubectl` is happy to apply this, some systems' pre-checks (eg Flux 2) reject the file because of this error.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2021-11-20 22:05 UTC, istio-testing commented
Hi @mt-inside. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-11-21 03:25 UTC, mandarjog commented
/ok-to-test

2021-11-21 03:27 UTC, istio-testing commented
@mt-inside: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | d4bd6beb27f06124f3208f934f99edfebae21623 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/36183/release-notes_istio/1462260817457057792) | true | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-11-21 03:30 UTC, mandarjog commented
This seems reasonable @douglas-reid doo you know why we use same port with two names? Is another system looking for name “grafana”?

2021-11-22 16:23 UTC, howardjohn requested changes
While the change itself looks reasonable, we are generating this from helm chart: manifests/addons/gen.sh

My guess is the default is port 80+3000, and we want just 3000 for legacy reasons, which ends up duplicated.

2021-11-23 10:58 UTC, mt-inside commented
Ah I wasn't aware of that mechanism. This is a bit weirder than I expected.

Grafana with default config only listens on 3000, doesn't open 80. Verified with netstat after running docker.io/grafana/grafana:8.2.5 locally.

By default the helm chart causes the Deployment to declare port 3000 (hard-coded) AND port 80 ([source](https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/_pod.tpl#L316-L322)).
* Port number 3000 is hard-coded
* Port 80 comes from the Service part of the values object. This looks like a straight-up bug, a spurious copy-and-paste from the [Service definition](https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/service.yaml#L38-L40)

Sadly, getting the Service on 3000, as Istio needs, will always result in a duplicate 3000 port on the Deployment, because the value is re-used.

I've raised upstream: https://github.com/grafana/helm-charts/pull/844

Suggest we leave this bug open until they merge?

2022-01-07 05:04 UTC, closed without merging

2022-04-27 14:08 UTC, mt-inside commented
FYI I'm still chasing this error upstream with Grafana - it was closed without merge or comment but I've asked what the deal is.