gateway chart: support envoy's bootstrap configuration override
istio/istio pull request #36892
Opened 2022-01-19 15:15 UTC by ryodocx

I implemented gateway's HelmChart mostly about this article:
https://medium.com/@nizam./envoy-layered-runtime-configuration-override-ac3499f82f6f

After this change, we can configure additonal bootstrap configuration of EnvoyProxy.
In order to override admin setting, runtime configuration, and so on.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [x] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [s] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2022-01-19 15:15 UTC, istio-testing commented
Hi @ryodocx. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-01-19 15:17 UTC, zirain commented
/ok-to-test

@ryodocx please sign CLA

2022-01-19 15:19 UTC, istio-testing commented
@ryodocx: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 195407b48042947182ee438b79cf9d48a5fd0c68 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/36892/release-notes_istio/1483820887424634880) | true | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-01-19 15:22 UTC, howardjohn requested changes
Our intent has been to keep this helm chart fairly minimal - similar to the core of other popular charts and the output of `helm chart create`. I think this drifts a bit from that, and introduces substantial complexity to expose a super advanced use case, which is also not the long term implementation of this feature (we have an experimental BOOTSTRAP_XDS_AGENT mode which requests bootstrap from XDS, which can override this more appropriately).

I appreciate the effort put into this but I am not sure its the right path. I would recommend BOOTSTRAP_XDS_AGENT or using last mile customizations (https://tech.aabouzaid.com/2020/09/3-ways-to-customize-off-the-shelf-helm-charts-with-kustomize-kubernetes.html). Cheers

2022-01-22 02:26 UTC, ryodocx commented
@howardjohn Thank you!
`BOOTSTRAP_XDS_AGENT=true` was worked with EnvoyFilter (`applyTo: BOOTSTRAP`).
Can override Envoy's bootstrap configuration at will.
Close this PullRequest.

However, I found bug of HelmChart.
Charts can't accept boolean at env now (v1.12.2). 
I fixed it. If it appropriate, I make new PR.
https://github.com/ryodocx/istio/commit/0c0d702d15a71e4b1d4ce381a2cf3659672cc002

2022-01-22 02:26 UTC, closed without merging