chore: adds vanity import.
istio/istio pull request #37277
Opened 2022-02-10 21:42 UTC by jcchavezs

**Please provide a description of this PR:**

This PR adds vanity import to all Go files to make it easier to consume them and to search. All this codebase is hosted at github.com/istio/istio but consumed as istio.io/istio which isn't easy to find out.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2022-02-10 21:42 UTC, istio-testing commented
Hi @jcchavezs. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-02-10 21:46 UTC, howardjohn requested changes
Thanks for the PR. I don't see a compelling reason to do this, and have not seen it on a number of projects with vanity URLs.

The URL is clearly defined in `go.mod`. This comment syntax seems to be a legacy from old days (https://docs.google.com/document/d/1jVFkZTcYbNLaTxXD9OcGfn7vYv5hWtPx9--lTx1gPMs/edit) before go.mod.

IF we are going to do this, we certainly need automation to enforce + automatically do it. That being said, I don't think we should since I don't think it adds value nor is it an established best practice in the golang community (from what i have seen)

2022-02-12 01:17 UTC, Arhell reviewed
/ok-to-test

2022-02-12 01:18 UTC, istio-testing commented
@jcchavezs: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-telemetry-mc_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-telemetry-mc_istio/1492306811984809984) | true | `/test integ-telemetry-mc_istio`
integ-ipv6_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-ipv6_istio/1492306812093861888) | true | `/test integ-ipv6_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-02-12 01:18 UTC, istio-testing commented
@jcchavezs: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-telemetry-mc_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-telemetry-mc_istio/1492306811984809984) | true | `/test integ-telemetry-mc_istio`
integ-ipv6_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-ipv6_istio/1492306812093861888) | true | `/test integ-ipv6_istio`
integ-telemetry-istiodremote_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-telemetry-istiodremote_istio/1492306812026753024) | true | `/test integ-telemetry-istiodremote_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-02-12 01:18 UTC, istio-testing commented
@jcchavezs: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-telemetry-mc_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-telemetry-mc_istio/1492306811984809984) | true | `/test integ-telemetry-mc_istio`
integ-ipv6_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-ipv6_istio/1492306812093861888) | true | `/test integ-ipv6_istio`
integ-telemetry-istiodremote_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-telemetry-istiodremote_istio/1492306812026753024) | true | `/test integ-telemetry-istiodremote_istio`
integ-pilot-multicluster_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-pilot-multicluster_istio/1492306812391657472) | true | `/test integ-pilot-multicluster_istio`
integ-cni_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-cni_istio/1492306811917701120) | true | `/test integ-cni_istio`
integ-telemetry_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-telemetry_istio/1492306811955449856) | true | `/test integ-telemetry_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-02-12 01:18 UTC, istio-testing commented
@jcchavezs: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-telemetry-mc_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-telemetry-mc_istio/1492306811984809984) | true | `/test integ-telemetry-mc_istio`
integ-ipv6_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-ipv6_istio/1492306812093861888) | true | `/test integ-ipv6_istio`
integ-telemetry-istiodremote_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-telemetry-istiodremote_istio/1492306812026753024) | true | `/test integ-telemetry-istiodremote_istio`
integ-pilot-multicluster_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-pilot-multicluster_istio/1492306812391657472) | true | `/test integ-pilot-multicluster_istio`
integ-cni_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-cni_istio/1492306811917701120) | true | `/test integ-cni_istio`
integ-telemetry_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-telemetry_istio/1492306811955449856) | true | `/test integ-telemetry_istio`
integ-helm_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-helm_istio/1492306816925700096) | true | `/test integ-helm_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-02-12 01:18 UTC, istio-testing commented
@jcchavezs: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-telemetry-mc_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-telemetry-mc_istio/1492306811984809984) | true | `/test integ-telemetry-mc_istio`
integ-ipv6_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-ipv6_istio/1492306812093861888) | true | `/test integ-ipv6_istio`
integ-telemetry-istiodremote_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-telemetry-istiodremote_istio/1492306812026753024) | true | `/test integ-telemetry-istiodremote_istio`
integ-pilot-multicluster_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-pilot-multicluster_istio/1492306812391657472) | true | `/test integ-pilot-multicluster_istio`
integ-cni_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-cni_istio/1492306811917701120) | true | `/test integ-cni_istio`
integ-telemetry_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-telemetry_istio/1492306811955449856) | true | `/test integ-telemetry_istio`
integ-helm_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-helm_istio/1492306816925700096) | true | `/test integ-helm_istio`
release-test_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/release-test_istio/1492306811892535296) | true | `/test release-test_istio`
integ-distroless_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-distroless_istio/1492306812056113152) | true | `/test integ-distroless_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-02-12 01:18 UTC, istio-testing commented
@jcchavezs: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-telemetry-mc_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-telemetry-mc_istio/1492306811984809984) | true | `/test integ-telemetry-mc_istio`
integ-ipv6_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-ipv6_istio/1492306812093861888) | true | `/test integ-ipv6_istio`
integ-telemetry-istiodremote_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-telemetry-istiodremote_istio/1492306812026753024) | true | `/test integ-telemetry-istiodremote_istio`
integ-pilot-multicluster_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-pilot-multicluster_istio/1492306812391657472) | true | `/test integ-pilot-multicluster_istio`
integ-cni_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-cni_istio/1492306811917701120) | true | `/test integ-cni_istio`
integ-telemetry_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-telemetry_istio/1492306811955449856) | true | `/test integ-telemetry_istio`
integ-helm_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-helm_istio/1492306816925700096) | true | `/test integ-helm_istio`
release-test_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/release-test_istio/1492306811892535296) | true | `/test release-test_istio`
integ-distroless_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-distroless_istio/1492306812056113152) | true | `/test integ-distroless_istio`
integ-security_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-security_istio/1492306814417506304) | true | `/test integ-security_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-02-12 01:18 UTC, istio-testing commented
@jcchavezs: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-telemetry-mc_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-telemetry-mc_istio/1492306811984809984) | true | `/test integ-telemetry-mc_istio`
integ-ipv6_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-ipv6_istio/1492306812093861888) | true | `/test integ-ipv6_istio`
integ-telemetry-istiodremote_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-telemetry-istiodremote_istio/1492306812026753024) | true | `/test integ-telemetry-istiodremote_istio`
integ-pilot-multicluster_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-pilot-multicluster_istio/1492306812391657472) | true | `/test integ-pilot-multicluster_istio`
integ-cni_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-cni_istio/1492306811917701120) | true | `/test integ-cni_istio`
integ-telemetry_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-telemetry_istio/1492306811955449856) | true | `/test integ-telemetry_istio`
integ-helm_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-helm_istio/1492306816925700096) | true | `/test integ-helm_istio`
release-test_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/release-test_istio/1492306811892535296) | true | `/test release-test_istio`
integ-distroless_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-distroless_istio/1492306812056113152) | true | `/test integ-distroless_istio`
integ-security_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-security_istio/1492306814417506304) | true | `/test integ-security_istio`
integ-operator-controller_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-operator-controller_istio/1492306812131610624) | true | `/test integ-operator-controller_istio`
unit-tests_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/unit-tests_istio/1492306811854786560) | true | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-02-12 01:18 UTC, istio-testing commented
@jcchavezs: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-telemetry-mc_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-telemetry-mc_istio/1492306811984809984) | true | `/test integ-telemetry-mc_istio`
integ-ipv6_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-ipv6_istio/1492306812093861888) | true | `/test integ-ipv6_istio`
integ-telemetry-istiodremote_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-telemetry-istiodremote_istio/1492306812026753024) | true | `/test integ-telemetry-istiodremote_istio`
integ-pilot-multicluster_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-pilot-multicluster_istio/1492306812391657472) | true | `/test integ-pilot-multicluster_istio`
integ-cni_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-cni_istio/1492306811917701120) | true | `/test integ-cni_istio`
integ-telemetry_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-telemetry_istio/1492306811955449856) | true | `/test integ-telemetry_istio`
integ-helm_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-helm_istio/1492306816925700096) | true | `/test integ-helm_istio`
release-test_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/release-test_istio/1492306811892535296) | true | `/test release-test_istio`
integ-distroless_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-distroless_istio/1492306812056113152) | true | `/test integ-distroless_istio`
integ-security_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-security_istio/1492306814417506304) | true | `/test integ-security_istio`
integ-operator-controller_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-operator-controller_istio/1492306812131610624) | true | `/test integ-operator-controller_istio`
unit-tests_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/unit-tests_istio/1492306811854786560) | true | `/test unit-tests_istio`
integ-pilot_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-pilot_istio/1492306812173553664) | true | `/test integ-pilot_istio`
integ-pilot-istiodremote-mc_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-pilot-istiodremote-mc_istio/1492306813570256896) | true | `/test integ-pilot-istiodremote-mc_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-02-12 01:18 UTC, istio-testing commented
@jcchavezs: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-telemetry-mc_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-telemetry-mc_istio/1492306811984809984) | true | `/test integ-telemetry-mc_istio`
integ-ipv6_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-ipv6_istio/1492306812093861888) | true | `/test integ-ipv6_istio`
integ-telemetry-istiodremote_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-telemetry-istiodremote_istio/1492306812026753024) | true | `/test integ-telemetry-istiodremote_istio`
integ-pilot-multicluster_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-pilot-multicluster_istio/1492306812391657472) | true | `/test integ-pilot-multicluster_istio`
integ-cni_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-cni_istio/1492306811917701120) | true | `/test integ-cni_istio`
integ-telemetry_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-telemetry_istio/1492306811955449856) | true | `/test integ-telemetry_istio`
integ-helm_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-helm_istio/1492306816925700096) | true | `/test integ-helm_istio`
release-test_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/release-test_istio/1492306811892535296) | true | `/test release-test_istio`
integ-distroless_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-distroless_istio/1492306812056113152) | true | `/test integ-distroless_istio`
integ-security_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-security_istio/1492306814417506304) | true | `/test integ-security_istio`
integ-operator-controller_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-operator-controller_istio/1492306812131610624) | true | `/test integ-operator-controller_istio`
unit-tests_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/unit-tests_istio/1492306811854786560) | true | `/test unit-tests_istio`
integ-pilot_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-pilot_istio/1492306812173553664) | true | `/test integ-pilot_istio`
integ-pilot-istiodremote-mc_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-pilot-istiodremote-mc_istio/1492306813570256896) | true | `/test integ-pilot-istiodremote-mc_istio`
analyze-tests_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/analyze-tests_istio/1492306817764560896) | true | `/test analyze-tests_istio`
integ-security-multicluster_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-security-multicluster_istio/1492306815252172800) | true | `/test integ-security-multicluster_istio`
integ-pilot-istiodremote_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-pilot-istiodremote_istio/1492306812731396096) | true | `/test integ-pilot-istiodremote_istio`
gencheck_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/gencheck_istio/1492306819442282496) | true | `/test gencheck_istio`
integ-security-istiodremote_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-security-istiodremote_istio/1492306816091033600) | true | `/test integ-security-istiodremote_istio`
release-notes_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/release-notes_istio/1492306820289531904) | true | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-02-12 01:18 UTC, istio-testing commented
@jcchavezs: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-telemetry-mc_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-telemetry-mc_istio/1492306811984809984) | true | `/test integ-telemetry-mc_istio`
integ-ipv6_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-ipv6_istio/1492306812093861888) | true | `/test integ-ipv6_istio`
integ-telemetry-istiodremote_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-telemetry-istiodremote_istio/1492306812026753024) | true | `/test integ-telemetry-istiodremote_istio`
integ-pilot-multicluster_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-pilot-multicluster_istio/1492306812391657472) | true | `/test integ-pilot-multicluster_istio`
integ-cni_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-cni_istio/1492306811917701120) | true | `/test integ-cni_istio`
integ-telemetry_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-telemetry_istio/1492306811955449856) | true | `/test integ-telemetry_istio`
integ-helm_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-helm_istio/1492306816925700096) | true | `/test integ-helm_istio`
release-test_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/release-test_istio/1492306811892535296) | true | `/test release-test_istio`
integ-distroless_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-distroless_istio/1492306812056113152) | true | `/test integ-distroless_istio`
integ-security_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-security_istio/1492306814417506304) | true | `/test integ-security_istio`
integ-operator-controller_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-operator-controller_istio/1492306812131610624) | true | `/test integ-operator-controller_istio`
unit-tests_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/unit-tests_istio/1492306811854786560) | true | `/test unit-tests_istio`
integ-pilot_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-pilot_istio/1492306812173553664) | true | `/test integ-pilot_istio`
integ-pilot-istiodremote-mc_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-pilot-istiodremote-mc_istio/1492306813570256896) | true | `/test integ-pilot-istiodremote-mc_istio`
analyze-tests_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/analyze-tests_istio/1492306817764560896) | true | `/test analyze-tests_istio`
integ-security-multicluster_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-security-multicluster_istio/1492306815252172800) | true | `/test integ-security-multicluster_istio`
integ-pilot-istiodremote_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-pilot-istiodremote_istio/1492306812731396096) | true | `/test integ-pilot-istiodremote_istio`
gencheck_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/gencheck_istio/1492306819442282496) | true | `/test gencheck_istio`
integ-security-istiodremote_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/integ-security-istiodremote_istio/1492306816091033600) | true | `/test integ-security-istiodremote_istio`
release-notes_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/release-notes_istio/1492306820289531904) | true | `/test release-notes_istio`
lint_istio | 91c7d62ec9c9cd940c125a11cf58f71f0bd11c4d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37277/lint_istio/1492306818603421696) | true | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-02-12 22:07 UTC, istio-testing commented
@jcchavezs: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-03-29 05:04 UTC, closed without merging