[WIP] Verifiable Configuration - manage the integrity of the Istio service mesh policies
istio/istio pull request #37634
Opened 2022-03-01 18:59 UTC by cmadam

Manage the integrity of the Istio service mesh policies by using a signing service to verify their authenticity.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2022-03-01 18:59 UTC, istio-testing commented
Hi @cmadam. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-03-01 19:35 UTC, howardjohn requested changes
This is the first I am hearing of this. Can you present a design doc to the WG before moving forward with an implementation?

2022-03-01 21:11 UTC, cmadam commented
> This is the first I am hearing of this. Can you present a design doc to the WG before moving forward with an implementation?

Yes, absolutely, I will present an RFC document to the WG.  My colleague, Mariam John, has added me to the agenda this week.

2022-03-08 22:05 UTC, istio-testing commented
@cmadam: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-04-16 05:04 UTC, closed without merging