`istio-start.sh clean` always try to clean the Istio iptables chains
istio/istio pull request #37702
Opened 2022-03-03 22:32 UTC by qudongfang

**Please provide a description of this PR:**

This PR resolves https://github.com/istio/istio/issues/37700

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [x] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2022-03-03 22:33 UTC, istio-testing commented
Hi @qudongfang. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-03-07 22:59 UTC, ericvn commented
/ok-to-test

2022-04-04 22:06 UTC, jacob-delgado commented
LGTM, but I don't know the history of this PR. Any @istio/wg-networking-maintainers have thoughts? If anyone approves then I'll sign it for T&R

2022-04-11 16:37 UTC, howardjohn requested changes
This also means if I have custom iptables and istio-clean-iptables happens to match on similar names they will no no longer work. This seems like it could cause a regression for some users

2022-05-27 05:03 UTC, closed without merging