Update the clusterMatch port match condition
istio/istio pull request #37979
Opened 2022-03-17 06:04 UTC by xichengliudui

**Please provide a description of this PR:**
```go
// FIXME: Ports on a cluster can be 0. the API only takes uint32 for ports
```
the cluster port can be set to ，so update the match condition

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [x] Networking

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2022-03-17 06:04 UTC, istio-testing commented
Hi @xichengliudui. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-03-17 17:20 UTC, howardjohn requested changes
I don't think this will work since we cannot distinguish between unset and 0

2022-03-18 13:23 UTC, Arhell reviewed
/ok-to-test

2022-03-18 13:28 UTC, istio-testing commented
@xichengliudui: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/unit-tests_istio/1504810779893829632) | true | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-18 13:32 UTC, istio-testing commented
@xichengliudui: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/unit-tests_istio/1504810779893829632) | true | `/test unit-tests_istio`
integ-ipv6_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-ipv6_istio/1504810780179042304) | true | `/test integ-ipv6_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-18 13:34 UTC, istio-testing commented
@xichengliudui: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/unit-tests_istio/1504810779893829632) | true | `/test unit-tests_istio`
integ-ipv6_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-ipv6_istio/1504810780179042304) | true | `/test integ-ipv6_istio`
integ-distroless_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-distroless_istio/1504810780137099264) | true | `/test integ-distroless_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-18 13:40 UTC, istio-testing commented
@xichengliudui: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/unit-tests_istio/1504810779893829632) | true | `/test unit-tests_istio`
integ-ipv6_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-ipv6_istio/1504810780179042304) | true | `/test integ-ipv6_istio`
integ-distroless_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-distroless_istio/1504810780137099264) | true | `/test integ-distroless_istio`
integ-pilot-multicluster_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-pilot-multicluster_istio/1504810780728496128) | true | `/test integ-pilot-multicluster_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-18 13:42 UTC, istio-testing commented
@xichengliudui: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/unit-tests_istio/1504810779893829632) | true | `/test unit-tests_istio`
integ-ipv6_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-ipv6_istio/1504810780179042304) | true | `/test integ-ipv6_istio`
integ-distroless_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-distroless_istio/1504810780137099264) | true | `/test integ-distroless_istio`
integ-pilot-multicluster_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-pilot-multicluster_istio/1504810780728496128) | true | `/test integ-pilot-multicluster_istio`
integ-pilot-istiodremote_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-pilot-istiodremote_istio/1504810781533802496) | true | `/test integ-pilot-istiodremote_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-18 13:44 UTC, istio-testing commented
@xichengliudui: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/unit-tests_istio/1504810779893829632) | true | `/test unit-tests_istio`
integ-ipv6_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-ipv6_istio/1504810780179042304) | true | `/test integ-ipv6_istio`
integ-distroless_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-distroless_istio/1504810780137099264) | true | `/test integ-distroless_istio`
integ-pilot-multicluster_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-pilot-multicluster_istio/1504810780728496128) | true | `/test integ-pilot-multicluster_istio`
integ-pilot-istiodremote_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-pilot-istiodremote_istio/1504810781533802496) | true | `/test integ-pilot-istiodremote_istio`
integ-pilot_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-pilot_istio/1504810780304871424) | true | `/test integ-pilot_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-18 13:45 UTC, istio-testing commented
@xichengliudui: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/unit-tests_istio/1504810779893829632) | true | `/test unit-tests_istio`
integ-ipv6_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-ipv6_istio/1504810780179042304) | true | `/test integ-ipv6_istio`
integ-distroless_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-distroless_istio/1504810780137099264) | true | `/test integ-distroless_istio`
integ-pilot-multicluster_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-pilot-multicluster_istio/1504810780728496128) | true | `/test integ-pilot-multicluster_istio`
integ-pilot-istiodremote_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-pilot-istiodremote_istio/1504810781533802496) | true | `/test integ-pilot-istiodremote_istio`
integ-pilot_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-pilot_istio/1504810780304871424) | true | `/test integ-pilot_istio`
integ-pilot-istiodremote-mc_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-pilot-istiodremote-mc_istio/1504810782368468992) | true | `/test integ-pilot-istiodremote-mc_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-18 13:46 UTC, istio-testing commented
@xichengliudui: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/unit-tests_istio/1504810779893829632) | true | `/test unit-tests_istio`
integ-ipv6_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-ipv6_istio/1504810780179042304) | true | `/test integ-ipv6_istio`
integ-distroless_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-distroless_istio/1504810780137099264) | true | `/test integ-distroless_istio`
integ-pilot-multicluster_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-pilot-multicluster_istio/1504810780728496128) | true | `/test integ-pilot-multicluster_istio`
integ-pilot-istiodremote_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-pilot-istiodremote_istio/1504810781533802496) | true | `/test integ-pilot-istiodremote_istio`
integ-pilot_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-pilot_istio/1504810780304871424) | true | `/test integ-pilot_istio`
integ-pilot-istiodremote-mc_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-pilot-istiodremote-mc_istio/1504810782368468992) | true | `/test integ-pilot-istiodremote-mc_istio`
integ-cni_istio | 37d2867acfd9a701a0bede90ba3281193f6c4994 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37979/integ-cni_istio/1504810779977715712) | true | `/test integ-cni_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-21 01:33 UTC, xichengliudui commented
> I don't think this will work since we cannot distinguish between unset and 0

If cannot distinguish between unset and 0, I will turn off pr

2022-03-21 01:33 UTC, closed without merging