Generate grpc bootstrap only when DISABLE_ENVOY=true and GRPC_XDS_BOO…
istio/istio pull request #37996
Opened 2022-03-18 06:12 UTC by hzxuzhonghu

…TSTRAP set

**Please provide a description of this PR:**

Without this, it always generate grpc bootstrap for sidecar.

```
k exec -ti sleep-557747455f-n4lf8 -c istio-proxy -- ls etc/istio/proxy/
SDS  XDS  envoy-rev0.json  grpc-bootstrap.json

```

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2022-03-18 06:15 UTC, istio-testing commented
@hzxuzhonghu: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/release-notes_istio/1504702332401618944) | true | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-18 06:31 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/release-notes_istio/1504702332401618944) | true | `/test release-notes_istio`
integ-helm_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-helm_istio/1504702329041981440) | true | `/test integ-helm_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-18 06:37 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/release-notes_istio/1504702332401618944) | true | `/test release-notes_istio`
integ-helm_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-helm_istio/1504702329041981440) | true | `/test integ-helm_istio`
integ-ipv6_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-ipv6_istio/1504702323480334336) | true | `/test integ-ipv6_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-18 06:37 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/release-notes_istio/1504702332401618944) | true | `/test release-notes_istio`
integ-helm_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-helm_istio/1504702329041981440) | true | `/test integ-helm_istio`
integ-ipv6_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-ipv6_istio/1504702323480334336) | true | `/test integ-ipv6_istio`
integ-distroless_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-distroless_istio/1504702323442585600) | true | `/test integ-distroless_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-18 06:37 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/release-notes_istio/1504702332401618944) | true | `/test release-notes_istio`
integ-helm_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-helm_istio/1504702329041981440) | true | `/test integ-helm_istio`
integ-ipv6_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-ipv6_istio/1504702323480334336) | true | `/test integ-ipv6_istio`
integ-distroless_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-distroless_istio/1504702323442585600) | true | `/test integ-distroless_istio`
integ-pilot-istiodremote_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-istiodremote_istio/1504702324847677440) | true | `/test integ-pilot-istiodremote_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-18 06:39 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/release-notes_istio/1504702332401618944) | true | `/test release-notes_istio`
integ-helm_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-helm_istio/1504702329041981440) | true | `/test integ-helm_istio`
integ-ipv6_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-ipv6_istio/1504702323480334336) | true | `/test integ-ipv6_istio`
integ-distroless_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-distroless_istio/1504702323442585600) | true | `/test integ-distroless_istio`
integ-pilot-istiodremote_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-istiodremote_istio/1504702324847677440) | true | `/test integ-pilot-istiodremote_istio`
integ-pilot-multicluster_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-multicluster_istio/1504702324017205248) | true | `/test integ-pilot-multicluster_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-18 06:44 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/release-notes_istio/1504702332401618944) | true | `/test release-notes_istio`
integ-helm_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-helm_istio/1504702329041981440) | true | `/test integ-helm_istio`
integ-ipv6_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-ipv6_istio/1504702323480334336) | true | `/test integ-ipv6_istio`
integ-distroless_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-distroless_istio/1504702323442585600) | true | `/test integ-distroless_istio`
integ-pilot-istiodremote_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-istiodremote_istio/1504702324847677440) | true | `/test integ-pilot-istiodremote_istio`
integ-pilot-multicluster_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-multicluster_istio/1504702324017205248) | true | `/test integ-pilot-multicluster_istio`
integ-pilot-istiodremote-mc_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-istiodremote-mc_istio/1504702325682343936) | true | `/test integ-pilot-istiodremote-mc_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-18 06:46 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/release-notes_istio/1504702332401618944) | true | `/test release-notes_istio`
integ-helm_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-helm_istio/1504702329041981440) | true | `/test integ-helm_istio`
integ-ipv6_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-ipv6_istio/1504702323480334336) | true | `/test integ-ipv6_istio`
integ-distroless_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-distroless_istio/1504702323442585600) | true | `/test integ-distroless_istio`
integ-pilot-istiodremote_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-istiodremote_istio/1504702324847677440) | true | `/test integ-pilot-istiodremote_istio`
integ-pilot-multicluster_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-multicluster_istio/1504702324017205248) | true | `/test integ-pilot-multicluster_istio`
integ-pilot-istiodremote-mc_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-istiodremote-mc_istio/1504702325682343936) | true | `/test integ-pilot-istiodremote-mc_istio`
integ-operator-controller_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-operator-controller_istio/1504702323522277376) | true | `/test integ-operator-controller_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-18 06:58 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/release-notes_istio/1504702332401618944) | true | `/test release-notes_istio`
integ-helm_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-helm_istio/1504702329041981440) | true | `/test integ-helm_istio`
integ-ipv6_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-ipv6_istio/1504702323480334336) | true | `/test integ-ipv6_istio`
integ-distroless_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-distroless_istio/1504702323442585600) | true | `/test integ-distroless_istio`
integ-pilot-istiodremote_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-istiodremote_istio/1504702324847677440) | true | `/test integ-pilot-istiodremote_istio`
integ-pilot-multicluster_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-multicluster_istio/1504702324017205248) | true | `/test integ-pilot-multicluster_istio`
integ-pilot-istiodremote-mc_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-istiodremote-mc_istio/1504702325682343936) | true | `/test integ-pilot-istiodremote-mc_istio`
integ-operator-controller_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-operator-controller_istio/1504702323522277376) | true | `/test integ-operator-controller_istio`
integ-pilot_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot_istio/1504702323555831808) | true | `/test integ-pilot_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-18 06:58 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/release-notes_istio/1504702332401618944) | true | `/test release-notes_istio`
integ-helm_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-helm_istio/1504702329041981440) | true | `/test integ-helm_istio`
integ-ipv6_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-ipv6_istio/1504702323480334336) | true | `/test integ-ipv6_istio`
integ-distroless_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-distroless_istio/1504702323442585600) | true | `/test integ-distroless_istio`
integ-pilot-istiodremote_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-istiodremote_istio/1504702324847677440) | true | `/test integ-pilot-istiodremote_istio`
integ-pilot-multicluster_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-multicluster_istio/1504702324017205248) | true | `/test integ-pilot-multicluster_istio`
integ-pilot-istiodremote-mc_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-istiodremote-mc_istio/1504702325682343936) | true | `/test integ-pilot-istiodremote-mc_istio`
integ-operator-controller_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-operator-controller_istio/1504702323522277376) | true | `/test integ-operator-controller_istio`
integ-pilot_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot_istio/1504702323555831808) | true | `/test integ-pilot_istio`
integ-cni_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-cni_istio/1504702323287396352) | true | `/test integ-cni_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-18 07:00 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/release-notes_istio/1504702332401618944) | true | `/test release-notes_istio`
integ-helm_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-helm_istio/1504702329041981440) | true | `/test integ-helm_istio`
integ-ipv6_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-ipv6_istio/1504702323480334336) | true | `/test integ-ipv6_istio`
integ-distroless_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-distroless_istio/1504702323442585600) | true | `/test integ-distroless_istio`
integ-pilot-istiodremote_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-istiodremote_istio/1504702324847677440) | true | `/test integ-pilot-istiodremote_istio`
integ-pilot-multicluster_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-multicluster_istio/1504702324017205248) | true | `/test integ-pilot-multicluster_istio`
integ-pilot-istiodremote-mc_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-istiodremote-mc_istio/1504702325682343936) | true | `/test integ-pilot-istiodremote-mc_istio`
integ-operator-controller_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-operator-controller_istio/1504702323522277376) | true | `/test integ-operator-controller_istio`
integ-pilot_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot_istio/1504702323555831808) | true | `/test integ-pilot_istio`
integ-cni_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-cni_istio/1504702323287396352) | true | `/test integ-cni_istio`
integ-security-multicluster_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-security-multicluster_istio/1504702327364259840) | true | `/test integ-security-multicluster_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-18 07:03 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/release-notes_istio/1504702332401618944) | true | `/test release-notes_istio`
integ-helm_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-helm_istio/1504702329041981440) | true | `/test integ-helm_istio`
integ-ipv6_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-ipv6_istio/1504702323480334336) | true | `/test integ-ipv6_istio`
integ-distroless_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-distroless_istio/1504702323442585600) | true | `/test integ-distroless_istio`
integ-pilot-istiodremote_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-istiodremote_istio/1504702324847677440) | true | `/test integ-pilot-istiodremote_istio`
integ-pilot-multicluster_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-multicluster_istio/1504702324017205248) | true | `/test integ-pilot-multicluster_istio`
integ-pilot-istiodremote-mc_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-istiodremote-mc_istio/1504702325682343936) | true | `/test integ-pilot-istiodremote-mc_istio`
integ-operator-controller_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-operator-controller_istio/1504702323522277376) | true | `/test integ-operator-controller_istio`
integ-pilot_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot_istio/1504702323555831808) | true | `/test integ-pilot_istio`
integ-cni_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-cni_istio/1504702323287396352) | true | `/test integ-cni_istio`
integ-security-multicluster_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-security-multicluster_istio/1504702327364259840) | true | `/test integ-security-multicluster_istio`
integ-security-istiodremote_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-security-istiodremote_istio/1504702328207314944) | true | `/test integ-security-istiodremote_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-18 07:20 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/release-notes_istio/1504702332401618944) | true | `/test release-notes_istio`
integ-helm_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-helm_istio/1504702329041981440) | true | `/test integ-helm_istio`
integ-ipv6_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-ipv6_istio/1504702323480334336) | true | `/test integ-ipv6_istio`
integ-distroless_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-distroless_istio/1504702323442585600) | true | `/test integ-distroless_istio`
integ-pilot-istiodremote_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-istiodremote_istio/1504702324847677440) | true | `/test integ-pilot-istiodremote_istio`
integ-pilot-multicluster_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-multicluster_istio/1504702324017205248) | true | `/test integ-pilot-multicluster_istio`
integ-pilot-istiodremote-mc_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-istiodremote-mc_istio/1504702325682343936) | true | `/test integ-pilot-istiodremote-mc_istio`
integ-operator-controller_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-operator-controller_istio/1504702323522277376) | true | `/test integ-operator-controller_istio`
integ-pilot_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot_istio/1504702323555831808) | true | `/test integ-pilot_istio`
integ-cni_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-cni_istio/1504702323287396352) | true | `/test integ-cni_istio`
integ-security-multicluster_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-security-multicluster_istio/1504702327364259840) | true | `/test integ-security-multicluster_istio`
integ-security-istiodremote_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-security-istiodremote_istio/1504702328207314944) | true | `/test integ-security-istiodremote_istio`
integ-security_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-security_istio/1504702326529593344) | true | `/test integ-security_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-18 07:23 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/release-notes_istio/1504702332401618944) | true | `/test release-notes_istio`
integ-helm_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-helm_istio/1504702329041981440) | true | `/test integ-helm_istio`
integ-ipv6_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-ipv6_istio/1504702323480334336) | true | `/test integ-ipv6_istio`
integ-distroless_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-distroless_istio/1504702323442585600) | true | `/test integ-distroless_istio`
integ-pilot-istiodremote_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-istiodremote_istio/1504702324847677440) | true | `/test integ-pilot-istiodremote_istio`
integ-pilot-multicluster_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-multicluster_istio/1504702324017205248) | true | `/test integ-pilot-multicluster_istio`
integ-pilot-istiodremote-mc_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-istiodremote-mc_istio/1504702325682343936) | true | `/test integ-pilot-istiodremote-mc_istio`
integ-operator-controller_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-operator-controller_istio/1504702323522277376) | true | `/test integ-operator-controller_istio`
integ-pilot_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot_istio/1504702323555831808) | true | `/test integ-pilot_istio`
integ-cni_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-cni_istio/1504702323287396352) | true | `/test integ-cni_istio`
integ-security-multicluster_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-security-multicluster_istio/1504702327364259840) | true | `/test integ-security-multicluster_istio`
integ-security-istiodremote_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-security-istiodremote_istio/1504702328207314944) | true | `/test integ-security-istiodremote_istio`
integ-security_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-security_istio/1504702326529593344) | true | `/test integ-security_istio`
integ-telemetry-mc_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-telemetry-mc_istio/1504702323367088128) | true | `/test integ-telemetry-mc_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-18 07:30 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/release-notes_istio/1504702332401618944) | true | `/test release-notes_istio`
integ-helm_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-helm_istio/1504702329041981440) | true | `/test integ-helm_istio`
integ-ipv6_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-ipv6_istio/1504702323480334336) | true | `/test integ-ipv6_istio`
integ-distroless_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-distroless_istio/1504702323442585600) | true | `/test integ-distroless_istio`
integ-pilot-istiodremote_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-istiodremote_istio/1504702324847677440) | true | `/test integ-pilot-istiodremote_istio`
integ-pilot-multicluster_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-multicluster_istio/1504702324017205248) | true | `/test integ-pilot-multicluster_istio`
integ-pilot-istiodremote-mc_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-istiodremote-mc_istio/1504702325682343936) | true | `/test integ-pilot-istiodremote-mc_istio`
integ-operator-controller_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-operator-controller_istio/1504702323522277376) | true | `/test integ-operator-controller_istio`
integ-pilot_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot_istio/1504702323555831808) | true | `/test integ-pilot_istio`
integ-cni_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-cni_istio/1504702323287396352) | true | `/test integ-cni_istio`
integ-security-multicluster_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-security-multicluster_istio/1504702327364259840) | true | `/test integ-security-multicluster_istio`
integ-security-istiodremote_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-security-istiodremote_istio/1504702328207314944) | true | `/test integ-security-istiodremote_istio`
integ-security_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-security_istio/1504702326529593344) | true | `/test integ-security_istio`
integ-telemetry-mc_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-telemetry-mc_istio/1504702323367088128) | true | `/test integ-telemetry-mc_istio`
integ-telemetry_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-telemetry_istio/1504702323329339392) | true | `/test integ-telemetry_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-18 07:30 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/release-notes_istio/1504702332401618944) | true | `/test release-notes_istio`
integ-helm_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-helm_istio/1504702329041981440) | true | `/test integ-helm_istio`
integ-ipv6_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-ipv6_istio/1504702323480334336) | true | `/test integ-ipv6_istio`
integ-distroless_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-distroless_istio/1504702323442585600) | true | `/test integ-distroless_istio`
integ-pilot-istiodremote_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-istiodremote_istio/1504702324847677440) | true | `/test integ-pilot-istiodremote_istio`
integ-pilot-multicluster_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-multicluster_istio/1504702324017205248) | true | `/test integ-pilot-multicluster_istio`
integ-pilot-istiodremote-mc_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot-istiodremote-mc_istio/1504702325682343936) | true | `/test integ-pilot-istiodremote-mc_istio`
integ-operator-controller_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-operator-controller_istio/1504702323522277376) | true | `/test integ-operator-controller_istio`
integ-pilot_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-pilot_istio/1504702323555831808) | true | `/test integ-pilot_istio`
integ-cni_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-cni_istio/1504702323287396352) | true | `/test integ-cni_istio`
integ-security-multicluster_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-security-multicluster_istio/1504702327364259840) | true | `/test integ-security-multicluster_istio`
integ-security-istiodremote_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-security-istiodremote_istio/1504702328207314944) | true | `/test integ-security-istiodremote_istio`
integ-security_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-security_istio/1504702326529593344) | true | `/test integ-security_istio`
integ-telemetry-mc_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-telemetry-mc_istio/1504702323367088128) | true | `/test integ-telemetry-mc_istio`
integ-telemetry_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-telemetry_istio/1504702323329339392) | true | `/test integ-telemetry_istio`
integ-telemetry-istiodremote_istio | 2caae6a0b91150b74086552554e39d5418d3d656 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37996/integ-telemetry-istiodremote_istio/1504702323396448256) | true | `/test integ-telemetry-istiodremote_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-18 17:40 UTC, stevenctl requested changes
This is intentional. If the application sets the bootstrap env it will pickup the bootstrap without needing to modify istio settings.

2022-03-21 02:39 UTC, hzxuzhonghu commented
Not sure the default setting though

2022-03-21 16:55 UTC, stevenctl commented
> Not sure the default setting though

The default setting of what? 

Also we can't have `only when DISABLE_ENVOY`; It's possible to have envoy enabled and exclude some gRPC ports from capture. That way if a Pod runs some regular TCP/HTTP stuff + gRPC, we can still use Envoy for non-grpc traffic.

2022-03-22 06:20 UTC, hzxuzhonghu commented
>The default setting of what?

The xds bootstrap env is not empty. 

The use case sounds very weird,

2022-03-23 04:52 UTC, stevenctl commented
This usecase has been cited by @costinm in the past. 

I don't really see the negative impact in generating the bootstrap. We don't have the actual env set, so the gRPC library won't actually use it unless the user modifies their app container to do so.

2022-03-25 20:55 UTC, costinm commented
The use case is an app that is using both proxyless gRPC and TCP/HTTP services with Envoy sidecar. 

Note that we are looking at other ways to generate the bootstrap - possibly as a library that can be linked to the app itself, so we may be able to remove this, but let's keep it until we have a replacement.

2022-03-26 01:16 UTC, hzxuzhonghu commented
SGTM

2022-03-26 01:16 UTC, closed without merging