chore: fixes httpbin yaml samples.
istio/istio pull request #38114
Opened 2022-03-24 19:24 UTC by jcchavezs

**Please provide a description of this PR:**

YAML files aren't right when it comes to identation, for example simply running kubectl apply -f https://github.com/istio/istio/blob/master/samples/httpbin/httpbin-gateway.yaml would return an error 'error converting YAML to JSON: yaml: line 25: mapping values are not allowed in this context' which can be fixed if the list values have the right identation.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2022-03-24 19:25 UTC, istio-testing commented
Hi @jcchavezs. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-03-24 20:34 UTC, frankbu reviewed
I'm not sure changing this one sample makes sense, since the formatting of every other one of our samples will also have the same issue. When we use the raw version of the file, it works fine: https://raw.githubusercontent.com/istio/istio/master/samples/httpbin/httpbin-gateway.yaml

2022-03-25 00:32 UTC, jcchavezs commented
I can change all samples or even better lint all yaml files in this repo
and have a check on CI. How does that look like?

tor. 24. mar. 2022, 21:34 skrev Frank Budinsky ***@***.***>:

> ***@***.**** commented on this pull request.
>
> I'm not sure changing this one sample makes sense, since the formatting of
> every other one of our samples will also have the same issue. When we use
> the raw version of the file, it works fine:
> https://raw.githubusercontent.com/istio/istio/master/samples/httpbin/httpbin-gateway.yaml
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/istio/pull/38114#pullrequestreview-920853644>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAXOYAQZR6L5G354S5GT533VBTGVRANCNFSM5RSC2APA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-28 15:36 UTC, howardjohn requested changes
The old indentation is fine, you are trying to apply HTML:

```
$ curl https://github.com/istio/istio/blob/master/samples/httpbin/httpbin-gateway.yaml -s | head






<!DOCTYPE html>
<html lang="en" data-color-mode="auto" data-light-theme="light" data-dark-theme="dark" >
  <head>
    <meta charset="utf-8">
```

2022-03-28 21:26 UTC, closed without merging