[WIP]replace golint with revive
istio/istio pull request #38287
Opened 2022-04-08 02:03 UTC by zirain

**Please provide a description of this PR:**

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [X] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2022-04-08 04:44 UTC, zirain commented on common/config/.golangci.yml
> +  revive:
these changes will be move to common-files

2022-04-08 04:45 UTC, zirain commented on common/config/.golangci.yml
> +      # - name: confusing-results
these rules contains too much noise, maybe we can enable them in the future?

2022-04-08 04:49 UTC, istio-testing commented
@zirain: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests_istio | fdf77bfb0843e132d875cdb861b4dae971253d0c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/38287/unit-tests_istio/1512290176498405376) | true | `/test unit-tests_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-08 05:26 UTC, istio-testing commented
@zirain: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests_istio | fdf77bfb0843e132d875cdb861b4dae971253d0c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/38287/unit-tests_istio/1512290176498405376) | true | `/test unit-tests_istio`
integ-pilot-multicluster_istio | fdf77bfb0843e132d875cdb861b4dae971253d0c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/38287/integ-pilot-multicluster_istio/1512290177328877568) | true | `/test integ-pilot-multicluster_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-08 08:50 UTC, zirain commented on common/config/.golangci.yml
> +  revive:
moved to https://github.com/istio/common-files

2022-04-08 08:50 UTC, zirain commented on common/config/.golangci.yml
> +      # - name: confusing-results
moved to https://github.com/istio/common-files

2022-04-08 14:19 UTC, ericvn reviewed
Looks good other than a few nits about what looks like inconsistent empty lines.

2022-04-08 14:29 UTC, howardjohn requested changes
Can we just move to the new linter but set the default golint rules? https://revive.run/docs#configuration

Some of these changes look worse to me and I would prefer we introduce new linter 1-by-1 so we can evaluate the impact.

My understanding is our goal with revive is to use a non-deprecated linter, not to introduce new rules?

2022-04-08 14:47 UTC, ericvn commented
> Can we just move to the new linter but set the default golint rules? https://revive.run/docs#configuration
> 
> Some of these changes look worse to me and I would prefer we introduce new linter 1-by-1 so we can evaluate the impact.
> 
> My understanding is our goal with revive is to use a non-deprecated linter, not to introduce new rules?

When I did my initial testing, I just renamed the `golint:` section `revive: ` and noted many of the same changes that are done here (~37 files seems familiar). I would be curious if these are indeed the same and these are all required with just the default.

2022-04-09 01:52 UTC, zirain commented
> Can we just move to the new linter but set the default golint rules? https://revive.run/docs#configuration

It's hard to do that.

> Some of these changes look worse to me and I would prefer we introduce new linter 1-by-1 so we can evaluate the impact.

can you point out which part became worse? we can disabled that rule.

2022-04-09 08:36 UTC, zirain commented on pkg/config/validation/validation.go
> -			} else {
[revie rule]superfluous-else: if block ends with a continue statement, so drop this else and outdent its block

2022-04-09 08:45 UTC, zirain commented on tools/bug-report/pkg/cluster/cluster.go
> -			for kAnnotation, vAnnotation := range eld.Annotations {
var-naming: don't use leading k in Go names; range var kAnnotation should be annotation

2022-04-09 08:46 UTC, zirain commented on security/pkg/pki/util/san_test.go
> +	if !san.Critical {
bool-literal-in-expr: omit Boolean literal in expression

2022-04-09 08:51 UTC, zirain commented on security/pkg/pki/ra/k8s_ra_test.go
> +	TestCACertFile        = "../testdata/example-ca-cert.pem"
var-declaration: should omit type string from declaration of var TestCACertFile; it will be inferred from the right-hand side

2022-04-09 09:16 UTC, istio-testing commented
@zirain: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-security-multicluster_istio | 0dd4e2a43de700e2550b373cb73be41ab8adda3b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/38287/integ-security-multicluster_istio/1512712231333138432) | true | `/test integ-security-multicluster_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-09 09:18 UTC, zirain commented
/test integ-security-multicluster_istio

2022-04-11 18:31 UTC, howardjohn approved these changes

2022-04-11 20:16 UTC, ericvn approved these changes
Comments fixed. LGTM

2022-04-12 01:41 UTC, hanxiaop approved these changes

2022-04-12 02:41 UTC, merged