Gateway additional containers
istio/istio pull request #38913
Opened 2022-05-13 20:21 UTC by gjacquet

**Please provide a description of this PR:**

Allow defining additional containers for a gateway. Similar to what was done in the gateways chart.
See #38912 for reference.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [x] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2022-05-13 20:22 UTC, istio-testing commented
Hi @gjacquet. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-05-13 21:12 UTC, howardjohn requested changes
I appreciate the use case but I think this is venturing in the category of something better suited for things like https://docs.solo.io/gloo-edge/latest/installation/gateway/kubernetes/helm_advanced/.

For context, while this is simple, there are probably 10 PRs this month for similar simple changes to the helm charts with no overlap between any of them.

Helm and bespoke configuration are not a good match.

2022-05-16 21:33 UTC, gjacquet commented
I fully understand that no helm chart will ever support every single use case out there.

However in this case, I was under the impression this chart was coming to replace istio's `manifests/charts/gateways/istio-ingress` / `manifests/charts/gateways/istio-egress` charts and they both already accept `additionalContainers` as a value.

Even if this chart is not really meant to be a replacement,  I believe it would make sense to have all the gateway related charts offer similar capabilities and accepts similar values.

2022-05-16 21:34 UTC, howardjohn commented
It is intended to be a replacement, but correcting the mistakes of the initial attempts where we had basically every field exposed which caused complexity and maintenance burdens. This new chart was explicitly designed to be a simple starting point for gateways.

2022-07-01 05:04 UTC, closed without merging