Add priorityClassName to gateway helm chart
istio/istio pull request #39252
Opened 2022-06-02 09:45 UTC by robinelfrink

**Please provide a description of this PR:**

Add `priorityClassName` to the gateway Helm Chart in `manifests/charts/gateway`.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [x] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2022-06-02 09:45 UTC, istio-testing commented
Hi @robinelfrink. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-06-02 15:24 UTC, istio-testing commented
@robinelfrink: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio | a7f8d31600e2b9b87f91d7ad9a126d2e6fe7aa4a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/39252/lint_istio/1532377176165322752) | true | `/test lint_istio`
integ-pilot-istiodremote_istio | a7f8d31600e2b9b87f91d7ad9a126d2e6fe7aa4a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/39252/integ-pilot-istiodremote_istio/1532377170297491456) | true | `/test integ-pilot-istiodremote_istio`
integ-pilot_istio | a7f8d31600e2b9b87f91d7ad9a126d2e6fe7aa4a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/39252/integ-pilot_istio/1532377168980480000) | true | `/test integ-pilot_istio`
integ-cni_istio | a7f8d31600e2b9b87f91d7ad9a126d2e6fe7aa4a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/39252/integ-cni_istio/1532377168720433152) | true | `/test integ-cni_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-06-02 15:25 UTC, istio-testing commented
@robinelfrink: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio | a7f8d31600e2b9b87f91d7ad9a126d2e6fe7aa4a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/39252/lint_istio/1532377176165322752) | true | `/test lint_istio`
integ-pilot-istiodremote_istio | a7f8d31600e2b9b87f91d7ad9a126d2e6fe7aa4a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/39252/integ-pilot-istiodremote_istio/1532377170297491456) | true | `/test integ-pilot-istiodremote_istio`
integ-pilot_istio | a7f8d31600e2b9b87f91d7ad9a126d2e6fe7aa4a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/39252/integ-pilot_istio/1532377168980480000) | true | `/test integ-pilot_istio`
integ-cni_istio | a7f8d31600e2b9b87f91d7ad9a126d2e6fe7aa4a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/39252/integ-cni_istio/1532377168720433152) | true | `/test integ-cni_istio`
integ-pilot-istiodremote-mc_istio | a7f8d31600e2b9b87f91d7ad9a126d2e6fe7aa4a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/39252/integ-pilot-istiodremote-mc_istio/1532377171132157952) | true | `/test integ-pilot-istiodremote-mc_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-06-02 15:31 UTC, istio-testing commented
@robinelfrink: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio | a7f8d31600e2b9b87f91d7ad9a126d2e6fe7aa4a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/39252/lint_istio/1532377176165322752) | true | `/test lint_istio`
integ-pilot-istiodremote_istio | a7f8d31600e2b9b87f91d7ad9a126d2e6fe7aa4a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/39252/integ-pilot-istiodremote_istio/1532377170297491456) | true | `/test integ-pilot-istiodremote_istio`
integ-pilot_istio | a7f8d31600e2b9b87f91d7ad9a126d2e6fe7aa4a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/39252/integ-pilot_istio/1532377168980480000) | true | `/test integ-pilot_istio`
integ-cni_istio | a7f8d31600e2b9b87f91d7ad9a126d2e6fe7aa4a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/39252/integ-cni_istio/1532377168720433152) | true | `/test integ-cni_istio`
integ-pilot-istiodremote-mc_istio | a7f8d31600e2b9b87f91d7ad9a126d2e6fe7aa4a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/39252/integ-pilot-istiodremote-mc_istio/1532377171132157952) | true | `/test integ-pilot-istiodremote-mc_istio`
integ-pilot-multicluster_istio | a7f8d31600e2b9b87f91d7ad9a126d2e6fe7aa4a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/39252/integ-pilot-multicluster_istio/1532377169462824960) | true | `/test integ-pilot-multicluster_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-06-02 15:36 UTC, howardjohn requested changes
Sorry you are caught in the between stages where we have made a decision but not documented it -- but the Environments WG has made a decision to not allow modifications to helm charts for these types of changes and instead prefer last mile customiation: https://docs.google.com/document/d/1wsa06GGiq1LEGwhkiPP0FKIZJqdAiue-VeBonWAzAyk/edit#bookmark=id.4ru6nai2al4s

2022-06-03 06:41 UTC, robinelfrink commented
Okay, thanks for the info.

We're using [Flux](https://fluxcd.io/) so we can easily add a `postRenderer` to our `HelmRelease` objects:

```
spec:
  postRenderers:
  - kustomize:
      patchesStrategicMerge:
      - kind: Deployment
        apiVersion: apps/v1
        spec:
          template:
            spec:
              priorityClassName: super-high-priority
```

2022-06-03 06:41 UTC, closed without merging