Make ENABLE_AUTO_SNI affects Istio Mutal TLS outbound cluster
istio/istio pull request #39299
Opened 2022-06-06 10:30 UTC by l8huang

Before this change, ENABLE_AUTO_SNI only affects simple TLS and mutual TLS
outbound cluster; it should be applied to Istio mutual TLS as well, to avoid
setting SNI for routing via egress gateway.

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2022-06-06 10:33 UTC, istio-testing commented
@l8huang: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | aaa459a5e46e58010fc40af3175f6fb288fbd786 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/39299/release-notes_istio/1533758182613061632) | true | `/test release-notes_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-06-06 10:36 UTC, istio-testing commented
@l8huang: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | aaa459a5e46e58010fc40af3175f6fb288fbd786 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/39299/release-notes_istio/1533758182613061632) | true | `/test release-notes_istio`
lint_istio | aaa459a5e46e58010fc40af3175f6fb288fbd786 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/39299/lint_istio/1533758180939534336) | true | `/test lint_istio`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-06-06 17:08 UTC, howardjohn requested changes
can you cover the use cases why we want this for istio_mutual?

Istio mutual has special SNI expectations that do NOT match the Host name

2022-06-06 21:53 UTC, l8huang commented
Our use case is E2E TLS through egress gateway:

app -- HTTP --> sidecar -- ISTIO MTLS --> egress gateway -- HTTPS --> mesh external service

We created DestinationRule like step 3 in [Egress Gateways with TLS Origination](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/#perform-tls-origination-with-an-egress-gateway), which has `sni` specified. Unfortunately we run into some scalability issues, so we want to avoid creating subset for every external service(there could be more than thousands external services). To do that, auto SNI need to be enabled in sidecar's outbound cluster.

2022-06-06 21:56 UTC, howardjohn commented
I see. IMO its a bit dangerous since its really only useful in select scenarios but its used everywhere. This would break multinetwork.

Use of Istio_mutual without the "istio sni" is really a bit a of hack due to use having some inflexible protocol decisions. Some of the future work on H2 connect as the transport protocol will fix this.

2022-06-07 02:15 UTC, hzxuzhonghu requested changes
Auto SNI should not apply to Istio_MUTUAL

2022-06-07 12:59 UTC, l8huang commented
I see using feature ENABLE_AUTO_SNI on Istio mutual TLS is improper now. Does it make sense to add a option to ProxyConfig to turn on auto SNI for Istio mutual TLS outbound cluster(intentionally giving up Istio MTLS auto passthrough)?

In our use case, we only need Istio mutual TLS from sidecar to egress gateway, egress gateway will originate a new simple TLS to external service; we don't use multinetwork(AUTO_PASSTHROUGH) at all.

2022-06-28 22:53 UTC, l8huang commented
Close because this conflicts with AUTO PASSTHROUGH.
A better solution for this use case could be using EnvoyFilter to enabled auto sni for sidecar's outbound cluster which points to egress gateway.

2022-06-28 22:53 UTC, closed without merging