Fix 0103 warning for not injected pods on the host network
istio/istio pull request #40220
Opened 2022-08-02 11:05 UTC by cnvergence

**Please provide a description of this PR:**
This fixes a warning that shows only on injection-enabled namespaces with deployed pods on the host network.
Automatic sidecar injection is disabled for such pods by default.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2022-08-02 13:19 UTC, GregHanson requested changes
@cnvergence could you add a [release note](https://github.com/istio/istio/tree/master/releasenotes) for this fix?

2022-08-02 13:20 UTC, GregHanson commented
/cherry-pick release-1.14

2022-08-02 13:20 UTC, istio-testing commented
@GregHanson: once the present PR merges, I will cherry-pick it on top of release-1.14 in a new PR and assign it to you.

<details>

In response to [this](https://github.com/istio/istio/pull/40220#issuecomment-1202542824):

>/cherry-pick release-1.14


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-08-02 15:52 UTC, howardjohn approved these changes

2022-08-03 13:00 UTC, ericvn commented on releasenotes/notes/40220.yaml
> +    **Fixed** IST0103 warning from `istioctl analyze` for not injected pods on the host network.
c/not injected/non-injected/

2022-08-03 13:44 UTC, ericvn approved these changes
RN looks good.

2022-08-05 07:27 UTC, cnvergence commented
@GregHanson PTAL

2022-08-08 07:45 UTC, cnvergence commented
/test integ-basic-arm64_istio

2022-08-08 07:45 UTC, cnvergence commented
/test unit-tests-arm64_istio

2022-08-08 08:41 UTC, merged

2022-08-08 08:43 UTC, istio-testing commented
@GregHanson: #40220 failed to apply on top of branch "release-1.14":
```
Applying: Fix 0103 warning on pods on the host network
Using index info to reconstruct a base tree...
M	pkg/config/analysis/analyzers/injection/injection.go
M	pkg/config/analysis/analyzers/testdata/injection.yaml
Falling back to patching base and 3-way merge...
Auto-merging pkg/config/analysis/analyzers/testdata/injection.yaml
CONFLICT (content): Merge conflict in pkg/config/analysis/analyzers/testdata/injection.yaml
Auto-merging pkg/config/analysis/analyzers/injection/injection.go
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Patch failed at 0001 Fix 0103 warning on pods on the host network
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

```

<details>

In response to [this](https://github.com/istio/istio/pull/40220#issuecomment-1202542824):

>/cherry-pick release-1.14


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-08-08 08:43 UTC, istio-testing commented
@GregHanson: new issue created for failed cherrypick: #40323

<details>

In response to [this](https://github.com/istio/istio/pull/40220#issuecomment-1202542824):

>/cherry-pick release-1.14


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-08-08 17:17 UTC, ericvn commented
/cherry-pick release-1.15

2022-08-08 17:17 UTC, istio-testing commented
@ericvn: new pull request created: #40335

<details>

In response to [this](https://github.com/istio/istio/pull/40220#issuecomment-1208392973):

>/cherry-pick release-1.15


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>