remove enabled components in object caches when exec prune
istio/istio pull request #40800
Opened 2022-09-05 08:59 UTC by tuhao1020

Signed-off-by: HaoTu <haotu@alauda.io>

Please provide a description of this PR:
flushes all object caches when exec prune, fix for https://github.com/istio/istio/issues/37828

To help us figure out who should review this PR, please put an X in all the areas that this PR affects.

 Configuration Infrastructure
 Docs
 Installation
 Networking
 Performance and Scalability
 Policies and Telemetry
 Security
 Test and Release
 User Experience
 Developer Infrastructure

2022-09-05 08:59 UTC, istio-testing commented
Hi @tuhao1020. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-09-05 09:19 UTC, zirain commented
/ok-to-test

2022-09-06 13:39 UTC, howardjohn commented on operator/pkg/helmreconciler/prune.go
> +			objCache.Mu.Lock()
nevr unlocked?

2022-09-07 01:06 UTC, tuhao1020 commented on operator/pkg/helmreconciler/prune.go
> +			objCache.Mu.Lock()
done

2022-09-16 07:15 UTC, zirain commented
/retest

2022-09-26 01:47 UTC, zirain commented
kindly ping @istio/wg-environments-maintainers , this will also fix https://github.com/istio/istio/issues/40903

2022-10-26 08:16 UTC, zirain commented
not stale

2022-10-27 01:55 UTC, zirain requested changes
I think this's not right after https://github.com/istio/istio/pull/41449 merged.

you should add `tuhao-test` into env `WATCH_NAMESPACE`

env:
          - name: WATCH_NAMESPACE
            value: istio-system,tuhao-test

2022-11-11 04:14 UTC, tuhao1020 commented
> I think this's not right after #41449 merged.
> 
> you should add `tuhao-test` into env `WATCH_NAMESPACE`
> 
> env: - name: WATCH_NAMESPACE value: istio-system,tuhao-test

Where does the WATCH_NAMESPACE environment variable need to be placed?

2022-12-11 05:02 UTC, closed without merging