Add leader election to protect mutatingwebhookconfiguration
istio/istio pull request #41228
Opened 2022-09-30 03:38 UTC by hzxuzhonghu

**Please provide a description of this PR:**

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2022-09-30 03:49 UTC, hzxuzhonghu commented on pilot/pkg/bootstrap/sidecarinjector.go
> +			patcher, err := webhooks.NewWebhookCertPatcher(s.kubeClient, args.Revision, s.istiodCertBundleWatcher)
this need leader election as well

2022-09-30 04:07 UTC, istio-testing commented
@hzxuzhonghu: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-pilot-multicluster_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575691625043070976) | true | `/test integ-pilot-multicluster`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 04:20 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-pilot-multicluster_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575691625043070976) | true | `/test integ-pilot-multicluster`
integ-pilot-istiodremote-mc_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575691626712403968) | true | `/test integ-pilot-istiodremote-mc`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 04:45 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-pilot-multicluster_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575691625043070976) | true | `/test integ-pilot-multicluster`
integ-pilot-istiodremote-mc_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575691626712403968) | true | `/test integ-pilot-istiodremote-mc`
integ-telemetry-mc_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575691621947674624) | true | `/test integ-telemetry-mc`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 04:46 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-pilot-multicluster_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575691625043070976) | true | `/test integ-pilot-multicluster`
integ-pilot-istiodremote-mc_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575691626712403968) | true | `/test integ-pilot-istiodremote-mc`
integ-telemetry-mc_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575691621947674624) | true | `/test integ-telemetry-mc`
integ-security-multicluster_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575691628394319872) | true | `/test integ-security-multicluster`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 08:08 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-pilot-multicluster_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575691625043070976) | true | `/test integ-pilot-multicluster`
integ-pilot-istiodremote-mc_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575691626712403968) | true | `/test integ-pilot-istiodremote-mc`
integ-telemetry-mc_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575691621947674624) | true | `/test integ-telemetry-mc`
integ-security-multicluster_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575691628394319872) | true | `/test integ-security-multicluster`
integ-ipv6_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575755512350248960) | true | `/test integ-ipv6`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 08:14 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-pilot-multicluster_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575691625043070976) | true | `/test integ-pilot-multicluster`
integ-pilot-istiodremote-mc_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575691626712403968) | true | `/test integ-pilot-istiodremote-mc`
integ-telemetry-mc_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575691621947674624) | true | `/test integ-telemetry-mc`
integ-security-multicluster_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575691628394319872) | true | `/test integ-security-multicluster`
integ-ipv6_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575755512350248960) | true | `/test integ-ipv6`
integ-operator-controller_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575755513709203456) | true | `/test integ-operator-controller`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 08:15 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-pilot-multicluster_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575691625043070976) | true | `/test integ-pilot-multicluster`
integ-pilot-istiodremote-mc_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575691626712403968) | true | `/test integ-pilot-istiodremote-mc`
integ-telemetry-mc_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575691621947674624) | true | `/test integ-telemetry-mc`
integ-security-multicluster_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575691628394319872) | true | `/test integ-security-multicluster`
integ-ipv6_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575755512350248960) | true | `/test integ-ipv6`
integ-operator-controller_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575755513709203456) | true | `/test integ-operator-controller`
integ-helm_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575755520994709504) | true | `/test integ-helm`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 08:16 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-pilot-multicluster_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575691625043070976) | true | `/test integ-pilot-multicluster`
integ-pilot-istiodremote-mc_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575691626712403968) | true | `/test integ-pilot-istiodremote-mc`
integ-telemetry-mc_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575691621947674624) | true | `/test integ-telemetry-mc`
integ-security-multicluster_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575691628394319872) | true | `/test integ-security-multicluster`
integ-ipv6_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575755512350248960) | true | `/test integ-ipv6`
integ-operator-controller_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575755513709203456) | true | `/test integ-operator-controller`
integ-helm_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575755520994709504) | true | `/test integ-helm`
integ-distroless_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575755512312500224) | true | `/test integ-distroless`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 08:16 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-pilot-multicluster_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575691625043070976) | true | `/test integ-pilot-multicluster`
integ-pilot-istiodremote-mc_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575691626712403968) | true | `/test integ-pilot-istiodremote-mc`
integ-telemetry-mc_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575691621947674624) | true | `/test integ-telemetry-mc`
integ-security-multicluster_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575691628394319872) | true | `/test integ-security-multicluster`
integ-ipv6_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575755512350248960) | true | `/test integ-ipv6`
integ-operator-controller_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575755513709203456) | true | `/test integ-operator-controller`
integ-helm_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575755520994709504) | true | `/test integ-helm`
integ-distroless_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575755512312500224) | true | `/test integ-distroless`
integ-ds_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ds_istio/1575755512392192000) | true | `/test integ-ds`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 08:22 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-pilot-multicluster_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575691625043070976) | true | `/test integ-pilot-multicluster`
integ-pilot-istiodremote-mc_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575691626712403968) | true | `/test integ-pilot-istiodremote-mc`
integ-telemetry-mc_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575691621947674624) | true | `/test integ-telemetry-mc`
integ-security-multicluster_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575691628394319872) | true | `/test integ-security-multicluster`
integ-ipv6_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575755512350248960) | true | `/test integ-ipv6`
integ-operator-controller_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575755513709203456) | true | `/test integ-operator-controller`
integ-helm_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575755520994709504) | true | `/test integ-helm`
integ-distroless_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575755512312500224) | true | `/test integ-distroless`
integ-ds_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ds_istio/1575755512392192000) | true | `/test integ-ds`
integ-pilot-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote_istio/1575755516229980160) | true | `/test integ-pilot-istiodremote`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 08:27 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-pilot-istiodremote-mc_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575691626712403968) | true | `/test integ-pilot-istiodremote-mc`
integ-telemetry-mc_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575691621947674624) | true | `/test integ-telemetry-mc`
integ-security-multicluster_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575691628394319872) | true | `/test integ-security-multicluster`
integ-ipv6_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575755512350248960) | true | `/test integ-ipv6`
integ-operator-controller_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575755513709203456) | true | `/test integ-operator-controller`
integ-helm_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575755520994709504) | true | `/test integ-helm`
integ-distroless_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575755512312500224) | true | `/test integ-distroless`
integ-ds_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ds_istio/1575755512392192000) | true | `/test integ-ds`
integ-pilot-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote_istio/1575755516229980160) | true | `/test integ-pilot-istiodremote`
integ-pilot-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575755515391119360) | true | `/test integ-pilot-multicluster`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 08:32 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-telemetry-mc_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575691621947674624) | true | `/test integ-telemetry-mc`
integ-security-multicluster_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575691628394319872) | true | `/test integ-security-multicluster`
integ-ipv6_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575755512350248960) | true | `/test integ-ipv6`
integ-operator-controller_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575755513709203456) | true | `/test integ-operator-controller`
integ-helm_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575755520994709504) | true | `/test integ-helm`
integ-distroless_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575755512312500224) | true | `/test integ-distroless`
integ-ds_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ds_istio/1575755512392192000) | true | `/test integ-ds`
integ-pilot-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote_istio/1575755516229980160) | true | `/test integ-pilot-istiodremote`
integ-pilot-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575755515391119360) | true | `/test integ-pilot-multicluster`
integ-pilot-istiodremote-mc_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575755517060452352) | true | `/test integ-pilot-istiodremote-mc`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 08:39 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-telemetry-mc_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575691621947674624) | true | `/test integ-telemetry-mc`
integ-security-multicluster_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575691628394319872) | true | `/test integ-security-multicluster`
integ-ipv6_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575755512350248960) | true | `/test integ-ipv6`
integ-operator-controller_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575755513709203456) | true | `/test integ-operator-controller`
integ-helm_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575755520994709504) | true | `/test integ-helm`
integ-distroless_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575755512312500224) | true | `/test integ-distroless`
integ-ds_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ds_istio/1575755512392192000) | true | `/test integ-ds`
integ-pilot-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote_istio/1575755516229980160) | true | `/test integ-pilot-istiodremote`
integ-pilot-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575755515391119360) | true | `/test integ-pilot-multicluster`
integ-pilot-istiodremote-mc_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575755517060452352) | true | `/test integ-pilot-istiodremote-mc`
integ-cni_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1575755512153116672) | true | `/test integ-cni`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 08:39 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-telemetry-mc_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575691621947674624) | true | `/test integ-telemetry-mc`
integ-security-multicluster_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575691628394319872) | true | `/test integ-security-multicluster`
integ-ipv6_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575755512350248960) | true | `/test integ-ipv6`
integ-operator-controller_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575755513709203456) | true | `/test integ-operator-controller`
integ-helm_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575755520994709504) | true | `/test integ-helm`
integ-distroless_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575755512312500224) | true | `/test integ-distroless`
integ-ds_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ds_istio/1575755512392192000) | true | `/test integ-ds`
integ-pilot-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote_istio/1575755516229980160) | true | `/test integ-pilot-istiodremote`
integ-pilot-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575755515391119360) | true | `/test integ-pilot-multicluster`
integ-pilot-istiodremote-mc_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575755517060452352) | true | `/test integ-pilot-istiodremote-mc`
integ-cni_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1575755512153116672) | true | `/test integ-cni`
integ-pilot_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1575755514543869952) | true | `/test integ-pilot`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 08:56 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-telemetry-mc_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575691621947674624) | true | `/test integ-telemetry-mc`
integ-security-multicluster_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575691628394319872) | true | `/test integ-security-multicluster`
integ-ipv6_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575755512350248960) | true | `/test integ-ipv6`
integ-operator-controller_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575755513709203456) | true | `/test integ-operator-controller`
integ-helm_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575755520994709504) | true | `/test integ-helm`
integ-distroless_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575755512312500224) | true | `/test integ-distroless`
integ-ds_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ds_istio/1575755512392192000) | true | `/test integ-ds`
integ-pilot-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote_istio/1575755516229980160) | true | `/test integ-pilot-istiodremote`
integ-pilot-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575755515391119360) | true | `/test integ-pilot-multicluster`
integ-pilot-istiodremote-mc_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575755517060452352) | true | `/test integ-pilot-istiodremote-mc`
integ-cni_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1575755512153116672) | true | `/test integ-cni`
integ-pilot_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1575755514543869952) | true | `/test integ-pilot`
integ-security-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-istiodremote_istio/1575755519581229056) | true | `/test integ-security-istiodremote`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 08:57 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-telemetry-mc_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575691621947674624) | true | `/test integ-telemetry-mc`
integ-ipv6_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575755512350248960) | true | `/test integ-ipv6`
integ-operator-controller_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575755513709203456) | true | `/test integ-operator-controller`
integ-helm_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575755520994709504) | true | `/test integ-helm`
integ-distroless_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575755512312500224) | true | `/test integ-distroless`
integ-ds_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ds_istio/1575755512392192000) | true | `/test integ-ds`
integ-pilot-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote_istio/1575755516229980160) | true | `/test integ-pilot-istiodremote`
integ-pilot-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575755515391119360) | true | `/test integ-pilot-multicluster`
integ-pilot-istiodremote-mc_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575755517060452352) | true | `/test integ-pilot-istiodremote-mc`
integ-cni_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1575755512153116672) | true | `/test integ-cni`
integ-pilot_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1575755514543869952) | true | `/test integ-pilot`
integ-security-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-istiodremote_istio/1575755519581229056) | true | `/test integ-security-istiodremote`
integ-security-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575755518746562560) | true | `/test integ-security-multicluster`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 09:00 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-telemetry-mc_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575691621947674624) | true | `/test integ-telemetry-mc`
integ-ipv6_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575755512350248960) | true | `/test integ-ipv6`
integ-operator-controller_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575755513709203456) | true | `/test integ-operator-controller`
integ-helm_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575755520994709504) | true | `/test integ-helm`
integ-distroless_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575755512312500224) | true | `/test integ-distroless`
integ-ds_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ds_istio/1575755512392192000) | true | `/test integ-ds`
integ-pilot-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote_istio/1575755516229980160) | true | `/test integ-pilot-istiodremote`
integ-pilot-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575755515391119360) | true | `/test integ-pilot-multicluster`
integ-pilot-istiodremote-mc_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575755517060452352) | true | `/test integ-pilot-istiodremote-mc`
integ-cni_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1575755512153116672) | true | `/test integ-cni`
integ-pilot_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1575755514543869952) | true | `/test integ-pilot`
integ-security-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-istiodremote_istio/1575755519581229056) | true | `/test integ-security-istiodremote`
integ-security-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575755518746562560) | true | `/test integ-security-multicluster`
integ-telemetry-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-istiodremote_istio/1575755512278945792) | true | `/test integ-telemetry-istiodremote`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 09:00 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-telemetry-mc_istio | 8c4a0606dba7f0e5843efcf074be411afa1686dd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575691621947674624) | true | `/test integ-telemetry-mc`
integ-ipv6_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575755512350248960) | true | `/test integ-ipv6`
integ-operator-controller_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575755513709203456) | true | `/test integ-operator-controller`
integ-helm_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575755520994709504) | true | `/test integ-helm`
integ-distroless_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575755512312500224) | true | `/test integ-distroless`
integ-ds_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ds_istio/1575755512392192000) | true | `/test integ-ds`
integ-pilot-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote_istio/1575755516229980160) | true | `/test integ-pilot-istiodremote`
integ-pilot-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575755515391119360) | true | `/test integ-pilot-multicluster`
integ-pilot-istiodremote-mc_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575755517060452352) | true | `/test integ-pilot-istiodremote-mc`
integ-cni_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1575755512153116672) | true | `/test integ-cni`
integ-pilot_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1575755514543869952) | true | `/test integ-pilot`
integ-security-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-istiodremote_istio/1575755519581229056) | true | `/test integ-security-istiodremote`
integ-security-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575755518746562560) | true | `/test integ-security-multicluster`
integ-telemetry-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-istiodremote_istio/1575755512278945792) | true | `/test integ-telemetry-istiodremote`
integ-telemetry_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry_istio/1575755512199254016) | true | `/test integ-telemetry`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 09:03 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ipv6_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575755512350248960) | true | `/test integ-ipv6`
integ-operator-controller_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575755513709203456) | true | `/test integ-operator-controller`
integ-helm_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575755520994709504) | true | `/test integ-helm`
integ-distroless_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575755512312500224) | true | `/test integ-distroless`
integ-ds_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ds_istio/1575755512392192000) | true | `/test integ-ds`
integ-pilot-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote_istio/1575755516229980160) | true | `/test integ-pilot-istiodremote`
integ-pilot-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575755515391119360) | true | `/test integ-pilot-multicluster`
integ-pilot-istiodremote-mc_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575755517060452352) | true | `/test integ-pilot-istiodremote-mc`
integ-cni_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1575755512153116672) | true | `/test integ-cni`
integ-pilot_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1575755514543869952) | true | `/test integ-pilot`
integ-security-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-istiodremote_istio/1575755519581229056) | true | `/test integ-security-istiodremote`
integ-security-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575755518746562560) | true | `/test integ-security-multicluster`
integ-telemetry-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-istiodremote_istio/1575755512278945792) | true | `/test integ-telemetry-istiodremote`
integ-telemetry_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry_istio/1575755512199254016) | true | `/test integ-telemetry`
integ-telemetry-mc_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575755512228614144) | true | `/test integ-telemetry-mc`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 09:07 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ipv6_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575755512350248960) | true | `/test integ-ipv6`
integ-operator-controller_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575755513709203456) | true | `/test integ-operator-controller`
integ-helm_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575755520994709504) | true | `/test integ-helm`
integ-distroless_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575755512312500224) | true | `/test integ-distroless`
integ-ds_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ds_istio/1575755512392192000) | true | `/test integ-ds`
integ-pilot-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote_istio/1575755516229980160) | true | `/test integ-pilot-istiodremote`
integ-pilot-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575755515391119360) | true | `/test integ-pilot-multicluster`
integ-pilot-istiodremote-mc_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575755517060452352) | true | `/test integ-pilot-istiodremote-mc`
integ-cni_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1575755512153116672) | true | `/test integ-cni`
integ-pilot_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1575755514543869952) | true | `/test integ-pilot`
integ-security-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-istiodremote_istio/1575755519581229056) | true | `/test integ-security-istiodremote`
integ-security-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575755518746562560) | true | `/test integ-security-multicluster`
integ-telemetry-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-istiodremote_istio/1575755512278945792) | true | `/test integ-telemetry-istiodremote`
integ-telemetry_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry_istio/1575755512199254016) | true | `/test integ-telemetry`
integ-telemetry-mc_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575755512228614144) | true | `/test integ-telemetry-mc`
integ-security_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security_istio/1575755517928673280) | true | `/test integ-security`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 10:01 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ipv6_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575755512350248960) | true | `/test integ-ipv6`
integ-operator-controller_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575755513709203456) | true | `/test integ-operator-controller`
integ-distroless_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575755512312500224) | true | `/test integ-distroless`
integ-ds_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ds_istio/1575755512392192000) | true | `/test integ-ds`
integ-pilot-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote_istio/1575755516229980160) | true | `/test integ-pilot-istiodremote`
integ-pilot-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575755515391119360) | true | `/test integ-pilot-multicluster`
integ-pilot-istiodremote-mc_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575755517060452352) | true | `/test integ-pilot-istiodremote-mc`
integ-cni_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1575755512153116672) | true | `/test integ-cni`
integ-pilot_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1575755514543869952) | true | `/test integ-pilot`
integ-security-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-istiodremote_istio/1575755519581229056) | true | `/test integ-security-istiodremote`
integ-security-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575755518746562560) | true | `/test integ-security-multicluster`
integ-telemetry-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-istiodremote_istio/1575755512278945792) | true | `/test integ-telemetry-istiodremote`
integ-telemetry_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry_istio/1575755512199254016) | true | `/test integ-telemetry`
integ-telemetry-mc_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575755512228614144) | true | `/test integ-telemetry-mc`
integ-security_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security_istio/1575755517928673280) | true | `/test integ-security`
integ-helm_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575784098306199552) | true | `/test integ-helm`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 10:08 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ipv6_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575755512350248960) | true | `/test integ-ipv6`
integ-operator-controller_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575755513709203456) | true | `/test integ-operator-controller`
integ-distroless_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575755512312500224) | true | `/test integ-distroless`
integ-ds_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ds_istio/1575755512392192000) | true | `/test integ-ds`
integ-pilot-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote_istio/1575755516229980160) | true | `/test integ-pilot-istiodremote`
integ-pilot-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575755515391119360) | true | `/test integ-pilot-multicluster`
integ-pilot-istiodremote-mc_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575755517060452352) | true | `/test integ-pilot-istiodremote-mc`
integ-cni_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1575755512153116672) | true | `/test integ-cni`
integ-pilot_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1575755514543869952) | true | `/test integ-pilot`
integ-security-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-istiodremote_istio/1575755519581229056) | true | `/test integ-security-istiodremote`
integ-security-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575755518746562560) | true | `/test integ-security-multicluster`
integ-telemetry-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-istiodremote_istio/1575755512278945792) | true | `/test integ-telemetry-istiodremote`
integ-telemetry_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry_istio/1575755512199254016) | true | `/test integ-telemetry`
integ-telemetry-mc_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575755512228614144) | true | `/test integ-telemetry-mc`
integ-security_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security_istio/1575755517928673280) | true | `/test integ-security`
integ-helm_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575784098306199552) | true | `/test integ-helm`
integ-basic-arm64_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-basic-arm64_istio/1575784090441879552) | true | `/test integ-basic-arm64`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 10:14 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ipv6_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575755512350248960) | true | `/test integ-ipv6`
integ-operator-controller_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575755513709203456) | true | `/test integ-operator-controller`
integ-distroless_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575755512312500224) | true | `/test integ-distroless`
integ-ds_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ds_istio/1575755512392192000) | true | `/test integ-ds`
integ-pilot-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575755515391119360) | true | `/test integ-pilot-multicluster`
integ-pilot-istiodremote-mc_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575755517060452352) | true | `/test integ-pilot-istiodremote-mc`
integ-cni_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1575755512153116672) | true | `/test integ-cni`
integ-pilot_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1575755514543869952) | true | `/test integ-pilot`
integ-security-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-istiodremote_istio/1575755519581229056) | true | `/test integ-security-istiodremote`
integ-security-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575755518746562560) | true | `/test integ-security-multicluster`
integ-telemetry-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-istiodremote_istio/1575755512278945792) | true | `/test integ-telemetry-istiodremote`
integ-telemetry_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry_istio/1575755512199254016) | true | `/test integ-telemetry`
integ-telemetry-mc_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575755512228614144) | true | `/test integ-telemetry-mc`
integ-security_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security_istio/1575755517928673280) | true | `/test integ-security`
integ-helm_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575784098306199552) | true | `/test integ-helm`
integ-basic-arm64_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-basic-arm64_istio/1575784090441879552) | true | `/test integ-basic-arm64`
integ-pilot-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote_istio/1575784093801517056) | true | `/test integ-pilot-istiodremote`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 10:15 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-operator-controller_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575755513709203456) | true | `/test integ-operator-controller`
integ-distroless_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575755512312500224) | true | `/test integ-distroless`
integ-ds_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ds_istio/1575755512392192000) | true | `/test integ-ds`
integ-pilot-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575755515391119360) | true | `/test integ-pilot-multicluster`
integ-pilot-istiodremote-mc_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575755517060452352) | true | `/test integ-pilot-istiodremote-mc`
integ-cni_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1575755512153116672) | true | `/test integ-cni`
integ-pilot_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1575755514543869952) | true | `/test integ-pilot`
integ-security-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-istiodremote_istio/1575755519581229056) | true | `/test integ-security-istiodremote`
integ-security-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575755518746562560) | true | `/test integ-security-multicluster`
integ-telemetry-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-istiodremote_istio/1575755512278945792) | true | `/test integ-telemetry-istiodremote`
integ-telemetry_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry_istio/1575755512199254016) | true | `/test integ-telemetry`
integ-telemetry-mc_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575755512228614144) | true | `/test integ-telemetry-mc`
integ-security_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security_istio/1575755517928673280) | true | `/test integ-security`
integ-helm_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575784098306199552) | true | `/test integ-helm`
integ-basic-arm64_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-basic-arm64_istio/1575784090441879552) | true | `/test integ-basic-arm64`
integ-pilot-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote_istio/1575784093801517056) | true | `/test integ-pilot-istiodremote`
integ-ipv6_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575784089737236480) | true | `/test integ-ipv6`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 10:26 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-operator-controller_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575755513709203456) | true | `/test integ-operator-controller`
integ-pilot-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575755515391119360) | true | `/test integ-pilot-multicluster`
integ-cni_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1575755512153116672) | true | `/test integ-cni`
integ-pilot_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1575755514543869952) | true | `/test integ-pilot`
integ-security-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-istiodremote_istio/1575755519581229056) | true | `/test integ-security-istiodremote`
integ-security-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575755518746562560) | true | `/test integ-security-multicluster`
integ-telemetry-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-istiodremote_istio/1575755512278945792) | true | `/test integ-telemetry-istiodremote`
integ-telemetry_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry_istio/1575755512199254016) | true | `/test integ-telemetry`
integ-telemetry-mc_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575755512228614144) | true | `/test integ-telemetry-mc`
integ-security_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security_istio/1575755517928673280) | true | `/test integ-security`
integ-helm_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575784098306199552) | true | `/test integ-helm`
integ-basic-arm64_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-basic-arm64_istio/1575784090441879552) | true | `/test integ-basic-arm64`
integ-pilot-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote_istio/1575784093801517056) | true | `/test integ-pilot-istiodremote`
integ-ipv6_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575784089737236480) | true | `/test integ-ipv6`
integ-ds_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ds_istio/1575784089779179520) | true | `/test integ-ds`
integ-distroless_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575784089695293440) | true | `/test integ-distroless`
integ-pilot-istiodremote-mc_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575784094640377856) | true | `/test integ-pilot-istiodremote-mc`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 10:28 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-pilot-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575755515391119360) | true | `/test integ-pilot-multicluster`
integ-cni_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1575755512153116672) | true | `/test integ-cni`
integ-pilot_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1575755514543869952) | true | `/test integ-pilot`
integ-security-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-istiodremote_istio/1575755519581229056) | true | `/test integ-security-istiodremote`
integ-security-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575755518746562560) | true | `/test integ-security-multicluster`
integ-telemetry-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-istiodremote_istio/1575755512278945792) | true | `/test integ-telemetry-istiodremote`
integ-telemetry_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry_istio/1575755512199254016) | true | `/test integ-telemetry`
integ-telemetry-mc_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575755512228614144) | true | `/test integ-telemetry-mc`
integ-security_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security_istio/1575755517928673280) | true | `/test integ-security`
integ-helm_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575784098306199552) | true | `/test integ-helm`
integ-basic-arm64_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-basic-arm64_istio/1575784090441879552) | true | `/test integ-basic-arm64`
integ-pilot-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote_istio/1575784093801517056) | true | `/test integ-pilot-istiodremote`
integ-ipv6_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575784089737236480) | true | `/test integ-ipv6`
integ-ds_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ds_istio/1575784089779179520) | true | `/test integ-ds`
integ-distroless_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575784089695293440) | true | `/test integ-distroless`
integ-pilot-istiodremote-mc_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575784094640377856) | true | `/test integ-pilot-istiodremote-mc`
integ-operator-controller_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575784091280740352) | true | `/test integ-operator-controller`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 10:41 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-cni_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1575755512153116672) | true | `/test integ-cni`
integ-pilot_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1575755514543869952) | true | `/test integ-pilot`
integ-security-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-istiodremote_istio/1575755519581229056) | true | `/test integ-security-istiodremote`
integ-security-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575755518746562560) | true | `/test integ-security-multicluster`
integ-telemetry-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-istiodremote_istio/1575755512278945792) | true | `/test integ-telemetry-istiodremote`
integ-telemetry_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry_istio/1575755512199254016) | true | `/test integ-telemetry`
integ-telemetry-mc_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575755512228614144) | true | `/test integ-telemetry-mc`
integ-security_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security_istio/1575755517928673280) | true | `/test integ-security`
integ-helm_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575784098306199552) | true | `/test integ-helm`
integ-basic-arm64_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-basic-arm64_istio/1575784090441879552) | true | `/test integ-basic-arm64`
integ-pilot-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote_istio/1575784093801517056) | true | `/test integ-pilot-istiodremote`
integ-ipv6_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575784089737236480) | true | `/test integ-ipv6`
integ-ds_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ds_istio/1575784089779179520) | true | `/test integ-ds`
integ-distroless_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575784089695293440) | true | `/test integ-distroless`
integ-pilot-istiodremote-mc_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575784094640377856) | true | `/test integ-pilot-istiodremote-mc`
integ-operator-controller_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575784091280740352) | true | `/test integ-operator-controller`
integ-pilot-multicluster_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575784092966850560) | true | `/test integ-pilot-multicluster`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 10:48 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-cni_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1575755512153116672) | true | `/test integ-cni`
integ-pilot_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1575755514543869952) | true | `/test integ-pilot`
integ-security-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575755518746562560) | true | `/test integ-security-multicluster`
integ-telemetry-istiodremote_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-istiodremote_istio/1575755512278945792) | true | `/test integ-telemetry-istiodremote`
integ-telemetry_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry_istio/1575755512199254016) | true | `/test integ-telemetry`
integ-telemetry-mc_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575755512228614144) | true | `/test integ-telemetry-mc`
integ-security_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security_istio/1575755517928673280) | true | `/test integ-security`
integ-helm_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575784098306199552) | true | `/test integ-helm`
integ-basic-arm64_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-basic-arm64_istio/1575784090441879552) | true | `/test integ-basic-arm64`
integ-pilot-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote_istio/1575784093801517056) | true | `/test integ-pilot-istiodremote`
integ-ipv6_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575784089737236480) | true | `/test integ-ipv6`
integ-ds_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ds_istio/1575784089779179520) | true | `/test integ-ds`
integ-distroless_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575784089695293440) | true | `/test integ-distroless`
integ-pilot-istiodremote-mc_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575784094640377856) | true | `/test integ-pilot-istiodremote-mc`
integ-operator-controller_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575784091280740352) | true | `/test integ-operator-controller`
integ-pilot-multicluster_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575784092966850560) | true | `/test integ-pilot-multicluster`
integ-security-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-istiodremote_istio/1575784097467338752) | true | `/test integ-security-istiodremote`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 10:51 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-cni_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1575755512153116672) | true | `/test integ-cni`
integ-pilot_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1575755514543869952) | true | `/test integ-pilot`
integ-security-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575755518746562560) | true | `/test integ-security-multicluster`
integ-telemetry_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry_istio/1575755512199254016) | true | `/test integ-telemetry`
integ-telemetry-mc_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575755512228614144) | true | `/test integ-telemetry-mc`
integ-security_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security_istio/1575755517928673280) | true | `/test integ-security`
integ-helm_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575784098306199552) | true | `/test integ-helm`
integ-basic-arm64_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-basic-arm64_istio/1575784090441879552) | true | `/test integ-basic-arm64`
integ-pilot-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote_istio/1575784093801517056) | true | `/test integ-pilot-istiodremote`
integ-ipv6_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575784089737236480) | true | `/test integ-ipv6`
integ-ds_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ds_istio/1575784089779179520) | true | `/test integ-ds`
integ-distroless_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575784089695293440) | true | `/test integ-distroless`
integ-pilot-istiodremote-mc_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575784094640377856) | true | `/test integ-pilot-istiodremote-mc`
integ-operator-controller_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575784091280740352) | true | `/test integ-operator-controller`
integ-pilot-multicluster_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575784092966850560) | true | `/test integ-pilot-multicluster`
integ-security-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-istiodremote_istio/1575784097467338752) | true | `/test integ-security-istiodremote`
integ-telemetry-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-istiodremote_istio/1575784089657544704) | true | `/test integ-telemetry-istiodremote`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 10:57 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-cni_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1575755512153116672) | true | `/test integ-cni`
integ-security-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575755518746562560) | true | `/test integ-security-multicluster`
integ-telemetry_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry_istio/1575755512199254016) | true | `/test integ-telemetry`
integ-telemetry-mc_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575755512228614144) | true | `/test integ-telemetry-mc`
integ-security_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security_istio/1575755517928673280) | true | `/test integ-security`
integ-helm_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575784098306199552) | true | `/test integ-helm`
integ-basic-arm64_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-basic-arm64_istio/1575784090441879552) | true | `/test integ-basic-arm64`
integ-pilot-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote_istio/1575784093801517056) | true | `/test integ-pilot-istiodremote`
integ-ipv6_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575784089737236480) | true | `/test integ-ipv6`
integ-ds_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ds_istio/1575784089779179520) | true | `/test integ-ds`
integ-distroless_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575784089695293440) | true | `/test integ-distroless`
integ-pilot-istiodremote-mc_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575784094640377856) | true | `/test integ-pilot-istiodremote-mc`
integ-operator-controller_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575784091280740352) | true | `/test integ-operator-controller`
integ-pilot-multicluster_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575784092966850560) | true | `/test integ-pilot-multicluster`
integ-security-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-istiodremote_istio/1575784097467338752) | true | `/test integ-security-istiodremote`
integ-telemetry-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-istiodremote_istio/1575784089657544704) | true | `/test integ-telemetry-istiodremote`
integ-pilot_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1575784092119601152) | true | `/test integ-pilot`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 10:59 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-security-multicluster_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575755518746562560) | true | `/test integ-security-multicluster`
integ-telemetry_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry_istio/1575755512199254016) | true | `/test integ-telemetry`
integ-telemetry-mc_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575755512228614144) | true | `/test integ-telemetry-mc`
integ-security_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security_istio/1575755517928673280) | true | `/test integ-security`
integ-helm_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575784098306199552) | true | `/test integ-helm`
integ-basic-arm64_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-basic-arm64_istio/1575784090441879552) | true | `/test integ-basic-arm64`
integ-pilot-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote_istio/1575784093801517056) | true | `/test integ-pilot-istiodremote`
integ-ipv6_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575784089737236480) | true | `/test integ-ipv6`
integ-ds_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ds_istio/1575784089779179520) | true | `/test integ-ds`
integ-distroless_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575784089695293440) | true | `/test integ-distroless`
integ-pilot-istiodremote-mc_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575784094640377856) | true | `/test integ-pilot-istiodremote-mc`
integ-operator-controller_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575784091280740352) | true | `/test integ-operator-controller`
integ-pilot-multicluster_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575784092966850560) | true | `/test integ-pilot-multicluster`
integ-security-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-istiodremote_istio/1575784097467338752) | true | `/test integ-security-istiodremote`
integ-telemetry-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-istiodremote_istio/1575784089657544704) | true | `/test integ-telemetry-istiodremote`
integ-pilot_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1575784092119601152) | true | `/test integ-pilot`
integ-cni_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1575784089523326976) | true | `/test integ-cni`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 11:28 UTC, ramaraochavali commented
It was added https://github.com/istio/istio/pull/39137 and then removed https://github.com/istio/istio/pull/39202/. See the comments here https://github.com/istio/istio/pull/39137#issuecomment-1138953953

2022-09-30 11:29 UTC, ramaraochavali requested changes
See my comments above. It was added some time back and removed because we do not have consensus that it works for revisions.

2022-09-30 11:33 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-telemetry_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry_istio/1575755512199254016) | true | `/test integ-telemetry`
integ-telemetry-mc_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575755512228614144) | true | `/test integ-telemetry-mc`
integ-security_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security_istio/1575755517928673280) | true | `/test integ-security`
integ-helm_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575784098306199552) | true | `/test integ-helm`
integ-basic-arm64_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-basic-arm64_istio/1575784090441879552) | true | `/test integ-basic-arm64`
integ-pilot-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote_istio/1575784093801517056) | true | `/test integ-pilot-istiodremote`
integ-ipv6_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575784089737236480) | true | `/test integ-ipv6`
integ-ds_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ds_istio/1575784089779179520) | true | `/test integ-ds`
integ-distroless_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575784089695293440) | true | `/test integ-distroless`
integ-pilot-istiodremote-mc_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575784094640377856) | true | `/test integ-pilot-istiodremote-mc`
integ-operator-controller_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575784091280740352) | true | `/test integ-operator-controller`
integ-pilot-multicluster_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575784092966850560) | true | `/test integ-pilot-multicluster`
integ-security-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-istiodremote_istio/1575784097467338752) | true | `/test integ-security-istiodremote`
integ-telemetry-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-istiodremote_istio/1575784089657544704) | true | `/test integ-telemetry-istiodremote`
integ-pilot_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1575784092119601152) | true | `/test integ-pilot`
integ-cni_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1575784089523326976) | true | `/test integ-cni`
integ-security-multicluster_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575784096632672256) | true | `/test integ-security-multicluster`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 11:43 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-telemetry_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry_istio/1575755512199254016) | true | `/test integ-telemetry`
integ-security_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security_istio/1575755517928673280) | true | `/test integ-security`
integ-helm_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575784098306199552) | true | `/test integ-helm`
integ-basic-arm64_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-basic-arm64_istio/1575784090441879552) | true | `/test integ-basic-arm64`
integ-pilot-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote_istio/1575784093801517056) | true | `/test integ-pilot-istiodremote`
integ-ipv6_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575784089737236480) | true | `/test integ-ipv6`
integ-ds_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ds_istio/1575784089779179520) | true | `/test integ-ds`
integ-distroless_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575784089695293440) | true | `/test integ-distroless`
integ-pilot-istiodremote-mc_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575784094640377856) | true | `/test integ-pilot-istiodremote-mc`
integ-operator-controller_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575784091280740352) | true | `/test integ-operator-controller`
integ-pilot-multicluster_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575784092966850560) | true | `/test integ-pilot-multicluster`
integ-security-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-istiodremote_istio/1575784097467338752) | true | `/test integ-security-istiodremote`
integ-telemetry-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-istiodremote_istio/1575784089657544704) | true | `/test integ-telemetry-istiodremote`
integ-pilot_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1575784092119601152) | true | `/test integ-pilot`
integ-cni_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1575784089523326976) | true | `/test integ-cni`
integ-security-multicluster_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575784096632672256) | true | `/test integ-security-multicluster`
integ-telemetry-mc_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575784089619795968) | true | `/test integ-telemetry-mc`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 11:46 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-security_istio | ff84336d2862db4d86c99177d34fed395f971bf9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security_istio/1575755517928673280) | true | `/test integ-security`
integ-helm_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575784098306199552) | true | `/test integ-helm`
integ-basic-arm64_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-basic-arm64_istio/1575784090441879552) | true | `/test integ-basic-arm64`
integ-pilot-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote_istio/1575784093801517056) | true | `/test integ-pilot-istiodremote`
integ-ipv6_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575784089737236480) | true | `/test integ-ipv6`
integ-ds_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ds_istio/1575784089779179520) | true | `/test integ-ds`
integ-distroless_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575784089695293440) | true | `/test integ-distroless`
integ-pilot-istiodremote-mc_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575784094640377856) | true | `/test integ-pilot-istiodremote-mc`
integ-operator-controller_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575784091280740352) | true | `/test integ-operator-controller`
integ-pilot-multicluster_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575784092966850560) | true | `/test integ-pilot-multicluster`
integ-security-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-istiodremote_istio/1575784097467338752) | true | `/test integ-security-istiodremote`
integ-telemetry-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-istiodremote_istio/1575784089657544704) | true | `/test integ-telemetry-istiodremote`
integ-pilot_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1575784092119601152) | true | `/test integ-pilot`
integ-cni_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1575784089523326976) | true | `/test integ-cni`
integ-security-multicluster_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575784096632672256) | true | `/test integ-security-multicluster`
integ-telemetry-mc_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575784089619795968) | true | `/test integ-telemetry-mc`
integ-telemetry_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry_istio/1575784089569464320) | true | `/test integ-telemetry`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-30 11:49 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-helm_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-helm_istio/1575784098306199552) | true | `/test integ-helm`
integ-basic-arm64_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-basic-arm64_istio/1575784090441879552) | true | `/test integ-basic-arm64`
integ-pilot-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote_istio/1575784093801517056) | true | `/test integ-pilot-istiodremote`
integ-ipv6_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ipv6_istio/1575784089737236480) | true | `/test integ-ipv6`
integ-ds_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-ds_istio/1575784089779179520) | true | `/test integ-ds`
integ-distroless_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-distroless_istio/1575784089695293440) | true | `/test integ-distroless`
integ-pilot-istiodremote-mc_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575784094640377856) | true | `/test integ-pilot-istiodremote-mc`
integ-operator-controller_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-operator-controller_istio/1575784091280740352) | true | `/test integ-operator-controller`
integ-pilot-multicluster_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1575784092966850560) | true | `/test integ-pilot-multicluster`
integ-security-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-istiodremote_istio/1575784097467338752) | true | `/test integ-security-istiodremote`
integ-telemetry-istiodremote_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-istiodremote_istio/1575784089657544704) | true | `/test integ-telemetry-istiodremote`
integ-pilot_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1575784092119601152) | true | `/test integ-pilot`
integ-cni_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1575784089523326976) | true | `/test integ-cni`
integ-security-multicluster_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575784096632672256) | true | `/test integ-security-multicluster`
integ-telemetry-mc_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575784089619795968) | true | `/test integ-telemetry-mc`
integ-telemetry_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry_istio/1575784089569464320) | true | `/test integ-telemetry`
integ-security_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security_istio/1575784095785422848) | true | `/test integ-security`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-08 02:00 UTC, hzxuzhonghu commented
We have supported leader election for revision, so i do think this is the right time to do so.

2022-10-08 04:37 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-pilot-istiodremote-mc_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575784094640377856) | true | `/test integ-pilot-istiodremote-mc`
integ-pilot_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1575784092119601152) | true | `/test integ-pilot`
integ-cni_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1575784089523326976) | true | `/test integ-cni`
integ-security-multicluster_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575784096632672256) | true | `/test integ-security-multicluster`
integ-telemetry-mc_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575784089619795968) | true | `/test integ-telemetry-mc`
integ-security_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security_istio/1575784095785422848) | true | `/test integ-security`
integ-pilot-multicluster_istio | cbdd78d1ec45020194bbcb001b5dc278d9417199 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1578597318930731008) | true | `/test integ-pilot-multicluster`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-08 04:38 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-pilot-istiodremote-mc_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575784094640377856) | true | `/test integ-pilot-istiodremote-mc`
integ-pilot_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1575784092119601152) | true | `/test integ-pilot`
integ-security-multicluster_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575784096632672256) | true | `/test integ-security-multicluster`
integ-telemetry-mc_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575784089619795968) | true | `/test integ-telemetry-mc`
integ-pilot-multicluster_istio | cbdd78d1ec45020194bbcb001b5dc278d9417199 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1578597318930731008) | true | `/test integ-pilot-multicluster`
integ-cni_istio | cbdd78d1ec45020194bbcb001b5dc278d9417199 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1578597315696922624) | true | `/test integ-cni`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-08 04:44 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-pilot-istiodremote-mc_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1575784094640377856) | true | `/test integ-pilot-istiodremote-mc`
integ-security-multicluster_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575784096632672256) | true | `/test integ-security-multicluster`
integ-telemetry-mc_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575784089619795968) | true | `/test integ-telemetry-mc`
integ-pilot-multicluster_istio | cbdd78d1ec45020194bbcb001b5dc278d9417199 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1578597318930731008) | true | `/test integ-pilot-multicluster`
integ-cni_istio | cbdd78d1ec45020194bbcb001b5dc278d9417199 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1578597315696922624) | true | `/test integ-cni`
integ-pilot_istio | cbdd78d1ec45020194bbcb001b5dc278d9417199 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1578597318096064512) | true | `/test integ-pilot`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-08 04:50 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-security-multicluster_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1575784096632672256) | true | `/test integ-security-multicluster`
integ-telemetry-mc_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575784089619795968) | true | `/test integ-telemetry-mc`
integ-pilot-multicluster_istio | cbdd78d1ec45020194bbcb001b5dc278d9417199 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1578597318930731008) | true | `/test integ-pilot-multicluster`
integ-cni_istio | cbdd78d1ec45020194bbcb001b5dc278d9417199 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1578597315696922624) | true | `/test integ-cni`
integ-pilot_istio | cbdd78d1ec45020194bbcb001b5dc278d9417199 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1578597318096064512) | true | `/test integ-pilot`
integ-pilot-istiodremote-mc_istio | cbdd78d1ec45020194bbcb001b5dc278d9417199 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1578597320612646912) | true | `/test integ-pilot-istiodremote-mc`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-08 05:06 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-telemetry-mc_istio | f969454a6712dd8d3c41ecf6a9bdc50459995e5d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1575784089619795968) | true | `/test integ-telemetry-mc`
integ-pilot-multicluster_istio | cbdd78d1ec45020194bbcb001b5dc278d9417199 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1578597318930731008) | true | `/test integ-pilot-multicluster`
integ-cni_istio | cbdd78d1ec45020194bbcb001b5dc278d9417199 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1578597315696922624) | true | `/test integ-cni`
integ-pilot_istio | cbdd78d1ec45020194bbcb001b5dc278d9417199 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1578597318096064512) | true | `/test integ-pilot`
integ-pilot-istiodremote-mc_istio | cbdd78d1ec45020194bbcb001b5dc278d9417199 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1578597320612646912) | true | `/test integ-pilot-istiodremote-mc`
integ-security-multicluster_istio | cbdd78d1ec45020194bbcb001b5dc278d9417199 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1578597322290368512) | true | `/test integ-security-multicluster`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-08 05:18 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-pilot-multicluster_istio | cbdd78d1ec45020194bbcb001b5dc278d9417199 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-multicluster_istio/1578597318930731008) | true | `/test integ-pilot-multicluster`
integ-cni_istio | cbdd78d1ec45020194bbcb001b5dc278d9417199 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1578597315696922624) | true | `/test integ-cni`
integ-pilot_istio | cbdd78d1ec45020194bbcb001b5dc278d9417199 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1578597318096064512) | true | `/test integ-pilot`
integ-pilot-istiodremote-mc_istio | cbdd78d1ec45020194bbcb001b5dc278d9417199 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot-istiodremote-mc_istio/1578597320612646912) | true | `/test integ-pilot-istiodremote-mc`
integ-security-multicluster_istio | cbdd78d1ec45020194bbcb001b5dc278d9417199 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1578597322290368512) | true | `/test integ-security-multicluster`
integ-telemetry-mc_istio | cbdd78d1ec45020194bbcb001b5dc278d9417199 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-telemetry-mc_istio/1578597315780808704) | true | `/test integ-telemetry-mc`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-08 07:02 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-cni_istio | cbdd78d1ec45020194bbcb001b5dc278d9417199 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1578597315696922624) | true | `/test integ-cni`
integ-security-multicluster_istio | cbdd78d1ec45020194bbcb001b5dc278d9417199 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1578597322290368512) | true | `/test integ-security-multicluster`
integ-pilot_istio | c3cc72743371df3ded31e319658811ccf27fffe3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1578634114146242560) | true | `/test integ-pilot`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-08 07:04 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-security-multicluster_istio | cbdd78d1ec45020194bbcb001b5dc278d9417199 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-security-multicluster_istio/1578597322290368512) | true | `/test integ-security-multicluster`
integ-pilot_istio | c3cc72743371df3ded31e319658811ccf27fffe3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-pilot_istio/1578634114146242560) | true | `/test integ-pilot`
integ-cni_istio | c3cc72743371df3ded31e319658811ccf27fffe3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41228/integ-cni_istio/1578634111755489280) | true | `/test integ-cni`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-11 01:34 UTC, hzxuzhonghu commented
@howardjohn ptal

2022-10-11 14:38 UTC, howardjohn commented
TBH it seems more expensive to maintain leader election (1 write per 15s per revision) than to not.. in current case we will ~never write to the webhook since it never needs changes. Not sure that this is worth the cause, given the thing it is fixing can only occur if a user has a broken cluster (inconsistent state between instances in the same revision) which already has guard mechanism (exponential backoff)

2022-10-12 01:42 UTC, hzxuzhonghu commented
>if a user has a broken cluster (inconsistent state between instances in the same revision) which already has guard mechanism (exponential backoff)
Where do we guard it now?

`1 write per 15s per revision` IMO this cost can be ignored, actually we have suffered from this during our certs rotate, not sure why one istiod does not update the newly caCert(hard to diagnose, maybe kubelet not work ).
I think we can do a little improvement for better debugability  for kind of this case

2022-10-13 01:35 UTC, hzxuzhonghu commented
Even in correct status, we donot need all instances to do one same thing. Which will report some error logs

2022-10-13 02:13 UTC, hzxuzhonghu commented
Why do you think leader election is a big deal once 15s

2022-10-13 02:15 UTC, howardjohn commented
Isn't the reason you want to add leader election to avoid wasteful writes
to the webhook? Which occur orders of magnitude less often than election
writes.

It's not just 1 write per 15s, it's multiplied by each istiod revision and
elections (we have about 6 already...). We see this taking a large amount
of k8s API server traffic already for existing elections

On Wed, Oct 12, 2022, 7:13 PM Zhonghu Xu ***@***.***> wrote:

> Why do you think leader election is a big deal once 15s
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/istio/pull/41228#issuecomment-1276934257>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEYGXI45HI35W2C4M6KGG3WC5V5ZANCNFSM6AAAAAAQZLESHU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-13 02:19 UTC, hzxuzhonghu commented
The main target is not to save write, it is to eliminate unnecessary conflicting / race write

2022-10-13 02:20 UTC, hzxuzhonghu commented
We can do some leader election reuse,  consider we have multi leader elections now, some may can be merged use one if the leader election itself  is wasteful

2022-10-27 03:35 UTC, hzxuzhonghu commented
close as not approved

2022-10-27 03:35 UTC, closed without merging