feat: Call ConvertToSidecarScope function with multiple goroutines
istio/istio pull request #41454
Opened 2022-10-16 04:58 UTC by wulianglongrd

**Please provide a description of this PR:**

issue #41453 

Call the `ConvertToSidecarScope` function with multiple goroutines to reduce the time consumption of the `initSidecarScopes` function.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [x] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2022-10-16 04:58 UTC, istio-testing commented
Hi @wulianglongrd. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-10-17 11:48 UTC, ramaraochavali commented
Can you please add a benchmark?

2022-10-17 16:02 UTC, howardjohn requested changes
I don't think we should do this. Its quite complex and has no benchmarks showing improvement. We already have issues that Istiod is too spiky in CPU - this can only make it spikier

2022-10-19 13:06 UTC, wulianglongrd commented
hello @howardjohn  @ramaraochavali , I have submitted the benchmark code. Below are my benchmark results on my mac.

**test env:**
```code
goos: darwin
goarch: amd64
cpu: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
```

**test result:**
Note that I changed the name of the "name" column. the `old` represent the original code, the `new` represent the code with multiple goroutines. Please read the benchmark source code for details.
```code
$ benchstat old.txt new.txt
name                                      old time/op    new time/op    delta
InitSidecarScopesThrottleService10-4       294µs ±20%     266µs ±17%   -9.32%  (p=0.004 n=20+20)
InitSidecarScopesThrottleService30-4       924µs ±14%     725µs ± 9%  -21.47%  (p=0.000 n=20+20)
InitSidecarScopesThrottleService50-4      1.97ms ±14%    1.41ms ±17%  -28.48%  (p=0.000 n=20+17)
InitSidecarScopesThrottleService100-4     5.67ms ±16%    3.77ms ±14%  -33.55%  (p=0.000 n=20+19)
InitSidecarScopesThrottleService200-4     19.1ms ±16%    12.0ms ±14%  -37.22%  (p=0.000 n=20+19)
InitSidecarScopesThrottleService300-4     45.3ms ±37%    27.6ms ±22%  -39.14%  (p=0.000 n=18+19)
InitSidecarScopesThrottleService400-4      110ms ±44%      50ms ±25%  -54.30%  (p=0.000 n=18+20)
InitSidecarScopesThrottleService500-4      111ms ±25%      78ms ±16%  -29.31%  (p=0.000 n=20+20)
InitSidecarScopesThrottleService1000-4     424ms ±40%     299ms ±22%  -29.52%  (p=0.000 n=19+20)

name                                      old alloc/op   new alloc/op   delta
InitSidecarScopesThrottleService10-4      74.0kB ± 0%    77.2kB ± 0%   +4.39%  (p=0.000 n=20+20)
InitSidecarScopesThrottleService30-4       229kB ± 0%     238kB ± 0%   +3.94%  (p=0.000 n=20+20)
InitSidecarScopesThrottleService50-4       407kB ± 0%     422kB ± 0%   +3.63%  (p=0.000 n=20+19)
InitSidecarScopesThrottleService100-4      943kB ± 0%     972kB ± 0%   +3.10%  (p=0.000 n=20+20)
InitSidecarScopesThrottleService200-4     2.38MB ± 0%    2.44MB ± 0%   +2.43%  (p=0.000 n=19+20)
InitSidecarScopesThrottleService300-4     4.40MB ± 0%    4.49MB ± 0%   +1.97%  (p=0.000 n=20+20)
InitSidecarScopesThrottleService400-4     6.61MB ± 0%    6.73MB ± 0%   +1.75%  (p=0.000 n=19+20)
InitSidecarScopesThrottleService500-4     9.46MB ± 0%    9.61MB ± 0%   +1.53%  (p=0.000 n=19+19)
InitSidecarScopesThrottleService1000-4    31.3MB ± 0%    31.6MB ± 0%   +0.92%  (p=0.000 n=20+20)

name                                      old allocs/op  new allocs/op  delta
InitSidecarScopesThrottleService10-4         757 ± 0%       793 ± 0%   +4.76%  (p=0.000 n=20+20)
InitSidecarScopesThrottleService30-4       2.84k ± 0%     2.94k ± 0%   +3.38%  (p=0.000 n=20+20)
InitSidecarScopesThrottleService50-4       5.72k ± 0%     5.88k ± 0%   +2.73%  (p=0.000 n=14+16)
InitSidecarScopesThrottleService100-4      16.4k ± 0%     16.7k ± 0%   +1.86%  (p=0.000 n=20+20)
InitSidecarScopesThrottleService200-4      52.8k ± 0%     53.4k ± 0%   +1.15%  (p=0.000 n=19+20)
InitSidecarScopesThrottleService300-4       109k ± 0%      110k ± 0%   +0.83%  (p=0.000 n=20+20)
InitSidecarScopesThrottleService400-4       186k ± 0%      187k ± 0%   +0.65%  (p=0.000 n=20+20)
InitSidecarScopesThrottleService500-4       282k ± 0%      284k ± 0%   +0.54%  (p=0.000 n=19+20)
InitSidecarScopesThrottleService1000-4     1.06M ± 0%     1.07M ± 0%   +0.28%  (p=0.000 n=20+20)
```

**benchmark cpu profile flamegraph**:
- before(the original code):

<img width="1318" alt="image" src="https://user-images.githubusercontent.com/14371864/196695734-4244eece-874e-4ba1-8e6a-a8ae44fc7ce2.png">

- after(with multiple goroutines):

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/14371864/196695849-17e5d427-cac8-4721-b581-9a832fc6d142.png">

From the above test results, using multiple goroutines can reduce the time consumption of the `initSidecarScopes` function, and the impact on CPU and memory is not obvious.

thanks.

2022-10-19 14:01 UTC, howardjohn commented
Its not true that the CPu usage is unchanged. You are looking at only relative CPU usage of different functions, if you look at the total CPU time spent its far greater with more goroutines.

Which makes sense - its  CPU bound process, its not possible to use less CPU by just changing which CPU runs the process..

2022-10-20 03:54 UTC, hzxuzhonghu commented
@wulianglongrd Could you give a graph of istiod, we want to see how `ConvertToSidecarScope` impacts the whole system.

I can understand all you want is to speed up the calc, and decrease xds latency, irrespective of cpu/memory cost.  It makes sense in your case, if this function is the bottle, I don't mind providing such option to satisfy different cases. We need a complete trace graph first.

2022-10-21 06:47 UTC, wulianglongrd commented
hello @howardjohn @hzxuzhonghu, Below are my perf results.

**perf process:**
1. Do not set `PILOT_SIDECARSCOPE_CONVERT_THROTTLE` to start and perf, get old.svg
2. Kill pilot-discovery
3. Set `export PILOT_SIDECARSCOPE_CONVERT_THROTTLE=4` to start and perf, get new.svg


**perf commands:**
```shell
$ perf record -F 99 -p {pid} -g -- sleep 40
$ perf script > old.perf
$ git clone https://github.com/brendangregg/FlameGraph
$ ./FlameGraph/stackcollapse-perf.pl old.perf > old.folded
$ ./FlameGraph/flamegraph.pl old.folded > old.svg
```

**perf result:**
- old.svg
![old](https://user-images.githubusercontent.com/14371864/197130412-ae5d91b1-a0dc-4c42-88bb-09b7f8ba82c1.svg)

- new.svg
![new](https://user-images.githubusercontent.com/14371864/197130462-57585f00-ddf1-4936-b389-dd93d7ec7bb6.svg)


thanks.

2022-10-21 06:55 UTC, wulianglongrd commented
Additional instructions:
After pilot-discovery is fully started, during perf, I create a `dr`.

2022-10-21 07:13 UTC, wulianglongrd commented
@hzxuzhonghu `old.trace.out` and `new.trace.out` all in the gz file.

[trace.tar.gz](https://github.com/istio/istio/files/9836540/trace.tar.gz)

2022-10-21 14:25 UTC, howardjohn commented
The flamegraph doesn't really give any new or useful info IMO (its actually largely identical before and after, as well). The concern is that its

* Complex
* Not safe (CPU spikes are already problematic, this makes them far worse)
* Not fixing the right problem (do less work instead of splitting the work across CPUs)

2022-10-24 14:16 UTC, sschepens commented
@wulianglongrd in the flamegraphs you posted it would seem your case is mostly governed by `MostSpecificHostMatch` which should theoretically be fast (a single map lookup in best case scenario), but apparently you're not hitting that case and instead fullscanning hostnames to match the most specific.

Could this maybe be an insight to look on?

@howardjohn i was looking into `MostSpecificHostMatch` wouldn't there be a more efficient way to find matching destination rules? maybe using a Trie structure instead of a list of destination rules, another way would be to actually separate wildcarded destinationrules so not to iterate all desintation rules until we find a matching one. Currently we're iterating all destination rules for every service needing one which doesn't have a equal destination rule.

2022-11-08 16:04 UTC, closed without merging

2023-12-19 03:28 UTC, wulianglongrd commented
When I submitted this PR, I had just started learning the Go language and read the source code of istio for the first time. Let's ignore this code implementation for now and look at three concerns:

> Complex

I totally agree. But if it can solve the performance bottleneck, then I think it is worth it.

> Not safe (CPU spikes are already problematic, this makes them far worse)

This may be a bit misunderstood. There is currently only one goroutine executing, which also means that it will only occupy one core of the CPU at most. This may be a reason for the long CPU usage?

> Not fixing the right problem (do less work instead of splitting the work across CPUs)

This might be considered full utilization of the CPU? In fact, most of the current CPUs should be idle, because the servers used are multi-core CPUs, but currently only one goroutine is executing.

Hello @howardjohn , what do you think ?

2023-12-19 20:29 UTC, howardjohn commented
Arguably using more CPU is worse because it further exacerbates Istiod's spiky usage, which makes autoscaling more challenging. Not sure I fully buy that argument though.

https://github.com/istio/istio/pull/48438 is somewhat related