[WIP] Support configuring TLS min/max version and ECDH curves
istio/istio pull request #42008
Opened 2022-11-15 15:35 UTC by jewertow

**Please provide a description of this PR:**

This change adds the ability to configure TLS min/max version and ECDH curves in SDS and webhook servers by passing the following arguments to istiod: `--tlsMinVersion=TLSv1_2 --tlsMaxVersion=TLSv1_3 --tlsEcdhCurves=P-256,P-384`.
Issue: #41772 

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2022-11-15 15:35 UTC, istio-testing commented
Skipping CI for Draft Pull Request.
If you want CI signal for your change, please convert it to an actual PR.
You can still manually trigger a test run with `/test all`

2022-11-15 15:39 UTC, istio-testing commented
@jewertow: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | e76c413fa486fcfab597eec9948725c12bccb57e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/42008/release-notes_istio/1592541866354544640) | true | `/test release-notes`
lint_istio | e76c413fa486fcfab597eec9948725c12bccb57e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/42008/lint_istio/1592541864085426176) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-11-15 16:11 UTC, jewertow commented
/test all

2022-11-16 14:19 UTC, istio-testing commented
@jewertow: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | 50b5b8ee2c0560ec0f72ea7d2343ba82ad94b3c3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/42008/unit-tests-arm64_istio/1592883869932064768) | true | `/test unit-tests-arm64`
unit-tests_istio | 50b5b8ee2c0560ec0f72ea7d2343ba82ad94b3c3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/42008/unit-tests_istio/1592883869885927424) | true | `/test unit-tests`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-11-16 15:56 UTC, howardjohn requested changes
See discussion in https://github.com/istio/api/pull/2543, can we hold off on discussion here to keep it in 1 place?

2022-11-30 22:38 UTC, jewertow commented
I'm closing as we decided on the community call today.

2022-11-30 22:38 UTC, closed without merging