helm: support custom imagePullPolicy for istio-operator
istio/istio pull request #42088
Opened 2022-11-21 10:52 UTC by my-git9

**Please provide a description of this PR:**
helm: support custom imagePullPolicy for istio-operator

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [x] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2022-11-21 10:58 UTC, istio-testing commented
@my-git9: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
gencheck_istio | 894a41c49b39416b75879d3b4cd3bbf624a276d3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/42088/gencheck_istio/1594644989869035520) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-11-21 11:20 UTC, zirain requested changes
https://github.com/istio/istio/pull/41200#pullrequestreview-1123677745

2022-11-21 12:17 UTC, my-git9 commented
/test gencheck

2022-11-21 12:24 UTC, my-git9 commented
> [#41200 (review)](https://github.com/istio/istio/pull/41200#pullrequestreview-1123677745)
The `imagePolicy` in the chart of other components can be customized. In addition to the operator, I think it is necessary to set the `imagePolicy as` a variable in terms of function and specification:
https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/values.yaml#L249
https://github.com/istio/istio/blob/master/manifests/charts/istio-cni/values.yaml#L94
https://github.com/istio/istio/blob/master/manifests/charts/gateways/istio-egress/values.yaml#L153
https://github.com/istio/istio/blob/master/manifests/charts/gateways/istio-ingress/values.yaml#L170

2022-11-28 17:13 UTC, jacob-delgado approved these changes

2022-11-29 00:49 UTC, zirain approved these changes

2022-11-29 01:26 UTC, merged