Re-enable dualuse workload cert generation (CommonName identical to the SAN)
istio/istio pull request #42123
Opened 2022-11-22 17:44 UTC by boeboe

**Please provide a description of this PR:**

Check feature request https://github.com/istio/istio/issues/42114

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ x] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2022-11-22 17:44 UTC, istio-testing commented
Hi @boeboe. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-11-22 18:05 UTC, shivanshu1333 commented
/ok-to-test

2022-11-22 18:09 UTC, istio-testing commented
@boeboe: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio | f1dadb777c57c4a80cc5a68e744c454d670e4cc8 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/42123/lint_istio/1595116301259378688) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-11-22 18:10 UTC, istio-testing commented
@boeboe: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio | f1dadb777c57c4a80cc5a68e744c454d670e4cc8 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/42123/lint_istio/1595116301259378688) | true | `/test lint`
gencheck_istio | f1dadb777c57c4a80cc5a68e744c454d670e4cc8 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/42123/gencheck_istio/1595116302106628096) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-11-23 00:31 UTC, howardjohn requested changes
Per discussion in https://github.com/istio/istio/issues/42114, lets get broader agreement from WG before proceeding with this

2022-12-23 21:14 UTC, costinm commented on pilot/cmd/pilot-agent/options/options.go
> +	isDualUseEnv = env.Register("IS_DUAL_USE", false,
I don't think this should be a setting in agent - the CA can decide what to include ( and should filter anything else )

2022-12-23 21:18 UTC, costinm reviewed
I generally think it is a great idea - but:
- should be a CA setting. We can't sign whatever the agent decides to put in the CSR, it must be verified. Also the info doesn't have to be in the CSR - a CA can add or set any field.
- we need to have a clear doc/spec on what we want to set - for example for CN I think we should follow the same conventions as K8S, there is no value in setting a spiffee URL as CN IMO
- we keep discussing adding other fields to the cert - like the Pod ID (can be validated by Istiod - avoids sending it as metadata) and even the canonical service name as a DNS record, which would further increase compat with non-Istio workloads.

2022-12-23 21:18 UTC, costinm commented on pkg/security/security.go
> +	// Whether to enable dual-use mode, which generates a workload certificate with a CommonName identical to
Same - what is added to cert should be a CA policy, not something the pods decide.

2023-02-07 05:04 UTC, closed without merging