Add labels to gateway pods
istio/istio pull request #42194
Opened 2022-11-29 11:55 UTC by vsoloviov

**Please provide a description of this PR:**
https://github.com/istio/istio/blob/master/manifests/charts/gateway/values.yaml#L76 says labels to be applied to _all_ resources, but pods template labels are missing, so pods are being created without these labels.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [x] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2022-11-29 11:55 UTC, istio-testing commented
Hi @vsoloviov. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-11-29 15:06 UTC, howardjohn requested changes
This duplicates labels since selectorLabels already has some of them

2022-11-29 15:07 UTC, howardjohn commented
I am also not sure its ocmmon in other charts to put things like `pp.kubernetes.io/managed-by: Helm` on the Pod - its actually false (same with the version); the pods are NOT managed by helm.

The comment is correct; its applied to all objects created by helm.

2022-11-30 07:08 UTC, vsoloviov commented
@howardjohn makes sense, I have updated the template to include only labels from `Values.labels`, so we don't include `gateway.labels` to Pod.

2022-12-04 02:02 UTC, Arhell reviewed
/ok-to-test

2023-01-18 05:04 UTC, closed without merging