Changes to provide overridden value to proxy labels in failoverPriority
istio/istio pull request #42395
Opened 2022-12-12 07:46 UTC by Purushotham233

Use this overridden value instead of proxy's value while assigining priority to endpoints

Changes to discuss the enhancement discussed in https://github.com/istio/istio/issues/39111

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [x] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2022-12-12 07:46 UTC, istio-testing commented
Hi @Purushotham233. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-12-12 08:26 UTC, hzxuzhonghu requested changes
I donot think it is a general solution that user could easily understand

2022-12-13 08:43 UTC, Purushotham233 commented
@hzxuzhonghu 

Will add documentation explaining the scenario when the overriding to be used along with subsets. Do you see some alternative approach to achieve the requirement?

I hope the requirement discussed in the issuehttps://github.com/istio/istio/issues/39111 is clear.

2023-01-26 08:04 UTC, closed without merging

2023-02-13 17:31 UTC, Purushotham233 commented
Not stale. Kindly re-open.

@howardjohn, Changes are made as per the discussion in [39111](https://github.com/istio/istio/issues/39111). 

This solution is deployed in our feature env.. Like to promote the solution once it is upstreamed.