rm DisableGatewayPortTranslationLabel
istio/istio pull request #42535
Opened 2022-12-21 06:54 UTC by hzxuzhonghu

**Please provide a description of this PR:**

rm `"experimental.istio.io/disable-gateway-port-translation"`

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2022-12-21 06:57 UTC, istio-testing commented
@hzxuzhonghu: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | a2135a2e7eeb200cea88a79d5eebb845cfe59eab | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/42535/unit-tests-arm64_istio/1605456664348069888) | true | `/test unit-tests-arm64`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-12-21 06:57 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | a2135a2e7eeb200cea88a79d5eebb845cfe59eab | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/42535/unit-tests-arm64_istio/1605456664348069888) | true | `/test unit-tests-arm64`
release-notes_istio | a2135a2e7eeb200cea88a79d5eebb845cfe59eab | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/42535/release-notes_istio/1605456675999846400) | true | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-12-21 07:01 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | a2135a2e7eeb200cea88a79d5eebb845cfe59eab | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/42535/unit-tests-arm64_istio/1605456664348069888) | true | `/test unit-tests-arm64`
release-notes_istio | a2135a2e7eeb200cea88a79d5eebb845cfe59eab | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/42535/release-notes_istio/1605456675999846400) | true | `/test release-notes`
unit-tests_istio | a2135a2e7eeb200cea88a79d5eebb845cfe59eab | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/42535/unit-tests_istio/1605456664301932544) | true | `/test unit-tests`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-12-21 15:26 UTC, howardjohn requested changes
This was added explicitly to support Knative, who is still using it. https://github.com/knative/operator/blob/6f94c4f029e102e753ea4786a4780acc0ceff42e/cmd/operator/kodata/ingress/1.8/net-istio.yaml#L119. The long term path is gateway-api

2022-12-22 00:25 UTC, hzxuzhonghu commented
got it

2022-12-22 00:27 UTC, closed without merging