Add configurable priorityClassName to Gateway
istio/istio pull request #42813
Opened 2023-01-13 21:41 UTC by erismaster

Add the ability to configure the priorityClassName in the "gateway" helm chart.

Signed-off-by: Derrik Campau <dcampau@vmware.com>

**Please provide a description of this PR:**

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [x] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2023-01-13 21:41 UTC, istio-testing commented
Hi @erismaster. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-01-13 21:45 UTC, erismaster commented
I updated the docs here to remove the statement that helm is being deprecated. I did a similar change in a [prior PR](https://github.com/istio/istio/pull/42018) but missed this one. 

Also, do I need to add this key into profiles/default.yaml? I see that there is a "gateways" section but that seems to line up with the older "gateways" chart, rather than the "gateway" chart.

2023-01-14 09:29 UTC, zirain requested changes
https://github.com/istio/istio/pull/42815#pullrequestreview-1248706607

2023-01-27 22:06 UTC, istio-testing commented
PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-03-01 05:04 UTC, closed without merging