[WIP] OCSP stapling
istio/istio pull request #42837
Opened 2023-01-17 04:08 UTC by lukbuc

**Please provide a description of this PR:**
This PR adds support for OCSP stapling with SDS is enabled.
When optional OSCP staple is present in kubernetes secret, pilot forwards staple inline bytes to Envoy.
This effectively enables OSCP stapling feature implemented in Envoy.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [*] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

Related to #17763

2023-01-17 04:08 UTC, istio-testing commented
Hi @lukbuc. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-01-17 07:11 UTC, kfaseela commented
could you please push the PR on master branch, so that it goes to the right working group owners for review?

2023-01-18 01:20 UTC, dhawton requested changes
This needs to be based and opened against master.

2023-01-18 12:19 UTC, closed without merging

2023-01-18 12:30 UTC, lukbuc commented
@kfaseela @dhawton Thank you. Raised new PR against master as you advised #42859
Sorting out CLA.