Update sample for metallb yaml file
istio/istio pull request #43049
Opened 2023-01-30 09:47 UTC by my-git9

**Please provide a description of this PR:**
Update sample for metallb yaml file

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [x] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2023-01-30 09:54 UTC, istio-testing commented
@my-git9: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | 2e84d665279fdeddcfbbe85683651bf466409a90 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43049/unit-tests-arm64_istio/1619995753894121472) | true | `/test unit-tests-arm64`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-01-30 15:08 UTC, ericvn requested changes
The change here is for a file in common which comes from an upstream istio/common-files repo. Any change would need to be made there and it would be copied out to the repos.

2023-01-30 15:12 UTC, ericvn commented
Noting also that this change will be picked up in all the testing and would need to be tested there first. @howardjohn may have steps that would test this before actually putting in the pipeline.

2023-01-30 16:31 UTC, howardjohn reviewed
I thought there is some CRD needed on mtallb new versions?

2023-01-30 16:31 UTC, howardjohn commented on common/scripts/metallb.yaml
> +          image: quay.io/metallb/speaker:v0.12.1
Need to avoid `quay.io`, they are unreliable. I've mirror to gcr.io/istio-testing/metallb/speaker

2023-01-30 16:31 UTC, howardjohn commented on common/scripts/metallb.yaml
> +            initialDelaySeconds: 10
do we really need this so long? This may make it take 20s to get ready, slowing down everything

2023-02-01 14:15 UTC, my-git9 commented
> I thought there is some CRD needed on mtallb new versions?

0.13 release needs some CRD, 0.12 release doesn't seems need

2023-02-01 14:16 UTC, my-git9 commented
> The change here is for a file in common which comes from an upstream istio/common-files repo. Any change would need to be made there and it would be copied out to the repos.

OK，thanks

2023-02-01 14:17 UTC, my-git9 commented
@howardjohn @ericvn Thanks for your review, I will close this PR and commit it in istio/common-files.

2023-02-01 14:17 UTC, closed without merging