NDS: merge name info by hostname
istio/istio pull request #43152
Opened 2023-02-06 02:52 UTC by dddddai

**Please provide a description of this PR:**
When a SE has multiple vips, we should merge those ips into the DNS name info instead of overriding
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mysql-external
spec:
  hosts:
  - mysql-01.foo.bar
  addresses:
  - 10.0.0.5
  - 10.0.0.6
  ports:
  - name: tcp
    number: 3306
    protocol: tcp
  location: MESH_EXTERNAL
```

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [x] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2023-02-06 06:35 UTC, hzxuzhonghu reviewed
Originally the addreesses in serviceentry are not to be resolved by DNS proxy. It is used to match traffic's dest IP.  Not sure if itmatters

2023-02-06 07:17 UTC, dddddai commented
I think it does matter: https://istio.io/latest/docs/ops/configuration/traffic-management/dns-proxy/#dns-capture-in-action

2023-02-06 11:08 UTC, hzxuzhonghu commented
Multi adrresses is not meant to be used for DNS resolving. It is to match dst addr.

2023-02-07 06:42 UTC, dddddai commented
Regardless of multiple addresses, the same happens to SE as a "decorator" of k8s Service? If we don't merge, the DNS proxy would not be able to resolve short names

We are doing a similar check when building sidecar scopes
https://github.com/istio/istio/blob/1.16.2/pilot/pkg/model/sidecar.go#L200-L209

2023-02-07 07:39 UTC, dddddai commented
Regardless of multiple addresses, the same happens to [SE as a "decorator" of k8s Service](https://github.com/istio/api/blob/1.16.2/networking/v1beta1/service_entry.proto#L824)? If we don't prioritize k8s Service, the DNS proxy would not be able to resolve short names

We are doing a similar check when building sidecar scopes
https://github.com/istio/istio/blob/1.16.2/pilot/pkg/model/sidecar.go#L200-L209

2023-02-07 08:18 UTC, hzxuzhonghu commented on pkg/dns/server/name_table.go
> +			if svc.Attributes.ServiceRegistry == provider.Kubernetes {
check `!strings.HasSuffix(hostName.String(), "."+constants.DefaultClusterSetLocalDomain)`

2023-02-07 08:23 UTC, hzxuzhonghu commented on pkg/dns/server/name_table_test.go
> +	decoratedService.Attributes.ServiceRegistry = provider.Kubernetes
Add another case: k8s service created ealier than SE

2023-02-07 08:33 UTC, dddddai commented on pkg/dns/server/name_table.go
> +			if svc.Attributes.ServiceRegistry == provider.Kubernetes {
Checked at L140

2023-02-07 08:38 UTC, hzxuzhonghu approved these changes

2023-02-13 15:27 UTC, GregHanson requested changes
since I don't think there is a linked issue for this one - could you link this PR (full url) in the `issues` field so the generated release notes link back to this.  This way users will be able to see your example ServiceEntry to determine whether or not this is something affecting them

2023-02-14 13:36 UTC, GregHanson approved these changes
release note looks good

2023-02-14 13:48 UTC, istio-testing commented
@dddddai: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests_istio | bd259dc4c8319ead984c758ae47dc5b365e7702d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43152/unit-tests_istio/1625489202609131520) | unknown | `/test unit-tests`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-14 14:25 UTC, dddddai commented
/retest

2023-02-14 14:40 UTC, merged