Added extra args to the istiod
istio/istio pull request #43166
Opened 2023-02-06 18:54 UTC by fsadykov

Hello Istio Comunity,

I was deploying the `istio` using helm by following the official documentation and I was not able to find the proper way of adding the extra arguments to `istiod` helm chart. It's very useful to add arguments see the example below
```
      - args:
        - discovery
        - --monitoringAddr=:15014
        - --log_output_level=default:info
        - --domain
        - cluster.local
        - --keepaliveMaxServerConnectionAge
        - 30m
        - --tlsCertFile=/var/run/secrets/istiod/tls/tls.crt
        - --tlsKeyFile=/var/run/secrets/istiod/tls/tls.key
        - --caCertFile=/var/run/secrets/istiod/tls/ca.crt
```

The values.yaml
```
  extraArgs:
  - --tlsCertFile=/var/run/secrets/istiod/tls/tls.crt
  - --tlsKeyFile=/var/run/secrets/istiod/tls/tls.key
  - --caCertFile=/var/run/secrets/istiod/tls/ca.crt
```
By using this feature during the helm deployment I am adding my root ca and CA for the istiod to use it

2023-02-06 18:54 UTC, istio-testing commented
Hi @fsadykov. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-02-07 01:44 UTC, morvencao reviewed
/ok-to-test

2023-02-07 01:45 UTC, istio-testing commented
@fsadykov: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 89b77b6a28986a9bd265308f86cf55ac157e35c5 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/release-notes_istio/1622773222502043648) | true | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-07 01:50 UTC, istio-testing commented
@fsadykov: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 89b77b6a28986a9bd265308f86cf55ac157e35c5 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/release-notes_istio/1622773222502043648) | true | `/test release-notes`
gencheck_istio | 89b77b6a28986a9bd265308f86cf55ac157e35c5 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/gencheck_istio/1622773221671571456) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-07 01:52 UTC, istio-testing commented
@fsadykov: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 89b77b6a28986a9bd265308f86cf55ac157e35c5 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/release-notes_istio/1622773222502043648) | true | `/test release-notes`
gencheck_istio | 89b77b6a28986a9bd265308f86cf55ac157e35c5 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/gencheck_istio/1622773221671571456) | true | `/test gencheck`
unit-tests-arm64_istio | 89b77b6a28986a9bd265308f86cf55ac157e35c5 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/unit-tests-arm64_istio/1622773210254675968) | true | `/test unit-tests-arm64`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-07 01:55 UTC, istio-testing commented
@fsadykov: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 89b77b6a28986a9bd265308f86cf55ac157e35c5 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/release-notes_istio/1622773222502043648) | true | `/test release-notes`
gencheck_istio | 89b77b6a28986a9bd265308f86cf55ac157e35c5 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/gencheck_istio/1622773221671571456) | true | `/test gencheck`
unit-tests-arm64_istio | 89b77b6a28986a9bd265308f86cf55ac157e35c5 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/unit-tests-arm64_istio/1622773210254675968) | true | `/test unit-tests-arm64`
unit-tests_istio | 89b77b6a28986a9bd265308f86cf55ac157e35c5 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/unit-tests_istio/1622773210212732928) | true | `/test unit-tests`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-07 05:07 UTC, fsadykov commented
/test release-notes

2023-02-07 05:11 UTC, istio-testing commented
@fsadykov: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
gencheck_istio | 89b77b6a28986a9bd265308f86cf55ac157e35c5 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/gencheck_istio/1622773221671571456) | true | `/test gencheck`
unit-tests_istio | 89b77b6a28986a9bd265308f86cf55ac157e35c5 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/unit-tests_istio/1622773210212732928) | true | `/test unit-tests`
unit-tests-arm64_istio | 0afea29c32f14255526096f38d7f0b84b2372a90 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/unit-tests-arm64_istio/1622824434731585536) | true | `/test unit-tests-arm64`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-07 05:17 UTC, istio-testing commented
@fsadykov: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests_istio | 89b77b6a28986a9bd265308f86cf55ac157e35c5 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/unit-tests_istio/1622773210212732928) | true | `/test unit-tests`
unit-tests-arm64_istio | 0afea29c32f14255526096f38d7f0b84b2372a90 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/unit-tests-arm64_istio/1622824434731585536) | true | `/test unit-tests-arm64`
gencheck_istio | 0afea29c32f14255526096f38d7f0b84b2372a90 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/gencheck_istio/1622824445586444288) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-07 05:20 UTC, costinm commented
I would suggest converting them to env variables or even better to mesh
config. We still have a couple of CLI args for Istiod - but not sure it's
worth the confusion.

On Mon, Feb 6, 2023 at 10:54 AM Farkhod Sadykov ***@***.***>
wrote:

> Hello Istio Comunity,
>
> I was deploying the istio using helm by following the official
> documentation and I was not able to find the proper way of adding the extra
> arguments to istiod helm chart. It's very useful to add arguments see the
> example below
>
>       - args:
>         - discovery
>         - --monitoringAddr=:15014
>         - --log_output_level=default:info
>         - --domain
>         - cluster.local
>         - --keepaliveMaxServerConnectionAge
>         - 30m
>         - --tlsCertFile=/var/run/secrets/istiod/tls/tls.crt
>         - --tlsKeyFile=/var/run/secrets/istiod/tls/tls.key
>         - --caCertFile=/var/run/secrets/istiod/tls/ca.crt
>
> The values.yaml
>
>   extraArgs:
>   - --tlsCertFile=/var/run/secrets/istiod/tls/tls.crt
>   - --tlsKeyFile=/var/run/secrets/istiod/tls/tls.key
>   - --caCertFile=/var/run/secrets/istiod/tls/ca.crt
>
> By using this feature during the helm deployment I am adding my root ca
> and CA for the istiod to use it
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/istio/istio/pull/43166
> Commit Summary
>
>    - 79cae74
>    <https://github.com/istio/istio/pull/43166/commits/79cae7472d2692258e0727b1d695c71b7854ea5c>
>    feat: Added extra args to the istiod
>
> File Changes
>
> (2 files <https://github.com/istio/istio/pull/43166/files>)
>
>    - *M*
>    manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
>    <https://github.com/istio/istio/pull/43166/files#diff-c71b5da3febbbad43972a7cfc22662ef85210a3c008217cc4e4f10f9dab701e0>
>    (3)
>    - *M* manifests/charts/istio-control/istio-discovery/values.yaml
>    <https://github.com/istio/istio/pull/43166/files#diff-72aceeff43207b39e2ff9d8d20cb5e26eafe3c7a07d3e648099887b3c47f549e>
>    (4)
>
> Patch Links:
>
>    - https://github.com/istio/istio/pull/43166.patch
>    - https://github.com/istio/istio/pull/43166.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/istio/pull/43166>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAUR2VHOATADBJ2NFTKII3WWFCHDANCNFSM6AAAAAAUTBH3XA>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-02-07 05:21 UTC, istio-testing commented
@fsadykov: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | 0afea29c32f14255526096f38d7f0b84b2372a90 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/unit-tests-arm64_istio/1622824434731585536) | true | `/test unit-tests-arm64`
gencheck_istio | 0afea29c32f14255526096f38d7f0b84b2372a90 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/gencheck_istio/1622824445586444288) | true | `/test gencheck`
unit-tests_istio | 0afea29c32f14255526096f38d7f0b84b2372a90 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/unit-tests_istio/1622824434689642496) | true | `/test unit-tests`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-07 05:35 UTC, fsadykov commented
@costinm It would be very nice if we could add the arguments. We are currently not using the `istioctl` or `istio-operator` to deploy it. So having the arguments definitely would help us to deploy properly. Regarding environment variables I was not able to find on official documentation 

https://istio.io/latest/docs/reference/commands/pilot-discovery/



We are using these arguments
```
  extraArgs:
  - --tlsCertFile=/var/run/secrets/istiod/tls/tls.crt
  - --tlsKeyFile=/var/run/secrets/istiod/tls/tls.key
  - --caCertFile=/var/run/secrets/istiod/tls/ca.crt
```

2023-02-07 16:07 UTC, ericvn commented on releasenotes/notes/istiod-helm-args.yaml
> +  **Added** added extra args to istio controller helm chart.
You don't need the double added.
Capitalize Istio.
Not sure if this is better under installation or extensibility.

2023-02-07 17:12 UTC, istio-testing commented
@fsadykov: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | 0afea29c32f14255526096f38d7f0b84b2372a90 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/unit-tests-arm64_istio/1622824434731585536) | true | `/test unit-tests-arm64`
unit-tests_istio | 0afea29c32f14255526096f38d7f0b84b2372a90 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/unit-tests_istio/1622824434689642496) | true | `/test unit-tests`
gencheck_istio | f198acb6d73a1875aae4b0918b35861601c3628b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/gencheck_istio/1623005080443686912) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-07 17:13 UTC, istio-testing commented
@fsadykov: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests_istio | 0afea29c32f14255526096f38d7f0b84b2372a90 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/unit-tests_istio/1622824434689642496) | true | `/test unit-tests`
gencheck_istio | f198acb6d73a1875aae4b0918b35861601c3628b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/gencheck_istio/1623005080443686912) | true | `/test gencheck`
unit-tests-arm64_istio | f198acb6d73a1875aae4b0918b35861601c3628b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/unit-tests-arm64_istio/1623005069030985728) | true | `/test unit-tests-arm64`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-07 17:16 UTC, istio-testing commented
@fsadykov: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
gencheck_istio | f198acb6d73a1875aae4b0918b35861601c3628b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/gencheck_istio/1623005080443686912) | true | `/test gencheck`
unit-tests-arm64_istio | f198acb6d73a1875aae4b0918b35861601c3628b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/unit-tests-arm64_istio/1623005069030985728) | true | `/test unit-tests-arm64`
unit-tests_istio | f198acb6d73a1875aae4b0918b35861601c3628b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/unit-tests_istio/1623005068993236992) | true | `/test unit-tests`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-07 17:23 UTC, istio-testing commented
@fsadykov: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
gencheck_istio | f198acb6d73a1875aae4b0918b35861601c3628b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/gencheck_istio/1623005080443686912) | true | `/test gencheck`
unit-tests_istio | f198acb6d73a1875aae4b0918b35861601c3628b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/unit-tests_istio/1623005068993236992) | true | `/test unit-tests`
unit-tests-arm64_istio | f9a42cc977a18b37bd5665a10024a3fbef15e7fe | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/unit-tests-arm64_istio/1623008707170275328) | true | `/test unit-tests-arm64`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-07 17:25 UTC, istio-testing commented
@fsadykov: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests_istio | f198acb6d73a1875aae4b0918b35861601c3628b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/unit-tests_istio/1623005068993236992) | true | `/test unit-tests`
unit-tests-arm64_istio | f9a42cc977a18b37bd5665a10024a3fbef15e7fe | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/unit-tests-arm64_istio/1623008707170275328) | true | `/test unit-tests-arm64`
gencheck_istio | f9a42cc977a18b37bd5665a10024a3fbef15e7fe | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/gencheck_istio/1623008733632139264) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-07 17:29 UTC, istio-testing commented
@fsadykov: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | f9a42cc977a18b37bd5665a10024a3fbef15e7fe | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/unit-tests-arm64_istio/1623008707170275328) | true | `/test unit-tests-arm64`
gencheck_istio | f9a42cc977a18b37bd5665a10024a3fbef15e7fe | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/gencheck_istio/1623008733632139264) | true | `/test gencheck`
unit-tests_istio | f9a42cc977a18b37bd5665a10024a3fbef15e7fe | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/unit-tests_istio/1623008707132526592) | true | `/test unit-tests`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-07 18:04 UTC, istio-testing commented
@fsadykov: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests_istio | f9a42cc977a18b37bd5665a10024a3fbef15e7fe | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/unit-tests_istio/1623008707132526592) | true | `/test unit-tests`
gencheck_istio | 26cdbb9f759cc8582b0f64dfe80e11debdccc82b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/gencheck_istio/1623018400332648448) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-07 19:10 UTC, costinm commented
Helm has a mechanism to update the env vars ( pilot.env ) - and we have a pretty large number of settings using env variables. We have a couple of remaining settings via args, but we never added a mechanism to specify them - in part to encourage devs to add any setting using either MeshConfig or env. 

I think with the exception of istioctl - none of the servers should require CLI args - which also means helm doesn't need 2 mechanism to customize the same kind of settings. 

So my suggestion was: if you need to configure one of the remaining options using CLI, it would be better to change the code to support env. My understanding was that all CLI args can also be set as env ( or someone has worked on this), so maybe that's already done, but that was long ago, don't remember the status.

2023-02-07 19:14 UTC, costinm commented
@therealmitchconnors - do you remember this ? Viper or something ? 

We also discussed having all settings in MeshConfig or ProxyConfig - with documentation on which can be dynamically changed without restart ( both env variables and CLI require restart - but if we have the same settings in MeshConfig, some can be made dynamic ).

2023-02-07 20:31 UTC, therealmitchconnors commented
Unfortunately, all the work to use viper to make all CLI settings accessible from ENV vars has been removed from the project.  Restoring that parity might be a better way to resolve this user's issue.

2023-02-07 20:40 UTC, istio-testing commented
@fsadykov: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-security-multicluster_istio | e255c58873050563f2295d476d7ca0fc3a8bdb72 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/integ-security-multicluster_istio/1623029689993924608) | true | `/test integ-security-multicluster`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-08 06:18 UTC, costinm commented
Are only those 3 args that are needed ? We can go case-by-case - either convert those args or use the same pattern we have for agent, check if the files exist ( and define a well-known location - we do support mounting volume as an option in helm ) and just deprecate the 3 CLI args.

Other opinions ? @howardjohn ? I guess we can add the args to helm as well - we have plenty of other options that are rarely used and an even larger number of options and APIs that will not be needed in ambient, maybe we can do an
Istiod args/options cleanup when ambient is ready and not worry for now ?

2023-02-08 16:43 UTC, bleggett commented
I agree that ultimately meshconfig or env vars are probably better choices. That being said, as long as istiod supports CLI flags, I think we should let people freely specify them with Helm overrides if they wish to.

2023-02-08 23:30 UTC, therealmitchconnors requested changes
After offline conversations with @fsadykov, I will expose these flags as environment variables, which can be set through pilot.env

2023-02-10 19:34 UTC, howardjohn commented
https://github.com/istio/istio/pull/42398/files is also adding some args... we may need a consistent approach

2023-02-11 05:38 UTC, costinm commented
We have settings in MeshConfig, env and CLI.

I can't imagine a consistent approach where all settings are in the CLI.
Env are a bit easier to work with - but can't support dynamic changes.
MeshConfig allows dynamic changes - and I think is the second best option (
actual CRD / API like we did for telemetry is better if the feature is
broadly used).

I was looking if we can change the code that returns 'env' variables to
peek inside MeshConfig ( using some field like we have in ProxyConfig for
meta / env for sidecar ).
Code seems pretty simple - but the deps are more tricky since the code is
in a different package. Opinions ?
That would make MeshConfig the only source for Istiod.

On Fri, Feb 10, 2023 at 11:34 AM John Howard ***@***.***>
wrote:

> https://github.com/istio/istio/pull/42398/files is also adding some
> args... we may need a consistent approach
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/istio/pull/43166#issuecomment-1426249306>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAUR2Q4Q6O7JUZKPAODU5TWW2J4XANCNFSM6AAAAAAUTBH3XA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-13 17:43 UTC, jacob-delgado commented
This has been an issue before for integrating cert-manager and istio-csr (see https://raw.githubusercontent.com/cert-manager/website/master/content/docs/tutorials/istio-csr/example/istio-config-getting-started.yaml).

I'm fine with meshConfig being the source of truth for all of this, but there's been discussions about deprecating that for years now. At this point I'd say it's not really going away. A real CRD would be the best approach, but that would require more resources than Istio has at this point.

Let's see what @therealmitchconnors does as that may be expedient for users, like ourselves, that have to modify charts to allow our users to expose modify these settings to fit their environments.

2023-02-15 22:05 UTC, istio-testing commented
PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-02-17 20:23 UTC, istio-testing commented
@fsadykov: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | e255c58873050563f2295d476d7ca0fc3a8bdb72 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/integ-ambient_istio/1626678661748887552) | true | `/test integ-ambient`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-28 19:43 UTC, istio-testing commented
@fsadykov: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | e255c58873050563f2295d476d7ca0fc3a8bdb72 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43166/integ-ambient_istio/1630654686170189824) | true | `/test integ-ambient`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-03-06 17:41 UTC, closed without merging

2023-04-28 07:06 UTC, Tenseiga commented
why was this closed. I think the requirement was a valid one.