fix disabling ALL_METRICS does not work as expected
istio/istio pull request #43179
Opened 2023-02-07 12:34 UTC by zirain

Signed-off-by: hejianpeng <hejianpeng2@huawei.com>

**Please provide a description of this PR:**

fixes: #43178

2023-02-07 12:37 UTC, istio-testing commented
@zirain: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | ec9976f7a61f06487e6a6112fa21028c57aef2f1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43179/release-notes_istio/1622937293608194048) | true | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-07 12:40 UTC, istio-testing commented
@zirain: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | ec9976f7a61f06487e6a6112fa21028c57aef2f1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43179/release-notes_istio/1622937293608194048) | true | `/test release-notes`
lint_istio | ec9976f7a61f06487e6a6112fa21028c57aef2f1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43179/lint_istio/1622937291095805952) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-07 12:42 UTC, istio-testing commented
@zirain: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | ec9976f7a61f06487e6a6112fa21028c57aef2f1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43179/release-notes_istio/1622937293608194048) | true | `/test release-notes`
lint_istio | ec9976f7a61f06487e6a6112fa21028c57aef2f1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43179/lint_istio/1622937291095805952) | true | `/test lint`
unit-tests-arm64_istio | ec9976f7a61f06487e6a6112fa21028c57aef2f1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43179/unit-tests-arm64_istio/1622937262582927360) | true | `/test unit-tests-arm64`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-07 12:45 UTC, istio-testing commented
@zirain: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | ec9976f7a61f06487e6a6112fa21028c57aef2f1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43179/release-notes_istio/1622937293608194048) | true | `/test release-notes`
lint_istio | ec9976f7a61f06487e6a6112fa21028c57aef2f1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43179/lint_istio/1622937291095805952) | true | `/test lint`
unit-tests-arm64_istio | ec9976f7a61f06487e6a6112fa21028c57aef2f1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43179/unit-tests-arm64_istio/1622937262582927360) | true | `/test unit-tests-arm64`
gencheck_istio | ec9976f7a61f06487e6a6112fa21028c57aef2f1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43179/gencheck_istio/1622937291938861056) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-10 19:41 UTC, kyessenov requested changes
LGTM, some style improvement.

2023-02-10 19:41 UTC, kyessenov commented on pilot/pkg/model/telemetry.go
> +	metricCfg := filterConfig.MetricsForClass(class)
reuse variable `listenerCfg` above

2023-02-10 19:41 UTC, kyessenov commented on pilot/pkg/model/telemetry.go
> +	if !metricCfg.Disabled {
superfluous check

2023-02-13 15:35 UTC, GregHanson commented on releasenotes/notes/43179.yaml
> +    **Fixed** disabling ALL_METRICS does not work as expected.
```suggestion
    **Fixed**  an issue where `ALL_METRICS` does not disable metrics as expected.
```

2023-02-13 23:05 UTC, kyessenov approved these changes
I'd like @lei-tang to take a look since we're close to a release.

2023-02-13 23:59 UTC, lei-tang approved these changes

2023-02-15 13:56 UTC, GregHanson approved these changes
release note looks good

2023-02-15 14:25 UTC, ericvn approved these changes
Test and RN look good.

2023-02-16 01:20 UTC, hzxuzhonghu approved these changes

2023-02-16 02:39 UTC, merged

2023-02-16 02:40 UTC, istio-testing commented
In response to a cherrypick label: #43179 failed to apply on top of branch "release-1.15":
```
Applying: fix disabling ALL_METERS does not work as expected
Using index info to reconstruct a base tree...
M	pilot/pkg/model/telemetry.go
Falling back to patching base and 3-way merge...
Auto-merging pilot/pkg/model/telemetry.go
CONFLICT (content): Merge conflict in pilot/pkg/model/telemetry.go
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Patch failed at 0001 fix disabling ALL_METERS does not work as expected
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

```

2023-02-16 02:40 UTC, istio-testing commented
In response to a cherrypick label: new issue created for failed cherrypick: #43392

2023-02-16 02:40 UTC, istio-testing commented
In response to a cherrypick label: #43179 failed to apply on top of branch "release-1.16":
```
Applying: fix disabling ALL_METERS does not work as expected
Using index info to reconstruct a base tree...
M	pilot/pkg/model/telemetry.go
Falling back to patching base and 3-way merge...
Auto-merging pilot/pkg/model/telemetry.go
CONFLICT (content): Merge conflict in pilot/pkg/model/telemetry.go
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Patch failed at 0001 fix disabling ALL_METERS does not work as expected
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

```

2023-02-16 02:40 UTC, istio-testing commented
In response to a cherrypick label: new issue created for failed cherrypick: #43393

2023-02-16 02:41 UTC, istio-testing commented
In response to a cherrypick label: new pull request created: #43394