Add label and annotations to gateway role
istio/istio pull request #43351
Opened 2023-02-15 08:30 UTC by anderssonw

**Please provide a description of this PR:**

Brings the chart more in line with the comment regarding labels and annotations. Currently, annotations and labels are not added to Role and RoleBinding for gateways, which is somewhat annoying seeing as our project would like to describe any role and rolebinding present in our cluster, unless we cant.

Simply adds the labels and annotations metadata in the same way other resources in the chart uses them.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [x] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2023-02-15 08:30 UTC, istio-testing commented
Hi @anderssonw. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-02-15 11:49 UTC, ymesika commented
/ok-to-test

2023-02-15 13:29 UTC, zirain requested changes
Thanks for the PR! This can and should be done by https://istio.io/latest/docs/setup/additional-setup/customize-installation-helm/

2023-02-15 14:54 UTC, howardjohn approved these changes
LGTM, intent of these is to be applied to all objects.

2023-02-16 07:25 UTC, anderssonw commented
> Thanks for the PR! This can and should be done by https://istio.io/latest/docs/setup/additional-setup/customize-installation-helm/

Why on earth should annotations and labels in a chart, documented as being applied to everything while it currently isn't, be applied through a custom patch? This seems very finicky for something as simple as annotations and labels.

2023-02-17 20:35 UTC, istio-testing commented
@anderssonw: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | b573d7654c236805d9ca25e47a233a81dc7be226 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43351/integ-ambient_istio/1626678587182551040) | true | `/test integ-ambient`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-21 03:24 UTC, zirain approved these changes

2023-02-21 03:28 UTC, istio-testing commented
@anderssonw: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | b573d7654c236805d9ca25e47a233a81dc7be226 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43351/integ-ambient_istio/1626678587182551040) | true | `/test integ-ambient`
release-notes_istio | b573d7654c236805d9ca25e47a233a81dc7be226 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43351/release-notes_istio/1627871883581984768) | unknown | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-21 15:48 UTC, howardjohn commented
/retest

2023-02-21 16:58 UTC, merged