remove PILOT_SKIP_VALIDATE_TRUST_DOMAIN
istio/istio pull request #43424
Opened 2023-02-17 03:43 UTC by hzxuzhonghu

**Please provide a description of this PR:**

This flag was introduced in #16798, not valid anymore

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [x] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2023-02-17 14:39 UTC, GregHanson requested changes
a release note should be added to highlight the removal of `PILOT_SKIP_VALIDATE_TRUST_DOMAIN` env var so users know it no longer needs to be configured in their deployments

2023-02-17 15:51 UTC, howardjohn commented
We have some usage of this in our distro, can you give me a bit of time to check with the owners if we can remove it? I think we can just want to verify.

2023-02-17 17:06 UTC, shankgan commented
looks LGTM to me

2023-02-17 17:15 UTC, howardjohn commented
LGTM

2023-02-17 18:31 UTC, richardwxn approved these changes

2023-02-17 20:26 UTC, istio-testing commented
@hzxuzhonghu: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | 97e4c66e0147c2e1c98fbc3be89143ed039d8f08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ambient_istio/1626678514704977920) | true | `/test integ-ambient`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-20 03:07 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | 97e4c66e0147c2e1c98fbc3be89143ed039d8f08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ambient_istio/1626678514704977920) | true | `/test integ-ambient`
unit-tests-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests-arm64_istio/1627504931403468800) | true | `/test unit-tests-arm64`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-20 03:07 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | 97e4c66e0147c2e1c98fbc3be89143ed039d8f08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ambient_istio/1626678514704977920) | true | `/test integ-ambient`
unit-tests-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests-arm64_istio/1627504931403468800) | true | `/test unit-tests-arm64`
unit-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests_istio/1627504931365720064) | true | `/test unit-tests`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-20 03:08 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | 97e4c66e0147c2e1c98fbc3be89143ed039d8f08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ambient_istio/1626678514704977920) | true | `/test integ-ambient`
unit-tests-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests-arm64_istio/1627504931403468800) | true | `/test unit-tests-arm64`
unit-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests_istio/1627504931365720064) | true | `/test unit-tests`
integ-basic-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-basic-arm64_istio/1627504932196192256) | true | `/test integ-basic-arm64`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-20 03:08 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | 97e4c66e0147c2e1c98fbc3be89143ed039d8f08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ambient_istio/1626678514704977920) | true | `/test integ-ambient`
unit-tests-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests-arm64_istio/1627504931403468800) | true | `/test unit-tests-arm64`
unit-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests_istio/1627504931365720064) | true | `/test unit-tests`
integ-basic-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-basic-arm64_istio/1627504932196192256) | true | `/test integ-basic-arm64`
release-test_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/release-test_istio/1627504931441217536) | true | `/test release-test`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-20 03:08 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | 97e4c66e0147c2e1c98fbc3be89143ed039d8f08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ambient_istio/1626678514704977920) | true | `/test integ-ambient`
unit-tests-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests-arm64_istio/1627504931403468800) | true | `/test unit-tests-arm64`
unit-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests_istio/1627504931365720064) | true | `/test unit-tests`
integ-basic-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-basic-arm64_istio/1627504932196192256) | true | `/test integ-basic-arm64`
release-test_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/release-test_istio/1627504931441217536) | true | `/test release-test`
analyze-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/analyze-tests_istio/1627504940576411648) | true | `/test analyze-tests`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-20 03:09 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | 97e4c66e0147c2e1c98fbc3be89143ed039d8f08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ambient_istio/1626678514704977920) | true | `/test integ-ambient`
unit-tests-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests-arm64_istio/1627504931403468800) | true | `/test unit-tests-arm64`
unit-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests_istio/1627504931365720064) | true | `/test unit-tests`
integ-basic-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-basic-arm64_istio/1627504932196192256) | true | `/test integ-basic-arm64`
release-test_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/release-test_istio/1627504931441217536) | true | `/test release-test`
analyze-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/analyze-tests_istio/1627504940576411648) | true | `/test analyze-tests`
integ-security_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security_istio/1627504937220968448) | true | `/test integ-security`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-20 03:09 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | 97e4c66e0147c2e1c98fbc3be89143ed039d8f08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ambient_istio/1626678514704977920) | true | `/test integ-ambient`
unit-tests-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests-arm64_istio/1627504931403468800) | true | `/test unit-tests-arm64`
unit-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests_istio/1627504931365720064) | true | `/test unit-tests`
integ-basic-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-basic-arm64_istio/1627504932196192256) | true | `/test integ-basic-arm64`
release-test_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/release-test_istio/1627504931441217536) | true | `/test release-test`
analyze-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/analyze-tests_istio/1627504940576411648) | true | `/test analyze-tests`
integ-security_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security_istio/1627504937220968448) | true | `/test integ-security`
integ-pilot_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot_istio/1627504933878108160) | true | `/test integ-pilot`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-20 03:09 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | 97e4c66e0147c2e1c98fbc3be89143ed039d8f08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ambient_istio/1626678514704977920) | true | `/test integ-ambient`
unit-tests-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests-arm64_istio/1627504931403468800) | true | `/test unit-tests-arm64`
unit-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests_istio/1627504931365720064) | true | `/test unit-tests`
integ-basic-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-basic-arm64_istio/1627504932196192256) | true | `/test integ-basic-arm64`
release-test_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/release-test_istio/1627504931441217536) | true | `/test release-test`
analyze-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/analyze-tests_istio/1627504940576411648) | true | `/test analyze-tests`
integ-security_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security_istio/1627504937220968448) | true | `/test integ-security`
integ-pilot_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot_istio/1627504933878108160) | true | `/test integ-pilot`
integ-operator-controller_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-operator-controller_istio/1627504933030858752) | true | `/test integ-operator-controller`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-20 03:09 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | 97e4c66e0147c2e1c98fbc3be89143ed039d8f08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ambient_istio/1626678514704977920) | true | `/test integ-ambient`
unit-tests-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests-arm64_istio/1627504931403468800) | true | `/test unit-tests-arm64`
unit-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests_istio/1627504931365720064) | true | `/test unit-tests`
integ-basic-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-basic-arm64_istio/1627504932196192256) | true | `/test integ-basic-arm64`
release-test_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/release-test_istio/1627504931441217536) | true | `/test release-test`
analyze-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/analyze-tests_istio/1627504940576411648) | true | `/test analyze-tests`
integ-security_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security_istio/1627504937220968448) | true | `/test integ-security`
integ-pilot_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot_istio/1627504933878108160) | true | `/test integ-pilot`
integ-operator-controller_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-operator-controller_istio/1627504933030858752) | true | `/test integ-operator-controller`
integ-ds_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ds_istio/1627504931713847296) | true | `/test integ-ds`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-20 03:09 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | 97e4c66e0147c2e1c98fbc3be89143ed039d8f08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ambient_istio/1626678514704977920) | true | `/test integ-ambient`
unit-tests-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests-arm64_istio/1627504931403468800) | true | `/test unit-tests-arm64`
unit-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests_istio/1627504931365720064) | true | `/test unit-tests`
integ-basic-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-basic-arm64_istio/1627504932196192256) | true | `/test integ-basic-arm64`
release-test_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/release-test_istio/1627504931441217536) | true | `/test release-test`
analyze-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/analyze-tests_istio/1627504940576411648) | true | `/test analyze-tests`
integ-security_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security_istio/1627504937220968448) | true | `/test integ-security`
integ-pilot_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot_istio/1627504933878108160) | true | `/test integ-pilot`
integ-operator-controller_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-operator-controller_istio/1627504933030858752) | true | `/test integ-operator-controller`
integ-ds_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ds_istio/1627504931713847296) | true | `/test integ-ds`
integ-distroless_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-distroless_istio/1627504931634155520) | true | `/test integ-distroless`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-20 03:09 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | 97e4c66e0147c2e1c98fbc3be89143ed039d8f08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ambient_istio/1626678514704977920) | true | `/test integ-ambient`
unit-tests-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests-arm64_istio/1627504931403468800) | true | `/test unit-tests-arm64`
unit-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests_istio/1627504931365720064) | true | `/test unit-tests`
integ-basic-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-basic-arm64_istio/1627504932196192256) | true | `/test integ-basic-arm64`
release-test_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/release-test_istio/1627504931441217536) | true | `/test release-test`
analyze-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/analyze-tests_istio/1627504940576411648) | true | `/test analyze-tests`
integ-security_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security_istio/1627504937220968448) | true | `/test integ-security`
integ-pilot_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot_istio/1627504933878108160) | true | `/test integ-pilot`
integ-operator-controller_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-operator-controller_istio/1627504933030858752) | true | `/test integ-operator-controller`
integ-ds_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ds_istio/1627504931713847296) | true | `/test integ-ds`
integ-distroless_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-distroless_istio/1627504931634155520) | true | `/test integ-distroless`
integ-ipv6_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ipv6_istio/1627504931671904256) | true | `/test integ-ipv6`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-20 03:09 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | 97e4c66e0147c2e1c98fbc3be89143ed039d8f08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ambient_istio/1626678514704977920) | true | `/test integ-ambient`
unit-tests-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests-arm64_istio/1627504931403468800) | true | `/test unit-tests-arm64`
unit-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests_istio/1627504931365720064) | true | `/test unit-tests`
integ-basic-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-basic-arm64_istio/1627504932196192256) | true | `/test integ-basic-arm64`
release-test_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/release-test_istio/1627504931441217536) | true | `/test release-test`
analyze-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/analyze-tests_istio/1627504940576411648) | true | `/test analyze-tests`
integ-security_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security_istio/1627504937220968448) | true | `/test integ-security`
integ-pilot_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot_istio/1627504933878108160) | true | `/test integ-pilot`
integ-operator-controller_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-operator-controller_istio/1627504933030858752) | true | `/test integ-operator-controller`
integ-ds_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ds_istio/1627504931713847296) | true | `/test integ-ds`
integ-distroless_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-distroless_istio/1627504931634155520) | true | `/test integ-distroless`
integ-ipv6_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ipv6_istio/1627504931671904256) | true | `/test integ-ipv6`
integ-telemetry-istiodremote_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry-istiodremote_istio/1627504931596406784) | true | `/test integ-telemetry-istiodremote`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-20 03:09 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | 97e4c66e0147c2e1c98fbc3be89143ed039d8f08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ambient_istio/1626678514704977920) | true | `/test integ-ambient`
unit-tests-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests-arm64_istio/1627504931403468800) | true | `/test unit-tests-arm64`
unit-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests_istio/1627504931365720064) | true | `/test unit-tests`
integ-basic-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-basic-arm64_istio/1627504932196192256) | true | `/test integ-basic-arm64`
release-test_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/release-test_istio/1627504931441217536) | true | `/test release-test`
analyze-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/analyze-tests_istio/1627504940576411648) | true | `/test analyze-tests`
integ-security_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security_istio/1627504937220968448) | true | `/test integ-security`
integ-pilot_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot_istio/1627504933878108160) | true | `/test integ-pilot`
integ-operator-controller_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-operator-controller_istio/1627504933030858752) | true | `/test integ-operator-controller`
integ-ds_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ds_istio/1627504931713847296) | true | `/test integ-ds`
integ-distroless_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-distroless_istio/1627504931634155520) | true | `/test integ-distroless`
integ-ipv6_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ipv6_istio/1627504931671904256) | true | `/test integ-ipv6`
integ-telemetry-istiodremote_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry-istiodremote_istio/1627504931596406784) | true | `/test integ-telemetry-istiodremote`
lint_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/lint_istio/1627504941453021184) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-20 03:09 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | 97e4c66e0147c2e1c98fbc3be89143ed039d8f08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ambient_istio/1626678514704977920) | true | `/test integ-ambient`
unit-tests-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests-arm64_istio/1627504931403468800) | true | `/test unit-tests-arm64`
unit-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests_istio/1627504931365720064) | true | `/test unit-tests`
integ-basic-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-basic-arm64_istio/1627504932196192256) | true | `/test integ-basic-arm64`
release-test_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/release-test_istio/1627504931441217536) | true | `/test release-test`
analyze-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/analyze-tests_istio/1627504940576411648) | true | `/test analyze-tests`
integ-security_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security_istio/1627504937220968448) | true | `/test integ-security`
integ-pilot_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot_istio/1627504933878108160) | true | `/test integ-pilot`
integ-operator-controller_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-operator-controller_istio/1627504933030858752) | true | `/test integ-operator-controller`
integ-ds_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ds_istio/1627504931713847296) | true | `/test integ-ds`
integ-distroless_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-distroless_istio/1627504931634155520) | true | `/test integ-distroless`
integ-ipv6_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ipv6_istio/1627504931671904256) | true | `/test integ-ipv6`
integ-telemetry-istiodremote_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry-istiodremote_istio/1627504931596406784) | true | `/test integ-telemetry-istiodremote`
lint_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/lint_istio/1627504941453021184) | true | `/test lint`
integ-helm_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-helm_istio/1627504939741745152) | true | `/test integ-helm`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-20 03:09 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | 97e4c66e0147c2e1c98fbc3be89143ed039d8f08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ambient_istio/1626678514704977920) | true | `/test integ-ambient`
unit-tests-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests-arm64_istio/1627504931403468800) | true | `/test unit-tests-arm64`
unit-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests_istio/1627504931365720064) | true | `/test unit-tests`
integ-basic-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-basic-arm64_istio/1627504932196192256) | true | `/test integ-basic-arm64`
release-test_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/release-test_istio/1627504931441217536) | true | `/test release-test`
analyze-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/analyze-tests_istio/1627504940576411648) | true | `/test analyze-tests`
integ-security_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security_istio/1627504937220968448) | true | `/test integ-security`
integ-pilot_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot_istio/1627504933878108160) | true | `/test integ-pilot`
integ-operator-controller_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-operator-controller_istio/1627504933030858752) | true | `/test integ-operator-controller`
integ-ds_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ds_istio/1627504931713847296) | true | `/test integ-ds`
integ-distroless_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-distroless_istio/1627504931634155520) | true | `/test integ-distroless`
integ-ipv6_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ipv6_istio/1627504931671904256) | true | `/test integ-ipv6`
integ-telemetry-istiodremote_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry-istiodremote_istio/1627504931596406784) | true | `/test integ-telemetry-istiodremote`
lint_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/lint_istio/1627504941453021184) | true | `/test lint`
integ-helm_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-helm_istio/1627504939741745152) | true | `/test integ-helm`
integ-cni_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-cni_istio/1627504931483160576) | true | `/test integ-cni`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-20 03:09 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | 97e4c66e0147c2e1c98fbc3be89143ed039d8f08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ambient_istio/1626678514704977920) | true | `/test integ-ambient`
unit-tests-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests-arm64_istio/1627504931403468800) | true | `/test unit-tests-arm64`
unit-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests_istio/1627504931365720064) | true | `/test unit-tests`
integ-basic-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-basic-arm64_istio/1627504932196192256) | true | `/test integ-basic-arm64`
release-test_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/release-test_istio/1627504931441217536) | true | `/test release-test`
analyze-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/analyze-tests_istio/1627504940576411648) | true | `/test analyze-tests`
integ-security_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security_istio/1627504937220968448) | true | `/test integ-security`
integ-pilot_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot_istio/1627504933878108160) | true | `/test integ-pilot`
integ-operator-controller_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-operator-controller_istio/1627504933030858752) | true | `/test integ-operator-controller`
integ-ds_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ds_istio/1627504931713847296) | true | `/test integ-ds`
integ-distroless_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-distroless_istio/1627504931634155520) | true | `/test integ-distroless`
integ-ipv6_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ipv6_istio/1627504931671904256) | true | `/test integ-ipv6`
integ-telemetry-istiodremote_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry-istiodremote_istio/1627504931596406784) | true | `/test integ-telemetry-istiodremote`
lint_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/lint_istio/1627504941453021184) | true | `/test lint`
integ-helm_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-helm_istio/1627504939741745152) | true | `/test integ-helm`
integ-cni_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-cni_istio/1627504931483160576) | true | `/test integ-cni`
integ-telemetry-mc_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry-mc_istio/1627504931567046656) | true | `/test integ-telemetry-mc`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-20 03:09 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | 97e4c66e0147c2e1c98fbc3be89143ed039d8f08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ambient_istio/1626678514704977920) | true | `/test integ-ambient`
unit-tests-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests-arm64_istio/1627504931403468800) | true | `/test unit-tests-arm64`
unit-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests_istio/1627504931365720064) | true | `/test unit-tests`
integ-basic-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-basic-arm64_istio/1627504932196192256) | true | `/test integ-basic-arm64`
release-test_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/release-test_istio/1627504931441217536) | true | `/test release-test`
analyze-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/analyze-tests_istio/1627504940576411648) | true | `/test analyze-tests`
integ-security_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security_istio/1627504937220968448) | true | `/test integ-security`
integ-pilot_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot_istio/1627504933878108160) | true | `/test integ-pilot`
integ-operator-controller_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-operator-controller_istio/1627504933030858752) | true | `/test integ-operator-controller`
integ-ds_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ds_istio/1627504931713847296) | true | `/test integ-ds`
integ-distroless_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-distroless_istio/1627504931634155520) | true | `/test integ-distroless`
integ-ipv6_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ipv6_istio/1627504931671904256) | true | `/test integ-ipv6`
integ-telemetry-istiodremote_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry-istiodremote_istio/1627504931596406784) | true | `/test integ-telemetry-istiodremote`
lint_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/lint_istio/1627504941453021184) | true | `/test lint`
integ-helm_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-helm_istio/1627504939741745152) | true | `/test integ-helm`
integ-cni_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-cni_istio/1627504931483160576) | true | `/test integ-cni`
integ-telemetry-mc_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry-mc_istio/1627504931567046656) | true | `/test integ-telemetry-mc`
integ-telemetry_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry_istio/1627504931520909312) | true | `/test integ-telemetry`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-20 03:10 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | 97e4c66e0147c2e1c98fbc3be89143ed039d8f08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ambient_istio/1626678514704977920) | true | `/test integ-ambient`
unit-tests-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests-arm64_istio/1627504931403468800) | true | `/test unit-tests-arm64`
unit-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests_istio/1627504931365720064) | true | `/test unit-tests`
integ-basic-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-basic-arm64_istio/1627504932196192256) | true | `/test integ-basic-arm64`
release-test_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/release-test_istio/1627504931441217536) | true | `/test release-test`
analyze-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/analyze-tests_istio/1627504940576411648) | true | `/test analyze-tests`
integ-security_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security_istio/1627504937220968448) | true | `/test integ-security`
integ-pilot_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot_istio/1627504933878108160) | true | `/test integ-pilot`
integ-operator-controller_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-operator-controller_istio/1627504933030858752) | true | `/test integ-operator-controller`
integ-ds_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ds_istio/1627504931713847296) | true | `/test integ-ds`
integ-distroless_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-distroless_istio/1627504931634155520) | true | `/test integ-distroless`
integ-ipv6_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ipv6_istio/1627504931671904256) | true | `/test integ-ipv6`
integ-telemetry-istiodremote_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry-istiodremote_istio/1627504931596406784) | true | `/test integ-telemetry-istiodremote`
lint_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/lint_istio/1627504941453021184) | true | `/test lint`
integ-helm_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-helm_istio/1627504939741745152) | true | `/test integ-helm`
integ-cni_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-cni_istio/1627504931483160576) | true | `/test integ-cni`
integ-telemetry-mc_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry-mc_istio/1627504931567046656) | true | `/test integ-telemetry-mc`
integ-telemetry_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry_istio/1627504931520909312) | true | `/test integ-telemetry`
integ-pilot-multicluster_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot-multicluster_istio/1627504934704386048) | true | `/test integ-pilot-multicluster`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-20 03:12 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | 97e4c66e0147c2e1c98fbc3be89143ed039d8f08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ambient_istio/1626678514704977920) | true | `/test integ-ambient`
unit-tests-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests-arm64_istio/1627504931403468800) | true | `/test unit-tests-arm64`
unit-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests_istio/1627504931365720064) | true | `/test unit-tests`
integ-basic-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-basic-arm64_istio/1627504932196192256) | true | `/test integ-basic-arm64`
release-test_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/release-test_istio/1627504931441217536) | true | `/test release-test`
analyze-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/analyze-tests_istio/1627504940576411648) | true | `/test analyze-tests`
integ-security_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security_istio/1627504937220968448) | true | `/test integ-security`
integ-pilot_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot_istio/1627504933878108160) | true | `/test integ-pilot`
integ-operator-controller_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-operator-controller_istio/1627504933030858752) | true | `/test integ-operator-controller`
integ-ds_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ds_istio/1627504931713847296) | true | `/test integ-ds`
integ-distroless_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-distroless_istio/1627504931634155520) | true | `/test integ-distroless`
integ-ipv6_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ipv6_istio/1627504931671904256) | true | `/test integ-ipv6`
integ-telemetry-istiodremote_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry-istiodremote_istio/1627504931596406784) | true | `/test integ-telemetry-istiodremote`
lint_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/lint_istio/1627504941453021184) | true | `/test lint`
integ-helm_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-helm_istio/1627504939741745152) | true | `/test integ-helm`
integ-cni_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-cni_istio/1627504931483160576) | true | `/test integ-cni`
integ-telemetry-mc_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry-mc_istio/1627504931567046656) | true | `/test integ-telemetry-mc`
integ-telemetry_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry_istio/1627504931520909312) | true | `/test integ-telemetry`
integ-pilot-multicluster_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot-multicluster_istio/1627504934704386048) | true | `/test integ-pilot-multicluster`
integ-pilot-istiodremote-mc_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot-istiodremote-mc_istio/1627504936386301952) | true | `/test integ-pilot-istiodremote-mc`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-20 03:12 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | 97e4c66e0147c2e1c98fbc3be89143ed039d8f08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ambient_istio/1626678514704977920) | true | `/test integ-ambient`
unit-tests-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests-arm64_istio/1627504931403468800) | true | `/test unit-tests-arm64`
unit-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests_istio/1627504931365720064) | true | `/test unit-tests`
integ-basic-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-basic-arm64_istio/1627504932196192256) | true | `/test integ-basic-arm64`
release-test_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/release-test_istio/1627504931441217536) | true | `/test release-test`
analyze-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/analyze-tests_istio/1627504940576411648) | true | `/test analyze-tests`
integ-security_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security_istio/1627504937220968448) | true | `/test integ-security`
integ-pilot_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot_istio/1627504933878108160) | true | `/test integ-pilot`
integ-operator-controller_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-operator-controller_istio/1627504933030858752) | true | `/test integ-operator-controller`
integ-ds_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ds_istio/1627504931713847296) | true | `/test integ-ds`
integ-distroless_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-distroless_istio/1627504931634155520) | true | `/test integ-distroless`
integ-ipv6_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ipv6_istio/1627504931671904256) | true | `/test integ-ipv6`
integ-telemetry-istiodremote_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry-istiodremote_istio/1627504931596406784) | true | `/test integ-telemetry-istiodremote`
lint_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/lint_istio/1627504941453021184) | true | `/test lint`
integ-helm_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-helm_istio/1627504939741745152) | true | `/test integ-helm`
integ-cni_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-cni_istio/1627504931483160576) | true | `/test integ-cni`
integ-telemetry-mc_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry-mc_istio/1627504931567046656) | true | `/test integ-telemetry-mc`
integ-telemetry_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry_istio/1627504931520909312) | true | `/test integ-telemetry`
integ-pilot-multicluster_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot-multicluster_istio/1627504934704386048) | true | `/test integ-pilot-multicluster`
integ-pilot-istiodremote-mc_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot-istiodremote-mc_istio/1627504936386301952) | true | `/test integ-pilot-istiodremote-mc`
integ-pilot-istiodremote_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot-istiodremote_istio/1627504935551635456) | true | `/test integ-pilot-istiodremote`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-20 03:12 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | 97e4c66e0147c2e1c98fbc3be89143ed039d8f08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ambient_istio/1626678514704977920) | true | `/test integ-ambient`
unit-tests-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests-arm64_istio/1627504931403468800) | true | `/test unit-tests-arm64`
unit-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests_istio/1627504931365720064) | true | `/test unit-tests`
integ-basic-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-basic-arm64_istio/1627504932196192256) | true | `/test integ-basic-arm64`
release-test_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/release-test_istio/1627504931441217536) | true | `/test release-test`
analyze-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/analyze-tests_istio/1627504940576411648) | true | `/test analyze-tests`
integ-security_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security_istio/1627504937220968448) | true | `/test integ-security`
integ-pilot_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot_istio/1627504933878108160) | true | `/test integ-pilot`
integ-operator-controller_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-operator-controller_istio/1627504933030858752) | true | `/test integ-operator-controller`
integ-ds_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ds_istio/1627504931713847296) | true | `/test integ-ds`
integ-distroless_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-distroless_istio/1627504931634155520) | true | `/test integ-distroless`
integ-ipv6_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ipv6_istio/1627504931671904256) | true | `/test integ-ipv6`
integ-telemetry-istiodremote_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry-istiodremote_istio/1627504931596406784) | true | `/test integ-telemetry-istiodremote`
lint_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/lint_istio/1627504941453021184) | true | `/test lint`
integ-helm_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-helm_istio/1627504939741745152) | true | `/test integ-helm`
integ-cni_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-cni_istio/1627504931483160576) | true | `/test integ-cni`
integ-telemetry-mc_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry-mc_istio/1627504931567046656) | true | `/test integ-telemetry-mc`
integ-telemetry_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry_istio/1627504931520909312) | true | `/test integ-telemetry`
integ-pilot-multicluster_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot-multicluster_istio/1627504934704386048) | true | `/test integ-pilot-multicluster`
integ-pilot-istiodremote-mc_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot-istiodremote-mc_istio/1627504936386301952) | true | `/test integ-pilot-istiodremote-mc`
integ-pilot-istiodremote_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot-istiodremote_istio/1627504935551635456) | true | `/test integ-pilot-istiodremote`
integ-security-istiodremote_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security-istiodremote_istio/1627504938907078656) | true | `/test integ-security-istiodremote`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-20 03:13 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | 97e4c66e0147c2e1c98fbc3be89143ed039d8f08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ambient_istio/1626678514704977920) | true | `/test integ-ambient`
unit-tests-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests-arm64_istio/1627504931403468800) | true | `/test unit-tests-arm64`
unit-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests_istio/1627504931365720064) | true | `/test unit-tests`
integ-basic-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-basic-arm64_istio/1627504932196192256) | true | `/test integ-basic-arm64`
release-test_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/release-test_istio/1627504931441217536) | true | `/test release-test`
analyze-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/analyze-tests_istio/1627504940576411648) | true | `/test analyze-tests`
integ-security_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security_istio/1627504937220968448) | true | `/test integ-security`
integ-pilot_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot_istio/1627504933878108160) | true | `/test integ-pilot`
integ-operator-controller_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-operator-controller_istio/1627504933030858752) | true | `/test integ-operator-controller`
integ-ds_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ds_istio/1627504931713847296) | true | `/test integ-ds`
integ-distroless_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-distroless_istio/1627504931634155520) | true | `/test integ-distroless`
integ-ipv6_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ipv6_istio/1627504931671904256) | true | `/test integ-ipv6`
integ-telemetry-istiodremote_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry-istiodremote_istio/1627504931596406784) | true | `/test integ-telemetry-istiodremote`
lint_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/lint_istio/1627504941453021184) | true | `/test lint`
integ-helm_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-helm_istio/1627504939741745152) | true | `/test integ-helm`
integ-cni_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-cni_istio/1627504931483160576) | true | `/test integ-cni`
integ-telemetry-mc_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry-mc_istio/1627504931567046656) | true | `/test integ-telemetry-mc`
integ-telemetry_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry_istio/1627504931520909312) | true | `/test integ-telemetry`
integ-pilot-multicluster_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot-multicluster_istio/1627504934704386048) | true | `/test integ-pilot-multicluster`
integ-pilot-istiodremote-mc_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot-istiodremote-mc_istio/1627504936386301952) | true | `/test integ-pilot-istiodremote-mc`
integ-pilot-istiodremote_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot-istiodremote_istio/1627504935551635456) | true | `/test integ-pilot-istiodremote`
integ-security-istiodremote_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security-istiodremote_istio/1627504938907078656) | true | `/test integ-security-istiodremote`
integ-security-multicluster_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security-multicluster_istio/1627504938059829248) | true | `/test integ-security-multicluster`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-20 03:13 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | 97e4c66e0147c2e1c98fbc3be89143ed039d8f08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ambient_istio/1626678514704977920) | true | `/test integ-ambient`
unit-tests-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests-arm64_istio/1627504931403468800) | true | `/test unit-tests-arm64`
unit-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/unit-tests_istio/1627504931365720064) | true | `/test unit-tests`
integ-basic-arm64_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-basic-arm64_istio/1627504932196192256) | true | `/test integ-basic-arm64`
release-test_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/release-test_istio/1627504931441217536) | true | `/test release-test`
analyze-tests_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/analyze-tests_istio/1627504940576411648) | true | `/test analyze-tests`
integ-security_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security_istio/1627504937220968448) | true | `/test integ-security`
integ-pilot_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot_istio/1627504933878108160) | true | `/test integ-pilot`
integ-operator-controller_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-operator-controller_istio/1627504933030858752) | true | `/test integ-operator-controller`
integ-ds_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ds_istio/1627504931713847296) | true | `/test integ-ds`
integ-distroless_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-distroless_istio/1627504931634155520) | true | `/test integ-distroless`
integ-ipv6_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ipv6_istio/1627504931671904256) | true | `/test integ-ipv6`
integ-telemetry-istiodremote_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry-istiodremote_istio/1627504931596406784) | true | `/test integ-telemetry-istiodremote`
lint_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/lint_istio/1627504941453021184) | true | `/test lint`
integ-helm_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-helm_istio/1627504939741745152) | true | `/test integ-helm`
integ-cni_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-cni_istio/1627504931483160576) | true | `/test integ-cni`
integ-telemetry-mc_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry-mc_istio/1627504931567046656) | true | `/test integ-telemetry-mc`
integ-telemetry_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry_istio/1627504931520909312) | true | `/test integ-telemetry`
integ-pilot-multicluster_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot-multicluster_istio/1627504934704386048) | true | `/test integ-pilot-multicluster`
integ-pilot-istiodremote-mc_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot-istiodremote-mc_istio/1627504936386301952) | true | `/test integ-pilot-istiodremote-mc`
integ-pilot-istiodremote_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot-istiodremote_istio/1627504935551635456) | true | `/test integ-pilot-istiodremote`
integ-security-istiodremote_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security-istiodremote_istio/1627504938907078656) | true | `/test integ-security-istiodremote`
integ-security-multicluster_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security-multicluster_istio/1627504938059829248) | true | `/test integ-security-multicluster`
gencheck_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/gencheck_istio/1627504942258327552) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-20 04:34 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | 97e4c66e0147c2e1c98fbc3be89143ed039d8f08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ambient_istio/1626678514704977920) | true | `/test integ-ambient`
integ-security_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security_istio/1627504937220968448) | true | `/test integ-security`
integ-pilot_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-pilot_istio/1627504933878108160) | true | `/test integ-pilot`
integ-telemetry-mc_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry-mc_istio/1627504931567046656) | true | `/test integ-telemetry-mc`
integ-telemetry_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry_istio/1627504931520909312) | true | `/test integ-telemetry`
integ-security-multicluster_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security-multicluster_istio/1627504938059829248) | true | `/test integ-security-multicluster`
integ-security-istiodremote_istio | e44ccf8fafd0cae9f499518ce2c3a7b129c2d2fb | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security-istiodremote_istio/1627520905615773696) | true | `/test integ-security-istiodremote`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-20 04:39 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | 97e4c66e0147c2e1c98fbc3be89143ed039d8f08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ambient_istio/1626678514704977920) | true | `/test integ-ambient`
integ-telemetry-mc_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-telemetry-mc_istio/1627504931567046656) | true | `/test integ-telemetry-mc`
integ-security-multicluster_istio | 5650003042d88efb524d250e6a34f6ac4ad998ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security-multicluster_istio/1627504938059829248) | true | `/test integ-security-multicluster`
integ-security-istiodremote_istio | e44ccf8fafd0cae9f499518ce2c3a7b129c2d2fb | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security-istiodremote_istio/1627520905615773696) | true | `/test integ-security-istiodremote`
integ-security_istio | e44ccf8fafd0cae9f499518ce2c3a7b129c2d2fb | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security_istio/1627520903929663488) | true | `/test integ-security`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-20 04:55 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | 97e4c66e0147c2e1c98fbc3be89143ed039d8f08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-ambient_istio/1626678514704977920) | true | `/test integ-ambient`
integ-security-istiodremote_istio | e44ccf8fafd0cae9f499518ce2c3a7b129c2d2fb | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security-istiodremote_istio/1627520905615773696) | true | `/test integ-security-istiodremote`
integ-security_istio | e44ccf8fafd0cae9f499518ce2c3a7b129c2d2fb | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security_istio/1627520903929663488) | true | `/test integ-security`
integ-security-multicluster_istio | e44ccf8fafd0cae9f499518ce2c3a7b129c2d2fb | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43424/integ-security-multicluster_istio/1627520904785301504) | true | `/test integ-security-multicluster`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-20 08:54 UTC, hzxuzhonghu commented
/retest

2023-02-20 14:45 UTC, linsun requested changes
Can you pls specify the alternative and document it properly before it is removed?

I am very sure there are users who use it.

2023-02-20 14:50 UTC, linsun commented
Is the better solution to use https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-CertificateData? @hzxuzhonghu

2023-02-20 19:36 UTC, dhawton requested changes

2023-02-20 19:36 UTC, dhawton commented on releasenotes/notes/43424.yaml
> +    **Removed** `PILOT_SKIP_VALIDATE_TRUST_DOMAIN` env from pilot which was unused for a long time.
```suggestion
    **Removed** `PILOT_SKIP_VALIDATE_TRUST_DOMAIN` environment variable from Pilot.
```

Also recommend an alternative suggestion.

2023-02-21 01:04 UTC, hzxuzhonghu commented
There is no alternative, the env is totally useless since very long before

2023-02-21 02:12 UTC, linsun commented
> There is no alternative, the env is totally useless since very long before

Can I request this to be discussed in Wed's WG meeting before approval of the PR?

2023-02-21 02:32 UTC, hzxuzhonghu commented
sure

2023-02-22 14:34 UTC, danehans commented
@hzxuzhonghu you will also need to sign the [CLA](https://github.com/istio/istio/pull/43424/checks?check_run_id=11478714629) for your PR to pass CI.

2023-02-22 15:16 UTC, danehans commented on releasenotes/notes/43424.yaml
> +    **Removed** `PILOT_SKIP_VALIDATE_TRUST_DOMAIN` environment variable from Pilot.
Needs newline.

2023-02-22 20:24 UTC, liminw commented
This flag was added to allow cross-trust-domain communication. From the description, it seems that this flag is no longer used? I wonder how cross-trust-domain communication is enabled today. @howardjohn @linsun Any idea?

2023-02-22 21:07 UTC, linsun commented
> This flag was added to allow cross-trust-domain communication. From the description, it seems that this flag is no longer used? I wonder how cross-trust-domain communication is enabled today. @howardjohn @linsun Any idea?

@liminw you are asking the right Q! this is exactly why we brought up this topic in today's WG meeting. @costinm suggested to use TrustDomainAlias instead of CertificateData for single root multiple trust domain validation.  What is your thoughts?

2023-02-23 01:45 UTC, hzxuzhonghu commented
It was introduced to control filter setting, and the filter was removed. why such an useless env should be kept? 

```
	filterConfig := &authn_filter.FilterConfig{
		Policy: p,
		// we can always set this field, it's no-op if mTLS is not used.
		SkipValidateTrustDomain: features.SkipValidateTrustDomain.Get(),
	}
```

2023-02-23 01:46 UTC, howardjohn commented
the important part is https://github.com/istio/istio/blob/1c70653e0eec55aed47674590767cd2dd4e8ff64/pilot/pkg/networking/plugin/authn/util.go#L24

2023-02-23 07:06 UTC, liminw commented
This flag is to 

> It was introduced to control filter setting, and the filter was removed. why such an useless env should be kept?
> 
> ```
> 	filterConfig := &authn_filter.FilterConfig{
> 		Policy: p,
> 		// we can always set this field, it's no-op if mTLS is not used.
> 		SkipValidateTrustDomain: features.SkipValidateTrustDomain.Get(),
> 	}
> ```

@hzxuzhonghu Thanks for the info. Could you point me to the PR where the filter was removed? Thanks.

2023-02-23 07:15 UTC, hzxuzhonghu commented
sorry for mistaken, it is set to always skip in  #26224

2023-03-03 14:52 UTC, istio-testing commented
PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-03-25 09:18 UTC, closed without merging