Fix syntax error for pod monitor resource
istio/istio pull request #43551
Opened 2023-02-23 05:06 UTC by luong-komorebi

**Please provide a description of this PR:**
When applying the pod monitor custom resource definition, this is the error:

![33666](https://user-images.githubusercontent.com/15828926/220824974-d10b4739-1f6f-427c-8c4c-d423c93de71d.png)

The root cause is because the original author used https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config syntax, instead of 
https://prometheus-operator.dev/docs/operator/api/#:~:text=in%20the%20future.-,RelabelConfig,-(Appears%20on syntax

2023-02-23 05:06 UTC, istio-testing commented
Hi @luong-komorebi. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-02-23 06:14 UTC, hanxiaop commented
/ok-to-test

2023-02-23 06:34 UTC, zirain requested changes
I'm not familiar with OpenShift, but we should follow Prometheus's doc?

@morvencao can you take a look?

2023-02-23 11:17 UTC, morvencao reviewed
/lgtm
these were introduced by https://github.com/istio/istio/pull/43434 @jewertow PTAL

2023-02-23 14:31 UTC, jewertow reviewed
I changed those fields by a mistake. Now the syntax is correct.

2023-02-23 16:08 UTC, howardjohn approved these changes

2023-02-24 06:10 UTC, zirain approved these changes

2023-02-24 06:41 UTC, merged