Download and install istioctl without path change
istio/istio pull request #43771
Opened 2023-03-05 16:55 UTC by ymesika

**Please provide a description of this PR:**

Currently at the end of the script the directory changes to home.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2023-03-05 17:04 UTC, istio-testing commented
@ymesika: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | d4ed64d1bd7c239e1c72b1f626240c143e51cfaf | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43771/release-notes_istio/1632426522906202112) | true | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-03-05 21:32 UTC, dhawton commented on releasenotes/notes/43771.yaml
> +    **Improved** executing the 'downloadIstioCtl.sh' script will not change to home directory at the end.
```suggestion
    **Improved** the `downloadIstioCtl.sh` script to not change to the home directory at the end.
```

2023-03-06 13:24 UTC, GregHanson approved these changes

2023-03-06 15:08 UTC, dhawton approved these changes

2023-03-06 15:47 UTC, howardjohn approved these changes

2023-03-06 16:11 UTC, ericvn requested changes

2023-03-06 16:11 UTC, ericvn commented on release/downloadIstioCtl.sh
> -rm -r "${tmp}"
We should remove the tmp directory

2023-03-06 16:17 UTC, istio-testing commented
@ymesika: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-telemetry-mc_istio | 3e32c6f653f0afffec41029161b28b17726dc8db | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43771/integ-telemetry-mc_istio/1632770195334369280) | unknown | `/test integ-telemetry-mc`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-03-06 16:28 UTC, ymesika commented on release/downloadIstioCtl.sh
> -rm -r "${tmp}"
Thanks.

2023-03-06 18:19 UTC, ericvn approved these changes

2023-03-06 18:58 UTC, merged