Bump iptables image for ztunnel
istio/istio pull request #44135
Opened 2023-03-28 04:01 UTC by yankay

**Please provide a description of this PR:**

Update base distroless image for ztunnel since there are fixed CVEs

2023-03-28 04:02 UTC, istio-testing commented
Hi @yankay. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-03-28 10:25 UTC, hanxiaop commented
/ok-to-test

2023-03-28 13:34 UTC, ericvn requested changes
I believe this was made part of the bin/update_deps.sh script, so would you please run that and include all the updates. Thanks.

2023-03-28 13:37 UTC, ericvn commented on pilot/docker/Dockerfile.ztunnel
> +# This version is from commit a8b3fb577adb785211ce704fdf892983fc268b11.
Remove the comment line since the script won't be updating that.

2023-03-28 16:18 UTC, howardjohn approved these changes

2023-03-29 19:15 UTC, ericvn commented
Note that a later PR updating update_deps and running it supersedes this PR.

2023-03-29 22:03 UTC, istio-testing commented
PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-04-03 02:26 UTC, yankay commented
It has been update by https://github.com/istio/istio/pull/44160
/close

2023-04-03 02:26 UTC, closed without merging