Add `istio.io/meshID` annotation to injection templates
istio/istio pull request #44242
Opened 2023-04-04 22:52 UTC by jewertow

**Please provide a description of this PR:**

This PR adds injection of `istio.io/meshID` to all istio-proxies: sidecars, default gateways, injected gateways, k8s api gateways, grpc-agent and waypoint.

This annotation will distinct metrics collected in multi-tenant meshes or in multi-cluster meshes with global Prometheus.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2023-04-04 22:53 UTC, istio-testing commented
@jewertow: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | ca62d94b1b750c96803e2f48749b544e19fd1ef1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/44242/release-notes_istio/1643386002191945728) | true | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-04-04 22:55 UTC, istio-testing commented
@jewertow: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | e142eeedbf7f0c3fc7f582de2c3f9fce888b7506 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/44242/release-notes_istio/1643386397588983808) | true | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-04-05 10:39 UTC, istio-testing commented
@jewertow: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | b3dc6e1a54d020a1e915f56848159bdd7619c2d0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/44242/release-notes_istio/1643563076772958208) | true | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-04-06 10:13 UTC, kebe7jun commented
If you just want to get the meshid from the metrics, maybe this can be achieved by configuring telemetry?
Like:

```
  telemetry:
    v2:
      prometheus:
        configOverride:
          inboundSidecar:
            metrics:
              - dimensions:
                  destination_mesh_id: "node.metadata['MESH_ID']"
                  source_mesh_id: "downstream_peer.mesh_id"
                  destination_cluster: "node.metadata['CLUSTER_ID']"
                  source_cluster: "downstream_peer.cluster_id"

```
This is how we currently use it.

2023-04-06 10:42 UTC, jewertow commented
> I not sure what's a global Prometheus? can you share more details?

@zirain I saw configurations where users have multiple clusters with short retention Prometheus instances and one cluster with long retention to which all others write scraped metrics. In such configurations mesh id would make it possible to distinct source of metrics.

> IMO, it's easy to achieve when Prometheus relabel? It's not necessary to add a new annotation.

Yes, this is an alternative, but I wanted to make it more seamless and transparent to users.

2023-04-06 10:44 UTC, jewertow commented
@kebe7jun thanks! I will try this approach. If I won't find any limitation of this solution, I will close this PR.

2023-04-06 16:40 UTC, kyessenov commented
@jewertow Make sure to use Telemetry API on the recent versions instead of operator config.

2023-04-06 22:09 UTC, istio-testing commented
PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-04-07 13:38 UTC, ericvn requested changes
I don't see istio.io/meshID in the annotations defined in istio/api. Without it defined there, the istioctl analyzer will generate an unknown annotation message and this will fail at least one istio.io test. Hold this PR out until that annotation is merged.

2023-05-08 14:30 UTC, costinm commented
Sorry I missed this - since it's really an API change we need to discuss it
first, not sure if injection is the right place ( Gateways created by
istiod, VMs, etc), don't think meshID is the
right way to identify tenants, etc. Also we need to consider the broader
context - is this something that can be done by the telemetry provider or
independent of Istio ?

On Sun, May 7, 2023 at 10:05 PM Istio Policy Bot ***@***.***>
wrote:

> 🧭 This issue or pull request has been automatically marked as stale
> because it has not had activity from an Istio team member since 2023-04-07.
> It will be closed on 2023-05-22 unless an Istio team member takes action.
> Please see this wiki page
> <https://github.com/istio/istio/wiki/Issue-and-Pull-Request-Lifecycle-Manager>
> for more information. Thank you for your contributions.
>
> *Created by the issue and PR lifecycle manager*.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/istio/pull/44242#issuecomment-1537753273>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAUR2U2UMMCCSKQ7YNVLIDXFB5H7ANCNFSM6AAAAAAWTKIXAU>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-05-08 14:41 UTC, costinm commented
Perfect - that was what I meant, relabeling, otel collector, etc - there
are many good ways to enhance the metrics with more information without
having the complexity in istio.

On Mon, May 8, 2023 at 7:36 AM Jacek Ewertowski ***@***.***>
wrote:

> Thank you for feedback, but I won't need this change, because we will
> enrich metrics with mesh id using relabelings.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/istio/pull/44242#issuecomment-1538468615>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAUR2UA3EG3KDUZDHFZAELXFEAHBANCNFSM6AAAAAAWTKIXAU>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-05-08 15:41 UTC, closed without merging