istioctl: add yaml output support for istioctl x revison list
istio/istio pull request #45015
Opened 2023-05-20 07:52 UTC by my-git9

**Please provide a description of this PR:**

Add yaml output support for `istioctl x revison list` and `istioctl x revison tag list` 

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

The test result:
<img width="1180" alt="image" src="https://github.com/istio/istio/assets/76980726/ea8b0dd9-ad5c-4abb-986d-ac59dbd3b10e">

<img width="808" alt="image" src="https://github.com/istio/istio/assets/76980726/c2988333-f639-4624-9dca-6d13ad1018c8">

2023-05-20 08:06 UTC, istio-testing commented
@my-git9: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio | a0990aff648575cbdd5db9632cb0d8b70a0f37c0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45015/lint_istio/1659830129523691520) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-05-20 09:11 UTC, my-git9 commented
/test integ-pilot-multicluster_istio

2023-05-23 05:40 UTC, hanxiaop requested changes
Do you have any use cases for this? I don't believe it provides a great user experience. If we include different revisions, displaying them in YAML rather than a summary or detailed JSON output is not optimal.

2023-05-23 08:03 UTC, my-git9 commented
> Do you have any use cases for this? I don't believe it provides a great user experience. If we include different revisions, displaying them in YAML rather than a summary or detailed JSON output is not optimal.

When there is many information, I believe that yaml has stronger readability than JSON. 
This is to provide users with more choices, just like other places.

2023-06-22 14:45 UTC, closed without merging