Fix status writer doing unnecessary update
istio/istio pull request #45157
Opened 2023-05-26 09:41 UTC by hanxiaop

**Please provide a description of this PR:**
Fix https://github.com/istio/istio/issues/44613

This fixes unnecessary updates when the resource conditions remain the same. 

However, it doesn't address situations where updateStatus encounters an error. This is a somewhat tricky issue in the statuswriter may need a lot more work. I tried to do with a backoff strategy, but it seems that writeFunc isn't the appropriate layer for this approach.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2023-05-26 15:14 UTC, howardjohn commented on pilot/pkg/status/manager.go
> +		if reflect.DeepEqual(lastStatus, m.Status) {
usually m.status is going to be a protobuf, doing reflect.DeepEqual on protobuf is not safe (will usually return false even when it shouldn't)

2023-05-27 10:34 UTC, istio-testing commented
@hanxiaop: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | 54c31cc1c7b7dbee70518463f3a23dd2d751ab48 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45157/unit-tests-arm64_istio/1662405504443355136) | true | `/test unit-tests-arm64`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-05-27 10:35 UTC, istio-testing commented
@hanxiaop: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | 54c31cc1c7b7dbee70518463f3a23dd2d751ab48 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45157/unit-tests-arm64_istio/1662405504443355136) | true | `/test unit-tests-arm64`
lint_istio | 54c31cc1c7b7dbee70518463f3a23dd2d751ab48 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45157/lint_istio/1662405532960428032) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-05-29 02:11 UTC, hzxuzhonghu commented
Do we have test covering this case

2023-05-29 09:03 UTC, hanxiaop commented
> Do we have test covering this case

Looks like we don't. I'll update with some tests.

2023-05-30 16:08 UTC, howardjohn requested changes
I am not sure this is safe? This assumes we have exclusive access on the status field -- we don't. It can change at any time, and it is our responsibility to reconcile it.

Additionally, its not clear to me why we need to store kubernetes objects in a map - the informers already do that, and correctly update when other sources change the status. Our implementation already ensures we do not do NOP updates wrt to the informer state as far as I know

2023-05-31 09:59 UTC, hanxiaop commented
> I am not sure this is safe? This assumes we have exclusive access on the status field -- we don't. It can change at any time, and it is our responsibility to reconcile it.

I was thinking we do since this is used in the old feature `PILOT_ENABLE_CONFIG_DISTRIBUTION_TRACKING` as well. Now I realized it's not since gateway is using the statuswriter as well which do not have exlusive access.

> Additionally, its not clear to me why we need to store kubernetes objects in a map - the informers already do that, and correctly update when other sources change the status. Our implementation already ensures we do not do NOP updates wrt to the informer state as far as I know

For this, same feature described above, the old feature had a ticker that frequently updated the resource, which is unrelated to the informer.

It looks like I'm not addressing the problem outlined in the issue. The fixes should now aim at optimizing the status update for the gateway and preventing NOP updates for the old feature. Also, the write operations must be safe.

I'm going to revisit the code and share my thoughts here.

2023-05-31 14:26 UTC, howardjohn commented
Sounds good. I am a bit worried we are spending a lot of time on a feature which, IMO, is fundamentally flawed and I worry will never promote out of alpha with only incremental changes. I will bring this up in the WG

2023-06-15 02:28 UTC, closed without merging