Fix VALIDATION_WEBHOOK_CONFIG_NAME is not respected
istio/istio pull request #45169
Opened 2023-05-26 19:11 UTC by l8huang

When multiple ValidatingWebhookConfiguration are created and VALIDATION_WEBHOOK_CONFIG_NAME is set to one of them explicitly, istiod still patches all of them.
 
**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [x] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2023-05-26 19:15 UTC, istio-testing commented
@l8huang: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/unit-tests-arm64_istio/1662174766070501376) | true | `/test unit-tests-arm64`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-05-26 19:16 UTC, howardjohn requested changes
I think this may break the modern flow,  which actually has 2 VWHs by default?

I would not consider this a simple bug fix, just a pure behavioral change, as the behavior has been the same since at least 1.13.

2023-05-26 19:21 UTC, istio-testing commented
@l8huang: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/unit-tests-arm64_istio/1662174766070501376) | true | `/test unit-tests-arm64`
unit-tests_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/unit-tests_istio/1662174766024364032) | true | `/test unit-tests`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-05-26 19:27 UTC, istio-testing commented
@l8huang: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/unit-tests-arm64_istio/1662174766070501376) | true | `/test unit-tests-arm64`
unit-tests_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/unit-tests_istio/1662174766024364032) | true | `/test unit-tests`
integ-helm_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/integ-helm_istio/1662174775818063872) | true | `/test integ-helm`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-05-26 19:32 UTC, istio-testing commented
@l8huang: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/unit-tests-arm64_istio/1662174766070501376) | true | `/test unit-tests-arm64`
unit-tests_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/unit-tests_istio/1662174766024364032) | true | `/test unit-tests`
integ-helm_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/integ-helm_istio/1662174775818063872) | true | `/test integ-helm`
integ-pilot-istiodremote_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/integ-pilot-istiodremote_istio/1662174770189307904) | true | `/test integ-pilot-istiodremote`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-05-26 19:34 UTC, istio-testing commented
@l8huang: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/unit-tests-arm64_istio/1662174766070501376) | true | `/test unit-tests-arm64`
unit-tests_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/unit-tests_istio/1662174766024364032) | true | `/test unit-tests`
integ-helm_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/integ-helm_istio/1662174775818063872) | true | `/test integ-helm`
integ-pilot-istiodremote_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/integ-pilot-istiodremote_istio/1662174770189307904) | true | `/test integ-pilot-istiodremote`
integ-cni_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/integ-cni_istio/1662174766162776064) | true | `/test integ-cni`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-05-26 19:37 UTC, l8huang commented
Thanks for your reply.

The use case is when multiple istio deployed in same k8s cluster, each of them has their own validation and injection webhook, so VALIDATION_WEBHOOK_CONFIG_NAME and VALIDATION_WEBHOOK_CONFIG_NAME are used to specify the webhook belongs to an Istio.

> I think this may break the modern flow, which actually has 2 VWHs by default?

Where can I find more details about above? Is it related to [Canary Upgrades](https://istio.io/latest/docs/setup/upgrade/canary/#stable-revision-labels-experimental)?

2023-05-26 19:39 UTC, howardjohn commented
Just doing plain old `istioctl install` deploys two today, one for global
and one for istio.io/rev=default

On Fri, May 26, 2023 at 12:38 PM l8huang ***@***.***> wrote:

> Thanks for your reply.
>
> The use case is when multiple istio deployed in same k8s cluster, each of
> them has their own validation and injection webhook, so
> VALIDATION_WEBHOOK_CONFIG_NAME and VALIDATION_WEBHOOK_CONFIG_NAME are used
> to specify the webhook belongs to an Istio.
>
> I think this may break the modern flow, which actually has 2 VWHs by
> default?
>
> Where can I find more details about above? Is it related to Canary
> Upgrades
> <https://istio.io/latest/docs/setup/upgrade/canary/#stable-revision-labels-experimental>
> ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/istio/pull/45169#issuecomment-1564844038>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEYGXJP2GTHPQWDAPDK2C3XIEBB5ANCNFSM6AAAAAAYQTCHKY>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-05-26 19:39 UTC, istio-testing commented
@l8huang: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/unit-tests-arm64_istio/1662174766070501376) | true | `/test unit-tests-arm64`
unit-tests_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/unit-tests_istio/1662174766024364032) | true | `/test unit-tests`
integ-helm_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/integ-helm_istio/1662174775818063872) | true | `/test integ-helm`
integ-pilot-istiodremote_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/integ-pilot-istiodremote_istio/1662174770189307904) | true | `/test integ-pilot-istiodremote`
integ-cni_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/integ-cni_istio/1662174766162776064) | true | `/test integ-cni`
integ-pilot_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/integ-pilot_istio/1662174768511586304) | true | `/test integ-pilot`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-05-26 19:39 UTC, istio-testing commented
@l8huang: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/unit-tests-arm64_istio/1662174766070501376) | true | `/test unit-tests-arm64`
unit-tests_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/unit-tests_istio/1662174766024364032) | true | `/test unit-tests`
integ-helm_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/integ-helm_istio/1662174775818063872) | true | `/test integ-helm`
integ-pilot-istiodremote_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/integ-pilot-istiodremote_istio/1662174770189307904) | true | `/test integ-pilot-istiodremote`
integ-cni_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/integ-cni_istio/1662174766162776064) | true | `/test integ-cni`
integ-pilot_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/integ-pilot_istio/1662174768511586304) | true | `/test integ-pilot`
integ-pilot-istiodremote-mc_istio | 9b816955269b3a157bb38f98c7ab882465593ac6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45169/integ-pilot-istiodremote-mc_istio/1662174771028168704) | true | `/test integ-pilot-istiodremote-mc`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-05-26 19:39 UTC, howardjohn commented
If you have multiple istiod you should use different revision for each.
then it works fine.

On Fri, May 26, 2023 at 12:39 PM John Howard ***@***.***> wrote:

> Just doing plain old `istioctl install` deploys two today, one for global
> and one for istio.io/rev=default
>
> On Fri, May 26, 2023 at 12:38 PM l8huang ***@***.***> wrote:
>
>> Thanks for your reply.
>>
>> The use case is when multiple istio deployed in same k8s cluster, each of
>> them has their own validation and injection webhook, so
>> VALIDATION_WEBHOOK_CONFIG_NAME and VALIDATION_WEBHOOK_CONFIG_NAME are used
>> to specify the webhook belongs to an Istio.
>>
>> I think this may break the modern flow, which actually has 2 VWHs by
>> default?
>>
>> Where can I find more details about above? Is it related to Canary
>> Upgrades
>> <https://istio.io/latest/docs/setup/upgrade/canary/#stable-revision-labels-experimental>
>> ?
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/istio/istio/pull/45169#issuecomment-1564844038>, or
>> unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AAEYGXJP2GTHPQWDAPDK2C3XIEBB5ANCNFSM6AAAAAAYQTCHKY>
>> .
>> You are receiving this because your review was requested.Message ID:
>> ***@***.***>
>>
>

2023-05-26 20:07 UTC, l8huang commented
The multiple Istio setups are in different namespace(e.g. istio-foo, istio-bar), they are running same istio version(1.10) and not using revision -- each of them manages workloads in different network segmentation and is scoped to a set of namespaces.

We are upgrading them to 1.17, also looking at Canary Upgrades, even we use revision, each of them will have same revision in its namespace. So, looking for using VALIDATION_WEBHOOK_CONFIG_NAME to ping the istiod to a specific webhook.

2023-05-26 20:10 UTC, howardjohn commented
They need to use revisions. See
https://preliminary.istio.io/latest/docs/setup/install/multiple-controlplanes/

On Fri, May 26, 2023 at 1:07 PM l8huang ***@***.***> wrote:

> The multiple Istio setups are in different namespace(e.g. istio-foo,
> istio-bar), they are running same istio version(1.10) and not using
> revision -- each of them manages workloads in different network
> segmentation and is scoped to a set of namespaces.
>
> We are upgrading them to 1.17, also looking at Canary Upgrades, even we
> use revision, each of them will have same revision in its namespace. So,
> looking for using VALIDATION_WEBHOOK_CONFIG_NAME to ping the istiod to a
> specific webhook.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/istio/pull/45169#issuecomment-1564886211>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEYGXJNJXH3DKGLIXATFLDXIEERVANCNFSM6AAAAAAYQTCHKY>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-05-29 01:29 UTC, lupindeterd commented
@howardjohn 
Did I get it right that we must use --revision if even if we're using different namespace for each same version control plane? What version did this become a default? It's break our installation due with this error.

`Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector-istio-foo ) Webhook overlaps with others: [istio-revision-tag-default-istio-bar/namespace.sidecar-injector.istio.io]. This may cause injection to occur twice.  `

2023-06-13 09:43 UTC, closed without merging