Update workload.Uid
istio/istio pull request #45327
Opened 2023-06-07 08:02 UTC by hzxuzhonghu

**Please provide a description of this PR:**

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2023-06-07 08:06 UTC, istio-testing commented
@hzxuzhonghu: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | 7c8a718ed4584bef1548bfe5764098eceb1ec7ee | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45327/unit-tests-arm64_istio/1666354863274987520) | true | `/test unit-tests-arm64`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-06-07 08:07 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | 7c8a718ed4584bef1548bfe5764098eceb1ec7ee | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45327/unit-tests-arm64_istio/1666354863274987520) | true | `/test unit-tests-arm64`
gencheck_istio | 7c8a718ed4584bef1548bfe5764098eceb1ec7ee | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45327/gencheck_istio/1666354875509772288) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-06-07 08:09 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | 7c8a718ed4584bef1548bfe5764098eceb1ec7ee | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45327/unit-tests-arm64_istio/1666354863274987520) | true | `/test unit-tests-arm64`
gencheck_istio | 7c8a718ed4584bef1548bfe5764098eceb1ec7ee | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45327/gencheck_istio/1666354875509772288) | true | `/test gencheck`
unit-tests_istio | 7c8a718ed4584bef1548bfe5764098eceb1ec7ee | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45327/unit-tests_istio/1666354863224655872) | true | `/test unit-tests`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-06-07 14:48 UTC, howardjohn requested changes
Can you provide context behind this change? I don't think its correct. Version is not part of a unique identifier in Kubernetes -- If I create a VirtualService, I get a v1alpha3 and v1beta1 that are _the same resource_

2023-06-08 01:14 UTC, hzxuzhonghu commented
As the example shows, we are settinf version as well

2023-06-08 01:39 UTC, hzxuzhonghu commented
@howardjohn ptal

```
// name format: <cluster>/<group>/<kind>/<namespace>/<name></section-name>
func (c *Controller) generatePodUID(p *v1.Pod) string {
	return c.clusterID.String() + "//" + "v1/pod/" + p.Namespace + "/" + p.Name
}
```

2023-06-09 01:21 UTC, hzxuzhonghu commented
>- If I create a VirtualService, I get a v1alpha3 and v1beta1 that are the same resource

@howardjohn It is not same resource, how to express same name VSes in v1alpha3  and v1beta1.
Though we donot support multi versions.

2023-06-09 01:24 UTC, howardjohn commented
they are the same - see
https://blog.howardjohn.info/posts/crd-versioning/#version-conversion. We
have 2 (or more) unique ids for the same resource which is unneeded. Should
just have 1

On Thu, Jun 8, 2023, 6:22 PM Zhonghu Xu ***@***.***> wrote:

>
>    - If I create a VirtualService, I get a v1alpha3 and v1beta1 that are
>    the same resource
>
> @howardjohn <https://github.com/howardjohn> It is not same resource, how
> to express same name VSes in v1alpha3 and v1beta1.
> Though we donot support multi versions.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/istio/pull/45327#issuecomment-1583784469>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEYGXNQYYAIY4CFLEWS5TLXKJ3DXANCNFSM6AAAAAAY5PDGOU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-09 03:45 UTC, hzxuzhonghu commented
I understand that, so if change all places to remove version, that is inconsistent with k8s url semantics

BTW, `generatePodUID` is not right

2023-06-12 14:59 UTC, howardjohn commented
Consistency with k8s url is not a desire - we are already not consistent

2023-06-12 15:11 UTC, howardjohn reviewed
cc @kdorosh can you verify this is ok?

2023-06-12 15:11 UTC, howardjohn commented on pilot/pkg/serviceregistry/kube/controller/ambientindex.go
> +	return c.clusterID.String() + "//" + "Pod/" + p.Namespace + "/" + p.Name
nit: prefer `pods` to `Pod`.

2023-06-12 15:29 UTC, kdorosh approved these changes
these changes lgtm

2023-06-13 01:07 UTC, hzxuzhonghu commented
ping @howardjohn

2023-06-13 01:11 UTC, howardjohn approved these changes

2023-06-13 02:03 UTC, merged