remove ownerRef for auto-registered workloadentry
istio/istio pull request #45328
Opened 2023-06-07 08:47 UTC by stevenctl

another alternative to deal with WorkloadGroup deletion being slow to recover WorkloadEntries. This makes it so there is nothing to recover. 

To make this change backwards compatible, we'd need to make this reconcile all auto-registered WorkloadEntry and remove existing owerref. I don't think that's worth doing.

2023-06-07 08:48 UTC, istio-testing commented
@stevenctl: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | e263d53b6206b03332ca24952102ece1faf6c2cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45328/release-notes_istio/1666366194044637184) | true | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-06-07 08:52 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | e263d53b6206b03332ca24952102ece1faf6c2cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45328/release-notes_istio/1666366194044637184) | true | `/test release-notes`
unit-tests-arm64_istio | e263d53b6206b03332ca24952102ece1faf6c2cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45328/unit-tests-arm64_istio/1666366181403004928) | true | `/test unit-tests-arm64`
unit-tests_istio | e263d53b6206b03332ca24952102ece1faf6c2cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45328/unit-tests_istio/1666366181348478976) | true | `/test unit-tests`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-06-07 09:10 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | e263d53b6206b03332ca24952102ece1faf6c2cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45328/unit-tests-arm64_istio/1666366181403004928) | true | `/test unit-tests-arm64`
unit-tests_istio | e263d53b6206b03332ca24952102ece1faf6c2cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45328/unit-tests_istio/1666366181348478976) | true | `/test unit-tests`
gencheck_istio | f5cd93ff695ae658232f604ae900036f9f999ee1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45328/gencheck_istio/1666371455132110848) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-06-07 09:10 UTC, istio-testing commented
@stevenctl: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | e263d53b6206b03332ca24952102ece1faf6c2cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45328/unit-tests-arm64_istio/1666366181403004928) | true | `/test unit-tests-arm64`
unit-tests_istio | e263d53b6206b03332ca24952102ece1faf6c2cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45328/unit-tests_istio/1666366181348478976) | true | `/test unit-tests`
gencheck_istio | f5cd93ff695ae658232f604ae900036f9f999ee1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45328/gencheck_istio/1666371455132110848) | true | `/test gencheck`
lint_istio | f5cd93ff695ae658232f604ae900036f9f999ee1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45328/lint_istio/1666371454297444352) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-06-07 09:37 UTC, hzxuzhonghu commented
What do you mean by recover WorkloadEntries

2023-06-07 09:45 UTC, hzxuzhonghu commented
We donot set OwnerReference.BlockOwnerDeletion, so wle will not block WLG deletion.  An d what do you mean by slow

2023-06-08 14:39 UTC, shashankram commented
> -1 to this. We are breaking standard Kubernetes practices for a super obscure edge case

It depends on the contract for autoregistered WEs. If they cannot exist when the corresponding WG is removed, we should keep the OwnerRef. Otherwise, it's not necessary to have an OwnerRef on the WE as long as there's business logic to clean them within some interval.

If we decide to leave the OwnerRef on the WE, let's also force disconnect the proxies as a proxy without WGs + WEs is a clear indicator of not participating in the mesh.

2023-06-08 14:54 UTC, costinm approved these changes
LGTM - I don't think we need to do anything for backwards compat, the autoregistration will self-heal as VMs get deleted. And for very long running VMs - it's same behavior as we had.

2023-06-08 15:00 UTC, howardjohn requested changes
Sorry to go back and forth so much on a minor edge case but this feels very wrong. ownerReference is the standard way to do this in Kubernetes, I don't feel comfortable removing this

2023-06-08 15:39 UTC, costinm commented
Set ownerReference to Istiod insead.

The WorkloadEntry is not owned by the WorkloadGroup - it is not the same
relation as Deployment and Pod.

I do agree that all created resources should have an ownerReference - not a
hard line, but it's good practice.
However the intent is for the owned resources to be deleted when the owner
is gone. We don't delete WE created by
a CI/CD for example if the WG is deleted - and AFAIK WE can exist
independently of the WG.

WG is used mainly as a policy to enhance the WE - I'm not even sure it is
strictly required for the auto-registration.





On Thu, Jun 8, 2023 at 8:00 AM John Howard ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Sorry to go back and forth so much on a minor edge case but this feels
> very wrong. ownerReference is the standard way to do this in Kubernetes, I
> don't feel comfortable removing this
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/istio/pull/45328#pullrequestreview-1470151492>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAUR2WRVO6DPMZDFJVVBZ3XKHSKBANCNFSM6AAAAAAY5Q4R3M>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-06-08 15:48 UTC, howardjohn commented
WG ~= Deployment.
If you create a Deployment the pod has ownerRef Deployment (technically
replicaset but still).

You can still create a Pod without a deployment and there is no ownerref -
same with WE. But if its from a Deployment it should be associated with it
IMO.

On Thu, Jun 8, 2023 at 8:43 AM Costin Manolache ***@***.***>
wrote:

> To expand my last comment: what is the reason we even require WG ? AFAIK it
> is possible to have a controller
> outside of Istiod that creates and manages WE without any WG. Arguably this
> would be a better practice, as
> the controller may be aware of VMs creation / deletion.
>
> For auto-registration - if a workload has a proper certificate - we have
> the SA and namespace, and it can provide
> its own labels and ports ( we do send them in XDS meta ). WG seems more of
> unnecessary complexity.
>
> On Thu, Jun 8, 2023 at 8:39 AM Costin Manolache ***@***.***> wrote:
>
> > Set ownerReference to Istiod insead.
> >
> > The WorkloadEntry is not owned by the WorkloadGroup - it is not the same
> > relation as Deployment and Pod.
> >
> > I do agree that all created resources should have an ownerReference - not
> > a hard line, but it's good practice.
> > However the intent is for the owned resources to be deleted when the
> owner
> > is gone. We don't delete WE created by
> > a CI/CD for example if the WG is deleted - and AFAIK WE can exist
> > independently of the WG.
> >
> > WG is used mainly as a policy to enhance the WE - I'm not even sure it is
> > strictly required for the auto-registration.
> >
> >
> >
> >
> >
> > On Thu, Jun 8, 2023 at 8:00 AM John Howard ***@***.***>
> > wrote:
> >
> >> ***@***.**** requested changes on this pull request.
> >>
> >> Sorry to go back and forth so much on a minor edge case but this feels
> >> very wrong. ownerReference is the standard way to do this in
> Kubernetes, I
> >> don't feel comfortable removing this
> >>
> >> —
> >> Reply to this email directly, view it on GitHub
> >> <https://github.com/istio/istio/pull/45328#pullrequestreview-1470151492
> >,
> >> or unsubscribe
> >> <
> https://github.com/notifications/unsubscribe-auth/AAAUR2WRVO6DPMZDFJVVBZ3XKHSKBANCNFSM6AAAAAAY5Q4R3M
> >
> >> .
> >> You are receiving this because your review was requested.Message ID:
> >> ***@***.***>
> >>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/istio/pull/45328#issuecomment-1582852291>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEYGXIHFGK47BFI2PNYUI3XKHXKTANCNFSM6AAAAAAY5Q4R3M>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-06-08 15:55 UTC, costinm commented
On Thu, Jun 8, 2023 at 8:49 AM John Howard ***@***.***> wrote:

> WG ~= Deployment.
> If you create a Deployment the pod has ownerRef Deployment (technically
> replicaset but still).
>

I don't think WG ~= Deployment. If I create a WG - it doesn't create WE
like a deployment would do.

It doesn't really do much anyway.

A Pod has onwerRef to the Deployment because the ReplicaSet and Deployment
are actually instantiating
the Pod - user creates a Deployment with the intent of pods getting
created.


> You can still create a Pod without a deployment and there is no ownerref -
> same with WE. But if its from a Deployment it should be associated with it
> IMO.
>

If the WG was creating VM instances and registering them - yes. That's what
instance groups do in GCP for example.




>
> On Thu, Jun 8, 2023 at 8:43 AM Costin Manolache ***@***.***>
> wrote:
>
> > To expand my last comment: what is the reason we even require WG ? AFAIK
> it
> > is possible to have a controller
> > outside of Istiod that creates and manages WE without any WG. Arguably
> this
> > would be a better practice, as
> > the controller may be aware of VMs creation / deletion.
> >
> > For auto-registration - if a workload has a proper certificate - we have
> > the SA and namespace, and it can provide
> > its own labels and ports ( we do send them in XDS meta ). WG seems more
> of
> > unnecessary complexity.
> >
> > On Thu, Jun 8, 2023 at 8:39 AM Costin Manolache ***@***.***> wrote:
> >
> > > Set ownerReference to Istiod insead.
> > >
> > > The WorkloadEntry is not owned by the WorkloadGroup - it is not the
> same
> > > relation as Deployment and Pod.
> > >
> > > I do agree that all created resources should have an ownerReference -
> not
> > > a hard line, but it's good practice.
> > > However the intent is for the owned resources to be deleted when the
> > owner
> > > is gone. We don't delete WE created by
> > > a CI/CD for example if the WG is deleted - and AFAIK WE can exist
> > > independently of the WG.
> > >
> > > WG is used mainly as a policy to enhance the WE - I'm not even sure it
> is
> > > strictly required for the auto-registration.
> > >
> > >
> > >
> > >
> > >
> > > On Thu, Jun 8, 2023 at 8:00 AM John Howard ***@***.***>
> > > wrote:
> > >
> > >> ***@***.**** requested changes on this pull request.
> > >>
> > >> Sorry to go back and forth so much on a minor edge case but this feels
> > >> very wrong. ownerReference is the standard way to do this in
> > Kubernetes, I
> > >> don't feel comfortable removing this
> > >>
> > >> —
> > >> Reply to this email directly, view it on GitHub
> > >> <
> https://github.com/istio/istio/pull/45328#pullrequestreview-1470151492
> > >,
> > >> or unsubscribe
> > >> <
> >
> https://github.com/notifications/unsubscribe-auth/AAAUR2WRVO6DPMZDFJVVBZ3XKHSKBANCNFSM6AAAAAAY5Q4R3M
> > >
> > >> .
> > >> You are receiving this because your review was requested.Message ID:
> > >> ***@***.***>
> > >>
> > >
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <https://github.com/istio/istio/pull/45328#issuecomment-1582852291>, or
> > unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AAEYGXIHFGK47BFI2PNYUI3XKHXKTANCNFSM6AAAAAAY5Q4R3M
> >
> > .
> > You are receiving this because your review was requested.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/istio/pull/45328#issuecomment-1582861235>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAUR2X5MZTCRJUPTOXOAH3XKHX7HANCNFSM6AAAAAAY5Q4R3M>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-07-03 19:41 UTC, closed without merging