fix ledger delete func
istio/istio pull request #45346
Opened 2023-06-08 03:50 UTC by shirleyyLi

To fix https://github.com/istio/istio/issues/41655

2023-06-08 03:51 UTC, istio-testing commented
@shirleyyLi: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | bd07c963c02e93e6084f854d46c9e410c952431b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45346/release-notes_istio/1666653996988764160) | true | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-06-08 03:57 UTC, shirleyyLi commented
/retest

2023-06-08 14:11 UTC, howardjohn commented
I am not familiar with this code so assigned @therealmitchconnors who is. But I think we will probably want tests

2023-07-07 16:13 UTC, therealmitchconnors requested changes
This looks good.  Can you add your repro function from the linked issue as a regression test?

2023-07-10 07:30 UTC, istio-testing commented
@shirleyyLi: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio | f88a31c8bab2bc039483d5485cc9cf3016cddc43 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45346/lint_istio/1678305130572681216) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-07-10 07:32 UTC, istio-testing commented
@shirleyyLi: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio | f88a31c8bab2bc039483d5485cc9cf3016cddc43 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45346/lint_istio/1678305130572681216) | true | `/test lint`
unit-tests-arm64_istio | f88a31c8bab2bc039483d5485cc9cf3016cddc43 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45346/unit-tests-arm64_istio/1678305119604576256) | true | `/test unit-tests-arm64`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-07-10 09:06 UTC, istio-testing commented
@shirleyyLi: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio | f88a31c8bab2bc039483d5485cc9cf3016cddc43 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45346/lint_istio/1678305130572681216) | true | `/test lint`
unit-tests_istio | 3ab8d7cbf77eae0021ade088e70dd45b16d2df3a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45346/unit-tests_istio/1678327253651427328) | true | `/test unit-tests`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-07-10 09:58 UTC, shirleyyLi commented
/retest

2023-07-10 10:05 UTC, istio-testing commented
@shirleyyLi: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio | f88a31c8bab2bc039483d5485cc9cf3016cddc43 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45346/lint_istio/1678305130572681216) | true | `/test lint`
unit-tests_istio | 3ab8d7cbf77eae0021ade088e70dd45b16d2df3a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45346/unit-tests_istio/1678342864129495040) | true | `/test unit-tests`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-07-10 10:11 UTC, istio-testing commented
@shirleyyLi: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests_istio | 3ab8d7cbf77eae0021ade088e70dd45b16d2df3a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45346/unit-tests_istio/1678342864129495040) | true | `/test unit-tests`
lint_istio | 80cfa9a00d5900f5ce8cf6e9ee7b0cf71e845a61 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45346/lint_istio/1678345532545699840) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-07-10 10:12 UTC, istio-testing commented
@shirleyyLi: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio | 80cfa9a00d5900f5ce8cf6e9ee7b0cf71e845a61 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45346/lint_istio/1678345532545699840) | true | `/test lint`
unit-tests_istio | 80cfa9a00d5900f5ce8cf6e9ee7b0cf71e845a61 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45346/unit-tests_istio/1678345521091055616) | true | `/test unit-tests`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-07-10 10:12 UTC, istio-testing commented
@shirleyyLi: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio | 80cfa9a00d5900f5ce8cf6e9ee7b0cf71e845a61 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45346/lint_istio/1678345532545699840) | true | `/test lint`
unit-tests_istio | 80cfa9a00d5900f5ce8cf6e9ee7b0cf71e845a61 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45346/unit-tests_istio/1678345521091055616) | true | `/test unit-tests`
unit-tests-arm64_istio | 80cfa9a00d5900f5ce8cf6e9ee7b0cf71e845a61 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45346/unit-tests-arm64_istio/1678345521137192960) | true | `/test unit-tests-arm64`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-08-25 05:04 UTC, closed without merging