fix check file exist
istio/istio pull request #45354
Opened 2023-06-08 13:19 UTC by rokkiter

**Please provide a description of this PR:**

When err!=nil , The file may exist. use fs.ErrNotExist check is more exact

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2023-06-08 13:19 UTC, istio-testing commented
Hi @rokkiter. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-06-08 14:05 UTC, ericvn commented
/ok-to-test

2023-06-08 14:09 UTC, istio-testing commented
@rokkiter: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 153ced03cebbabb9a94e3bfc0447c44f48dec111 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45354/release-notes_istio/1666808811823828992) | true | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-06-08 14:09 UTC, howardjohn requested changes
This may change behavior if we get another error. 

I would prefer to not change this unless we have a real world bug caused by this. Generally PRs like this look innocent then cause outages later... I would encourage you to focus on issues impacting users

2023-06-09 02:12 UTC, rokkiter commented
Think review. In the future, I will avoid submitting this kind of pr

2023-06-09 02:12 UTC, closed without merging