unify authn for xds and sds clients
istio/istio pull request #45455
Opened 2023-06-14 07:41 UTC by hzxuzhonghu

**Please provide a description of this PR:**

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2023-06-14 07:42 UTC, hzxuzhonghu commented on pkg/security/authentication.go
this is originally from pilot/pkg/xds/auth.go

2023-06-14 07:44 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 919da348a289226bb8efb77a11e38c9b61704ec6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45455/release-notes_istio/1668886305100009472) | true | `/test release-notes`
unit-tests-arm64_istio | 919da348a289226bb8efb77a11e38c9b61704ec6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45455/unit-tests-arm64_istio/1668886292005392384) | true | `/test unit-tests-arm64`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-06-14 07:51 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 919da348a289226bb8efb77a11e38c9b61704ec6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45455/release-notes_istio/1668886305100009472) | true | `/test release-notes`
unit-tests-arm64_istio | 919da348a289226bb8efb77a11e38c9b61704ec6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45455/unit-tests-arm64_istio/1668886292005392384) | true | `/test unit-tests-arm64`
unit-tests_istio | 919da348a289226bb8efb77a11e38c9b61704ec6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45455/unit-tests_istio/1668886291946672128) | true | `/test unit-tests`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-06-14 07:57 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | 919da348a289226bb8efb77a11e38c9b61704ec6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45455/unit-tests-arm64_istio/1668886292005392384) | true | `/test unit-tests-arm64`
unit-tests_istio | 919da348a289226bb8efb77a11e38c9b61704ec6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45455/unit-tests_istio/1668886291946672128) | true | `/test unit-tests`
release-notes_istio | 3cf7df87def1362abe93cfedeeb253d04d5ec604 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45455/release-notes_istio/1668889886322593792) | true | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-06-14 07:59 UTC, istio-testing commented
@hzxuzhonghu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests_istio | 919da348a289226bb8efb77a11e38c9b61704ec6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45455/unit-tests_istio/1668886291946672128) | true | `/test unit-tests`
release-notes_istio | 3cf7df87def1362abe93cfedeeb253d04d5ec604 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45455/release-notes_istio/1668889886322593792) | true | `/test release-notes`
unit-tests-arm64_istio | 3cf7df87def1362abe93cfedeeb253d04d5ec604 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45455/unit-tests-arm64_istio/1668889856949882880) | true | `/test unit-tests-arm64`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-06-14 08:25 UTC, costinm reviewed
Not sure XDS and SDS/CA clients should have the same behavior. 

For XDS - it is fine to use lighter auth, there is nothing secret - just configs and endpoints. 

For SDS/CA - we want more strict auth. Unfortunately we don't do a lot of checks - like 
verify the IP address ( now that we have the reverse index ), but should become stronger.

Not strongly against this change - IMO longer term it would be best to put a gateway in front of Istiod and use our own authn/authz instead of custom.

2023-06-14 14:58 UTC, howardjohn requested changes

2023-06-15 02:28 UTC, hzxuzhonghu commented on security/pkg/nodeagent/caclient/providers/citadel/client_test.go
> +			return nil, status.Error(codes.Unauthenticated, err.Error())
This is the test, i can restore it too

2023-06-15 02:31 UTC, hzxuzhonghu commented on pkg/security/authentication.go
> +var AuthPlaintext = env.Register("XDS_AUTH_PLAINTEXT", false,
It does not change sds. YOu can see the return value of Authenticate for CA server is nil, nil when it is through 15010(plaintext)

But we donot allow nil for SDS

2023-06-15 02:31 UTC, hzxuzhonghu commented on security/pkg/server/ca/server.go
> +	if caller == nil || err != nil {
@howardjohn It does not allow nil caller

2023-06-19 01:18 UTC, hzxuzhonghu commented
@howardjohn ptaL

2023-06-20 22:27 UTC, howardjohn approved these changes
LGTM aside from metric. Can you fix and remove hold?

2023-06-20 22:27 UTC, howardjohn commented on pkg/security/authentication.go
> +// stream ( 15010 ) - returns an empty list of principals and no errors.
nit: "empty list of principals" should be updated, its now a nil struct

2023-06-20 22:27 UTC, howardjohn commented on security/pkg/server/ca/server.go
> -		s.monitoring.AuthnError.Increment()
seems we lost this?

2023-06-21 09:29 UTC, hzxuzhonghu commented on security/pkg/server/ca/server.go
> -		s.monitoring.AuthnError.Increment()
good catch

2023-06-21 10:09 UTC, merged