delete newpod define
istio/istio pull request #45851
Opened 2023-07-06 09:57 UTC by zhengbingxian

**Please provide a description of this PR:**
no need to define newpod.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [X] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2023-07-06 09:58 UTC, istio-testing commented
Hi @zhengbingxian. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-07-06 15:05 UTC, howardjohn requested changes
Thanks for the PR! Welcome to the community. Please focus on making impactful changes, these changes are not the best use of time. See https://github.com/istio/istio/wiki/Development-Conventions#superfluous-changes.

You can query [here](https://github.com/istio/istio/issues?q=is%3Aopen+is%3Aissue+label%3A%22community%2Fgood+first+issue%22) for Good First Issues (we are planning to add more to this list asap)

2023-07-07 01:27 UTC, zhengbingxian commented
@howardjohn Sure,but origin code it make confuse.such as :

- we define `pod` equals to `newpod`.   
- In eventUpdate, define `newpod` and `oldpod` to use, But `s.AddPodToMesh(pod)` use `pod` rather than `newPod`.    

There are two  variable declarations, do the same thing.  In one scope mixed use `pod` and `newPod` ，very confusing when read。

2023-07-07 22:05 UTC, istio-testing commented
PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-07-10 05:39 UTC, closed without merging