fix: NPE when compare func is nil
istio/istio pull request #46069
Opened 2023-07-19 06:13 UTC by yyzxw

**Please provide a description of this PR:**

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2023-07-19 06:13 UTC, istio-testing commented
Hi @yyzxw. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-07-19 16:43 UTC, howardjohn requested changes
Why is this needed? Users should not pass a nil function? If they do, panic seems correct - they wrote a bug

2023-07-20 10:47 UTC, yyzxw commented
Thanks for you review @howardjohn , when I was about to add unit tests to `slice.go`, it was found that it might cause NPE, and I thought that as an exported function should handle some exceptions.

2023-07-20 15:39 UTC, howardjohn commented
I don't think so. Most of these are wrapping Go stdlib functions. They
don't handle them either, which is a good indication we shouldn't either.

On Thu, Jul 20, 2023 at 3:47 AM yyzxw ***@***.***> wrote:

> Thanks for you review @howardjohn <https://github.com/howardjohn> , when
> I was about to add unit tests to slice.go, it was found that it might
> cause NPE, and I thought that as an exported function should handle some
> exceptions.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/istio/pull/46069#issuecomment-1643697384>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEYGXNYJNCC5EQSXBCYRMTXREEFZANCNFSM6AAAAAA2PNB6NQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-24 13:09 UTC, closed without merging