pkg: fix typos in comments and tests
istio/istio pull request #46132
Opened 2023-07-24 08:07 UTC by alexandear

This PR fixes spelling mistakes in comments and tests in `pkg` directory.

- [ ] Ambient
- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [x] Test and Release
- [] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2023-07-24 08:07 UTC, istio-testing commented
Hi @alexandear. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-07-24 08:42 UTC, hanxiaop approved these changes

2023-07-24 13:46 UTC, ymesika approved these changes

2023-08-08 15:02 UTC, lei-tang requested changes

2023-08-08 15:02 UTC, lei-tang commented on pkg/workloadapi/workload.pb.go
> +	// Typically, this is not set and per-workload identity is used to verfiy
The "verfiy" in the PR is a typo. The original word "verify" is correct.

2023-08-08 15:02 UTC, lei-tang commented on pkg/workloadapi/workload.proto
> +  // Typically, this is not set and per-workload identity is used to verfiy
The "verfiy" in the PR is a typo. The original word "verify" is correct.

2023-08-08 15:05 UTC, lei-tang commented on pkg/workloadapi/workload.pb.go
> +	// Typically, this is not set and per-workload identity is used to verfiy
Reverted in later commit.

2023-08-08 15:06 UTC, lei-tang commented on pkg/workloadapi/workload.proto
> +  // Typically, this is not set and per-workload identity is used to verfiy
Reverted in later commit.

2023-08-08 15:06 UTC, lei-tang approved these changes

2023-08-08 16:06 UTC, istio-testing commented
@alexandear: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-ambient_istio | a1f1d2efc874af039f27498258a291e797319e48 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46132/integ-ambient_istio/1688940661039960064) | unknown | `/test integ-ambient`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-08-08 16:43 UTC, merged