feat(charts/gateway): add podLabels property
istio/istio pull request #46275
Opened 2023-08-02 06:15 UTC by jannis-a

2023-08-02 06:16 UTC, istio-testing commented
Hi @jannis-a. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-08-02 07:39 UTC, hanxiaop requested changes
Are there any reasons that we have to add `podLabels`? Why not just use `.Values.labels`?

2023-08-02 08:11 UTC, jannis-a commented
@hanxiaop one use case in my setup is to enable pod readiness gateways with AWS load balancer controller. This requires the pods to have a label e.g. `elbv2.k8s.aws/pod-readiness-gate-inject=enabled` in order to get mutated by its webhook, but I don't want these labels on all other resources deployed by the gateway chart. 🙂

2023-08-09 02:00 UTC, hanxiaop commented
> @hanxiaop one use case in my setup is to enable pod readiness gateways with AWS load balancer controller. This requires the pods to have a label e.g. `elbv2.k8s.aws/pod-readiness-gate-inject=enabled` in order to get mutated by its webhook, but I don't want these labels on all other resources deployed by the gateway chart. 🙂

Do these extra labels somehow influence your gateway installation for other resources?

2023-09-23 05:05 UTC, closed without merging