Fix istio-cni-node crash when the Kubernetes pod network is not implemented using veth
istio/istio pull request #46654
Opened 2023-08-23 08:34 UTC by zengyuxing007

**Please provide a description of this PR:**

Fix istio-cni-node crash when the Kubernetes pod network is not implemented using veth

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [x] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [x] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2023-08-23 08:37 UTC, istio-testing commented
@zengyuxing007: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 2266cdcfde2b0a9b04e1a00a193538dfd3f83ca6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46654/release-notes_istio/1694266768941387776) | true | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-08-23 14:04 UTC, howardjohn requested changes
This code is invalid, can never be reached

2023-08-28 03:34 UTC, istio-testing commented
@zengyuxing007: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio | 2266cdcfde2b0a9b04e1a00a193538dfd3f83ca6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46654/lint_istio/1694266767251083264) | true | `/test lint`
release-notes_istio | 425149bfbf3efc008b554f8167d35cba0dce3468 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46654/release-notes_istio/1696002513557262336) | true | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-08-28 03:36 UTC, zengyuxing007 commented
```shell
2023-08-22T02:48:30.355908Z     info    ambient HostIP changed: () -> (10.0.172.14)
2023-08-22T02:48:30.356095Z     warn    ambient failed to get device: not veth implemented CNI
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x214f41f]
goroutine 74 [running]:
github.com/vishvananda/netlink.VethPeerIndex(0x0)
        github.com/vishvananda/netlink@v1.2.1-beta.2/link_linux.go:3320 +0x9f
istio.io/istio/cni/pkg/ambient.getPeerIndex(...)
        istio.io/istio/cni/pkg/ambient/net_linux.go:325
istio.io/istio/cni/pkg/ambient.(*Server).updateNodeProxyEBPF(0xc00004fef0, 0xc0008a1a98?, 0x0)
        istio.io/istio/cni/pkg/ambient/net_linux.go:104 +0xdd
istio.io/istio/cni/pkg/ambient.(*Server).ReconcileZtunnel(0xc00004fef0)
        istio.io/istio/cni/pkg/ambient/server.go:245 +0x7e5
istio.io/istio/cni/pkg/ambient.(*Server).Reconcile(0xc00004fef0, {0x2799d20?, 0xc0016a59b0?})
        istio.io/istio/cni/pkg/ambient/informers.go:108 +0xf05
istio.io/istio/pkg/kube/controllers.WithGenericReconciler.func1.1({0x2799d20?, 0xc0016a59b0?})
        istio.io/istio/pkg/kube/controllers/queue.go:73 +0x27
istio.io/istio/pkg/kube/controllers.Queue.processNextItem({{0x2df97b0, 0xc001633980}, 0xc0011c6350, {0x2a0addc, 0x7}, 0x5, 0xc0016791c0, 0xc000496ea0})
        istio.io/istio/pkg/kube/controllers/queue.go:158 +0x1a6
istio.io/istio/pkg/kube/controllers.Queue.Run.func1()
        istio.io/istio/pkg/kube/controllers/queue.go:112 +0x4e
created by istio.io/istio/pkg/kube/controllers.Queue.Run
        istio.io/istio/pkg/kube/controllers/queue.go:110 +0x1d1
```

@howardjohn   I made a mistake in the first submission by using the editing feature on GitHub.

resubmit and provide the stack trace information for the error mentioned above. Thanks~

2023-08-28 16:48 UTC, howardjohn approved these changes

2023-08-28 16:48 UTC, howardjohn commented
/retest

2023-08-28 17:25 UTC, merged