manifests: fix setting proxy UID and GID in gateway templates on OpenShift
istio/istio pull request #46835
Opened 2023-09-04 21:59 UTC by jewertow

**Please provide a description of this PR:**

This is a follow-up to #45394.

Currently, deployments for gateways created from charts `gateway`, `gateways/istio-ingress` and `gateways/istio-egress` with injection template fail to create pods, because got UID/GID 1337, so still require anyuid SCC. I removed `.ProxyUID` and `.ProxyGID` from those charts, because injection webhook does not use those templates. Instead, we should set `.ProxyUID` and `.ProxyGID` in `gateway-injection-template`, but it's not trivial, because `gateway` chart allows to customize securityContext, so it's not obvious how to override it.

On the other hand, we didn't set `ProxyUID` and `ProxyGID` in the kube-gateway template, while we know these values during template evaluation, so I fixed it.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2023-09-04 22:03 UTC, istio-testing commented
@jewertow: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | e68d5359463b6e06069ebda15a55f8e4b982cfd4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46835/release-notes_istio/1698818225720004608) | true | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-09-04 22:07 UTC, jewertow commented
/test release-notes

2023-09-04 22:08 UTC, istio-testing commented
@jewertow: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio | e68d5359463b6e06069ebda15a55f8e4b982cfd4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46835/lint_istio/1698818223966785536) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-09-04 22:16 UTC, istio-testing commented
@jewertow: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio | e68d5359463b6e06069ebda15a55f8e4b982cfd4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46835/lint_istio/1698818223966785536) | true | `/test lint`
integ-pilot-istiodremote_istio | e68d5359463b6e06069ebda15a55f8e4b982cfd4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46835/integ-pilot-istiodremote_istio/1698818217343979520) | true | `/test integ-pilot-istiodremote`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-09-04 22:19 UTC, istio-testing commented
@jewertow: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio | e68d5359463b6e06069ebda15a55f8e4b982cfd4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46835/lint_istio/1698818223966785536) | true | `/test lint`
integ-pilot-istiodremote_istio | e68d5359463b6e06069ebda15a55f8e4b982cfd4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46835/integ-pilot-istiodremote_istio/1698818217343979520) | true | `/test integ-pilot-istiodremote`
integ-pilot-istiodremote-mc_istio | e68d5359463b6e06069ebda15a55f8e4b982cfd4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46835/integ-pilot-istiodremote-mc_istio/1698818218145091584) | true | `/test integ-pilot-istiodremote-mc`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-09-04 22:19 UTC, istio-testing commented
@jewertow: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio | e68d5359463b6e06069ebda15a55f8e4b982cfd4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46835/lint_istio/1698818223966785536) | true | `/test lint`
integ-pilot-istiodremote_istio | e68d5359463b6e06069ebda15a55f8e4b982cfd4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46835/integ-pilot-istiodremote_istio/1698818217343979520) | true | `/test integ-pilot-istiodremote`
integ-pilot-istiodremote-mc_istio | e68d5359463b6e06069ebda15a55f8e4b982cfd4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46835/integ-pilot-istiodremote-mc_istio/1698818218145091584) | true | `/test integ-pilot-istiodremote-mc`
integ-pilot_istio | e68d5359463b6e06069ebda15a55f8e4b982cfd4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46835/integ-pilot_istio/1698818215561400320) | true | `/test integ-pilot`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-09-04 22:21 UTC, istio-testing commented
@jewertow: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio | e68d5359463b6e06069ebda15a55f8e4b982cfd4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46835/lint_istio/1698818223966785536) | true | `/test lint`
integ-pilot-istiodremote_istio | e68d5359463b6e06069ebda15a55f8e4b982cfd4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46835/integ-pilot-istiodremote_istio/1698818217343979520) | true | `/test integ-pilot-istiodremote`
integ-pilot-istiodremote-mc_istio | e68d5359463b6e06069ebda15a55f8e4b982cfd4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46835/integ-pilot-istiodremote-mc_istio/1698818218145091584) | true | `/test integ-pilot-istiodremote-mc`
integ-pilot_istio | e68d5359463b6e06069ebda15a55f8e4b982cfd4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46835/integ-pilot_istio/1698818215561400320) | true | `/test integ-pilot`
integ-pilot-multicluster_istio | e68d5359463b6e06069ebda15a55f8e4b982cfd4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46835/integ-pilot-multicluster_istio/1698818216400261120) | true | `/test integ-pilot-multicluster`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-09-04 22:23 UTC, istio-testing commented
@jewertow: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio | e68d5359463b6e06069ebda15a55f8e4b982cfd4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46835/lint_istio/1698818223966785536) | true | `/test lint`
integ-pilot-istiodremote_istio | e68d5359463b6e06069ebda15a55f8e4b982cfd4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46835/integ-pilot-istiodremote_istio/1698818217343979520) | true | `/test integ-pilot-istiodremote`
integ-pilot-istiodremote-mc_istio | e68d5359463b6e06069ebda15a55f8e4b982cfd4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46835/integ-pilot-istiodremote-mc_istio/1698818218145091584) | true | `/test integ-pilot-istiodremote-mc`
integ-pilot_istio | e68d5359463b6e06069ebda15a55f8e4b982cfd4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46835/integ-pilot_istio/1698818215561400320) | true | `/test integ-pilot`
integ-pilot-multicluster_istio | e68d5359463b6e06069ebda15a55f8e4b982cfd4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46835/integ-pilot-multicluster_istio/1698818216400261120) | true | `/test integ-pilot-multicluster`
integ-cni_istio | e68d5359463b6e06069ebda15a55f8e4b982cfd4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46835/integ-cni_istio/1698818213225172992) | true | `/test integ-cni`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-09-05 13:44 UTC, jwendell approved these changes

2023-09-05 16:50 UTC, bleggett commented on manifests/charts/gateway/templates/deployment.yaml
> +          {{- if not (eq .Values.global.platform "openshift") }}
+1 - `global` is explicitly for values that span multiple charts, and we're adding it to (effectively) 1 chart here, which feels wrong.

2023-09-05 16:50 UTC, bleggett commented on manifests/charts/gateway/templates/deployment.yaml
>              allowPrivilegeEscalation: false
The options seem to be

1. Don't allow custom securityContext at all, and have  an `openshift` conditional.
2. Allow custom securityContext, and put our defaults in the default `values.yaml` (meaning people can break things with careless overrides)
3. Use a templating func  to force-overwrite whatever the custom securityContext is with the key-values we "must" have.


Of those 3 seems the best, for better or for worse we have a hardcoded depedency on the nonconfigurable value `1337` so we should probably always override any user-supplied `runAsUser`/`runAsGroup` keyvalues.

2023-09-05 17:01 UTC, bleggett requested changes
See [Helm playground](https://helm-playground.com/#t=LQhQFMA8EMFsAcA24BcACA3h4aB0A1aRAV3AGdcBLAF3FjLQB81qB7ATTkSbQDtLeAE3C9qaAExoAvlNBlwAY2IAnGgE8Awq1FRqKUFhyUAZnkIlyuBdurQB4ZQGVFK9Vp2QxM0GkzY0ACTwysS84IIa1JBoKAC8aKywNGZEpBTWonZhTi6q1Jo2umgARCG8AIJkAKryysUlZZUA4sqsxPDFMmgAxADu4GgAFtDKgtbCaACMAMzTAOxoxqzKLIPkA%2BCI8r1ryuAANGhkrGiUAOa8ywPUa7CnpoLtiJQK0LSCp7yrA-DQZPKCYACNCCF7UHx%2BHBsTiwbhBMrhSLRZj8IQiMSSby%2BRrVWroGbzCE4lpteD42ZzAz%2BTbyaSyXyvX4AI0oz2olHI%2Bl8vkErTJEN8OHKABlhRCiIhWL0AAqqABurPAZ3AAFEyK9EG9KNp0MYiPIqTgRB8uqAgA&v=LQhQEsBcFMFsGcBcACA2gIgGbgE70ugDTLrzQDGA9gHYAm6AuqFdZAIbjXQ4DKFArjigBPAMI0YAD0iJQyZGwA2iygHcACkIBu4RdADm0AKLxyStpHA0UkHP2hzkd6gEF4AVTI4UARgAsfgDsjs5uAOI4lPwADr4BwUA) for an IMO cleaner solution in line with option 3 mentioned above.

2023-09-06 03:05 UTC, hzxuzhonghu commented
so why no sidecar template updated

2023-09-12 22:02 UTC, istio-testing commented
PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-09-15 11:51 UTC, closed without merging