Fix inconsistency of sidecar workloadselector if it's nil
istio/istio pull request #46921
Opened 2023-09-11 08:03 UTC by hanxiaop

**Please provide a description of this PR:**
Currently the sidecarScope workloadSelector has an inconsistent behavior:
If we have a sidecar resource with label, a namespace default resource without selector(created before the resource with label): the former one will be used.
If we have a sidecar resource with label, a namespace default resource without selector("workloadSelector: {}", and created before the resource with label), the later will be used.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [x] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2023-09-11 08:05 UTC, istio-testing commented
@hanxiaop: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 534791d4598b7d0f8fa052380a41811ff5481780 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46921/release-notes_istio/1701144487075516416) | true | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-09-11 08:06 UTC, hanxiaop commented
/test release-notes

2023-09-11 08:25 UTC, hzxuzhonghu reviewed
TBH, i am not sure whether we should make {} equal to nil for workload selector. 

For SE's workload selector, {} does not equal to nil

2023-09-11 08:47 UTC, hanxiaop commented
> TBH, i am not sure whether we should make {} equal to nil for workload selector.
> 
> For SE's workload selector, {} does not equal to nil

Thanks for the info. Perhaps it was designed intentionally? 

I made this fix since right now if I apply a Sidecar resource with `workloadSelector: {}`, I receive a warning:
```
k edit sidecar default
Warning: sidecar: workload selector specified without labels, will be applied to all services in namespace
```
I thought it's similar to default namespace Sidecar behavior, but it's actually not default since it overrides the specific one with workload selector. Or should we improve the warning a little bit?

2023-09-11 10:16 UTC, hzxuzhonghu commented
The warning was intentionally added in #40840

2023-09-11 14:49 UTC, howardjohn requested changes
This seems like a breaking change, the selectors are not all consistent unfortunately

2023-09-12 02:24 UTC, hanxiaop commented
Thanks for the info

2023-09-12 02:24 UTC, closed without merging