Fix ambient profile installation
istio/istio pull request #47774
Opened 2023-11-07 07:20 UTC by hanxiaop

**Please provide a description of this PR:**
Currently the ambient profile installation defaults to distroless. When I use my own built images, which are not distroless, and apply an overlay file:
```
hub: somehub
tag: sometag
values:
  global:
    variant: ""
```
I expect all the components to follow my default global settings, which should not have distroless. However the current behavior is that pilot and ztunnel still have the distroless suffix.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [x] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2023-11-07 07:21 UTC, hanxiaop commented
/cc @howardjohn

2023-11-07 07:24 UTC, istio-testing commented
@hanxiaop: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | f58cb917c7814b38341984c8302880d461d8f027 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/47774/release-notes_istio/1721790426509217792) | true | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-11-07 07:24 UTC, hanxiaop commented
/test release-notes

2023-11-10 21:55 UTC, howardjohn reviewed
I am think I had this originally and switch to the current state as the e2e tests broke in postsubmit

2023-11-11 13:04 UTC, hanxiaop commented
> I am think I had this originally and switch to the current state as the e2e tests broke in postsubmit

@howardjohn I looked back at the history and originally, only the global variant was specified, which meant that CNI was also "distroless". This PR explicitly sets:
```
cni:
  variant: "" # CNI distroless doesn't work yet.
```
So I think it won't cause the issue?

2023-11-13 15:25 UTC, howardjohn requested changes
This doesn't work?

```
$ istioctl manifest generate -d manifests --set profile=ambient | rg image:.*cni
        image: gcr.io/istio-testing/install-cni:latest-distroless
```

2023-11-14 05:24 UTC, hanxiaop commented
> This doesn't work?
> 
> ```
> $ istioctl manifest generate -d manifests --set profile=ambient | rg image:.*cni
>         image: gcr.io/istio-testing/install-cni:latest-distroless
> ```

Tried some approaches but didn't find great solutions to handle all the cases.

2023-11-14 05:24 UTC, closed without merging