pilot: gateway-api: gateway: Add SANS validation
istio/istio pull request #48013
Opened 2023-11-23 00:09 UTC by cbzzz

**Please provide a description of this PR:**
Adds a Gateway API option to enable [`Gateway.ServerTLSSettings.subjectAltNames`](https://istio.io/latest/docs/reference/config/networking/gateway/#ServerTLSSettings). 

This Istio-specific `Gateway` option (`gateway.istio.io/subject-alt-names`) accepts a comma-separated list of alternate names for client certificate verification with mutual TLS.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2023-11-23 00:09 UTC, istio-testing commented
Hi @cbzzz. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-11-23 00:42 UTC, zirain commented
cc @howardjohn @frankbu

2023-11-27 19:01 UTC, keithmattix requested changes
1. I'm not sure this change by itself does anything; there's no plumbing that I can see from a label to the tls.Options
2. Even if this is complete, it needs a test
3. Adding Istio specific gateway labels makes me pause. Have you shared this feature request with the gateway api community?

2023-11-27 20:40 UTC, keithmattix commented
Ah i didn't realize we already do this pattern; I'm not as opposed if we've already explicitly endorsed this pattern for now. SAN validation seems like a reasonable field to add

2023-11-27 21:15 UTC, howardjohn commented
Just to be clear the current one is intended to be experimental and
temporary. Its less compelling, IMO, to expand it now since there is
already an existing GEP (
https://github.com/kubernetes-sigs/gateway-api/pull/2273); at the time the
first one was added we were years away from upstream support

On Mon, Nov 27, 2023 at 12:40 PM Keith Mattix II ***@***.***>
wrote:

> Ah i didn't realize we already do this pattern; I'm not as opposed if
> we've already explicitly endorsed this pattern for now. SAN validation
> seems like a reasonable field to add
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/istio/pull/48013#issuecomment-1828565918>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEYGXLCFD6NPY34RCJ45P3YGT3D5AVCNFSM6AAAAAA7W7SWV6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMRYGU3DKOJRHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-11-27 22:28 UTC, frankbu commented
> Its less compelling, IMO, to expand it now since there is
already an existing GEP

The existing GEP you're refering to is for mutual tls termination, making slow progress, but hopefully will let us deprecate/remove our Istio-specific option next year. That said, unless I'm missing something, I don't think there's any upstream GEP about the proposed SAN option in this PR?

2024-01-13 05:04 UTC, closed without merging