Keep test config rules when nocleanup specified
istio/istio pull request #48294
Opened 2023-12-12 08:33 UTC by hzxuzhonghu

**Please provide a description of this PR:**

This will make the configs uncleaned up when `istio.test.nocleanup` set. Facilitate debugging integration test cases

2023-12-12 08:35 UTC, istio-testing commented
@hzxuzhonghu: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 96e86cd343e9e56d63f273bb682006f8697bff08 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/48294/release-notes_istio/1734491567177076736) | true | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-12-12 11:34 UTC, hzxuzhonghu commented
/test release-notes

2023-12-12 15:06 UTC, GregHanson approved these changes
lgtm

2023-12-12 15:11 UTC, howardjohn requested changes
This breaks common use case. The intent with CleanupConditionally is that its for permanent test fixtures, like deploying Prometheus, the fake external service ServiceEntry, etc.

If we make all configs follow this, then you cannot run more than one tests. For example, if I run a test with config A and then another with config B, _both_ will apply.

We could maybe add another option to cover this case, but this will break a pretty critical usage IMO.

FWIW, how I handle this typically is to just Ctrl+C/Ctrl+Z the test... not ideal, though.

2023-12-13 02:25 UTC, hzxuzhonghu commented
Yeah, I realized what you mean. But I am curious the ci passed, so it looks no much influence

2023-12-13 02:32 UTC, howardjohn commented
ci doesn't use the nocleanup mode is why (

On Tue, Dec 12, 2023, 6:25 PM Zhonghu Xu ***@***.***> wrote:

> Yeah, I realized what you mean. But I am curious the ci passed, so it
> looks no much influence
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/istio/pull/48294#issuecomment-1853166769>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEYGXLOMDWWMPG5FSN6YA3YJEGY5AVCNFSM6AAAAABARB3CFSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNJTGE3DMNZWHE>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2024-01-27 05:03 UTC, closed without merging