Fix high CPU consumption on pilot when in-cluster analysis is enabled
istio/istio pull request #50157
Opened 2024-03-29 03:10 UTC by hanxiaop

**Please provide a description of this PR:**
Resolves https://github.com/istio/istio/issues/49340.

I think the root cause is that the set will never be nil, but rather an empty initialized set, which results in the analysis being stuck in a push loop forever.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [x] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2024-03-29 03:12 UTC, istio-testing commented
@hanxiaop: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 10b3512be5054c382399c46f3c1b1cee421a4d85 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/50157/release-notes_istio/1773548180693061632) | true | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-03-30 04:05 UTC, hzxuzhonghu commented on pkg/util/concurrent/debouncer.go
> +			if combinedEvents.Len() > 0 {
good catch

2024-03-30 04:09 UTC, hzxuzhonghu approved these changes
I donot quite understand how inProcessAnalysis work, just wondering how can we make it mature. 

It is there for years, but rarely have heard any usage/bug reported

2024-03-30 17:06 UTC, dhawton requested changes

2024-03-30 17:06 UTC, dhawton commented on releasenotes/notes/50157.yaml
> +  **Fixed** an issue that pilot CPU consumption is abnormally high when the in-cluster analysis is enabled.
```suggestion
  **Fixed** an issue where pilot CPU consumption was abnormally high when the in-cluster analysis was enabled.
```

2024-04-01 01:36 UTC, hanxiaop commented on releasenotes/notes/50157.yaml
> +  **Fixed** an issue that pilot CPU consumption is abnormally high when the in-cluster analysis is enabled.
@dhawton Fixed, PTAL again.

2024-04-01 01:38 UTC, hanxiaop commented
> I donot quite understand how inProcessAnalysis work, just wondering how can we make it mature.
> 
> It is there for years, but rarely have heard any usage/bug reported

@hzxuzhonghu I think the concern is, this analysis controller is not quite scalable, and requires a large resource consumption. I'd rather implement https://github.com/istio/istio/issues/48468 before it gets mature.

2024-04-01 13:43 UTC, dhawton approved these changes

2024-04-01 13:44 UTC, merged

2024-04-01 13:45 UTC, istio-testing commented
In response to a cherrypick label: new pull request created: #50178

2024-04-01 13:46 UTC, istio-testing commented
In response to a cherrypick label: new pull request created: #50179