use SpawnUpstreamSpan instead of startChildSpan
istio/istio pull request #50307
Opened 2024-04-06 11:16 UTC by zirain

**Please provide a description of this PR:**

xref: https://github.com/envoyproxy/envoy/pull/29659

TODO: consider enable `SpawnUpstreamSpan` for all trace provider?

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [x] Networking
- [ ] Performance and Scalability
- [x] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2024-04-06 11:20 UTC, istio-testing commented
@zirain: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio | f8e78c20868aad41085ca5f23c1049940d2144fa | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/50307/lint_istio/1776569655683452928) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-04-08 15:45 UTC, howardjohn requested changes
This seems like a big change but there is no release note, changed tests, description of what it does, ...?

Can you give some more info?

2024-04-08 15:58 UTC, zirain commented
> This seems like a big change but there is no release note, changed tests, description of what it does, ...?
> 
> Can you give some more info?

only related to skywalking user, and the behavior is same as before, https://github.com/envoyproxy/envoy/pull/29659 proposal an new(better?) API for this?

[StartChildSpan](https://github.com/envoyproxy/go-control-plane/blob/db0b36a50fa8230b3f8edd718f108a64c74d7880/envoy/extensions/filters/http/router/v3/router.pb.go#L50) is marked as Deprecated.

envoy related code:
https://github.com/envoyproxy/envoy/blob/56f4afdf841ee3cb353ab077f225b0e30988643c/source/common/router/upstream_request.cc#L100

2024-04-08 20:07 UTC, howardjohn approved these changes

2024-04-08 20:47 UTC, merged