wasmplugin: implement INITIAL phase
istio/istio pull request #50308
Opened 2024-04-06 12:10 UTC by zirain

**Please provide a description of this PR:**

xref: https://github.com/istio/api/pull/3143
fix: https://github.com/istio/istio/issues/50012

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [x] Networking
- [ ] Performance and Scalability
- [x] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2024-04-06 12:12 UTC, istio-testing commented
@zirain: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 5d7144b9f5ac4c927b565b238f8546ff55bd7c0c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/50308/release-notes_istio/1776583364602499072) | true | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-04-07 06:38 UTC, hzxuzhonghu approved these changes

2024-04-07 06:57 UTC, ramaraochavali requested changes
Let us align on the API first

2024-04-11 00:21 UTC, zirain commented
No need for this PR.

2024-04-11 00:21 UTC, closed without merging