update some example imagepullpolicy to IfNotPresent
istio/istio pull request #51246
Opened 2024-05-26 15:11 UTC by my-git9

**Please provide a description of this PR:**

Update some example imagepullpolicy to IfNotPresent

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2024-05-27 00:20 UTC, craigbox commented
I went through the PRs that committed each and didn't see any indication they need to be set to `Always`.

2024-05-27 00:20 UTC, craigbox approved these changes

2024-05-27 23:21 UTC, ericvn commented
Note that setting them to IfNotPresent will not force a reload of newer images if they exist. I believe in the past, we always wanted to force a user to use the latest and greatest images.

2024-05-27 23:21 UTC, ericvn requested changes
More discussion needed if we want to make sure the user is using the latest images.

2024-05-27 23:21 UTC, ericvn commented
/retest

2024-05-27 23:22 UTC, ericvn commented
/retest all

2024-05-27 23:22 UTC, istio-testing commented
@ericvn: The `/retest` command does not accept any targets.
The following commands are available to trigger required jobs:
* `/test bookinfo-build`
* `/test gencheck`
* `/test integ-ambient`
* `/test integ-basic-arm64`
* `/test integ-cni`
* `/test integ-distroless`
* `/test integ-ds`
* `/test integ-helm`
* `/test integ-ipv6`
* `/test integ-operator-controller`
* `/test integ-pilot`
* `/test integ-pilot-istiodremote`
* `/test integ-pilot-istiodremote-mc`
* `/test integ-pilot-multicluster`
* `/test integ-security`
* `/test integ-security-istiodremote`
* `/test integ-security-multicluster`
* `/test integ-telemetry`
* `/test integ-telemetry-discovery`
* `/test integ-telemetry-istiodremote`
* `/test integ-telemetry-mc`
* `/test lint`
* `/test macbuildcheck`
* `/test release-notes`
* `/test release-test`
* `/test unit-tests`
* `/test unit-tests-arm64`

The following commands are available to trigger optional jobs:
* `/test benchmark`
* `/test experimental-tracing`
* `/test integ-ambient-calico`
* `/test integ-assertion`

Use `/test all` to run the following jobs that were automatically triggered:
* `gencheck_istio`
* `integ-ambient_istio`
* `integ-basic-arm64_istio`
* `integ-cni_istio`
* `integ-distroless_istio`
* `integ-ds_istio`
* `integ-helm_istio`
* `integ-ipv6_istio`
* `integ-operator-controller_istio`
* `integ-pilot-istiodremote-mc_istio`
* `integ-pilot-istiodremote_istio`
* `integ-pilot-multicluster_istio`
* `integ-pilot_istio`
* `integ-security-istiodremote_istio`
* `integ-security-multicluster_istio`
* `integ-security_istio`
* `integ-telemetry-discovery_istio`
* `integ-telemetry-istiodremote_istio`
* `integ-telemetry-mc_istio`
* `integ-telemetry_istio`
* `lint_istio`
* `macbuildcheck_istio`
* `release-notes_istio`
* `release-test_istio`
* `unit-tests-arm64_istio`
* `unit-tests_istio`



<details>

In response to [this](https://github.com/istio/istio/pull/51246#issuecomment-2134134949):

>/retest all
>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository.
</details>

2024-05-27 23:22 UTC, ericvn commented
/test all

2024-05-27 23:45 UTC, craigbox commented
Most of the existing samples are `imagePullPolicy: ifNotPresent` already. Happy to have the discussion but I saw this PR as being just bringing a couple of outliers into line.

(I will say that when people benchmark things like Bookinfo, we don't want the container re-pulled every time.)

2024-05-28 02:22 UTC, zirain commented on samples/httpbin/sample-client/fortio-deploy.yaml
> +        imagePullPolicy: IfNotPresent
IMO, should keep this as `Always` because it's not static.

2024-05-28 17:35 UTC, merged