Fix WatchedResource data race
istio/istio pull request #51688
Opened 2024-06-24 17:21 UTC by wulianglongrd

fix #51685

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [x] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2024-06-24 17:21 UTC, istio-testing commented
Skipping CI for Draft Pull Request.
If you want CI signal for your change, please convert it to an actual PR.
You can still manually trigger a test run with `/test all`

2024-06-24 17:21 UTC, wulianglongrd commented
/test all

2024-06-24 17:24 UTC, istio-testing commented
@wulianglongrd: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio | 65ffbf8b4182fc703e2403e892ef97a122c55afe | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/51688/lint_istio/1805290246191976448) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-06-24 17:24 UTC, istio-testing commented
@wulianglongrd: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio | 65ffbf8b4182fc703e2403e892ef97a122c55afe | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/51688/lint_istio/1805290246191976448) | true | `/test lint`
gencheck_istio | 65ffbf8b4182fc703e2403e892ef97a122c55afe | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/51688/gencheck_istio/1805290236775763968) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-06-24 17:26 UTC, wulianglongrd commented
/test all

2024-06-24 18:07 UTC, howardjohn commented on pkg/xds/server.go
> +	if len(r.ResourceNames) > 0 {
I am worried about this cost. Especially since its to support a debug interface, which doesn't even depend on resourceNames

2024-06-25 09:18 UTC, hzxuzhonghu requested changes
I am thinking we should not fix this kind of race. It doenot influence istio work correctly. But introducing performance issue.

2024-06-25 09:47 UTC, wulianglongrd commented
I'm not sure if this fix makes sense. In theory there are data races in the core process (but I haven't really encountered them in production), for example:

read：

https://github.com/istio/istio/blob/27a44759d96d7e532a62321c8a2e2f33f6920e1f/pilot/pkg/xds/ads.go#L635


write：

https://github.com/istio/istio/blob/27a44759d96d7e532a62321c8a2e2f33f6920e1f/pkg/xds/server.go#L405

2024-06-25 12:40 UTC, hzxuzhonghu commented
I think they cannot run concurrently, donot they run in a goroutine.

2024-06-25 12:58 UTC, wulianglongrd commented
> I think they cannot run concurrently, donot they run in a goroutine.

You are correct, my example above is incorrect.

2024-06-25 14:03 UTC, howardjohn commented
Its only the debug interfaces that do the concurrent access

2024-07-22 04:54 UTC, closed without merging