Fix Handling of Deletions in EDS Cache and Update Functions
istio/istio pull request #52588
Opened 2024-08-08 19:23 UTC by srinivassurishetty

**Please provide a description of this PR:**

Added logic to ensure that any keys without corresponding endpoints are explicitly treated as deletions by sending a `nil` endpoints update.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2024-08-08 19:24 UTC, istio-testing commented
@srinivassurishetty: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | d9bb8efeae45e2285a6b2460d61e2615c3b4311e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/52588/release-notes_istio/1821628284400570368) | true | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-08-08 19:29 UTC, istio-testing commented
@srinivassurishetty: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | d9bb8efeae45e2285a6b2460d61e2615c3b4311e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/52588/release-notes_istio/1821628284400570368) | true | `/test release-notes`
unit-tests-arm64_istio | d9bb8efeae45e2285a6b2460d61e2615c3b4311e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/52588/unit-tests-arm64_istio/1821628286074097664) | true | `/test unit-tests-arm64`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-08-08 19:35 UTC, istio-testing commented
@srinivassurishetty: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | d9bb8efeae45e2285a6b2460d61e2615c3b4311e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/52588/release-notes_istio/1821628284400570368) | true | `/test release-notes`
unit-tests-arm64_istio | d9bb8efeae45e2285a6b2460d61e2615c3b4311e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/52588/unit-tests-arm64_istio/1821628286074097664) | true | `/test unit-tests-arm64`
unit-tests_istio | d9bb8efeae45e2285a6b2460d61e2615c3b4311e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/52588/unit-tests_istio/1821628286912958464) | true | `/test unit-tests`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-08-08 19:53 UTC, howardjohn requested changes
I don't really understand the difference here...? This will need a test anyways though, and the test will help me understand :slightly_smiling_face: .

Thanks for the PR

2024-08-09 02:55 UTC, srinivassurishetty commented
> I don't really understand the difference here...? This will need a test anyways though, and the test will help me understand 🙂 .
> 
> Thanks for the PR

The change ensures that keys without corresponding endpoints are correctly handled as deletions by sending a `nil` update, which is implemented in the for block at the end.  I've also modified the function to work within a single loop.

```
func (s *Controller) doEdsUpdate(keys sets.Set[instancesKey]) {
	endpoints := s.buildEndpoints(keys)
	shard := model.ShardKeyFromRegistry(s)

        // Delete
	if len(endpoints) == 0 {
		for k := range keys {
			s.XdsUpdater.EDSUpdate(shard, string(k.hostname), k.namespace, nil)
		}
	} else {
		// Update each endpoint in the XdsUpdater.
		for k, eps := range endpoints {
			s.XdsUpdater.EDSUpdate(shard, string(k.hostname), k.namespace, eps)
		}
	}

	// Ensure any keys without corresponding endpoints are treated as deletions.
	for dKey := range keys {
		if _, ok := endpoints[dKey]; !ok {
			s.XdsUpdater.EDSUpdate(shard, string(dKey.hostname), dKey.namespace, nil)
		}
	}
}
```

2024-08-09 03:46 UTC, hzxuzhonghu reviewed
Seems you are fixing a bug, can you elaborate a little bit more and add some tests

2024-08-12 15:20 UTC, istio-testing commented
@srinivassurishetty: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | d9bb8efeae45e2285a6b2460d61e2615c3b4311e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/52588/unit-tests-arm64_istio/1821628286074097664) | true | `/test unit-tests-arm64`
unit-tests_istio | d9bb8efeae45e2285a6b2460d61e2615c3b4311e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/52588/unit-tests_istio/1821628286912958464) | true | `/test unit-tests`
release-notes_istio | bfffb52fae58ab56fc11642a69064b3576d8eafb | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/52588/release-notes_istio/1823016655303741440) | true | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-08-12 15:26 UTC, istio-testing commented
@srinivassurishetty: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests_istio | d9bb8efeae45e2285a6b2460d61e2615c3b4311e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/52588/unit-tests_istio/1821628286912958464) | true | `/test unit-tests`
release-notes_istio | bfffb52fae58ab56fc11642a69064b3576d8eafb | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/52588/release-notes_istio/1823016655303741440) | true | `/test release-notes`
unit-tests-arm64_istio | bfffb52fae58ab56fc11642a69064b3576d8eafb | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/52588/unit-tests-arm64_istio/1823016656985657344) | true | `/test unit-tests-arm64`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-08-12 15:27 UTC, istio-testing commented
@srinivassurishetty: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | bfffb52fae58ab56fc11642a69064b3576d8eafb | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/52588/release-notes_istio/1823016655303741440) | true | `/test release-notes`
unit-tests-arm64_istio | bfffb52fae58ab56fc11642a69064b3576d8eafb | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/52588/unit-tests-arm64_istio/1823016656985657344) | true | `/test unit-tests-arm64`
unit-tests_istio | bfffb52fae58ab56fc11642a69064b3576d8eafb | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/52588/unit-tests_istio/1823016657828712448) | true | `/test unit-tests`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-08-12 16:40 UTC, howardjohn approved these changes
Thanks for the fix and the test. This makes perfect sense to me now after seeing the test

2024-08-12 17:22 UTC, istio-testing commented
@srinivassurishetty: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | bfffb52fae58ab56fc11642a69064b3576d8eafb | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/52588/unit-tests-arm64_istio/1823016656985657344) | true | `/test unit-tests-arm64`
unit-tests_istio | bfffb52fae58ab56fc11642a69064b3576d8eafb | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/52588/unit-tests_istio/1823016657828712448) | true | `/test unit-tests`
release-notes_istio | a7fe0349eba64967ef6457e556b563b960712503 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/52588/release-notes_istio/1823047315603066880) | true | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-08-12 17:33 UTC, srinivassurishetty commented
> Thanks for the fix and the test. This makes perfect sense to me now after seeing the test

Thanks @howardjohn

2024-08-12 17:34 UTC, srinivassurishetty commented
> Seems you are fixing a bug, can you elaborate a little bit more and add some tests

Yes done.

2024-08-12 17:55 UTC, srinivassurishetty commented
/retest

2024-08-12 18:18 UTC, istio-testing commented
@srinivassurishetty: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-security-multicluster_istio | a7fe0349eba64967ef6457e556b563b960712503 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/52588/integ-security-multicluster_istio/1823047308921540608) | true | `/test integ-security-multicluster`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-08-12 18:20 UTC, srinivassurishetty commented
/retest

2024-08-12 19:11 UTC, merged

2024-08-12 19:14 UTC, istio-testing commented
In response to a cherrypick label: new pull request created: #52647

2024-08-12 19:14 UTC, istio-testing commented
In response to a cherrypick label: new pull request created: #52648

2024-08-12 19:14 UTC, istio-testing commented
In response to a cherrypick label: new pull request created: #52649

2024-08-12 19:15 UTC, istio-testing commented
In response to a cherrypick label: new pull request could not be created: failed to create pull request against istio/istio#release-1.23 from head istio-testing:cherry-pick-52588-to-release-1.23: status code 422 not one of [201], body: {"message":"Validation Failed","errors":[{"resource":"PullRequest","code":"custom","message":"A pull request already exists for istio-testing:cherry-pick-52588-to-release-1.23."}],"documentation_url":"https://docs.github.com/rest/pulls/pulls#create-a-pull-request","status":"422"}

2024-08-12 19:15 UTC, istio-testing commented
In response to a cherrypick label: new pull request could not be created: failed to create pull request against istio/istio#release-1.22 from head istio-testing:cherry-pick-52588-to-release-1.22: status code 422 not one of [201], body: {"message":"Validation Failed","errors":[{"resource":"PullRequest","code":"custom","message":"A pull request already exists for istio-testing:cherry-pick-52588-to-release-1.22."}],"documentation_url":"https://docs.github.com/rest/pulls/pulls#create-a-pull-request","status":"422"}

2024-08-12 19:15 UTC, istio-testing commented
In response to a cherrypick label: new pull request could not be created: failed to create pull request against istio/istio#release-1.23 from head istio-testing:cherry-pick-52588-to-release-1.23: status code 422 not one of [201], body: {"message":"Validation Failed","errors":[{"resource":"PullRequest","code":"custom","message":"A pull request already exists for istio-testing:cherry-pick-52588-to-release-1.23."}],"documentation_url":"https://docs.github.com/rest/pulls/pulls#create-a-pull-request","status":"422"}