authz support string contains match
istio/istio pull request #52583
Opened 2024-08-08 17:47 UTC by wulianglongrd

support string contains match, fix https://github.com/istio/istio/issues/52557

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [x] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2024-08-08 17:47 UTC, istio-testing commented
Skipping CI for Draft Pull Request.
If you want CI signal for your change, please convert it to an actual PR.
You can still manually trigger a test run with `/test all`

2024-08-08 17:48 UTC, wulianglongrd commented
/test all

2024-08-08 17:54 UTC, istio-testing commented
@wulianglongrd: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | 3cf86d4083f34c7f4393cc703e96244b161a6e06 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/52583/unit-tests-arm64_istio/1821604351341236224) | true | `/test unit-tests-arm64`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-08-09 00:42 UTC, wulianglongrd commented
/test all

2024-08-09 00:46 UTC, wulianglongrd commented on pilot/pkg/security/authz/matcher/header_test.go
> +			V:    "*/productpage",
the old unit tests treat it as a `suffix` match, this PR treat it as a `contains` match(see L81).

2024-08-09 04:03 UTC, hzxuzhonghu requested changes
I think the right solution should to support regex match

2024-08-09 04:12 UTC, wulianglongrd commented
> I think the right solution should to support regex match

Thanks for the review, I have similar ideas to yours, but I currently don't have a good way to express regex semantics. 

Do you have any suggestions for using [key or values](https://istio.io/latest/docs/reference/config/security/authorization-policy/#Condition) to express regex semantics?

2024-08-09 04:32 UTC, wulianglongrd commented
BTW, currently values support the following semantics:
1. `*`: preset match
2. `*{anything}`: suffix match
3. `{anything}*`: prefix match
4. the rest: exact match

Use `regex://` prefix to express regex semantics?

2024-08-09 06:31 UTC, hzxuzhonghu commented
seems too hardcoding, how about adding a new field type []StringMatcher like what we do in VS, this field to deprecate the old `values`

2024-08-10 15:13 UTC, howardjohn commented
Thanks for the PR. I have a few concerns

1. As this is an API change to a v1 API, this should go through API review before implementation 
2. This seems inconsistent to apply only to headers
3. The intended use case here seems to be matching multiple headers flattened into a single one, but doesn't actually do that securely - I worry this would lead to easily miswritten policies that introduce vulnerability

2024-08-12 04:31 UTC, wulianglongrd commented
> seems too hardcoding, how about adding a new field type []StringMatcher like what we do in VS, this field to deprecate the old `values`

Thanks, this solution makes sense to me.

2024-08-12 04:39 UTC, wulianglongrd commented
Thanks.

> 1. As this is an API change to a v1 API, this should go through API review before implementation

agree.

> 2. This seems inconsistent to apply only to headers

Thanks for pointing this out, it also applies to `:method` and probably nothing else.

> 3. The intended use case here seems to be matching multiple headers flattened into a single one, but doesn't actually do that securely - I worry this would lead to easily miswritten policies that introduce vulnerability

 😊 Can you give an example for this?

2024-08-12 16:30 UTC, howardjohn commented
> 😊 Can you give an example for this?

Yes, sorry I sent that from my phone so was hard to elaborate..

In your example:
* rule is `*foo=*`. `"Cookie: not-foo=bar"` unexpecedly matches
* rule is `*foo*`. `"X-foo: not foo bar"` unexpectedly matches

2024-08-24 07:38 UTC, wulianglongrd commented
@hzxuzhonghu @howardjohn 

How about using the following syntax? One of `values`, `notValues`, `match`. The new `match` field is `StringMatch` type.

```yaml
  rules:
  - when:
    # old syntax
    - key: request.headers[header]
      values: ["value"]

    # new syntax: exact match
    - key: request.headers[header1]
      match:
        exact: value1

    # new syntax: prefix match
    - key: request.headers[header2]
      match:
        prefix: value2

    # new syntax: regex match
    - key: request.headers[header3]
      match:
        regex: value3
```

2024-08-26 11:33 UTC, hzxuzhonghu commented
>Note: at least one of `values`, `notValues` or `match` must be set.

only one or at least one?

2024-08-26 12:00 UTC, wulianglongrd commented
> > Note: at least one of `values`, `notValues` or `match` must be set.
> 
> only one or at least one?

a. values, not_values
b. match

At least one of `a` or `b`. when `a` is selected, at least one of `values` or `not_values`.

2024-08-26 15:22 UTC, howardjohn commented
In that past we have had pretty conclusive decision to not add regex into authz policy. See discussion in https://github.com/istio/istio/issues/25021 and many linked issues.

Even to serve this use case, regex is inappropriate as I tried to show in https://github.com/istio/istio/pull/52583#issuecomment-2284453746.

2024-08-26 15:26 UTC, howardjohn commented
What is really desired here, it seems, is to be able to match on individual headers instead of merged ones

2024-08-27 09:29 UTC, hzxuzhonghu commented
>>Note: at least one of values, notValues or match must be set.

>only one or at least one?

@wulianglongrd I think it should be only one, not more than one. Like you cannot specify string match with values, they can conflict

2024-08-27 09:31 UTC, hzxuzhonghu commented
>What is really desired here, it seems, is to be able to match on individual headers instead of merged ones

@howardjohn regex can be used to match this with `;` provided, for more complex case, it may need envoy to support

2024-08-28 16:32 UTC, wulianglongrd commented
Sorry for the late reply.

> In that past we have had pretty conclusive decision to not add regex into authz policy. See discussion in #25021 and many linked issues.

Thanks @howardjohn . I take a quick look and saw some reasons for not implementing regex: https://github.com/istio/istio/issues/16585#issuecomment-912846421, https://github.com/istio/istio/issues/16585#issuecomment-1456359549, https://github.com/istio/istio/issues/16585#issuecomment-1164633757, https://github.com/istio/istio/issues/16585#issuecomment-984790462 . BTW, it seems that the `path templating matching`(https://github.com/istio/istio/pull/50365) currently only supports `path`, which does not cover https://github.com/istio/istio/issues/52557 issue (`request.headers`).


> Even to serve this use case, regex is inappropriate as I tried to show in #52583 (comment).

I think correct regex can prevent these issues. But, inaccurate regex may cause security issues.


> What is really desired here

The motivation is to fix https://github.com/istio/istio/issues/52557 and hope that the matching rules of authz and VS are consistent.


> I think it should be only one, not more than one. Like you cannot specify string match with values, they can conflict

Thanks @hzxuzhonghu . Yes, if it is "more than one", the usage will be more complicated and there may be conflicts.

2024-08-28 16:40 UTC, howardjohn commented
#52557 is really a structured match requirement.. If we had a way to match on individual split headers instead of aggregated ones, it would solve this.

That is, instead of matching against `cookie1=whatever; cookie2=whatever;`, it would match against `cookie1=whatever` and `cookie2=whatever`. Not sure what this would look like in terms of API, AND vs OR them together, etc though.

2024-10-13 05:03 UTC, closed without merging