added a unit test for envoysocketfunction
istio/istio pull request #52770
Opened 2024-08-20 15:41 UTC by visheshtha

While going through `networking.go` in pilot pkg,found out that no testcase was written for `envoysocketprotocol` function so added a testcase for it in `networking_test.go`.

2024-08-20 17:00 UTC, bleggett requested changes
Hi - thanks for opening this!

```
func (tp TransportProtocol) ToEnvoySocketProtocol() core.SocketAddress_Protocol {
	if tp == TransportProtocolQUIC {
		return core.SocketAddress_UDP
	}
	return core.SocketAddress_TCP
}
```

This is the function under test here. 

The behavior being tested here is trivial, so this test doesn't add meaningful value.

What would be welcome are

1. Tests that make a meaningful impact on (measured) code coverage, especially coverage of important paths with minimal coverage.
2. Enabling code coverage reporting generally, so (1) is easier to show, we have several issues open for this already: https://github.com/istio/istio/issues/43902 and https://github.com/istio/istio/issues/50991

2024-08-21 16:20 UTC, MorrisLaw reviewed
In addition to what @bleggett has already pointed out, it's good to also checkout the integration tests that exist. It's possible that this is being tested there instead. Sometimes, it makes more sense to test certain areas of the code as a part of an integration test as opposed to unit testing when the function itself is trivial, but maybe less trivial as a part of a certain scenario.

So, if an integration test doesn't exist for a situation where envoySocketProtocol is being used as part of a larger test, maybe you can add one there that you think is useful under `tests/integration/ambient/pilot`. Use this document for guidance on writing integration tests: https://github.com/istio/istio/wiki/Writing-Good-Integration-Tests if you end up going down that route.

Thanks again for your contribution!

2024-09-02 10:18 UTC, visheshtha commented
Hi @bleggett @MorrisLaw ,Thanks for reviewing,could you please help me with the function whose addition of a testcase(unit testcase) won't be a trivial one or a way to find such functions whose testcase additions are worth adding

2024-09-06 01:58 UTC, MorrisLaw commented
> Hi @bleggett @MorrisLaw ,Thanks for reviewing,could you please help me with the function whose addition of a testcase(unit testcase) won't be a trivial one or a way to find such functions whose testcase additions are worth adding. Also the path which you mentioned for the changes to be added,doesn't exists.

Sorry, that was a typo. Should have been `tests/integration/pilot` not `tests/integration/ambient/pilot`.

Pilot related integration tests can be located [here](https://github.com/istio/istio/tree/master/tests/integration/pilot).

But as @bleggett has pointed out in the [issue](https://github.com/istio/istio/issues/50991) he shared, knowing which areas have poor coverage and which don't aren't easily identifiable at the moment. There's not a readily available list to share with you. But if you find another part of code that you think needs testing or seems to be in the critical path of Istio functionality, feel free to reach out in the[ Istio slack, during one of the weekly meetings ](https://github.com/istio/community/blob/master/WORKING-GROUPS.md#working-group-meetings)or create an issue to get feedback as opposed to making a PR for a test that might not be needed (this will save you time and increase your chance of landing PRs). Hope this helps!

2024-09-10 17:36 UTC, visheshtha commented
Hi @MorrisLaw ,thank you for responding,totally agree,also I have raised an issue regarding this, #52964, PTAL!

2024-10-26 05:04 UTC, closed without merging