Return nil if gRPC stream returns io.EOF instead of returning io.EOF itself.
istio/istio pull request #52833
Opened 2024-08-23 17:45 UTC by ingwonsong

Currently, in istio-agent, if there is an EOF from Recv for the upstream, xds_proxy sends EOF error to the downstream.
But, since EOF is meaning the graceful termination of the connection, we need to return `nil` instead of EOF.
Note that this returning EOF is regarded as 'Unknown' error in gRPC and so Envoy is now displaying confusing error message like:

```
... warning envoy config external/envoy/source/extensions/config_subscription/grpc/grpc_stream.h:152 
StreamAggregatedResources gRPC config stream to xds-grpc closed: 2, EOF thread=15
```
(2 is Unknown error code.)

Change-Id: I88e225acad5a359f663eaf6b215c601b13410ea0

2024-08-23 18:19 UTC, howardjohn requested changes
I still don't think this makes sense..

First, we shouldn't obscure the error we send to envoy. If we don't like how envoy logs an error ,we should change envoy... but we already did that! https://github.com/envoyproxy/envoy/blob/3f36f1466de11624958614a3fd46d9ce208ed5b5/source/extensions/config_subscription/grpc/grpc_stream.h#L191

Are you sure you are not just using a really old version of envoy?

2024-08-23 18:19 UTC, howardjohn commented on pkg/istio-agent/xds_proxy.go
>  		proxyLog.WithLabels("id", con.conID).Warnf("upstream terminated with unexpected error %v", err)
won't this now log "unexpected error nil"?

2024-08-23 21:05 UTC, ingwonsong commented
> I still don't think this makes sense..
> 
> First, we shouldn't obscure the error we send to envoy. If we don't like how envoy logs an error ,we should change envoy... but we already did that! https://github.com/envoyproxy/envoy/blob/3f36f1466de11624958614a3fd46d9ce208ed5b5/source/extensions/config_subscription/grpc/grpc_stream.h#L191

Actually, I think this is for having the same error in Envoy.
If we return `io.EOF` in `StreamAggregatedResources` or `DeltaAggregatedResources`, in the client side, it will be `Unknown` error because gRPC server will  wrap `io.EOF` with gRPC error and put `Unknown` error code. 
That's the reason why we are seeing `closed: 2, EOF`.

Therefore, I think that we need to return `nil` from the handlers, to make Envoy get the same `io.EOF`.

Am I missing something?

> Are you sure you are not just using a really old version of envoy?

I don't think that this is Envoy version issue, but

2024-08-23 21:06 UTC, howardjohn commented
> I don't think that this is Envoy version issue, but

How is it not? The current envoy clear logs this at DEBUG level... https://github.com/envoyproxy/envoy/blob/3f36f1466de11624958614a3fd46d9ce208ed5b5/source/extensions/config_subscription/grpc/grpc_stream.h#L191

2024-08-23 21:14 UTC, ingwonsong commented
> https://github.com/envoyproxy/envoy/blob/3f36f1466de11624958614a3fd46d9ce208ed5b5/source/extensions/config_subscription/grpc/grpc_stream.h#L191

I thought that the log was coming from 
https://github.com/envoyproxy/envoy/blob/3f36f1466de11624958614a3fd46d9ce208ed5b5/source/extensions/config_subscription/grpc/grpc_stream.h#L184

because "warn" message is logged when it is not in ("deadline exceeded", "resource exhausted", "unavailable").

https://github.com/envoyproxy/envoy/blob/3f36f1466de11624958614a3fd46d9ce208ed5b5/source/extensions/config_subscription/grpc/grpc_stream.h#L232-L243

2024-08-23 21:18 UTC, howardjohn reviewed
Thats not what I see:

```
2024-08-23T21:18:30.621784Z     debug   xdsproxy        upstream terminated with status rpc error: code = Unavailable desc = error reading from server: EOF     id=4
2024-08-23T21:18:30.621821Z     debug   xdsproxy        disconnected from delta XDS server: localhost:15012     id=4
2024-08-23T21:18:30.621910Z     debug   xdsproxy        downstream terminated with status rpc error: code = Canceled desc = context canceled    id=4
2024-08-23T14:18:30.622110Z     debug   envoy config external/envoy/source/extensions/config_subscription/grpc/grpc_stream.h:183        DeltaAggregatedResources gRPC config stream to xds-grpc closed: 14, error reading from server: EOF      thread=296841
```

2024-08-23 21:20 UTC, howardjohn commented
At the very least we should forward the rror as a gRPC UNAVAILABLE error, not just `nil`.

2024-08-23 21:22 UTC, ingwonsong commented
> At the very least we should forward the error as a gRPC UNAVAILABLE error, not just `nil`.

It does totally make sense to me. 

Btw, how did you get "Unavailable" from your log? it is already returning "Unavailable" error code for upstream's EOF?

2024-08-23 21:24 UTC, ingwonsong commented
Anyway, if we returns Unavailable, Envoy is now getting different error with xds_proxy. 

But, Unavailable makes sense to me.

2024-08-23 21:26 UTC, howardjohn commented
> > At the very least we should forward the error as a gRPC UNAVAILABLE error, not just `nil`.
> 
> It does totally make sense to me.
> 
> Btw, how did you get "Unavailable" from your log? it is already returning "Unavailable" error code for upstream's EOF?

I have never been able to get anything except that for disconnects. Not sure how you are seeing otherwise...

2024-08-23 21:42 UTC, ingwonsong commented
Ah.. I realized that graceful closing an ADS connection by Server (istiod) does not happen in Istio. Right?

In our case, ADS connection is disconnected by Server periodically, so that we are seeing this unlike OSS Istio.

If returning `Unavailable` is acceptable, I would like to go with it. WDYT?

2024-08-23 21:57 UTC, howardjohn commented
Istiod does the gracefully close as well. I tested a lot ways to close the
server and couldn't reproduce

On Fri, Aug 23, 2024, 2:42 PM Ingwon Song ***@***.***> wrote:

> Ah.. I realized that graceful closing an ADS connection by Server (istiod)
> does not happen in Istio. Right?
>
> In our case, ADS connection is disconnected by Server periodically, so
> that we are seeing this unlike OSS Istio.
>
> If returning Unavailable is acceptable, I would like to go with it. WDYT?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/istio/pull/52833#issuecomment-2307847133>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEYGXORXOBDBO2STUNAWPTZS6UFHAVCNFSM6AAAAABNATGGGWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMBXHA2DOMJTGM>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2024-08-23 22:52 UTC, ingwonsong commented
> Istiod does the gracefully close as well. I tested a lot ways to close the server and couldn't reproduce

When it does graceful close? (Here I meant that, by "graceful close", gRPC server stream handler returns `nil`.)
I couldn't find the code path, except the `force_disconnect`.

When I run the following command, I could get the same error logs.

```
# force disconnect
$ kubectl exec -it -n istio-system istiod-75944fff9b-q82m9 --  curl http://localhost:15014/debug/force_disconnect?proxyID=httpbin-8944f8d9-xnks9.echo
```

```
2024-08-23T22:48:11.573554Z	warning	envoy config external/envoy/source/extensions/config_subscription/grpc/grpc_stream.h:155	DeltaAggregatedResources gRPC config stream to xds-grpc closed: 2, EOF	thread=19
```

2024-08-24 00:16 UTC, qfel commented
> At the very least we should forward the rror as a gRPC UNAVAILABLE error, not just nil.

io.EOF is **not** an error. Successful stream termination (eg. CloseSend) will cause the client to see io.EOF. Ie. logically the RPC status is OK/SUCCESS/0. So the correct behavior in a proxy is to generally translate io.EOF to nil/CloseSend.

2024-08-24 00:22 UTC, howardjohn approved these changes
thanks for the fix and additional context

2024-08-24 00:54 UTC, merged

2024-08-24 00:55 UTC, istio-testing commented
In response to a cherrypick label: #52833 failed to apply on top of branch "release-1.22":
```
Applying: Return nil for io.EOF
Using index info to reconstruct a base tree...
M	pilot/pkg/xds/delta.go
M	pkg/istio-agent/xds_proxy.go
A	pkg/xds/server.go
Falling back to patching base and 3-way merge...
CONFLICT (modify/delete): pkg/xds/server.go deleted in HEAD and modified in Return nil for io.EOF. Version Return nil for io.EOF of pkg/xds/server.go left in tree.
Auto-merging pkg/istio-agent/xds_proxy.go
Auto-merging pilot/pkg/xds/delta.go
CONFLICT (content): Merge conflict in pilot/pkg/xds/delta.go
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Patch failed at 0001 Return nil for io.EOF
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

```

2024-08-24 00:55 UTC, istio-testing commented
In response to a cherrypick label: new issue created for failed cherrypick: #52838

2024-08-24 00:55 UTC, istio-testing commented
In response to a cherrypick label: new pull request created: #52839

2024-08-24 00:56 UTC, istio-testing commented
In response to a cherrypick label: #52833 failed to apply on top of branch "release-1.21":
```
Applying: Return nil for io.EOF
Using index info to reconstruct a base tree...
M	pilot/pkg/grpc/grpc.go
M	pilot/pkg/xds/delta.go
M	pkg/istio-agent/xds_proxy.go
A	pkg/xds/server.go
Falling back to patching base and 3-way merge...
CONFLICT (modify/delete): pkg/xds/server.go deleted in HEAD and modified in Return nil for io.EOF. Version Return nil for io.EOF of pkg/xds/server.go left in tree.
Auto-merging pkg/istio-agent/xds_proxy.go
CONFLICT (content): Merge conflict in pkg/istio-agent/xds_proxy.go
Auto-merging pilot/pkg/xds/delta.go
CONFLICT (content): Merge conflict in pilot/pkg/xds/delta.go
Auto-merging pilot/pkg/grpc/grpc.go
CONFLICT (content): Merge conflict in pilot/pkg/grpc/grpc.go
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Patch failed at 0001 Return nil for io.EOF
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

```

2024-08-24 00:56 UTC, istio-testing commented
In response to a cherrypick label: new issue created for failed cherrypick: #52840