added a testcase for isfilevalid
istio/istio pull request #52948
Opened 2024-08-30 17:04 UTC by visheshtha

While going through the go file,found out that there's no testcase for the function `isValidFile` in (https://github.com/istio/istio/blob/master/istioctl/pkg/analyze/analyze.go) so added a testcase for the function isValidFile in [https://github.com/istio/istio/blob/master/istioctl/pkg/analyze/analyze_test.go](https://github.com/istio/istio/blob/master/istioctl/pkg/analyze/analyze_test.go)

2024-08-30 17:48 UTC, bleggett requested changes
```
func isValidFile(f string) bool {
	ext := filepath.Ext(f)
	for _, e := range fileExtensions {
		if e == ext {
			return true
		}
	}
	return false
}
```

is the function under test here (and which itself could be simplified)

The behavior being tested here is trivial, so this test doesn't add meaningful value - it wouldn't improve measurable coverage rates, and doesn't improve coverage of critical sections.

What would be welcome are

- Tests that make a measurable impact on code coverage rates, especially coverage of important paths with minimal coverage.

- Enabling code coverage reporting for Istio generally, so (1) is easier for contributors like yourself to show, we have several issues open for this already, e.g.  https://github.com/istio/istio/issues/50991

2024-09-02 10:21 UTC, visheshtha commented
Hi @bleggett,Thanks for reviewing,could you please help me with the function whose addition of a testcase(unit testcase) won't be a trivial one or a way to find such functions whose testcase additions are worth adding.

2024-09-04 21:37 UTC, bleggett commented
> Hi @bleggett,Thanks for reviewing,could you please help me with the function whose addition of a testcase(unit testcase) won't be a trivial one or a way to find such functions whose testcase additions are worth adding.

Yes, what would be very welcome would be

1. [Using `golang` test coverage to find packages/files with low or no coverage](https://go.dev/doc/build-cover), and adding tests to those. If you show me that the thing you are testing has no real coverage, and you add coverage to the package/file, that's something measurably meaningful.

2. Adding coverage reports to specific components via `makefile` - e.g. generating coverage reports to `istio-cni` as mentioned in https://github.com/istio/istio/issues/50991 - we don't have to do coverage for everything at once, but starting small by generating the reports on a component-by-component basis and then using that to justify new tests would be very useful.

Hope that helps! Let me know if you have more questions.

2024-10-09 14:39 UTC, MorrisLaw commented
hey @visheshtha I recently added some documentation around how integration tests are setup with a link to documentation on how to add one. Maybe looking into that area might be helpful in finding gaps or areas where more coverage would be useful. Important to note though that integration tests are a bit harder to figure out. But if you do, it is immensely helpful and sometimes even more meaningful than a simple unit test.

https://github.com/istio/istio/blob/master/architecture/tests/integration.md

2024-10-10 05:41 UTC, visheshtha commented on istioctl/pkg/analyze/analyze_test.go
> +			name:     "Test .json extension",
Thanks @MorrisLaw,yes sure,i'll take a look.

2024-10-10 09:20 UTC, visheshtha commented
> hey @visheshtha I recently added some documentation around how integration tests are setup with a link to documentation on how to add one. Maybe looking into that area might be helpful in finding gaps or areas where more coverage would be useful. Important to note though that integration tests are a bit harder to figure out. But if you do, it is immensely helpful and sometimes even more meaningful than a simple unit test.
> 
> https://github.com/istio/istio/blob/master/architecture/tests/integration.md

Hi @MorrisLaw,thanks,will surely look towards adding integration tests.

2024-11-25 05:04 UTC, closed without merging