fix `istio install` output incorrect version
istio/istio pull request #53324
Opened 2024-09-27 09:42 UTC by nicole-lihui

resolved #53323

**Please provide a description of this PR:**

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Please check any characteristics that apply to this pull request.**

- [X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2024-09-27 09:44 UTC, istio-testing commented
@nicole-lihui: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-basic-arm64_istio | 3c32de87f2ff6ae998009fcf162720762ab3f6cb | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/53324/integ-basic-arm64_istio/1839601560032645120) | true | `/test integ-basic-arm64`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-09-27 09:46 UTC, nicole-lihui commented
/test integ-basic-arm64

2024-09-27 13:53 UTC, howardjohn requested changes
https://github.com/istio/istio/issues/53323#issuecomment-2379340246

2024-10-08 07:23 UTC, nicole-lihui commented
ok,this phenomenon needs to be reconsidered and the current approach abandoned

2024-10-08 07:23 UTC, closed without merging