Support serving istio and user TLS on same port
istio/istio pull request #53469
Opened 2024-10-08 03:12 UTC by wtzhang23

**Please provide a description of this PR:**
Allow serving Istio mTLS and user TLS on the same port if PeerAuthentication is permissive. See [RFC](https://docs.google.com/document/d/13ciYV5H85rOc_EH1LcuoVyCFxFu_n4SpNq1luvHmRmA/edit#heading=h.xw1gqgyqs5b).

Fixes #51768

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [x] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2024-10-08 03:12 UTC, istio-testing commented
Hi @wtzhang23. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository.
</details>

2024-10-14 23:07 UTC, wtzhang23 commented
Tested via the following script
```sh
TEST_DIR=/tmp/test-istio-dual-tls
mkdir -p ${TEST_DIR}
GOBIN=${TEST_DIR} go install istio.io/release-builder@latest

envsubst <<EOF > ${TEST_DIR}/build-manifest.yaml
version: 1.24.0
docker: docker.io/istio
directory: ${TEST_DIR}/istio-release
dependencies:
  istio:
    git: https://github.com/wtzhang23/istio
    branch: dual-tls-ingress
outputs: ["docker", "helm"]
skipGenerateBillOfMaterials: true
EOF
${TEST_DIR}/release-builder build --manifest ${TEST_DIR}/build-manifest.yaml

kind create cluster --name istio-test-dual-tls --kubeconfig ${TEST_DIR}/.kubeconfig
for archive in ${TEST_DIR}/istio-release/out/docker/*; do
    echo "Preloading ${archive}"
    kind load image-archive --name istio-test-dual-tls <(gzip --decompress --stdout ${archive})
done
kubectl create namespace --kubeconfig ${TEST_DIR}/.kubeconfig istio-system
helm install istio-base ${TEST_DIR}/istio-release/out/helm/base-1.24.0.tgz -n istio-system --kubeconfig ${TEST_DIR}/.kubeconfig
helm install istiod ${TEST_DIR}/istio-release/out/helm/istiod-1.24.0.tgz -n istio-system --kubeconfig ${TEST_DIR}/.kubeconfig --set env.ENABLE_TLS_ON_SIDECAR_INGRESS=true --wait

kubectl create namespace --kubeconfig ${TEST_DIR}/.kubeconfig test-server
kubectl label namespace --kubeconfig ${TEST_DIR}/.kubeconfig test-server istio-injection=enabled --overwrite
openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes -keyout ${TEST_DIR}/tls.key -out ${TEST_DIR}/tls.crt -subj "/CN=foo.bar"
kubectl create secret tls --kubeconfig ${TEST_DIR}/.kubeconfig -n test-server tls-cert --cert ${TEST_DIR}/tls.crt --key ${TEST_DIR}/tls.key
cat <<EOF | kubectl apply --kubeconfig ${TEST_DIR}/.kubeconfig -f -
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: default
  namespace: test-server
spec:
  mtls:
    mode: PERMISSIVE
---
apiVersion: networking.istio.io/v1
kind: Sidecar
metadata:
  name: test-tls
  namespace: test-server
spec:
  workloadSelector:
    labels:
      app: test-server
  ingress:
    - port:
        number: 80
        protocol: HTTPS
      tls:
        mode: SIMPLE
        serverCertificate: /etc/tls-secrets/tls.crt
        privateKey: /etc/tls-secrets/tls.key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-server
  namespace: test-server
  labels:
    app: test-server
spec:
  selector:
    matchLabels:
      app: test-server
  template:
    metadata:
      labels:
        app: test-server
      annotations:
        sidecar.istio.io/userVolumeMount: '[{"name":"tls-cert","mountPath":"/etc/tls-secrets","readOnly":true}]'
    spec:
      containers:
      - name: httpbin
        image: kennethreitz/httpbin
        ports:
        - containerPort: 80
      volumes:
      - name: tls-cert
        secret:
          secretName: tls-cert
---
apiVersion: v1
kind: Service
metadata:
  name: test-server
  namespace: test-server
spec:
  selector:
    app: test-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
EOF


kubectl create namespace --kubeconfig ${TEST_DIR}/.kubeconfig test-client-mesh
kubectl label namespace --kubeconfig ${TEST_DIR}/.kubeconfig test-client-mesh istio-injection=enabled --overwrite
cat <<EOF | kubectl apply --kubeconfig ${TEST_DIR}/.kubeconfig -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-client-mesh
  namespace: test-client-mesh
  labels:
    app: test-client-mesh
spec:
  selector:
    matchLabels:
      app: test-client-mesh
  template:
    metadata:
      labels:
        app: test-client-mesh
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      volumes:
      - name: tls-cert
        secret:
          secretName: tls-cert
EOF

kubectl create namespace --kubeconfig ${TEST_DIR}/.kubeconfig test-client
cat <<EOF | kubectl apply --kubeconfig ${TEST_DIR}/.kubeconfig -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-client
  namespace: test-client
  labels:
    app: test-client
spec:
  selector:
    matchLabels:
      app: test-client
  template:
    metadata:
      labels:
        app: test-client
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      volumes:
      - name: tls-cert
        secret:
          secretName: tls-cert
EOF

sleep 40

kubectl exec --kubeconfig ${TEST_DIR}/.kubeconfig -n test-server deploy/test-server -c istio-proxy -- curl localhost:15000/config_dump > ${TEST_DIR}/config_dump.json
kubectl exec --kubeconfig ${TEST_DIR}/.kubeconfig -n test-client-mesh deploy/test-client-mesh -- curl http://test-server.test-server.svc.cluster.local:80/headers
kubectl exec --kubeconfig ${TEST_DIR}/.kubeconfig -n test-client deploy/test-client -- curl --insecure https://test-server.test-server.svc:80/headers
```

2024-10-15 00:43 UTC, zirain commented
/ok-to-test

2024-10-15 00:43 UTC, istio-testing commented
@wtzhang23: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | ce9a7155f628245b3182932f0e027a03480745a7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/53469/release-notes_istio/1845988774400495616) | true | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-10-15 00:45 UTC, istio-testing commented
@wtzhang23: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | ce9a7155f628245b3182932f0e027a03480745a7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/53469/release-notes_istio/1845988774400495616) | true | `/test release-notes`
lint_istio | ce9a7155f628245b3182932f0e027a03480745a7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/53469/lint_istio/1845988772726968320) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-10-15 00:52 UTC, istio-testing commented
@wtzhang23: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | ce9a7155f628245b3182932f0e027a03480745a7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/53469/release-notes_istio/1845988774400495616) | true | `/test release-notes`
lint_istio | ce9a7155f628245b3182932f0e027a03480745a7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/53469/lint_istio/1845988772726968320) | true | `/test lint`
unit-tests_istio | ce9a7155f628245b3182932f0e027a03480745a7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/53469/unit-tests_istio/1845988777315536896) | true | `/test unit-tests`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-10-22 17:41 UTC, bleggett commented
> **Please provide a description of this PR:** Allow serving Istio mTLS and user TLS on the same port if PeerAuthentication is permissive. See [RFC](https://docs.google.com/document/d/13ciYV5H85rOc_EH1LcuoVyCFxFu_n4SpNq1luvHmRmA/edit#heading=h.xw1gqgyqs5b).
> 
> Fixes #51768 Depends on #53396

I'm not sure exactly what you mean by `Istio mTLS` here - there is really no such thing.

Are you saying you want the same port to terminate TLS _and_ mTLS traffic, at the same time?

2024-10-22 18:03 UTC, wtzhang23 commented
Yes, sorry for my misleading naming. When I mention `Istio mTLS`, I really mean "mTLS using Istio-specific ALPNs". I'll update the wording.

2024-10-23 04:08 UTC, hzxuzhonghu commented
To speed up the procedure, It is better to present on the meeting https://docs.google.com/document/d/1wsa06GGiq1LEGwhkiPP0FKIZJqdAiue-VeBonWAzAyk/edit#heading=h.o8pz6aqnzzgk

2024-10-23 04:26 UTC, wtzhang23 commented
Added doc to the list of those in review

2024-10-24 13:46 UTC, wtzhang23 commented on pilot/pkg/networking/core/listener_inbound.go
>  			lp := istionetworking.ModelProtocolToListenerProtocol(cc.port.Protocol)
TODO: Will need to ensure that the permissive TLS chains are not built when `tlsSettings != nil`.

2024-10-24 15:26 UTC, wtzhang23 commented on pilot/pkg/networking/core/listener_inbound.go
>  			lp := istionetworking.ModelProtocolToListenerProtocol(cc.port.Protocol)
Addressed in [8d29fdd](https://github.com/istio/istio/pull/53469/commits/8d29fdd1aaa3b6f1150ab32555306b693db6ec23)

2024-10-24 15:30 UTC, istio-testing commented
@wtzhang23: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio | 8d29fdd1aaa3b6f1150ab32555306b693db6ec23 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/53469/lint_istio/1849472265389871104) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-10-24 15:49 UTC, istio-testing commented
@wtzhang23: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio | 8d29fdd1aaa3b6f1150ab32555306b693db6ec23 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/53469/lint_istio/1849472265389871104) | true | `/test lint`
gencheck_istio | bf1b37edc61bad845e33ddebfd3c5c9e29144060 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/53469/gencheck_istio/1849478080951750656) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-10-24 15:51 UTC, istio-testing commented
@wtzhang23: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
gencheck_istio | bf1b37edc61bad845e33ddebfd3c5c9e29144060 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/53469/gencheck_istio/1849478080951750656) | true | `/test gencheck`
lint_istio | bf1b37edc61bad845e33ddebfd3c5c9e29144060 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/53469/lint_istio/1849478089331970048) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-10-24 16:06 UTC, istio-testing commented
@wtzhang23: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
gencheck_istio | bf1b37edc61bad845e33ddebfd3c5c9e29144060 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/53469/gencheck_istio/1849478080951750656) | true | `/test gencheck`
lint_istio | f7f343b6582da65335c4a5910bba2d71dcae8ef3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/53469/lint_istio/1849482140190773248) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-10-24 16:07 UTC, istio-testing commented
@wtzhang23: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio | f7f343b6582da65335c4a5910bba2d71dcae8ef3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/53469/lint_istio/1849482140190773248) | true | `/test lint`
gencheck_istio | f7f343b6582da65335c4a5910bba2d71dcae8ef3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/53469/gencheck_istio/1849482131802165248) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-10-29 18:00 UTC, howardjohn requested changes
Looks pretty solid, just a few comments. Nice work!

2024-10-30 23:35 UTC, wtzhang23 commented on pilot/pkg/networking/core/listener_inbound.go
> +				cc.permissive = true
Do you think the distinction between listener names is needed? Could keep it simple and use the same names for both.

2024-10-30 23:41 UTC, istio-testing commented
@wtzhang23: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | 0bbbc3da047efc7e89779900200460ef9225924c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/53469/unit-tests-arm64_istio/1851770460690190336) | true | `/test unit-tests-arm64`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-10-30 23:44 UTC, istio-testing commented
@wtzhang23: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
unit-tests-arm64_istio | 0bbbc3da047efc7e89779900200460ef9225924c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/53469/unit-tests-arm64_istio/1851770460690190336) | true | `/test unit-tests-arm64`
unit-tests_istio | 0bbbc3da047efc7e89779900200460ef9225924c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/53469/unit-tests_istio/1851770461529051136) | true | `/test unit-tests`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-11-29 05:20 UTC, wtzhang23 commented
Any way to mark this as not stale?

2024-12-14 05:04 UTC, closed without merging