Feat/update code coverage
istio/istio pull request #54478
Opened 2024-12-26 17:54 UTC by chansuke

**Please provide a description of this PR:**

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2024-12-26 17:54 UTC, istio-testing commented
Hi @chansuke. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository.
</details>

2024-12-26 17:59 UTC, howardjohn requested changes

2024-12-26 17:59 UTC, howardjohn commented on .github/workflows/coverage.yaml
> +    runs-on: ubuntu-latest
Dumping a file to $ARTIFACTS will upload it in prow

2025-01-13 16:40 UTC, bleggett commented
/ok-to-test

2025-01-13 16:41 UTC, istio-testing commented
@chansuke: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | de8d361a33b6a33219151e03eab3b267488d93be | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/54478/release-notes_istio/1878844733220982784) | true | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2025-01-16 02:09 UTC, my-git9 reviewed
/test release-notes

2025-01-22 17:47 UTC, bleggett approved these changes
This LGTM (it at least provides a manual/local coverage threshold check, and a coverage report for prow).

Thanks!

2025-01-22 17:50 UTC, howardjohn commented on prow/config/coverage.yaml
Do we need this?

2025-01-22 17:50 UTC, howardjohn commented on prow/coverage.sh
> +    gsutil cp "${REPORT_COVERAGE}" "gs://${GCS_BUCKET:-istio-prow}/coverage/${GIT_SHA}.out"
I don't know that we need to do this, just dump a file into $ARTIFACTS and prow will automatically include it.

2025-01-22 17:50 UTC, howardjohn commented on prow/coverage.sh
> +COVERAGE_THRESH_PCT="${COVERAGE_THRESH_PCT:-50}" # Default coverage threshold
I am not sure what the point of a threshold is given we are not going to enforce it

2025-01-22 17:50 UTC, howardjohn commented on prow/coverage.sh
> +COVERAGE_THRESH_PCT="${COVERAGE_THRESH_PCT:-50}" # Default coverage threshold
To clarify -- there are different opinions from different people on the usefulness of reporting coverage in general, but adding coverage gates has been explicitly rejected.

2025-01-26 01:35 UTC, chansuke commented on prow/coverage.sh
> +    gsutil cp "${REPORT_COVERAGE}" "gs://${GCS_BUCKET:-istio-prow}/coverage/${GIT_SHA}.out"
ok

2025-01-26 06:49 UTC, chansuke commented on prow/config/coverage.yaml
Oh, we don't need this

2025-01-26 08:36 UTC, istio-testing commented
@chansuke: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
integ-telemetry-discovery_istio | 9074ff2f9060718616bdff26e4d7933e28f3fc66 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/54478/integ-telemetry-discovery_istio/1883430389725270016) | true | `/test integ-telemetry-discovery`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2025-01-26 09:46 UTC, chansuke commented
/retest

2025-01-27 14:50 UTC, howardjohn commented on prow/coverage.sh
> +go test ./... -coverprofile="${REPORT_COVERAGE}" || true
Do we really want to ignore failures?

2025-01-27 14:50 UTC, howardjohn commented on prow/coverage.sh
> +overcover --coverprofile="${REPORT_COVERAGE}" ./cni/...
Why do we need ./... and ./cni/...

2025-03-04 10:09 UTC, istio-testing commented
PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository.
</details>

2025-03-07 02:03 UTC, chansuke commented
@howardjohn 
friendly ping

2025-03-07 22:56 UTC, howardjohn approved these changes

2025-03-07 23:28 UTC, merged