Fix pilot revisions uninstall tests for Openshift Service Mesh
istio/istio pull request #54494
Opened 2024-12-29 15:20 UTC by MaxBab

**Please provide a description of this PR:**
Fixes: https://github.com/istio/istio/issues/54493

When during the pilot "revisions uninstall" tests, the Openshift Service Mesh Istioctl binary is used, the test fails with the following error: "istioctl error: Error: unknown flag: --revision"

That happens because the istioctl binary of Openshift Service Mesh does not support "uninstall" parameter.

Added "skipIfOpenShiftServiceMeshIstioctlUsed" function that will check the istioctl binary and will skip the "revisions uninstall" tests in case Openshift Service Mesh Istioctl binary is used.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [X] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [X] Control Plane Revisions

**Please check any characteristics that apply to this pull request.**

- [X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2024-12-29 15:20 UTC, istio-testing commented
Hi @MaxBab. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository.
</details>

2024-12-30 16:25 UTC, howardjohn requested changes
I don't think it makes sense to make the Istio test framework have built-in support for skipping tests based on a vendor fork removing functionality. The framework has **very rich** support for skipping tests that you can already use

2024-12-30 18:00 UTC, MaxBab commented
> I don't think it makes sense to make the Istio test framework have built-in support for skipping tests based on a vendor fork removing functionality. The framework has **very rich** support for skipping tests that you can already use

Ok, got it.

2024-12-30 18:01 UTC, closed without merging

2024-12-31 06:32 UTC, MaxBab commented
@howardjohn 
Are there any other options to skip the tests other than "-skip"?
I would like to check for a way to not define each test I would like to skip separately.