change default sds fetch timeout for files at gateway
istio/istio pull request #54506
Opened 2024-12-31 11:39 UTC by ramaraochavali

Recently we ran in to an issue when gateway certs expired, the client to fetch the certs did not write the certs yet in the file location but gateway was generated by our controller - These are two async processes. As a result of that, listener went live with failed SDS config. This PR sets the initial fetch timeout to zero (similar to default and root CA). It is controlled by feature flag now. If this is acceptable, I will add compatibility profile and release notes.

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

2024-12-31 11:41 UTC, istio-testing commented
@ramaraochavali: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_istio | 93f23152963aec6d36fa9ced0b1639a81df0c6b6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/54506/release-notes_istio/1874057776024522752) | true | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-12-31 13:52 UTC, keithmattix commented on pilot/pkg/security/model/authentication.go
> +		if proxy.Type == model.Router {
Do we want the feature flag to apply to sidecars that use file based secrets? If so, then maybe this conditional needs to be relaxed? If we do want it to only apply to gateways, then we should probably rename the flag to indicate that

2024-12-31 17:49 UTC, howardjohn requested changes
I am super worried about this. The initial fetch stuff was intended to insure that a single bad configuration cannot take out the entire gateway. This was from learning of large enterprises with 1000s of certificates, where a single bad domain caused site-wide outages which is terrifying behavior.

2024-12-31 17:50 UTC, howardjohn commented
I don't necessarily mind an opt in to a strict mode, but I think its a very unsafe default

2025-01-01 04:57 UTC, ramaraochavali commented on pilot/pkg/security/model/authentication.go
> +		if proxy.Type == model.Router {
Only for gateways. Will change the flag name

2025-01-01 05:32 UTC, ramaraochavali commented
> The initial fetch stuff was intended to insure that a single bad configuration cannot take out the entire gateway. This was from learning of large enterprises with 1000s of certificates, where a single bad domain caused site-wide outages which is terrifying behavior.

Was that for credential or for files? Earlier it used be opt-in and I only [removed](https://github.com/istio/istio/pull/30948) it in the past for files.  But the problem with updates going live in 15s breaking a domain is also bad if not equally bad.  BTW, have you tried this recently? When I tried setting initial_fetch_timeout to 0s in SDS for listener, Envoy came up with dynamic_warming_secrets and if you send requests it fails with `downstream_context_secrets_not_ready`

2025-01-01 06:37 UTC, ramaraochavali commented
> 
I don't necessarily mind an opt in to a strict mode, but I think its a very unsafe default


Sure. Please validate once if gateway does not come up with single bad domain

2025-01-02 02:47 UTC, hzxuzhonghu commented
In this expired cert case, could be simple to resolve by doing cert rotate ealier. `InitialFetchTimeout` only influence the first response, just not a reliable way for your case.

2025-01-02 03:55 UTC, ramaraochavali commented
> In this expired cert case, could be simple to resolve by doing cert rotate ealier.

We do cert rotate earlier. But the rotated cert comes in a new path which is downloaded from Vault and we write the Gateway with the new path (these are async). Some times gateway is written first before file is downloaded (if vault responds late). In this case, it becomes a new SDS flow and initFetchtimeout comes.

2025-01-13 10:15 UTC, closed without merging